### ISSUE TITLE
How to provide token for SASL_SSL explicitly?

### ISSUE THREAD

**Issue by andrewstanovsky** [Blizzard/node-rdkafka#1026]
I'm trying to migrate my KafkaJS code to Node-RdKafka but I couldn't find an equivalent.

KafkaJS snippet:

```
    const kafka = new Kafka({
        clientId: "test-producer",
        brokers: ['<broker_fqdn_port>'],
        ssl: true,
        sasl: {
            mechanism: 'oauthbearer',
            oauthBearerProvider: async () => {
                return {
                    value: token
                }
            },
        }
    });
```
I'm getting token outside of the kafka client and plan to refresh it using this token provider approach. I was trying to find the same mechanism in Node-RdKafka but with no success. I've also tried `oauthbearer_token_refresh_cb` but it looks like it's called much later than initial `connect()` call.

Please, let me know if it's even possible with the latest version at all

**Comment by andrewstanovsky** [comment]
The workaround has been merged in and is available in ^3.0.1:

https://github.com/Blizzard/node-rdkafka/commit/f594d1138b0435a0e73dd563828faa6dcad39bc3

**Comment by pveller** [comment]
Hey @andrewstanovsky , any particular reason that you decided not to implement `oauthbearer_token_refresh_cb`? You are listening to other callbacks (e.g. rebalance), why not this one? 

It would be much nicer to pass in the token as-is with the expiration that is set on it and have librdkafka call back when it needs a new one as is about to poll, no?  I am not sure I can know in node-rdkafka when exactly the consumer will need a new token so I guess my options are to preemptively set a new one in a pre-scheduled `setTimeout()` or handle auth errors coming back from librdkafka? 

I am probably missing something. Thanks

**Comment by andrewstanovsky** [comment]
I explored this approach initially, but since the callback on native level runs outside of V8, you need to make a special call to V8 and wait for it to finish going full cycle through event loop, which I deemed to be overly complicated, given strict time requirements, besides it's pretty trivial to do that on nodejs level. I also tried to do that there right in node-rdkafka itself, but also wanted to avoid complicating things that would need thorough testing before merging in.

**Comment by pveller** [comment]
@andrewstanovsky , I did not realize that `librdkafka` will do it all by itself if my IDP is a standard OAuth2/OIDC. I ended up doing a super simple thing with:

```
{
  'security.protocol': 'sasl_ssl',
  'sasl.mechanisms': 'OAUTHBEARER',
  'sasl.oauthbearer.method': 'oidc',
  'sasl.oauthbearer.client.id': authClientId,
  'sasl.oauthbearer.client.secret': authClientSecret,
  'sasl.oauthbearer.token.endpoint.url': authTokenUrl,
}
```

from what I read in the code, it has a built-in refresh callback if you don't provide your own: https://github.com/confluentinc/librdkafka/blob/d86b001bef29aaa5955fb8645865ff34ed516653/src/rdkafka.c#L2346

so I guess you only need to do it in the JS land when you can't delegate to `librdkafka` and your IDP. This is probably worth documenting in node-rdkafka README or in the OAuth examples? as an alternative to explicit `setOauthBearerToken()`?

**Comment by andrewstanovsky** [comment]
Yes, I saw this as well, but it wouldn't satisfy my case, where I do not have client secret. I just had an API that returns me a token based on some entity ID (Azure user managed identity case).
