### ISSUE TITLE
Please expose topic name on Producer.Topic instance

### ISSUE THREAD

**Issue by thanpolas** [Blizzard/node-rdkafka#107]
Hello,

I am developing a [kafka-avro library](https://github.com/waldophotos/kafka-avro) that depends on your library and it adds a layer on top for Avro Schemas validation and serialization. The `Producer.Topic` class will return a magic object which has no properties, I can see it is used with rdkafka and local bindings.

I'd like to kindly ask if it's possible that you expose the topic name as a string on the returned instance so I can use it on my end to apply Avro schema validations and serialization.

Because of that, I had to change the signature of the `produce()` method to 5 arguments to also include the topic name as a string.

**Comment by webmakersteve** [comment]
Hi there. Glad to see you're getting some use out of the library.

The good news is, there is already a way to get the topic name from a native Topic 

https://github.com/Blizzard/node-rdkafka/blob/master/src/topic.cc#L58

Just call the `name()` method on that object and it will tell you.

Hope this helps.

**Comment by thanpolas** [comment]
awesome, that's what i needed, thanks @webmakersteve!
