### ISSUE TITLE
Clarification: Consumer `error` event handling

### ISSUE THREAD

**Issue by thanpolas** [Blizzard/node-rdkafka#109]
The Consumer instance emits an `error` event. As per the examples and documentation, this is an error originating from Kafka and we should handle it as we see fit.

I just wanted to clarify that the above statement is correct as in node, the `error` event means that the runtime entered an unrecoverable state and the process should be terminated.

If that's the case, would you consider renaming the event to `kafkaError` for clarity and disambiguation?

**Comment by webmakersteve** [comment]
The goal of the library is basically to never be in an unrecoverable state. The error event just means `librdkafka` reported an error, but there is no indication that that error will be crash-worthy.

https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L152

Here are the error codes. 

All errors that get bubbled up to JavaScript from C++ land will get emitted by the error event, so you can do appropriate logging. Perhaps `error` is a misnomer from the way most Emitters work. I'll look into changing that and how that would look.

**Comment by thanpolas** [comment]
One very important side-effect that I forgot to mention was that if the `error` event is not caught from any listener, the node process will terminate itself.

**Comment by webmakersteve** [comment]
Yes. That is default functionality in Node.js: if an Emitter emits an `error` event without there being a listener, it bubbles up and throws.

**Comment by webmakersteve** [comment]
Closing the issue because of inactivity. Please feel free to open it if you still have questions or need help.
