### ISSUE TITLE
Receipt of produced messages

### ISSUE THREAD

**Issue by thanpolas** [Blizzard/node-rdkafka#110]
Hello,

I am trying to figure out a way of getting produce receipts per message produced but I don't think that's possible since there is an event for produce-receipts without having the ability to link them to produced messages.

What is your suggestion if I want to have per message produced receipts?

**Comment by webmakersteve** [comment]
The only way you can get a "produce receipt" is by listening to the `delivery-report` event and opting into it  by adding `dr_cb: true` to your producer config.

This will emit an event every time your produced message gets into kafka successfully or unsuccessfully based on your ack settings. There is no way to automatically correlate them with your messages, however (depending on your version).

In the future you can use `dr_msg_cb` which will include the message payload in the report. I believe in the most recent version you can use the `opaque`, which is the 5th parameter to the produce function.

Whatever you include in there will also be included in the report. 

```js
producer.on('delivery-report', (err, report) => {
   // Do work here
});
```

**Comment by thanpolas** [comment]
I tested the `opaque` and it works nice, I can include the whole message there along with control info like retry attempts... 

Can you think of any downsides to doing this (memory considerations/leaks)? How have you implemented resending messages up to `n` times?

**Comment by webmakersteve** [comment]
I haven't implemented retries. It is implemented by librdkafka internally. `message.send.max.retries` defaults to 2.

The opaque just makes a pointer to the in memory JavaScript data object, so it shouldn't cause any performance issues. It does keep the data in scope so it doesn't get GC'd until after the delivery report or error comes back, however. So if your queue size is too large and things start failing it may consume more memory.

**Comment by thanpolas** [comment]
Thank you @webmakersteve for all your patience and help!
