### ISSUE TITLE
Hide Logs

### ISSUE THREAD

**Issue by stefanodecillis** [Blizzard/node-rdkafka#1106]
Hi,

sorry i couldnt find the solution in this wrapper issues and readmes. I'm trying to disable the logs that kafka client (producer) is "producing" when publishing messages. 

All my logs file are filled by `Message delivered to topic: topic-name, partition: 0`. I tried with 

```
debug: 'broker',
log_level: 2;
```

with no success. Do you know how can I better configure my client and avoid debug logs? My desire is to keep only critical and error logs if possible

**Comment by andrewstanovsky** [comment]
Remove that 'debug: 'broker'' line completely as its name implies - it's not for normal usage, and add 'event.error' callback. There are more callbacks that you might want to add, like 'connection.failure' for example

**Comment by stefanodecillis** [comment]
that makes sense! It actually worked overwriting the logs 
Thanks!
