### ISSUE TITLE
Any way to get delivery messages after a producer has been killed?

### ISSUE THREAD

**Issue by martinambrus** [Blizzard/node-rdkafka#112]
Hi,

We're currently running into the problem of being unable to check whether messages were really written to Kafka once our Producer has died. We're using Docker containers, so it's possible that one app starts, Producer is created, sends 1000 messages and waits for their delivery reports. In the meanwhile, the app crashes and we're unable to verify if those 1000 messages were delivered, since the deliver_report function of the old producer no longer exists.

Is there any way to circumvent this, so we can make our app more durable?

Thanks!

**Comment by webmakersteve** [comment]
Is your entire application dying or is it just the producer? In either case there is no way to get the delivery reports from a dead client.

You will need to engineer a solution of writing delivery reports or pending messages to memory or disk so when you boot up you can see which messages weren't cleared for delivery at the time of the crash. 

If the crash is happening outside of the producer's logic you should try to make it more fault tolerant so you can start a shutdown sequence that can make use of `flush` to flush the rest of the messages to kafka before shutting down. This method will be available soon in the `librdkafka` upgrade.

**Comment by martinambrus** [comment]
Thank you for your reply. This basically came up during a fault-tolerance test and we were wondering if there was a way to recover from a NodeJS app crash. Seems we need to engineer a solution in this case.
