### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by jmarca** [Blizzard/node-rdkafka#115]
Hi, just learning kafka etc., so it is likely I'm doing something wrong.

I followed the instructions for running tests.  I cloned this repo, did `git submodule init` followed by `git submodule update`, then did an `npm install` to download dependencies.  

Then, in my kafka directory, I followed the "getting started guide" and fired up zookeeper and kafka as follows:

In screen 1, I did 

``` 
bin/zookeeper-server-start.sh config/zookeeper.properties
```
and in another screen session I did 
```
bin/kafka-server-start.sh config/server.properties
```
(Note both of these used the default server.properties that are distributed with Kafka source code, version 2.11-0.10.1.0) (in other words, brain dead clueless settings)

Then to run the tests I ran `make`.  The first time through I got two errors.  Then I ran make again and just got one error (which makes me suspect the first, non-repeating error happened because something wasn't right in kafka the first time through, then was okay the second time??)

The failing test says:

```
  1) Producer with dr_cb should connect to Kafka:
     Uncaught AssertionError: Broker id is not set
      at e2e/producer.spec.js:53:11
      at lib/client.js:351:7
```

Running on slackware 14.2 (-current), node v7.2.0

**Comment by webmakersteve** [comment]
Do you have any way of checking the metadata returned by your Kafka broker? You can use KafkaCat, which uses `librdkafka` under the hood just like `node` does.

```sh
kafkacat -L -b broker:9092 [-t topic]
```

Note: topic is optional

Just see what `librdkafka` is returning back for your set up. There is a chance that the broker ID isn't set so `librdkafka` doesn't know what to do with the metadata it is being given.

**Comment by jmarca** [comment]
Haven't had a chance to get back to this, but I didn't want to mention a few items I noticed between posting and getting your reply. (I did just try to quickly npm install -g kafkacat but no executable got installed, so I'll return to that later)

I was able to make the tests pass once.  I started a cluster of three "nodes" on my laptop.  I messed up and started in the order node 1, node 2, and then node 0 on the default port.  Then the tests passed.  No idea why, I wasn't able to reproduce that starting the three nodes in order of 0, 1, 2.

Second, I get the "double error" if I delete the temporary zookeeper and kafka directories in the /tmp directory (again, I'm following the quickstart guide on the kafka site)

Third, after setting up a three node kafka cluster and after wiping and restarting with a clean /tmp [zookeeper, kafka] directories, I ran the tests, got both failures on the first run, and on the second run got a timeout error in the mocha test.  So I hacked the Makefile and added the mocha command line option "--timeout 0", and for some reason, the tests refused to end, just chugged along using up CPU. 

I will try to spend more time with this in the coming days.

**Comment by webmakersteve** [comment]
Kafkacat isn't an `npm` module. You need to install it through a package repository or install it from source. It is maintained by the creator of `librdkafka`.

I don't know about your specific `kafka` situation but the tests are not meant to be run in an unstable environment where kafka's log directories are being deleted. They should be run on a kafka broker that is being left alone. In the end I am testing the interoperability of the node code with `librdkafka`'s c++ code.

Can you show me the tests that aren't passing for you? What is your Kafka broker version? Have you seeded the topics required for running the end to end tests? There are a lot of variables.

**Comment by jmarca** [comment]
Thanks for replying.

First I'm not trying to be a pest, I am just a new user trying to run the tests out of the box, and I'm trying to help this project by describing my failing test situation.

As to your statement about a stable kafka environment and not deleting log files, I respectfully disagree.  I recognize that I have a basic environment, and it may well be that my off-the-shelf deployment is why the tests are failing.  However, I think my setup is a valid one, as it is the bare minimum as described in the Kafka quick start docs.  

No I haven't "seeded" anything, but I *have* followed the testing instructions.  If kafka needs seeding,  then those actions *should*  be part of the test scaffolding, or else described in the readme section [here](https://github.com/Blizzard/node-rdkafka#tests).

kafkacat before:

[kafkacat_before.txt](https://github.com/Blizzard/node-rdkafka/files/778260/kafkacat_before.txt)


The failing test:

```
 ./node_modules/.bin/mocha --timeout 0 -R list e2e/producer.spec.js --bail

  1) Producer with dr_cb should connect to Kafka

  0 passing (158ms)
  1 failing

  1) Producer with dr_cb should connect to Kafka:
     Uncaught AssertionError: Broker id is not set
      at e2e/producer.spec.js:53:11
      at lib/client.js:351:7
```


kafkacat output after *just* running the failing test:

[kafkacat_after.txt](https://github.com/Blizzard/node-rdkafka/files/778297/kafkacat_after.txt)


Also, (again after tearing down and restarting zookeeper and kafka) if I run all the tests and e2e tests, I see:

```
james@emma node-rdkafka[master]$ ./node_modules/.bin/mocha --timeout 0 -R list test

  ․  super_: 0ms
  ․ native addon exports something: 0ms
  ․ native addon exports valid producer: 0ms
  ․ native addon exports valid consumer: 1ms
  ․ native addon exports version: 0ms
  ․ Consumer cannot be set without a topic config: 0ms
  ․ Consumer can be given a topic config: 0ms
  ․ Consumer throws us an error if we provide an invalid configuration value: 0ms
  ․ Consumer throws us an error if topic config is given something invalid: 0ms
  ․ Consumer ignores function arguments for global configuration: 0ms
  ․ Consumer ignores function arguments for topic configuration: 0ms
  ․ KafkaConsumer client is an object: 0ms
  ․ KafkaConsumer client requires configuration: 0ms
  ․ KafkaConsumer client has necessary methods from superclass: 0ms
  ․ KafkaConsumer client has necessary bindings for librdkafka 1:1 binding: 0ms
  ․ Producer client is an object: 0ms
  ․ Producer client requires configuration: 0ms
  ․ Producer client has necessary methods from superclass: 0ms
  ․ TopicReadable stream exports a stream class: 0ms
  ․ TopicReadable stream can be instantiated: 0ms
  ․ TopicReadable stream properly reads off the fake client: 2ms
  ․ TopicReadable stream properly reads correct number of messages but does not stop: 0ms
  ․ TopicReadable stream can be piped around: 1ms
  ․ TopicReadable stream stops reading on unsubscribe: 0ms

  24 passing (15ms)

james@emma node-rdkafka[master]$ ./node_modules/.bin/mocha --timeout 0 -R list e2e/*spec.js

  ․ Consumer/Producer should be able to produce, consume messages, read position: subscribe/consumeOnce: 4369ms
  ․ Consumer/Producer should be able to produce and consume messages: consumeLoop: 2287ms
  ․ Consumer/Producer should be able to produce and consume messages: empty key and empty value: 2286ms
  ․ Consumer/Producer should be able to produce and consume messages: null key and null value: 2287ms
  ․ Consumer committed and position before assign, committed offsets are empty: 312ms
  ․ Consumer committed and position before assign, position returns an empty array: 10ms
  ․ Consumer committed and position after assign, should get committed array without offsets : 1269ms
  ․ Consumer committed and position after assign and commit, should get committed offsets: 714ms
  - Consumer committed and position after assign, before consume, position should return an array without offsets (Timing out issue in this situation, so pending)
  ․ Consumer committed and position should obey the timeout: 12ms
  ․ Consumer subscribe should be able to subscribe: 217ms
  ․ Consumer subscribe should be able to unsusbcribe: 412ms
  ․ Consumer assign should be able to take an assignment: 312ms
  - Consumer assign should be able to take an empty assignment - EXCLUDED because of https://github.com/Blizzard/node-rdkafka/issues/63
  ․ Consumer disconnect should happen gracefully: 143ms
  ․ Consumer disconnect should happen without issue after subscribing: 152ms
  ․ Consumer disconnect should happen without issue after consuming: 1658ms
  ․ Consumer disconnect should happen without issue after consuming an error: 152ms
  ․ Consumer group/Producer should be able to commit, read committed, and restart from the committed offset: 15284ms
  ․ Consumer group/Producer should be able to commitSync, read committed and restart from the committed offset: 20979ms
  1) Producer with dr_cb should connect to Kafka
  ․ Producer with dr_cb should produce a message with a null payload and null key: 201ms
  - Producer with dr_cb should produce a message with an empty payload and empty key (https://github.com/Blizzard/node-rdkafka/issues/36)
  ․ Producer with dr_cb should produce a message with a payload and key: 400ms
  ․ Producer with dr_cb should produce a message with an opaque: 200ms
  ․ Producer with dr_cb should get 100% deliverability: 240ms
  ․ Producer with dr_cb should produce a message to a Topic object: 401ms
  ․ Producer with_dr_msg_cb should produce a message with a null payload and null key: 201ms

  24 passing (1m)
  3 pending
  1 failing

  1) Producer with dr_cb should connect to Kafka:
     Uncaught AssertionError: Broker id is not set
      at e2e/producer.spec.js:53:11
      at lib/client.js:351:7

```

and get the following, longer output from kafkacat:
[kafkacat_afterb.txt](https://github.com/Blizzard/node-rdkafka/files/778302/kafkacat_afterb.txt)

I also dumped kafka 0, 1, 2 output to files, as well as zookeeper output, in case that would help.

I also added a `console.log(metadata)`, and I see:

```
james@emma node-rdkafka[master]$ ./node_modules/.bin/mocha --timeout 0 -R list e2e/producer.spec.js --bail

    Producer with dr_cb should connect to Kafka:
{ orig_broker_id: 0,
  orig_broker_name: 'localhost:9092/0',
  topics: [],
  brokers: 
   [ { id: 2, host: 'localhost', port: 9094 },
     { id: 1, host: 'localhost', port: 9093 },
     { id: 0, host: 'localhost', port: 9092 } ] }
  1) Producer with dr_cb should connect to Kafka

  0 passing (161ms)
  1 failing

  1) Producer with dr_cb should connect to Kafka:
     Uncaught AssertionError: Broker id is not set
      at e2e/producer.spec.js:54:11
      at lib/client.js:351:7
```


Ah!  figured it out!

The test says:

```
var t = require('assert');
...
t.ok(metadata.orig_broker_id, 'Broker id is not set');
```

Node API docs state: https://nodejs.org/api/assert.html#assert_assert_ok_value_message

```
assert.ok(0);
// throws "AssertionError: 0 == true"
```

In this case, metadata.orig_broker_id === 0, so assert.ok is the wrong test, as 0 is false.

Perhaps the tests should be:

```
t.ok(metadata.orig_broker_id !== undefined,'Broker id is not set')
```

If I make that change, the tests pass.




Finally I cannot reproduce my initial issue seeing two errors, no matter what I do with three nodes.

**Comment by webmakersteve** [comment]
Closing this issue because I think it's fixed with your merged PR. Please re-open if I'm wrong!
