### ISSUE TITLE
null/empty key/value not honored in delivery report

### ISSUE THREAD

**Issue by mimaison** [Blizzard/node-rdkafka#117]
When sending a message with an empty key, the delivery report we receive has a `null` key instead of an empty string. 
With dr_msg_cb, when sending an empty payload, the delivery report we receive has an `undefined` payload

**Comment by webmakersteve** [comment]
Fixed with commit ef49abe651ab02c46128b3284a03ed93bbe5daaa. Will get pushed with update to 0.8
