### ISSUE TITLE
GLIBCXX_3.4.21 not found

### ISSUE THREAD

**Issue by Industrial** [Blizzard/node-rdkafka#125]
Hi. I'm getting this error on Ubuntu.

`Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /service/node_modules/node-rdkafka/build/Release/node-librdkafka.node)`

I'd also like to run this in the nodejs docker container, but I'm not sure what the packages are that I need to install in order for this to work.

**Comment by webmakersteve** [comment]
You probably need to have that dependency to compile it. The docker container for node may not come with all of the dependencies, or they may not be binary compatible, to try to save space when you may not need it. Can you reproduce this on ubuntu outside a container?

**Comment by Industrial** [comment]
Yes, so my question would be what the package names would be that I need in order to run this on Ubuntu

**Comment by webmakersteve** [comment]
https://launchpad.net/ubuntu/+source/glibc
