### ISSUE TITLE
delivery-report event not being fired

### ISSUE THREAD

**Issue by tony-cocco** [Blizzard/node-rdkafka#128]
I followed the sample code and then some and have connected to my Kafka brokers. I see messages being added in the logs. However, a `delivery-report` event is not sent as my handler is never called.

Can someone verify this code is correct?

```javascript
var kafka = require('node-rdkafka');

var producer = new kafka.Producer({
    'client.id': config.kafka.clientId,
    'metadata.broker.list': config.kafka.connectionString,
    'dr_cb': true
  }, {
    'request.required.acks': 1 // listed as default, but set explicitly
  });

  producer.connect();
  producer.on('ready', () => {
    try {
      producer.produce(topic, null, new Buffer('test'), null, Date.now());
    }
    catch (err) {
      console.error(err);
    }
  });
  producer.on('delivery-report', (err, report) => {
    console.log(err, report); // <-- never prints
  });
  producer.on('error', err => {
    console.error(err);
  });
```

node-rdkafka version: 0.8.0
macOS Sierra 10.12.3

**Comment by webmakersteve** [comment]
Make sure you're calling `producer.poll()` on occasion to tell `librdkafka` to fetch events like `delivery-reports` or they won't emit. 

You can put this on an interval, but if you don't do connection checking you should probably wrap it in a `try ... catch`

**Comment by tony-cocco** [comment]
@webmakersteve thanks for your reply.

I added a `setInterval(producer.poll, 3000)` and got my DR. My only issue is the documentation for `poll` says:

> This happens automatically on transactions such as produce.

Is this not the case? Or simply a timing issue?

**Comment by webmakersteve** [comment]
That's part of the README i didn't update when I made the upgrade to 0.7. I'll fix that. Thanks for catching it!
