### ISSUE TITLE
"npm install" failed on "npm ERR! node-rdkafka@0.8.0 install: `node-gyp rebuild`"

### ISSUE THREAD

**Issue by mr-kawaii** [Blizzard/node-rdkafka#129]
I'm writing a simple Kafka consumer app using node-rdkafka. So far I can only run "npm install" successfully with node v6.3.1 and npm v3.10.3. I tried upgrading to the latest version, e.g. node v6.10.0 and npm v3.10.10, or even the even later version, node v7 and npm v4, both failed with same error. What am I doing wrong? I tried different versions on both mac and ubuntu.

```../deps/librdkafka/src/rdkafka_sasl.c: In function 'rd_kafka_sasl_io_event':
../deps/librdkafka/src/rdkafka_sasl.c:129:23: error: 'rd_kafka_transport_t {aka struct rd_kafka_transport_s}' has no member named 'rktrans_sasl'
         return rktrans->rktrans_sasl.recv(rktrans,
                       ^
In file included from /usr/include/string.h:635:0,
                 from ../deps/librdkafka/src/rd.h:45,
                 from ../deps/librdkafka/src/rdkafka_int.h:44,
                 from ../deps/librdkafka/src/rdkafka_sasl.c:29:
../deps/librdkafka/src/rdkafka_sasl.c: In function 'rd_kafka_sasl_client_new':
../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: 'rd_kafka_conf_t {aka struct rd_kafka_conf_s}' has no member named 'sasl'
         if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
```

and

```
npm ERR! Linux 3.13.0-110-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-rdkafka@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-rdkafka package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-rdkafka
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-rdkafka
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/npm-debug.log
```

Also I've reduced to minimal dependencies in package.json
```
{
  "name": "kafka-monitor",
  "dependencies": {
    "node-rdkafka": "^0.8.0",
    "node-uuid": "^1.4.7"
  }
}
```

**Comment by webmakersteve** [comment]
It looks like you do not have SASL on your machine. You need to install the development headers and binaries before you run the install or it will fail for that reason. If you do not need SASL, you can prefix your `npm install` with the environment variable `WITH_SASL=0`.

**Comment by mr-kawaii** [comment]
With WITH_SASL=0, "npm install" worked.
However why I could get certain version of node/npm to work without having to define WITH_SASL=0?

**Comment by webmakersteve** [comment]
It's because `node-rdkafka` has a dependency on the `sasl` library, but we allow you to compile without it in the only way possible - by specifying a variable saying you don't want it.

If you don't want to have to do that you can install the sasl libraries for your platform. What operating system are you installing this on?

**Comment by mr-kawaii** [comment]
I guess was asking about:

on ubuntu A, node v6.3.1 and npm v3.10.3, npm install succeeded. (Why did this succeed without WITH_SASL = 0)
on ubuntu B, node v6.10.0 and npm v3.10.10, npm install failed.
on ubuntu C, node v6.10.0 and npm v3.10.10, with WITH_SASL=0, npm install succeeded.

**Comment by webmakersteve** [comment]
One of them probably had the `sasl` libraries installed. Maybe something else installed on it has sasl as a dependency. 

Run this and find out!

```sh
ldconfig -p | grep libsasl
```

**Comment by mr-kawaii** [comment]
`ldconfig -p | grep libsasl`
gave me
`libsasl2.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsasl2.so.2`

and now I could not replicate the same behavior with new vagrant ubuntu instances. I have to specify WITH_SASL always in order to install.

I'm ok with WITH_SASL=0. Thanks for your help.
