### ISSUE TITLE
Unable to rewind the consumer to a previous offset position

### ISSUE THREAD

**Issue by maxplanck76er** [Blizzard/node-rdkafka#136]
Hello,

I am using 0.8.0 version of node-rdkafka and I would like to rewind my consumer to a defined offset, I have tried this but it doesn't seem to work :
```
this.consumer.unassign();
this.consumer.assign([{"topic":"my-topic","offset":"25","partition":"0"}]);

```

Any idea ?
Thx.

**Comment by thanpolas** [comment]
This is a known issue unfortunately. Check out #102

**Comment by webmakersteve** [comment]
Can you post the code you are using to consume as well?

**Comment by webmakersteve** [comment]
Closing this because inactivity, and because the changes are implemented.
