### ISSUE TITLE
On producer, once queue is full, we can't produce anymore [v0.8.0]

### ISSUE THREAD

**Issue by danlevan** [Blizzard/node-rdkafka#138]
I'm trying to produce a lot of data to kafka `producer.produce(...)` and once I get the `Kafka.CODES.ERRORS.ERR__QUEUE_FULL` (after 100000 messages), I can't produce anymore (even if i retry after a few seconds after). Seems like it's stuck in that state. The 100000 messages are in kafka though but I can't produce new messages.

I tried with the `producer.getWriteStream(...)` and it fails here: https://github.com/Blizzard/node-rdkafka/blob/master/lib/util/topicWritable.js#L168

For testing, I lower the buffering message number like this
```
const configProducer = {
  'metadata.broker.list': ['localhost:9092'],
  'queue.buffering.max.messages': 10,
  'queue.buffering.max.ms': 100,
  'batch.num.messages': 2,
};
```

Is there anything we should do to reset the queue state?

**Comment by webmakersteve** [comment]
You need to run `poll` or it won't know they've been received by Kafka. I'm going to be added a method to auto-poll in the next release to make this more painless.

I would just recommend running poll every second or so, but how frequently you do it will depend on how fast you are producing.

**Comment by danlevan** [comment]
Oh thanks, yeah that's what I was missing.
I'll add an interval of 1s + call poll manually when I get a queue full error.

**Comment by senthil5053** [comment]
@danlevan  Could you please share the code snippet on how exactly you got this fixed ?
BTW, I use stream api with below code :
```
writeStream.write(data);
writeStream.producer.poll();
```
