### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ishitat** [Blizzard/node-rdkafka#142]
[npm-debug.log.txt](https://github.com/Blizzard/node-rdkafka/files/858155/npm-debug.log.txt)

**Comment by webmakersteve** [comment]
Unfortunately that log doesn't tell me anything, so I can't tell why it isn't installing on your platform.

```
1035 silly lifecycle node-rdkafka@0.8.0~install: Args: [ '-c', 'node-gyp rebuild' ]
1036 silly lifecycle node-rdkafka@0.8.0~install: Returned: code: 1  signal: null
1037 info lifecycle node-rdkafka@0.8.0~install: Failed to exec install script
```

Some part of the install script is returning 1, but I'm not seeing any relevant `stdout`. Did you pipe stdout to a file and upload that? NPM has its own debug log that would have more information about why things didn't work, iirc.

But first, do you have `libsasl` installed on your machine? If not, you will need to either install it, or run `npm install` with the environment variable `WITH_SASL=0` to ensure `librdkafka` does not try to compile with it.

**Comment by ishitat** [comment]
Thanks it worked.
