### ISSUE TITLE
kafka consume one message and stop listening

### ISSUE THREAD

**Issue by ishitat** [Blizzard/node-rdkafka#146]
Hi,

I want to achieve something like this. Consumer connect to kafka node. Fetch a message (If exists) and return.

How can I do it with this lib?

**Comment by webmakersteve** [comment]
There is documentation in the README.md that should help you learn how to fetch a message. You need to instantiate a consumer, subscribe to topics, and consume 1 message.

```js
const Kafka = require('node-rdkafka');

const consumer = new Kafka.KafkaConsumer({ ... }, {});

consumer.connect()
   .on('ready', () => {
      consumer.subscribe([ 'topic' ]);
      
      consumer.consume(1, function(err, message) {
          if (err) { // did not get a message

          }
      });
   });
```

**Comment by webmakersteve** [comment]
Closing the issue due to inactivity. Please re-open if you need more help, and please take a look at all the documentation in the README.md and the full docs. Hopefully they're helpful!

**Comment by ishitat** [comment]
I wrote the exact code. But code doesn't exist after returning 1 message.  It keep listening for the new message. I want to return null is no message is available or return only 1 message if available.

**Comment by webmakersteve** [comment]
That code will not keep listening for more messages, but there are sockets open to the Kafka broker so it will not exit unless you manually disconnect.

If `err` is not set, `message` still may be null. After that, if you don't care about messages anymore, `.disconnect()` from the broker, and that will allow your code to exit.
