### ISSUE TITLE
I can't install node-rdkafka in centos

### ISSUE THREAD

**Issue by gopimr2** [Blizzard/node-rdkafka#147]
I get below error when i "npm install node-rdkafka" 
[ i am using npm@3.10.3 , node@v6.4.0]

  >  checking for socket (by compile)... ok
      parsing version '0x000904ff'... ok (0.9.4)
      checking for libpthread (by pkg-config)... failed
      checking for libpthread (by compile)... ok
      checking for zlib (by pkg-config)... failed
      checking for zlib (by compile)... failed (disable)
      checking for libcrypto (by pkg-config)... failed
      checking for libcrypto (by compile)... failed (disable)
      checking for liblz4 (by pkg-config)... failed
      checking for liblz4 (by compile)... failed (disable)
      checking for libssl (by pkg-config)... failed
      checking for libssl (by compile)... failed (disable)
      checking for libsasl2 (by pkg-config)... failed
      checking for libsasl2 (by compile)... failed (disable)
      checking for libsasl (by pkg-config)... failed
      checking for libsasl (by compile)... failed (disable)
      checking for regex (by compile)... ok
      checking for librt (by pkg-config)... failed
      checking for librt (by compile)... ok
      checking for strndup (by compile)... ok
      checking for nm (by env NM)... ok (cached)
      checking for python (by command)... ok
      Generated Makefile.config
      Generated config.h

     Configuration

     summary:
      prefix                   /usr/local
      ARCH                     x86_64
      CPU                      generic
      GEN_PKG_CONFIG           y
      ENABLE_DEVEL             n
      ENABLE_VALGRIND          n
      ENABLE_REFCNT_DEBUG      n
      ENABLE_SHAREDPTR_DEBUG   n
      ENABLE_LZ4               y
      ENABLE_SSL               y
      ENABLE_SASL              y
      MKL_APP_NAME             librdkafka
      MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
      MKL_DISTRO               Linux
      CC                       gcc
      CXX                      g++
      LD                       ld
      NM                       nm
      OBJDUMP                  objdump
      STRIP                    strip
      CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith
      PKG_CONFIG               pkg-config
      INSTALL                  install
      LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
      LDFLAG_LINKERSCRIPT      -Wl,--version-script=
      RDKAFKA_VERSION_STR      0.9.4
      MKL_APP_VERSION          0.9.4
      LIBS                     -lpthread -lrt
      CXXFLAGS                 -Wno-non-virtual-dtor
      SYMDUMPER                $(NM) -D
      exec_prefix              /usr/local
      bindir                   /usr/local/bin
      sbindir                  /usr/local/sbin
      libexecdir               /usr/local/libexec
      datadir                  /usr/local/share
      sysconfdir               /usr/local/etc
      sharedstatedir           /usr/local/com
      localstatedir            /usr/local/var
      libdir                   /usr/local/lib
      includedir               /usr/local/include
      infodir                  /usr/local/info
      mandir                   /usr/local/man

     Generated

     config.cache

    Now type 'make' to build
      TOUCH Release/obj.target/deps/librdkafka_config.stamp
      CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdaddr.o
      CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdavl.o
      CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdcrc32.o
      CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdgz.o
    ../deps/librdkafka/src/rdgz.c:32:18: fatal error: zlib.h: No such file or directory
     #include <zlib.h>
                      ^
     compilation

     terminated.

     make:

     

    *** [Release/obj.target/librdkafka/deps/librdkafka/src/rdgz.o] Error 1
     make: Leaving directory `/srv/package/node_modules/node-rdkafka/build'
     gyp ERR! build error
     gyp ERR! stack Error: `make` failed with exit code: 2
     gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-
     gyp/lib/build.js:276:23)
     gyp ERR! stack     at emitTwo (events.js:106:13)
     gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
     gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
     gyp ERR! System Linux 3.10.0-514.2.2.el7.x86_64
     gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-
     gyp/bin/node-gyp.js" "rebuild"
     gyp ERR! cwd /srv/package/node_modules/node-rdkafka
     gyp ERR! node -v v6.4.0
     gyp ERR! node-gyp -v v3.3.1
     gyp ERR! not ok
    npm info lifecycle node-rdkafka@0.10.0~install: Failed to exec install script
    npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-rdkafka" "--build-from-source" "--loglevel" "info"
    npm ERR! node v6.4.0
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE

    npm ERR! node-rdkafka@0.10.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-rdkafka@0.10.0 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by webmakersteve** [comment]
Where is your `node.js` installed? It should have included zlib, so it's very strange that you wouldn't have it on the machine.

In any event, I can tell you are going to run into a problem trying to install this because you do not have `libsasl2` on your machine. You can circumvent that problem by installing without it: `WITH_SASL=0 npm install`

But for your libz problem, run this:

`yum install zlib`

**Comment by gopimr2** [comment]
Thanks @webmakersteve.

**Comment by senthil5053** [comment]
can someone help me understand how libsasl2 can be installed in mac ?

**Comment by webmakersteve** [comment]
@senthil5053 I believe it is installed by default. Try running `ls /usr/lib/ | grep sasl` to see if any results show up.

**Comment by IdanAdar** [comment]
> In any event, I can tell you are going to run into a problem trying to install this because you do not have libsasl2 on your machine. You can circumvent that problem by installing without it: WITH_SASL=0 npm install

How does one install this missing piece in CentOS?

**Comment by webmakersteve** [comment]
It should be libsasl-dev in the centos yum repositories.
