### ISSUE TITLE
Script in docker cannot connect to kafka

### ISSUE THREAD

**Issue by crystoy** [Blizzard/node-rdkafka#149]
Version :
kafka : 2.11-0.10.2.0
node-rdkafka : v0.10.0
librdkafka: v0.9.4

My script(A Producer) cannot connect to kafka server, without any data|error messages|events received, just no response.I can't find out the problem. But the script runs good outside the container...
And I tested other clients(kafka-node & no-kafka) in the same container, they ran without problems.
Anyone encountered the same problem? Or any suggestions will help, thanks!

**Comment by webmakersteve** [comment]
Where is your kafka? And you say your script is running inside the container? 

Do this:

```js
producer.connect(null, (err, metadata) => console.log(metadata);
```

**Comment by crystoy** [comment]
Kafka is in a container too,and they are within the same network.
Here is the error message:
```
{ Error: Local: Erroneous state
    at Function.createLibrdkafkaError [as create] (/data/app/node_modules/node-rdkafka/lib/error.js:260:10)
    at /data/app/node_modules/node-rdkafka/lib/client.js:183:28
  message: 'Local: Erroneous state',
  code: -172,
  errno: -172,
  origin: 'kafka' }

```

**Comment by webmakersteve** [comment]
That's the error message from running `producer.connect`? What configuration are you giving the client?

**Comment by crystoy** [comment]
Yes,it is.
The client config is:
```
this.producer = new Kafka.Producer({
    'metadata.broker.list': 'kafka:9092'
});
```
'kafka' is the hostname of container.
Nothing else.

**Comment by webmakersteve** [comment]
So, that error message doesn't help me a lot currently. I'm going to put it on my list to make the error message better, but what's happening is that librdkafka is giving me an error code when trying to create your producer. Not even in the act of fetching metadata, but just in creating the producer.

You say this runs fine outside of your container? What happens if you try to make a consumer in there?

**Comment by crystoy** [comment]
Yes, the script runs fine outside container.
And, I tried a consumer,there is a different error message from consumer.connect:
```
{ Error: Failed to create thread: No such file or directory (2)
    at Error (native)
  origin: 'failed to create thread',
  message: 'no such file or directory (2)',
  code: -1,
  errno: -1,
  stack: 'Error: Failed to create thread: No such file or directory (2)\n    at Error (native)' }
```

**Comment by webmakersteve** [comment]
It looks like your consumer can't allocate a thread to run. This is probably a restriction of the container you're using - perhaps the OS is capped out on threads by running both kafka and this application?

The other kafka clients are JS side only so they only use v8 threadpool, which means they may not have the issue.

**Comment by crystoy** [comment]
My container is based on node-alpine + pm2, I'll test it in a container based on other OS and feedback later.
Thanks for your help.

**Comment by crystoy** [comment]
I tested the script in a debian-based container, and now it works fine!
So,maybe it is a problem of the Alpine OS or so?
And if I still want to use this OS, what should I do then?
Thanks again.

**Comment by webmakersteve** [comment]
It could be a limitation of the limited system libraries on `alpine`. I would suggest trying to use docker-compose to have these two things running in separate containers with orchestration if you want to use alpine and perhaps that fixes the issue. Otherwise, I'm not entirely sure as I don't test against it.

**Comment by crystoy** [comment]
OK,I got it. Thank you for your help.

**Comment by webmakersteve** [comment]
Closing the issue. Please re-open if there's anything else not working as expected!
