### ISSUE TITLE
Issue with key parameter when using Producer

### ISSUE THREAD

**Issue by ArtemisMucaj** [Blizzard/node-rdkafka#15]
I'm trying to produce keyed messages to Kafka but for some reason the key value I get back during delivery report events is null

`
produce({
  message: data.content,
  key: data.key,
  topic: ...
}, ... )
`

`
{"topic_name":"vpn","partition":0,"offset":1137763,"key":null}
`

Any ideas?

**Comment by webmakersteve** [comment]
The key parameter wasn't being passed at the c++ level. I had turned it off a while ago because we weren't using it. Just put it back on so if it is provided it should be used.

Currently running against CI.

**Comment by webmakersteve** [comment]
Merged into master. Will publish shortly to `0.3.1`

**Comment by webmakersteve** [comment]
Published. Re-open the issue if you are still seeing the problem.

**Comment by ArtemisMucaj** [comment]
Works for me! Thanks :+1:
