### ISSUE TITLE
librdkafka always build when install new node package.

### ISSUE THREAD

**Issue by MarvinWilliam** [Blizzard/node-rdkafka#152]
I use yarn to manage my node packages.
But each time I use `yarn add` to install a new package,node-rdkafka will rebuild.
Could this package like node-sass, build once when install?

**Comment by webmakersteve** [comment]
`librdkafka` has a configuration step that generates a header file for the code to use, so it knows what libraries are available to it, etc. This configuration step cannot be cached as done, as the environment the code is compiling on may have change. There is then a chain of dependencies that need to resolve based on that `config.h` file, which causes the entirety of librdkafka to recompile. 

I imagine this is just the way yarn does installs - running install on the entire project each time. Some projects that do not depend on system libraries do not need to configure themselves in this way, but this is a side effect of the configure step. I don't think there is a way to fix this.

Alternatively, if it bothers you, you can install the `librdkafka` library to your system and specify through an environment `BUILD_LIBRDKAFKA=0` variable that you want to use the system `librdkafka`. It will not build the source if you do that.

**Comment by MarvinWilliam** [comment]
@webmakersteve I would try this way, thx.

**Comment by james-rabbit** [comment]
Could `librdkafka` keep a cache key based on the system libraries used to build it?
Currently this module does not fit very well with the normal flow of using npm, it makes every operation take much longer.

**Comment by james-rabbit** [comment]
Looking deeper into things, this problem is not specific to node-rdkafka and seems to be something yarn intends to fix instead: https://github.com/yarnpkg/yarn/issues/932
