### ISSUE TITLE
Can not create docker image

### ISSUE THREAD

**Issue by vbicer** [Blizzard/node-rdkafka#154]
**When I try to build an docker image image console output  says;**

npm ERR! node-rdkafka@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@0.10.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-rdkafka package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by webmakersteve** [comment]
I need a bit more information. It is more than likely that you are missing a dependent library. The one that most people miss is `libsasl`. Please make sure you install it in your docker image, or that you compile without it by specifying `WITH_SASL=0` as an environment variable.

**Comment by vbicer** [comment]
ENV WITH_SASL 0 works thanks.
