### ISSUE TITLE
SyntaxError: invalid syntax while evaluating condition '${BUILD_LIBRDKAFKA:-1}==1' in binding.gyp at character 1

### ISSUE THREAD

**Issue by jimjaeger** [Blizzard/node-rdkafka#159]
Syntax error during install / compile of node-rdkafka

**Comment by webmakersteve** [comment]
What platform are you on? Can you give me the full logs for this install and environment variables that are being set?

**Comment by jimjaeger** [comment]
windows 7 64Bit. Do you have instructions to get it installed on there?

**Comment by webmakersteve** [comment]
Librdkafka compiles on windows, but node-rdkafka does not. This is a known issue. Unfortunately, it is very low on the priority list for me and will likely never be done unless a contribution is offered to make it work.

Sorry for the confusion. This information is in the top of the README however. Please see issue #45. If you are willing to make it work there I would be happy to review a PR!

Closing the issue. Please re-open if you see it necessary.
