### ISSUE TITLE
Delivery report's offset is off by 1 ?

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#161]
Hi
if we start producing to an empty topic, the first delivery_report in node_rdkafka will have an offset of 1, and then the others follow from that.

If that first message is consumed, its offset is 0.

This mismatch does not appear in Java (0.10.2) or in librdkafka (0.94) where the first message has offset 0 both in a delivery report as well as in a consumed message.

Behavior seen with both node_rdkafka 0.10.0 and 0.6.3

**Comment by edoardocomar** [comment]
looks like it may be a librdkafka issue.

these are the outputs of the node-rdkafka producer example  
from https://github.com/Blizzard/node-rdkafka/blob/master/examples/producer.md

running against a topic testtopic7 (to be autocreated)
```
$ node producer.js
producer ready.{"name":"rdkafka#producer-1"}
delivery-report: {"topic":"testtopic7","partition":0,"offset":1,"key":"key-0","size":7}
producer disconnected. {"connectionOpened":1493206642026}
```
the offset is 1 which is wrong


if I add the setting and change the topic
```
   'produce.offset.report' : true
```
to the topic object I get the correct offset
```
$ node producer.js
producer ready.{"name":"rdkafka#producer-1"}
delivery-report: {"topic":"testtopic8","partition":0,"offset":0,"key":"key-0","size":7}
producer disconnected. {"connectionOpened":1493206866975}
```

**Comment by edoardocomar** [comment]
@edenhill this appears to be the case with your C++ example too

if we just hack `rdkafka_example_cpp` it to print the offset
```
class ExampleDeliveryReportCb : public RdKafka::DeliveryReportCb {
 public:
  void dr_cb (RdKafka::Message &message) {
    std::cout << "Message delivery for (" << message.offset() << " offset): " <<
```

we get these outputs

```
$ ./rdkafka_example_cpp -P -t testtopic2 -X topic.produce.offset.report=true -b localhost:9092
% Created producer rdkafka#producer-1
message0
% Produced message (8 bytes)
message1
% Produced message (8 bytes)
Message delivery for (0 offset): Success
```

```
$ ./rdkafka_example_cpp -P -t testtopic9  -b localhost:9092
% Created producer rdkafka#producer-1
mmms
% Produced message (4 bytes)
mmmsss
% Produced message (6 bytes)
Message delivery for (1 offset): Success
```

In the latter case the offset of 1 is wrong.

**Comment by mimaison** [comment]
From our **very minimal** testing, the offset value seems to be off by 1. Is that always the case ?

If without `produce.offset.report`, the offset could be anything, why not setting it to something obviously wrong (-1 ?) to avoid confusion ? No value is better than something invalid.

Also according to https://github.com/edenhill/librdkafka/wiki/FAQ#how-do-i-get-the-offset-of-a-produced-message, `produce.offset.report` is "cheap", so why not have it enabled by default ?

**Comment by mimaison** [comment]
From our **very minimal** testing, the offset value seems to be off by 1. Is that always the case ?

If without `produce.offset.report`, the offset could be anything, why not setting it to something obviously wrong (-1 ?) to avoid confusion ? No value is better than something invalid.

Also according to https://github.com/edenhill/librdkafka/wiki/FAQ#how-do-i-get-the-offset-of-a-produced-message, `produce.offset.report` is "cheap", so why not have it enabled by default ?

**Comment by webmakersteve** [comment]
I'll wait on @edenhill's comment for this. If there is a way for me to make a distinction between an offset not being reported and one that is, i would be happy to not set it unless it is reported.

**Comment by edoardocomar** [comment]
Hi @edenhill what do you think ?

**Comment by edoardocomar** [comment]
looks like this could be fixed by
https://github.com/edenhill/librdkafka/pull/1387

**Comment by webmakersteve** [comment]
Maybe! We'll see!

**Comment by edenhill** [comment]
The workaround is to set `produce.offset.report` to `true`, and yes, it is very cheap so please do enable it by default in your Node.JS bindings.

**Comment by webmakersteve** [comment]
I believe this is fixed in the new version of librdkafka released - so closing the issue.
