### ISSUE TITLE
npm node-rdkafka fails to build due to missing files in version

### ISSUE THREAD

**Issue by dror-ventura** [Blizzard/node-rdkafka#164]
dependencies: {
...
"node-rdkafka": "0.10.0"
...
}

And upon build using:
`npm install`
i receive the error:
`gyp: Call to 'find librdkafka/src-cpp -name *.cpp' returned exit status 1`
when checking the released file in npm the files from librdkafka are missing...

I solved it by using the commit sha
dependencies: {
...
"node-rdkafka": "git+https://github.com/Blizzard/node-rdkafka.git#6c2ebe84ded6dff74cb003d6e1476d51e9319783",
...
}
Please fix it when you have the chance...
I prefer not to install git inside my docker image

Thanks

**Comment by webmakersteve** [comment]
This should be fixed with 0.10.2. Sorry. Tried to do a last minute publish when I got home, but my local machine didn't have the submodule dependency...
