### ISSUE TITLE
Include TypeScript 2.0+ Type Declarations

### ISSUE THREAD

**Issue by jdconley** [Blizzard/node-rdkafka#166]
TypeScript declarations in node modules provide a great way to publish your interface to consumers, enabling tooling to do compile-time type/interface checks. This is also really useful when working in IDE's that support the standard and is already supported by at least VS Code and IntelliJ IDEA.

[TypeScript Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

If you [include it in your library distribution](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) it will automatically get picked up by the TypeScript compiler.

**Comment by webmakersteve** [comment]
If you find that this would help you, I'd be happy to accept and review a PR. But it isn't something that will likely get priority otherwise.

**Comment by webmakersteve** [comment]
I think this has been added recently!

**Comment by thebigredgeek** [comment]
Has it?  I don't see the definitions...

**Comment by anodynos** [comment]
There is an `index.d.ts` indeed, but there are so many `: any` that makes it semi-useful... 
It seems it's been auto-gen with [dts-gen](https://github.com/Microsoft/dts-gen) much like [Yolean/node-rdkafka-types](https://github.com/Yolean/node-rdkafka-types/blob/master/index.d.ts)... 

It just needs some love:-)
