### ISSUE TITLE
Questions on updating broker urls and producer disconnect

### ISSUE THREAD

**Issue by blakambr** [Blizzard/node-rdkafka#167]
Just a couple of implementation questions around the use of node-rdkafka:

1.  Is there a way to update broker urls without creating a new instance of the kafka produce/consumer for dynamic environments?
2. Upon disconnecting, are expected that event emitters are cleaned up or is that something we will need to cater for?
3. What is the correct way of handling an error during a disconnect? Do we simply need to retry disconnecting again?

Thanks :)

**Comment by webmakersteve** [comment]
1. The config is completely immutable - that is, you cannot update the broker urls without creating a new one.  This is the nature of the way Kafka is intended to work - you provide it a bootstrap server and it learns about all the other dynamic servers by using the metadata.
2. When you disconnect, the emitter is not cleaned up. If you don't want your old events to fire when you disconnect you will need to manually remove all of your subscribed events, however, in this case, it is probably better for you to simply make a new client.
3. The goal with librdkafka is that you are never truly disconnected. It is constantly trying to reconnect on a backoff schedule. The node `disconnect` event is only fired when you tell the client to disconnect, which means it closes the librdkafka handle so it does not try to connect or reconnect. You should be able to use it without fear that you need to do the reconnection yourself! It is all handled by the underlying library.

**Comment by webmakersteve** [comment]
Hope the answer has helped! Reopen the issue if not :)

**Comment by fega** [comment]
Hello @webmakersteve , Somethines I have errors like `error: internal error Error: Producer not connected
` node-rdkafka is doing something to handle this kind of errors under the hood?

**Comment by webmakersteve** [comment]
Once the initial connect happens successfully, librdkafka will automatically deal with disconnections and reconnections. But the initial connect can fail and needs to be retried manually if it does.
