### ISSUE TITLE
Getting list of all topics using consumer

### ISSUE THREAD

**Issue by michallevin** [Blizzard/node-rdkafka#168]
I am attempting to get a list of all topics using the consumer before subscribing to them.  Looking at the example, I tried this:

```
const consumer = new Kafka.KafkaConsumer({
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'rdkafka-106',
  'enable.auto.commit': false,
  'offset.store.method': 'broker'
}, {
  'auto.offset.reset': 'beginning'
});

consumer.on('ready', (arg) => {
  console.log(`consumer ready.${JSON.stringify(arg)}`);
  console.log(consumer.getMetadata());
});
```

But the output is:
```
consumer ready.{"name":"rdkafka#consumer-1"}
undefined
```

If I set 'debug' to 'all' I do see events with the topics, but I am looking to get a list of all topics in one call. What am I doing wrong?

**Comment by webmakersteve** [comment]
`getMetadata` is an asynchronous method. It doesn't return the metadata, it fetches it. 

When you run the `connect` method to connect to the broker, it will pass you back the metadata in that callback, as a connect implicitly gets metadata.

```js
consumer.connect(null, (err, metadata) => {
   // Now you have the metadata
});
```

Otherwise, using your code:

```js
consumer.on('ready', (info) => {
  consumer.getMetadata(null,(err, metadata) => {
     // Now you have the metadata
  });
});
```

You can also access the metadata on the `_metadata` property, which is meant to be used internally, but still accessible.

```js
consumer.on('ready', (arg) => {
  console.log(`consumer ready.${JSON.stringify(arg)}`);
  console.log(consumer._metadata);
});
```

**Comment by michallevin** [comment]
@webmakersteve Thank you!!
The ``metadata.md`` example was throwing me off:
```
var Kafka = require('../');

var producer = new Kafka.Producer({
  'metadata.broker.list': 'localhost:9092',
  'client.id': 'hey',
  'compression.codec': 'snappy'
});

producer.connect()
  .on('ready', function(i) {
    console.log(i);
    console.log(producer.getMetadata());
  })
  .on('event.error', function(err) {
    console.log(err);
  });
```

Also, the consumer connect is not mandatory, and on('ready') is still required afterwards? If yes, then what is the purpose of connect? Which one of your examples would you recommend for getting a list of topics and then subscribing to them?

**Comment by michallevin** [comment]
@webmakersteve Another related question:
If I need to poll for new topics at a set interval and keep my consumer connected, do I need a new consumer/producer to do so? Calling consumer.getMetadata does not seem to return newly added topics.

**Comment by webmakersteve** [comment]
I'll update that example, as it is outdated. There used to be `getMetadata` and `fetchMetadata`, but we removed those I think very early into the release.

When you call `consumer.getMetadata` it should get the most recent metadata in the cluster. However, I see that the API for fetching metadata changed (even though the signature is the same). To get around this for now, just pass in `true` to `getMetadata` as the first parameter. That should fetch metadata if I'm correct. But I will get to fixing this bug!

**Comment by webmakersteve** [comment]
This fix has been added into the library!
