### ISSUE TITLE
Expose rd_kafka_query_watermark_offsets 

### ISSUE THREAD

**Issue by rnpridgeon** [Blizzard/node-rdkafka#169]
Perhaps I have missed it but I do not see where node-rdkafka provides a convenient means of finding either the earliest or latest offset for a given topicPartition. 

It would be nice if node-rdkafka exposed `rd_kafka_query_watermark_offsets` which would provide this functionality.

**Comment by rnpridgeon** [comment]
for reference: 

https://github.com/edenhill/librdkafka/blob/0a9458e36fd9be347fdf74f42814bb9a61064f71/src/rdkafka.h#L1754-L1765

**Comment by webmakersteve** [comment]
New PR that adds support to watermark offsets.
