### ISSUE TITLE
undefined symbol when using consumer.seek

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#173]
Trying to run trunk code and a consumer that does :

```
consumer.on('ready', function(arg) {
  console.log('consumer ready.' + JSON.stringify(arg));

consumer.subscribe([ topicName ]);

  consumer.seek({
  topic: topicName,
  partition: 0,
  offset: 0
  }, 0, function(err) {
    console.log("seek callback " + err);
    consumer.consume();
  });
```

I get (on macOS)

```
dyld: lazy symbol binding failed: Symbol not found: __ZN9NodeKafka13KafkaConsumer4SeekERKN7RdKafka14TopicPartitionEi
  Referenced from: /Users/ecomar/devel/ws-github/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace
```

similar on Linux

**Comment by mimaison** [comment]
It's probably worth adding an e2e test as well. Not only it will catch these but also provide examples how to use it

**Comment by webmakersteve** [comment]
Getting there! Was going to do it a bit before release. Good to see you caught it already though as I hadn't tested .

**Comment by webmakersteve** [comment]
Fixed on the master branch, but I found out that confusingly, seek is not included in `librdkafka` 0.9.5. The header file had it added Feb 12th but it was removed before release. I added a precompiler directive so if you are using a version greater than 0.9.5 it should automatically be included, otherwise it will throw an ERR__UNKNOWN.

**Comment by edoardocomar** [comment]
thanks, however running  `node-rdkafka` master against `librdkafka` master 
fails with ` Symbol not found: _rd_kafka_sasl_plain_provider`
actually that also happens running the tests with make.

```
Error: dlopen(/Users/ecomar/devel/ws-mariposa/message-hub-samples/kafka-nodejs-console-sample/node_modules/node-rdkafka/build/Release/node-librdkafka.node, 1): Symbol not found: _rd_kafka_sasl_plain_provider
  Referenced from: /Users/ecomar/devel/ws-mariposa/message-hub-samples/kafka-nodejs-console-sample/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace
```

I guess we need a new stable librdkafka ?

**Comment by webmakersteve** [comment]
With the librdkafka upgrade this should now be fixed. Closing the issue. Re-open if you're still experiencing it.
