### ISSUE TITLE
How does the consumer work

### ISSUE THREAD

**Issue by rakshitajain5** [Blizzard/node-rdkafka#180]
I am using flowing mode consumer with my node application. I want to fetch only few number of messages at a time. Does it keep fetching messages and buffer them in a queue? If yes, then can we change this configuration and put a limit on the number of messages fetched?
@webmakersteve Can you please help. We are facing lot of issues with the consumer.

**Comment by jmwilkinson** [comment]
This is a similar use case that I was facing. The general repeated steps are:

1. Consume batch of messages
2. Perform processing
3. Commit offsets

I do not believe you can use flowing mode to accomplish this.

I built some code off a comment to #176, which may be helpful to you. I am currently facing issues with the third step (committing offsets), and I have an open question about it: #184.

**Comment by rakshitajain5** [comment]
I tried consuming in batches using the below code - 
`setInterval(function() {
                consumer.consume(500);
            }, 1000);`

But only one consumer seems to be working , rest are not fetching any data from kafka . here is the status of consumer group. 

<img width="1404" alt="kafka" src="https://cloud.githubusercontent.com/assets/12950844/26677017/c29b7b0a-46e7-11e7-9a4e-5ffe97db25a6.png">

As you can see only one consumer is fetching while all others are in hanged state.

**Comment by webmakersteve** [comment]
Is this one consumer or do you have multiple consumers consuming from this topic? I see all the client ids are rdkafka (which is the default for librdkafka - i definitely recommend changing it).

I would need to see an example of your code to know why it may not be consuming off of most of these partitions. And I would need to know a bit about your stack:

1) How many node processes are running?
2) How many instances of KafkaConsumer do you have?
3) How many topics are in the subscription?
4) What configuration are you passing in to node-rdkafka?

**Comment by rakshitajain5** [comment]
I have a consumer group consisting of 2 consumers(4 core machines). There are 4 processes running on both the 2 node machines, thus giving a total of 8 node processes. There is only one topic from which I am consuming. 
`var consumer = new Kafka.KafkaConsumer({
        'group.id': 'calllog',
        'metadata.broker.list': process.env.KAFKA_SERVERS,
        'enable.auto.commit': false,

    }, { 'auto.offset.reset': 'smallest' });`

**Comment by webmakersteve** [comment]
When you consume using only one instance of KafkaConsumer, does it consume from all topics? 

Also, on a 4 core box you should only have 3 processes for node max. Otherwise you won't give the kernel a dedicated core to use. 

Can you add `debug: 'cgrp,topic,fetch'` to your config and read the log lines to see what assignments each is given?

**Comment by rakshitajain5** [comment]
yeah, only one instance does work fine. 
I tried using 3 node processes as well but still it is not working. 
The consumer consumes from only few partitions and then go in hanged state. Also, when I kill node processes on any one consumer, the other starts working again and start consuming the messages from the remaining partitions.

**Comment by webmakersteve** [comment]
Can you add that debug parameter and make sure you are listening to `event.log` and log the messages it sends while they are in a hanged state? This will expose the internal librdkafka logs

**Comment by rakshitajain5** [comment]
I added the debug statement and ran using 3 node processes on 2 consumers. The following is the screenshot of the logs generated in the hanged state - 
<img width="1440" alt="screen shot 2017-06-07 at 12 59 52 pm" src="https://user-images.githubusercontent.com/12950844/26867061-6ca33136-4b81-11e7-974d-3f4c18e3f310.png">

Also the status of consumer group in kafka - 
<img width="1276" alt="screen shot 2017-06-07 at 12 44 23 pm" src="https://user-images.githubusercontent.com/12950844/26867115-a28c625e-4b81-11e7-8e7d-0bfc7106f6e0.png">


One consumer was consuming from partitions 2,3 and 6 while the other from partition 7.

**Comment by rakshitajain5** [comment]
Also, I tested on using 2 node process on 2 servers. I noticed that 1 of the processes on 1 server was doing only heartbeat check and was not fetching while it was assigned 2 partitions by kafka broker. Following is the logs from that particular process - 
<img width="1440" alt="screen shot 2017-06-07 at 3 19 45 pm" src="https://user-images.githubusercontent.com/12950844/26872765-52e0680e-4b95-11e7-9496-b0f18541419c.png">

**Comment by webmakersteve** [comment]
Can you try using the read stream instead and see if the problem reproduces? You should be able to implement it to essentially the same effect if you just add a listener to `on('data')`

**Comment by webmakersteve** [comment]
You should see fetches in the logs very frequently, so any consumer that does not show fetches is likely in error somehow. The only way it wouldn't fetch is if there were no assigned partitions.

You should also log the current assignment on an interval so we can ensure librdkafka knows about the assignments it has - although the logs should show that.

Also, an attached file of the logs from start up to end would be helpful. It is hard to get the full context with a screenshot.

**Comment by rakshitajain5** [comment]
How can I know which assignments are assigned to a particular instance of consumer from rdkafka. Kafka shows that the partitions are being assigned to a particular consumer. But probably the consumer does not fetch it somehow.

We don't want to use read stream as we want to commit the offset manually.

**Comment by webmakersteve** [comment]
There is a method on the consumer called 'assignments' that you can call.

Additionally, the stream does NOT commit for you. And I just want to see how if it fixed the problem because if it does this would be indicative of an issue in the node layer.

**Comment by rakshitajain5** [comment]
We modified our code to ```consumer.consume(500,function(err,data){console.log(err);  console.log(data) }); ``` and ran 8 processes(4 on each consumer). I found that two of the consumers were only doing only heartbeats and data was coming empty. The logs are too heavy and therefore I am attaching the screenshot only. null is the error and [] is the data logged above  
<img width="1440" alt="screen shot 2017-06-08 at 12 37 01 pm" src="https://user-images.githubusercontent.com/12950844/26916545-69d4ca74-4c48-11e7-83bd-9c76b76d5e95.png">

Meanwhile I'll try with read stream as well.

**Comment by rakshitajain5** [comment]
[c1.log.zip](https://github.com/Blizzard/node-rdkafka/files/1060433/c1.log.zip)

**Comment by chetandev** [comment]
consumer fetching few messages in a partition then  hangs and only prints  []  on data event

**Comment by rakshitajain5** [comment]
All the consumer instances work fine with auto commit. The problem occurs only in manual commit.

**Comment by webmakersteve** [comment]
Sorry to get back to this issue so late. Does the problem continue on the latest version, or did you get a solution? 

The commits can happen in random order but you should take care not to commit after every operation. It can be expensive since Kafka internally writes to a compact topic all the brokers share. 

If you are doing the batch process method you should commit on an interval and ensure that the write to cassandra is idempotent. When we do a similar thing in our applications we keep a record of the max processed offsets per topic per partition and then run a commit there on an interval.

**Comment by prabugp** [comment]
> The commits can happen in random order 
If consumer1 is processing message1, and message2 gets delivered(in flowing mode) and processed before message1, then the commit would move the offset to 3 for that consumer group. If for some reason, consumer1 couldn't complete message1 processing, there is no way we can reprocess message1 by any mechanism. Is this the right understanding? 

How does one control redelivery of messages, with at_least_once guarantee and asynchronous processing of messages in Node (and hence offset commits) in flowing mode?

In non-flowing mode, I don't think this is as big a concern, but only if we commit per message (but then again it has its costs). And how does one `not commit` if there is a processing error and want to re-process the message or any message after the message, given the consumer code is idemptotent?

Sorry if some of these are basic/stupid questions - but I'm new to asynchronously processing kafka messages in flowing mode and trying to learn the intricacies still.

**Comment by webmakersteve** [comment]
Kafka offsets are not stored just on a group basis. They are stored per group per topic per partition. No two consumers will ever be processing the same partition of messages, so they will never overwrite each other's offsets. 

If you need to process messages asynchronously you should keep track of each partition / topic and the each offset that has been processed. Then, commit the lowest common denominator.

**Comment by fsck-mount** [comment]
@prabugp Yes, you are correct. But if you see, Kafka does it's job.  it given you message1 and gave you message 2 and message 3 as well. And you committed msg3. Which means, you have arrived at msg 3 and committed. 

msg1 processing is up to you, It failed, so, you need to take care about it internally. At least once is guaranteed. If you don't want to skip any message processing failures, maintain redis queue or something which will have failed messages and you process them later.

**Comment by prabugp** [comment]
> If you need to process messages asynchronously you should keep track of each partition / topic and the each offset that has been processed. Then, commit the lowest common denominator.

This is what we have built as well. Thanks for confirming @webmakersteve @fsck-mount !

One related question: If we set the commit policy to manual (disable auto commit), and let's say that the processing of a message takes a long time, is there a timeout of sorts before Kafka/librd/noderd decides to re-deliver the message because the commit didn't arrive in time?

I understand when the consumer goes down before committing, kafka doesn't receive the heartbeat and a new consumer will get that message since the offset is not committed. But when the consumer is alive, what's the time before which it must commit?

**Comment by webmakersteve** [comment]
Kafka will not re-deliver the message to you as long as you are heartbeating with the broker. Librdkafka has a thread that handles that for you, so unless your application actually dies or loses network connectivity, this shouldn't be an issue. 

You have as long as you want to take to commit. And in `librdkafka`, your processing time is not linked to the heartbeat interval.

**Comment by syahiaoui** [comment]
Hi, I have the same probleme @rakshitajain5  did you find some solution ?
