### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by chetandev** [Blizzard/node-rdkafka#181]
Kafka topics contains more than 5 lakh records while consuming from single consumer i am getting following errors

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node::Abort() [node]
2: 0xfcde1c [node]
3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
6: 0xbd140c [node]
7: 0xbd1d75 [node]
8: v8::internal::JSObject::AddDataElement(v8::internal::Handlev8::internal::JSObject, unsigned int, v8::internal::Handlev8::internal::Object, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [node]
9: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handlev8::internal::Object, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [node]
10: v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handlev8::internal::Object, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [node]
11: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handlev8::internal::Object, v8::internal::Handlev8::internal::Object, v8::internal::Handlev8::internal::Object, v8::internal::LanguageMode) [node]
12: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0x1c3a509092a7

**Comment by webmakersteve** [comment]
Unfortunately this doesn't help me at all. I need to know how you are consuming. 

Additionally, if you can make an isolated test case that shows a memory leak it would be helpful. 

How much memory are you giving node for its new and old space? And have you tracked memory usage over time?

**Comment by eladitzhakian** [comment]
I'm also experiencing this memory leak.
The memory allocated for the node process is the default allocation (looks like ~1.3GB on my machine)
This is how the consumer is configured:
```
const consumer = new KafkaConsumer({
    'group.id': 'mygroupid',
    'metadata.broker.list': brokers,
  }, {
    'auto.offset.reset': 'earliest',
  })
```

**Comment by InfinitiesLoop** [comment]
What version of node? And on what platform are you running? More of your code is necessary to attempt to reproduce.

**Comment by eladitzhakian** [comment]
@InfinitiesLoop running within a docker container that runs Ubuntu 16.04. Node version is 7.9.0. here's the relevant consumer code:

```
  consumer.connect()
  logger.info('Waiting for consumer to become ready')
  await eventToPromise(consumer, 'ready')
  consumer.subscribe(topics)
  consumer.consume()
  return Observable.create(observer => {
    consumer.on('data', m => observer.next(m))
    consumer.on('error', err => observer.error(err))
    consumer.on('disconnected', () => {
            observer.complete()
    })
```

And where actually handling the events:
```
consumer
  .flatMap(async ({ event }) => handleEvent(event))
  .subscribe(
    () => { stats.processed += 1 },
    reject,
    resolve,
  )
```

**Comment by kidlj** [comment]
I'm facing the same problem, with 1m messages to consume.

```
<--- Last few GCs --->

[32398:0x392f990] 33316003 ms: Mark-sweep 1411.1 (1473.5) -> 1411.0 (1443.0) MB, 3217.9 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 3218 ms) last resort 
[32398:0x392f990] 33319564 ms: Mark-sweep 1411.0 (1443.0) -> 1410.9 (1443.0) MB, 3560.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x31f5cd79bbd9 <JS Object>
    1: _parsePacket [/usr/local/wemedia-platform/article-log/node_modules/mysql/lib/protocol/Protocol.js:270] [pc=0x15cb43bbd12](this=0x965f1db7689 <a Protocol with map 0x102b4a284409>)
    2: arguments adaptor frame: 1->0
    3: write [/usr/local/wemedia-platform/article-log/node_modules/mysql/lib/protocol/Parser.js:~27] [pc=0x15cb45239b8](this=0x965f1dbaf71 <a Parser with map 0x102b4a287ab1>,...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x136849c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewStruct(v8::internal::InstanceType) [node]
 6: v8::internal::Factory::NewTuple3(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
 7: v8::internal::LoadIC::LoadFromPrototype(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>) [node]
 8: v8::internal::LoadIC::GetMapIndependentHandler(v8::internal::LookupIterator*) [node]
 9: v8::internal::IC::ComputeHandler(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>) [node]
10: v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [node]
11: v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [node]
12: 0xf734df [node]
13: v8::internal::Runtime_KeyedLoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x15cb41840bd
Aborted

```
I'm using stream mode, Here's my consuming code:

```
const Kafka = require('node-rdkafka')
const log = require('./log')

let stream = Kafka.KafkaConsumer.createReadStream(
  {
    'metadata.broker.list': 'test1:9092,test2:9092',
    'group.id': 'node-consumer-test1',
    'socket.keepalive.enable': true,
    'enable.auto.commit': false
  },
  {
    'auto.offset.reset': 'earliest'
  },
  {
    'topics': ['userlog']
  }
)

let counter = 0
let numMessages = 10

stream.on('data', async function (m) {
  counter++
  try {
    // process this message 
    await processMessage(m)

    if (counter % numMessages === 0) {
      stream.consumer.commit()
    }
  } catch (error) {
    console.log(error)
  }
})

stream.on('error', function (err) {
  console.log('ERROR', err)
  process.exit(1)
})

stream.consumer.on('event.error', function (err) {
  console.log('ERROR', err)
})
```

At first 10-15 minutes it runs well, but later it can only process about 1 message per second, very slowly, and finally aborted because of out of memory.

**Comment by yoelfme** [comment]
hey @eladitzhakian how did you resolve your issue, because I'm also experiencing this memory leak? any ideas?

**Comment by erik-stephens** [comment]
@yoelfme This issue was created before edenhill/librdkafka#1384 resolved.  If your librdkafka version is before that one, then should upgrade.

**Comment by webmakersteve** [comment]
What function is returning that observable? Looking at your code right there it looks like it would probably be okay, unless you were falling behind on consuming messages.

I strongly recommend using the stream API instead of an observable so you could support backpressuing your stream so you do not fall behind. `librdkafka` unthrottled consumes very quickly.

But as @erik-stephens said, upgrading `librdkafka` is a good step if you are on an older version.
