### ISSUE TITLE
NPM dep files different than github

### ISSUE THREAD

**Issue by tinder-dyakobian** [Blizzard/node-rdkafka#183]
I was following the readme file and it said to use `Kafka.Producer.createWriteStream` but that wasn't working so I looked at the docs in the dep folder and it showed I should use `Kafka.Producer.getWriteStream`.

**Comment by webmakersteve** [comment]
Sorry about this. I am in between versions here! The README reflects the version that has not been released yet, but I plan on releasing it today so hopefully this discrepancy goes away

**Comment by webmakersteve** [comment]
The new version was released yesterday, so hopefully that fixes the issue.
