### ISSUE TITLE
Unable to produce message with an AVRO Key.

### ISSUE THREAD

**Issue by joelnet** [Blizzard/node-rdkafka#189]
I have created a publisher and consumer using the kafka-rest service found here: http://docs.confluent.io/current/kafka-rest/docs/intro.html. This is working fine.

I am attempting to convert the producer to use node-rdkafka, but **I am finding the AVRO keys are being truncated**.

Example of a good message (using kafka-rest):
```
{"key":"AAAAAAEGbm93","value":"AAAAAALAy6+TCw==","partition":0,"offset":46500,"topic":null}
```

Example of a bad message, missing key (using node-rdkafka):
```
{"key":"","value":"AAAAAALy/LiTCw==","partition":0,"offset":46567,"topic":null}
```

A couple experiments:
```
// Buffer's
const encodedKey = encode(schema.key, keySchemaId, key);
const encodedValue = encode(schema.value, valueSchemaId, value);

// key is a Buffer and will be truncated
producer.produce('topic', null, encodedValue, encodedKey);
> {"key":"","value":"AAAAAALy/LiTCw==","partition":0,"offset":46567,"topic":null}

// key is a string and will be truncated
producer.produce('topic', null, encodedValue, encodedKey.toString('utf8'));
> {"key":"","value":"AAAAAALy/LiTCw==","partition":0,"offset":46567,"topic":null}

// still truncated
producer.produce('topic', null, encodedValue, '\x00\x00\x00\x00\x01\x06now');
> {"key":"","value":"AAAAAALy/LiTCw==","partition":0,"offset":46567,"topic":null}

// key is double base64 encoded (and invalid)
producer.produce('topic', null, encodedValue, encodedKey.toString('base64'));
> {"key":"QUFBQUFBRUdibTkz","value":"AAAAAALy/LiTCw==","partition":0,"offset":46567,"topic":null}

// key will be set to TEST
producer.produce('topic', null, encodedValue, 'TEST\x00\x00\x00\x00\x01\x06now');
> {"key":"TEST","value":"AAAAAALy/LiTCw==","partition":0,"offset":46567,"topic":null}
```

based on my last test, it seems that the key is being truncated at the first `\x00`, most-likely due to null-termination.

I am guessing that node-rdkafka is calling a C++ `produce` method that is calling `key->size()` instead of another overload that will allow you to set the size of the key. (I'm looking in ProducerImpl.cpp at RdKafka::ProducerImpl::produce).

I'm not that familiar with calling C++ from node, so this is as far as I can take this issue.

Thank you for taking the time to read this :)

**Comment by webmakersteve** [comment]
Buffer keys are currently not supported, so all of the inputs for keys will end at the null terminator. If buffers work at all it is because they are getting casted to strings.

#190 Allows keys to be passed in as buffers, which should fix the problem you are having.

**Comment by joelnet** [comment]
Thanks for such a fast response!

I am testing this new branch with this code block: (encodedValue and encodedKey are both Buffers)
```
producer.produce(topic, null, encodedValue, encodedKey);
> {"key":"AAAAAAKyq8KTCw==","value":"AAAAAAKyq8KTCw==","partition":0,"offset":46598,"topic":null}
```

I have noticed the key is incorrectly set to the encodedValue, when it should be set to the encodedKey.

This code block works as expected and produces the correct message:
```
producer.produce(topic, null, encodedValue, encodedKey.toString());
> {"key":"AAAAAAEGbm93","value":"AAAAAAKm8cKTCw==","partition":0,"offset":46599,"topic":null}
```

Cheers!

**Comment by webmakersteve** [comment]
Can you try once more? Saw the typo!

**Comment by joelnet** [comment]
Everything works!

**Comment by wakurth** [comment]
Hi:

Any idea on when you will be cutting a minor release for this fix? I also went through the same set of troubleshooting steps as @joelnet only to find myself here at the end of the day :)

**Comment by smastous** [comment]
Hey guys, we're also running into this problem.  Is there anything we can do to help cut a release?  We'd be happy to do some PRs or write unit tests etc if more work is needed.

**Comment by joelnet** [comment]
I installed it directly from the buffer-keys branch with this command

`npm install Blizzard/node-rdkafka#buffer-keys`

**Comment by webmakersteve** [comment]
Cutting a release today!
