### ISSUE TITLE
librdkafka assertion on subscribe 

### ISSUE THREAD

**Issue by Pchelolo** [Blizzard/node-rdkafka#19]
This is just FYI since I don't think it's a bug in `librdkafka`, not here. When I create many processes with consumers that belong to the same consumer group, sometimes I get `librdkafka` assert on partition assignment: https://github.com/edenhill/librdkafka/issues/761 For now I've solved the problem by commenting out the code that sets up the `rebalance_cb` as it seem to fix that and use my own fork, but it would be nice to understand it better and fix. No particular steps to reproduce as well as no small test case unfortunately.

**Comment by webmakersteve** [comment]
Thanks for letting me know. I'll keep an eye out on the outstanding `librdkafka` issue.

**Comment by webmakersteve** [comment]
It looks like Magnus has added this to his 0.9.2 milestone. I'll be sure to keep an eye out for its release and update the packaged source when it ships.

**Comment by webmakersteve** [comment]
Rebalance is now opt-in so this should fix the issue without needing to comment out the `rebalance_cb`

**Comment by webmakersteve** [comment]
PR #56 should address assertion as it was patched in librdkafka. Merge pending CI pass

**Comment by webmakersteve** [comment]
Upgraded librdkafka which I believe fixes this issue. #114
