### ISSUE TITLE
isConnected returns an object

### ISSUE THREAD

**Issue by fega** [Blizzard/node-rdkafka#194]
checking this issue I found 

Client.prototype.isConnected = function() {
 return this._isConnected && this._client;
};
this returns the object, al least in node 6.11
look this example from repl
```
> let a,b
undefined
> a = {hello:"hello"}
{ hello: 'hello' }
> b = {hi:"hi"}
{ hi: 'hi' }
> (a && b)
{ hi: 'hi' }
```

**Comment by webmakersteve** [comment]
Fixed with 12b0d85da1f404741e0988757ed085d49da6867b
