### ISSUE TITLE
Delay when producing messages

### ISSUE THREAD

**Issue by HannesP** [Blizzard/node-rdkafka#200]
I used to use `kafka-node`, but switched to `node-rdkafka` due to bugginess in message consumption. However, that has left me with a new problem – message production appears to be much slower. Before, the message was sent immediately after it was created in the application. With `node-rdkafka`, it takes about 0.5 seconds before it's delivered. In my application that's an unacceptable delay. Can it be sped up somehow?

Here's the relevant parts of the code:
```
// Setting up the Kafka connection

const Kafka = require('node-rdkafka');

const producer = new Kafka.Producer({
    'metadata.broker.list': 'localhost:9092',
    'client.id': 'test-producer',
});

producer.connect();

// Creating messages

producer.produce('a-test-topic', null, new Buffer(some_string));
```

**Comment by edenhill** [comment]
Try setting ´queue.buffering.max.ms` to `1`

More info here:
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

**Comment by HannesP** [comment]
@edenhill That solved it. Many thanks!
