### ISSUE TITLE
Pause/resume consumption?

### ISSUE THREAD

**Issue by HannesP** [Blizzard/node-rdkafka#201]
In other Kafka APIs, I've seen methods to pause and resume consumption of messages (e.g. `KafkaConsumer#pause`). Is there something similar in `node-rdkafka`?

**Comment by patrixgdd** [comment]
Same here.
Please implement the pause() and resume().

**Comment by webmakersteve** [comment]
`librdkafka` does not expose such a thing. Here is the header file: https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1452

If you need to pause and resume you should consume `n` number of messages at a time. It will not consume for you unless you use the consume loop implementation, which is not recommended for applications such as this.

If you have an example of code you need to pause/resume in I can take a look to figure out the best way to adapt it.

**Comment by teckays** [comment]
@webmakersteve an example use case would be when using pattern topic subscription, ex:
```
...
consumer.subscribe(['^topic.*'])

consumer.on('data', data => {
  console.log('TOPIC:', data.topic)
})

// producing messages
producer.produce('topic.foo', null, new Buffer('Foo'))
// logs: TOPIC: topic.foo

// producing messages
producer.produce('topic.bar', null, new Buffer('Bar'))
// logs: TOPIC: topic.bar

// Listening to some external event emitters
EventEmitter.on('external.event', () => {
   consumer.pause('topic.foo')
})

// produce message and skip consuming until consumer.resume('topic.foo') is called
producer.produce('topic.foo', null, new Buffer('Foo'))
```

**Comment by fsck-mount** [comment]
@webmakersteve Any update here?
Here is another use case: 

I've a consumer in which I'll commit offsets manually. Let's say in case of any unexpected error or user interruption, we need to stop consuming the message ( an event listener on data) and commit the offsets via `consumer.commit()` and then need to disconnect via `consumer.disconnect()`. So, if the pause is not there, then few messages will be consumed after committing and before disconnecting. 

This problem has to be solved by using pause only. So, I guess pause is mandatory to have.

**Comment by webmakersteve** [comment]
It's fine if messages are consumed after you commit. As long as you don't commit their offsets they will get replayed when you rebalance.

In any event, I did find that pause and resume had been added, so they've been added (albeit, so far untested) to node-rdkafka.

https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L569-L595

**Comment by fsck-mount** [comment]
@webmakersteve  I guess, you didn't get what I'm trying to do. 

I agree with you that messages will be replayed., but here the thing we need to achieve exactly once. When the messages are replayed, we are going to have duplicated messages. But, if I pause the messages, and commit. Then I'll never have duplicated messages. 


To work around this, 

currently, 

```node
let stopping =  false;
consumer = new Kafka.KafkaConsumer();
consumer.on('ready', function () {
consumer.connect()
consumer.subscribe(['test']);
})

consumer.on('data', (m)=> {
if (stopping) {
processit(m)
}
})

function stop() {
stopping = true;
consumer.commit();
consumer.disconnect();
}
```

If puase is there, you don't need to worry about that, you can be sure that only those messages are committed.

**Comment by webmakersteve** [comment]
Okay, so you're trying to get exactly once semantics. You probably aren't going to get them, for a variety of potential reasons, no matter what you do using node-rdkafka right now.

Kafka didn't support exactly once until 0.11 and librdkafka is not built to do exactly once just yet. Your best bet is to consume ONE message at a time (do NOT use the stream as it fetches more than one), and do what you're doing in your application there, using a flag.

In any event, as I linked above, pause and resume have been implemented, but I just encourage you to not expect for kafka and librdkafka under the hood to be providing you exactly once and accommodate for duplication somehow in your application.

**Comment by fsck-mount** [comment]
@webmakersteve Yes, I get it. But all I'm trying to do is to reduce the duplicates. However thanks :) 👍

**Comment by bobrowadam** [comment]
@webmakersteve Did you happen to test the consumer.pause()/ resume() functions?

**Comment by webmakersteve** [comment]
Tests haven't been written for pause/resume. Will look at writing those soon (tm).
