### ISSUE TITLE
Tags missing for the latest published npm versions

### ISSUE THREAD

**Issue by AdrianVasiliu** [Blizzard/node-rdkafka#213]
The versions 1.0.2, 1.0.3, and 1.0.4 have been published to https://registry.npmjs.org/node-rdkafka, while the latest tag in the repo is 1.0.1 (https://github.com/Blizzard/node-rdkafka/tags).
Wouldn't be a good practice to systematically tag when `npm publish`ing?

**Comment by webmakersteve** [comment]
Correct. There are a few missing right now. It was because they ended up essentially being quick fixes to some problems we were seeing in our production environment (streamAsBatch fixed the issue for the most part).

I will tag the current latest with its release note(s).

**Comment by AdrianVasiliu** [comment]
ok, thanks @webmakersteve

**Comment by webmakersteve** [comment]
Just updated the releases. Am going to close this issue out. Again, it is my goal to have releases for all the releases, it was just a crazy week last week 😛
