### ISSUE TITLE
missing API to stop consuming 

### ISSUE THREAD

**Issue by cjolif** [Blizzard/node-rdkafka#218]
In the context of tests, I would like to stop consuming. More particularly I want to stop the infinite loop that is started when consume() is called. Calling disconnect() does not seem to stop the infinite loop and I don't see any "un-consume" API?

**Comment by webmakersteve** [comment]
`disconnect` should stop the infinite loop that is started after a few seconds. Are you not seeing that behavior?

**Comment by webmakersteve** [comment]
Additionally, https://github.com/Blizzard/node-rdkafka/commit/74e344f319ad66b46e796f618c1b6328c64a3caf added support for pause and resume.

**Comment by teckays** [comment]
@webmakersteve Wonder how is that working hence the following error is thrown:
```
Error pausing topic ReferenceError: topic is not defined
    at KafkaConsumer.pause (/Users/.../node_modules/node-rdkafka/lib/kafka-consumer.js:594:59)
```
[here](https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L594)

which is kind of weird where is `getWatermarkOffsets(topic, partition)`'s `topic, partition` coming from if the method parameter is `topicPartitions`

**Comment by evollu** [comment]
looks like the implementation code is copied over into multiple methods like `pause` and `resume`?

**Comment by teckays** [comment]
Looks like none of the NodeJS libraries offer advanced consumer/producer API's which kinda pushes me toward a pure Scala implementation (which is not necessarily a bad thing)

**Comment by akowpak-ssimwave** [comment]
Perhaps I'm doing something wrong, but, it doesn't appear that disconnect is stopping the infinite loop for me.  I have this code:

```
