### ISSUE TITLE
Loading problem in node-bindings dependency with Angular 4

### ISSUE THREAD

**Issue by alis-sol** [Blizzard/node-rdkafka#219]
Hello,

Sorry in advance if this is a noob problem, but I'm new to front-end development and it seems like I must've been a really bad person all these years and thus been sent to hell. The latest problem is loading/using node-rdkafka and its dependencies, although it doesn't seem to be node-rdkafka's fault.

I'm using Angular 4 / Node (all latest) and tried loading node-rdkafka. After struggling a lot to get the require function to be found and finally load node-rdkafka, I got an error while loading its node-bindings dependency. I found https://github.com/TooTallNate/node-bindings/pull/20 and checked out the current master head with the fix (commit 228973f31d1fcda05c1745f8ca1d74e19c9bc9ca), but I still get the following error:

Uncaught TypeError: exists is not a function
    at Function.getRoot (bindings.js:158)
    at bindings (bindings.js:60)
    at Object.../../../../node-rdkafka/librdkafka.js (librdkafka.js:10)
    at __webpack_require__ (bootstrap 592fa04…:54)
    at Object.../../../../node-rdkafka/lib/client.js (client.js:14)
    at __webpack_require__ (bootstrap 592fa04…:54)
    at Object.../../../../node-rdkafka/lib/kafka-consumer.js (kafka-consumer.js:13)
    at __webpack_require__ (bootstrap 592fa04…:54)
    at Object.../../../../node-rdkafka/lib/index.js (index.js:10)
    at __webpack_require__ (bootstrap 592fa04…:54)

Thanks for any help,

Carlos

**Comment by alis-sol** [comment]
I also get these warnings when runnning ng serve:

WARNING in ./~/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression

**Comment by webmakersteve** [comment]
This is going to work in a front end environment :( We rely on c++ bindings to work, unless I'm misunderstanding what you're trying to do.

**Comment by caeaugusto** [comment]
Thank you for the response. What I need to do is receive kafka messages on web clients (notifications) and I don't know if I'm missing anything obvious here. I understand that I can translate kafka messaging to web sockets on a server but that was what I wanted to avoid at the beginning since a kafka tcp client existed. A few months ago I learned about confluent's rest proxy, it seems to be just that but I didn't have time to take a look at it yet.

Do you have a better option for receiving kafka messages on web clients?

**Comment by alis-sol** [comment]
Thank you for the response. What I need to do is receive kafka messages on web clients (notifications) and I don't know if I'm missing anything obvious here. I understand that I can translate kafka messaging to web sockets on a server but that was what I wanted to avoid at the beginning since a kafka tcp client existed. A few months ago I learned about confluent's rest proxy, it seems to be just that but I didn't have time to take a look at it yet.
Do you have a better option for receiving kafka messages on web clients?

**Comment by webmakersteve** [comment]
I don't particularly have any recommended solution for consuming kafka messages on web clients. A pure-javascript front end capable kafka would be a totally different project that used totally different technologies to make it work.

I've never had to do what you're suggesting, but having some sort of rest proxy seems to be the way to go for the web.

**Comment by alis-sol** [comment]
Ok Stephen, thank you very much for taking your time!

Cheers

**Comment by webmakersteve** [comment]
No problem! Good luck!
