### ISSUE TITLE
KafkaConsumer.consume(cb) doesn't exist

### ISSUE THREAD

**Issue by hugebdu** [Blizzard/node-rdkafka#220]
though is mentioned in API.

See [`else`](https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L352) branching - it cannot handle callback as a first argument.

**Comment by webmakersteve** [comment]
You're right. This was deprecated several versions ago. I can update the docs - where did you see it?

**Comment by webmakersteve** [comment]
You're right. That specific syntax was deprecated. I updated it in master so it should work the way you're using it, but unless you want to use it from master until I upgrade it, provide `undefined` as the first parameter and it should work.

https://github.com/Blizzard/node-rdkafka/commit/5396cfd2ff1497a0a9ef0d563fd03c9e4b640154

**Comment by hugebdu** [comment]
That's what i do.
Thanks!

**Comment by webmakersteve** [comment]
Released!
