### ISSUE TITLE
Authentication failure: (errno: Invalid argument) when Produce to secured sasl plain kafka.

### ISSUE THREAD

**Issue by armenthiz** [Blizzard/node-rdkafka#221]
Recently i was following https://developer.ibm.com/opentech/2017/05/31/kafka-acls-in-practice/ to enabled SASL PLAIN security in kafka.

Then when i want to use this library for produce to kafka secured sasl plain topic. i get this error

`Authentication failure: (errno: Invalid argument)`

This is code that i use to produce.

    var Kafka = require('node-rdkafka');
    var producer = Kafka.Producer({
      'debug': 'all',
      'metadata.broker.list': 'localhost:9092',
      'security.protocol': 'sasl_plaintext',
      'sasl.username': 'root',
      'sasl.password': 'admin!',
      'sasl.mechanisms': 'PLAIN',
    });

    // producer.connect();
    producer.connect(null, (err, metadata) => {
       console.log(metadata);
       console.error(err);
       console.log('Connected')
    });

    producer.on('ready', function () {
      try {
        producer.produce('topic1', null, new Buffer('Awesome'), null, Date.now())
      } catch (err) {
        console.log('A error occured')
      }
    });

    // Any errors we encounter, including connection errors
    producer.on('event.error', function(err) {
      console.log('Error from producer');
      console.log(err);
    })

    producer
      .on('event.log', function(event) {
          console.log(event)
          const loggedEvent = {
            severity: event.severity,
            fac: event.fac
          };

          if (event.severity >= 7) {
            console.log(loggedEvent, event.message);
          } else if (event.severity === 6 || event.severity === 5) {
            console.log(loggedEvent, event.message);
          } else if (event.severity === 4) {
            console.log(loggedEvent, event.message);
          } else if (event.severity > 0) {
            console.log(loggedEvent, event.message);
          } else {
            console.log(loggedEvent, event.message);
          }
    })

**Comment by webmakersteve** [comment]
I believe this happens when librdkafka is compiled without support for the authentication method you are using, but SASL should be enabled by default.

I'm going to add a method to help debug these types of issues and I'll release it today.

**Comment by webmakersteve** [comment]
I have published a new release (1.0.6) that has a `features` property on the `node-rdkafka` object. Can you `console.log` the result of that?

```js
const kafka = require('node-rdkafka');
console.log(kafka.features);
console.log(kafka.librdkafkaVersion);
```

**Comment by desiena** [comment]
Hi Steve. I'm seeing the same issue when producing with SASL_SSL. The output of the code you posted is 
```
[ 'gzip', 'snappy', 'ssl', 'sasl', 'regex', 'lz4' ]
0.9.5
```

**Comment by webmakersteve** [comment]
Can you add the config field `debug: 'security'` to your config and then post the logs of running your code there? It should give more information about authentication.

**Comment by desiena** [comment]
I get two types of messages, those with `Broker SSL certificate verified` and those with `Auth in state CONNECT (handshake not supported)`.  I've found that adding `'api.version.request': true`, as specified [here](https://github.com/ibm-messaging/message-hub-samples/issues/16), to the config solves this problem.

**Comment by webmakersteve** [comment]
Cool. If that fixes your issue I think we should add it to the docs or a wiki on the repo so it can help others who have similar problems. I'll leave the issue open until those docs are complete, unless you're having any additional problems.

**Comment by desiena** [comment]
Sounds good. I'm not sure if this solves armenthiz's problem with sasl_plaintext though.

**Comment by desiena** [comment]
Also, that config solves a similar issue with the consumer.
