### ISSUE TITLE
Which version of apache/kafka is the latest to support?

### ISSUE THREAD

**Issue by kylezhang** [Blizzard/node-rdkafka#223]
## Which version of apache/kafka is the latest to support?
` 0.10.x or 0.11.x `

**Comment by webmakersteve** [comment]
I think `librdkafka` is tested on 0.10.x but it is said to support anything >= 0.9

**Comment by kylezhang** [comment]
Thanks for your answer, but i hope your answer [like this](https://github.com/SOHU-Co/kafka-node/issues/712)
`0.11 should work without any issues.`
