### ISSUE TITLE
npm ERR! node-rdkafka@1.0.6 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by ecastill** [Blizzard/node-rdkafka#225]
node-rdkafka stops the server from installing my project, I've added some of the errors I get below

* npm WARN optional dep failed, continuing snappy@5.0.5
* gyp ERR! not ok
* gyp ERR! node-gyp -v v2.0.1
* gyp ERR! node -v v4.2.4
* gyp ERR! cwd /app/node_modules/jda-rest-storage/node_modules/kafka-node/node_modules/snappy
* gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
* npm ERR! Linux 2.6.32-642.15.1.el6.x86_64
* npm ERR! Exit status 1
* npm ERR! node-rdkafka@1.0.6 install: `node-gyp rebuild`
* npm ERR! This is most likely a problem with the node-rdkafka package,
* npm ERR! Failed at the node-rdkafka@1.0.6 install script 'node-gyp rebuild'.
* npm ERR!

**Comment by edoardocomar** [comment]
I experienced errors in the gyp build when I had the CDPATH env variable set

**Comment by webmakersteve** [comment]
I'm a little confused here. I'm seeing errors about `kafka-node` and the `snappy` dependency. We do not have a dependency on snappy in this library. 

Also, that node-rdkafka version is a little outdated. Can you try using version 2? And do you have SASL installed?

**Comment by matthax** [comment]
You're installing the wrong library, the errors are for The `node-kafka` library which has an optional dependency on `snappy`. If you're on Windows you'll need to install `snappy` and make sure you've got the correct windows build tools.

**Comment by webmakersteve** [comment]
I'm going to close this issue as we haven't had any new information in a while. Please re-open if you're still experiencing problems (and are using the right library!)
