### ISSUE TITLE
Replay ability

### ISSUE THREAD

**Issue by FuzzOli87** [Blizzard/node-rdkafka#226]
Hello!

I've been looking for a way to tell a consumer to read from a certain offset. 'auto.offset.reset' works only if I change the groupId. 

Do you have any suggestions into how to do something like this?

**Comment by webmakersteve** [comment]
The suggested way to do this is to use `seek` to go to the offsets for each topic partition you want to read from. This should be available in the most recent version of hte library.

Sorry for the late response! Things sometimes fall through the cracks in GitHub issues ><

**Comment by FuzzOli87** [comment]
@webmakersteve Thanks for responding! I learned a long time ago that when it comes to open source, patience and understanding is key. 

I haven't had to use this feature yet, but we are about to start implementing a way to recreate state on application start as a local store so we will start using it soon.
