### ISSUE TITLE
node-rdkafka not using default partitioner when none set.

### ISSUE THREAD

**Issue by rhysmccaig** [Blizzard/node-rdkafka#23]
I had made a minor change in https://github.com/Blizzard/node-rdkafka/pull/22 that i thought would fix the default partitioning behavior, but some subsequent tests seem to indicate that this fix hasn't worked.

Manually setting partition to -1 in the produce function works, but when not specifying a partition, all my messages are still being put into partition 0.

Note that i need to verify that i haven't done something boneheaded in my own code (like using the wrong branch..) and will review in more detail this evening, but wanted to get this in here in case anyone else sees this issue. Im not experienced in c++ but will see if i can at least add some unit tests for the behaviour.

**Comment by webmakersteve** [comment]
You did fix it in c++ land but it wasn't fixed in JS land. Can you try this fix?

https://github.com/Blizzard/node-rdkafka/tree/js-partition-fix

That also does some stuff on the JS side.

**Comment by rhysmccaig** [comment]
Yep, will test this out shortly

**Comment by rhysmccaig** [comment]
Perfect - that solved the problem. Thanks Steve.

**Comment by webmakersteve** [comment]
No problem! Will publish this momentarily.

**Comment by webmakersteve** [comment]
Published.
