### ISSUE TITLE
Kafka Admin API

### ISSUE THREAD

**Issue by MrDHat** [Blizzard/node-rdkafka#238]
For our use case, we need an ability to manage ACL and create topics on the fly using the node app. Does the library support that?

**Comment by webmakersteve** [comment]
No. `librdkafka` does not yet support using the admin API because it is very new in Kafka. I believe it will be adding the support in the future, and when it does, we will support it :)

**Comment by MrDHat** [comment]
Ah.. ok. Seems like we'll have to go for Java for this project. Thanks!
