### ISSUE TITLE
On running "npm install node-rdkafka" getting error

### ISSUE THREAD

**Issue by asinha08** [Blizzard/node-rdkafka#245]
On Ubuntu 16.04, NodeJS v6.11.2

On running "npm install node-rdkafka" getting following error
../deps/librdkafka/src/rdkafka_sasl_cyrus.c:39:23: fatal error: sasl/sasl.h: No such file or directory
compilation terminated.
deps/librdkafka.target.mk:158: recipe for target 'Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_cyrus.o' failed

**Comment by webmakersteve** [comment]
Have you installed `libsasl-dev` on your machine? Currently it is required for running node-rdkafka.

**Comment by asinha08** [comment]
Thanks it works.
