### ISSUE TITLE
Memory Leak in 2.0.0

### ISSUE THREAD

**Issue by jeffmontagna** [Blizzard/node-rdkafka#246]
When running the consumer-flow example with the 30 second timer removed all system memory will be consumed.

node: 4.8.4 and 8.4.0
Kafka: 0.11.0
Ubuntu: 16.04 VM
RAM: 2G
Result: Consumes all memory within 5-10 minutes

Changing some of the V8 options like `--max-old-space-size=1024` only results in a quicker
crash.  There's no memory leak with 2.0.0 in OS X or using the master branch with 0.11.0 of rdkafka library.  This same behavior was obvserved in another application the uses KafkaConsumer, but with auto commit set to true.

**Comment by krystianity** [comment]
We are having a similar issue.

**Comment by kstaken** [comment]
What was the reason that the library was rolled back from librdkafka 0.11.0 to 0.9.5? We're definitely seeing off heap leaks that appeared to be resolved with the new version of the dependency.

**Comment by edenhill** [comment]
You are most likely seeing librdkafka issue https://github.com/edenhill/librdkafka/issues/1384

**Comment by webmakersteve** [comment]
We rolled back because an issue with producing null keys that has since been fixed. Will upgrade as soon as that is released, and I believe it is close to being released.

**Comment by krystianity** [comment]
To anyone else that might land here, with memory consumption issues: You just might be missing some config [params](https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/README.md#memory-usage)

**Comment by kstaken** [comment]
Did the updated librdkafka ever get released? Still blockers on moving this library to it?

**Comment by webmakersteve** [comment]
A release candidate was "released" yesterday. I am going to make a build with the release candidate but not publish it to NPM until it has been officially released.

**Comment by webmakersteve** [comment]
New version released with 0.11.1!
