### ISSUE TITLE
Authentication increasing the latency?

### ISSUE THREAD

**Issue by vishnuchittamuru** [Blizzard/node-rdkafka#250]
Description:

Using node-rdkafka to connect to a secure cluster is causing some serious lag when reading and writing messages. The scenario is a simple round trip communication between two services.
service1 -> writes to topicA and reads from topicB
service2 -> reads from topicA and writes to topicB

The initial round trip time is well over 3s for a message. After researching on how to reduce latency and going through different issues and wiki entries, we found that the settings 
> queue.buffering.max.ms
> fetch.wait.max.ms
> fetch.error.backoff.ms
> waitInterval

impact the latency of the reads and writes. Using these, we were able to get the round trip time to much less than 3s in the local Kafka instance(non-secure).

When trying to connect to the secure Cluster with authentication in place and with the same settings mentioned above, the latency is not consistent. It is varying from less than a 100ms to more than 5s. If the messages are coming in with enough time between them, it is performing as expected. If there are continuous stream of messages, the time taken is going very high. 

I would assume the authentication would add a couple milliseconds to the time but not a couple of seconds. I was wondering if there might be any other settings that might be causing this delay. 

Any help would be greatly appreciated!!!

Versions:
node-rdkafka - 2.0.0
nodejs - 8.x.x
kafka - 0.10.x

**Comment by edenhill** [comment]
Please share your anonymised client configuration (auth mechanism in particular).
You may also enable debug=protocol,security to see what is going on under the hood, look for the protocol response round-trip-times (rtt).

**Comment by vishnuchittamuru** [comment]
The issue was due to internal network.
Thanks.
