### ISSUE TITLE
Consumer doesn't throw when attempting to subscribe before unsubscribing

### ISSUE THREAD

**Issue by FuzzOli87** [Blizzard/node-rdkafka#251]
```
const kafka = require('node-rdkafka');
const delay = require('delay');

const consumer = new kafka.KafkaConsumer({
  'group.id': 'consumer',
  'metadata.broker.list': 'kafka:9092',
  'broker.version.fallback': '0.10.0', // If kafka node doesn't have API, use this instead
  'api.version.request': true, // Request the api version of Kafka node
  event_cb: true
});

consumer.on('error', error => console.log('errorz', error));
consumer.on('event.log', log => console.log('event log'));
consumer.on('error', log => console.log('error'));
consumer.on('unsubscribed', log => console.log('unsubscribed'));
consumer.connect();

function subscribeTestTopic(zconsumer) {
  zconsumer.subscribe(['TEST_TOPIC_TWO']);
  zconsumer.consume();
  zconsumer.on('data', (data) => {
    console.log('DATA RECEIVED TEST', data);
    const dataMsg = JSON.parse(data.value.toString());
    console.log('parsed data', dataMsg);
  });
}

function subscribeTestInternalTopic(zconsumer) {
  zconsumer.subscribe(['TEST_TOPIC_INTERNAL']);
  zconsumer.consume();
  zconsumer.on('data', (data) => {
    console.log('DATA RECEIVED Internal', data);
    const dataMsg = JSON.parse(data.value.toString());
    console.log('parsed data', dataMsg);
  });
}

consumer.on('ready', () => {
  console.log('consumer is ready');
  subscribeTestTopic(consumer);
  consumer.unsubscribe();
  subscribeTestInternalTopic(consumer);

  const producer = new kafka.Producer({
    'metadata.broker.list': 'kafka:9092',
    'broker.version.fallback': '0.10.0', // If kafka node doesn't have API, use this instead
    'api.version.request': true // Request the api version of Kafka node
  });

  producer.connect();
  producer.on('ready', () => {
    console.log('producer is ready');
    try {
      delay(8000).then(() => {
        console.log('producing');
        producer.produce(
          'TEST_TOPIC_INTERNAL',
          null,
          Buffer.from(JSON.stringify({ test: 'test' }))
        );
        producer.produce('TEST_TOPIC_TWO', null, Buffer.from(JSON.stringify({ test: 'test' })));
      });
    } catch (e) {
      console.error(e);
    }
  });

```

I expected the code to throw an error when attempting to subscribe twice but nothing. When the producer puts out both events, the original subscribed event still fires. However, it fires with the message of the TEST_TOPIC_INTERNAL. In other words, it "unsubscribed" from the TEST_TOPIC_TWO topic but the listener still fires and is picked up twice. 

Am I missing something here? It doesn't look like unsubscribe ditches the original callback assigned to then "ready" event which leads to duplicate handling in this case.

**Comment by webmakersteve** [comment]
It looks like you're calling unsubscribe between the two subscribes.

If you still get some messages from the first topic you unsubscribed form it is probably because they have already been read on the first connect and are in `librdkafka`'s internal buffer.

Or maybe I'm misunderstanding your issue. Which listener is firing? I assume the `data` listener?

**Comment by krystianity** [comment]
1. There is no error event, because you call `unsubscribe`
2. `consumer.on("ready",..)` will only fire once for the `.connect()` call
3. as Stephen said you might see more `data` events, because there might be messages still being processed from the buffer

**Comment by FuzzOli87** [comment]
Hi @webmakersteve @krystianity 

Sorry for the late response! I was at a conference.

You are right, the example I gave was cloudy. Essentially what I was attempting to show is that my own expectation when I call "unsubscribe" from a consumer is that messages will no longer be received from any handler.

During my local testing, I found that calling unsubscribe and immediately subscribing to another topic led to the previous handler triggering as well. It wasn't detached from the listeners of the previous unsubscribed topic. The handler would NOT trigger if I put a message in from the unsubscribed topic, which means it works with that, but the previous handler fired for the new subscribed topic.

So, I think maybe my expectations where wrong. It looks like unsubscribe is meant to keep the SAME handler configured once and just listen to different topics. The way I attempted to use it was that not only did unsubscribe ditch the old topics but also the handlers configured for it.

**Comment by webmakersteve** [comment]
Correct. If you want to do what you're describing it may be better to have multiple consumers. The handlers are not cleared on a new subscription.

I'm going to close the issue but feel free to open it if you still have outstanding questions.
