### ISSUE TITLE
Is version 2.0.0 using librdkafka 0.11.0?

### ISSUE THREAD

**Issue by ancashoria** [Blizzard/node-rdkafka#252]
Hi, 
I have installed the latest `node-rdkafka` version from npm (2.0.0) when I run `console.log(Kafka.librdkafkaVersion)` I get 0.9.5. 
Is there any way to get a version of `node-rdkafka` that uses `librdkafka@0.11.0`?

Thanks

**Comment by webmakersteve** [comment]
No. There is a bug I am waiting to be fixed in `librdkafka`. Once that is upgraded, I will upgrade `node-rdkafka` to use the updated version.

**Comment by ancashoria** [comment]
Alright, thanks. Looking forward to the update.
