### ISSUE TITLE
Error when running in docker container

### ISSUE THREAD

**Issue by quorak** [Blizzard/node-rdkafka#258]
hey there,

thx for the great work. Just came about one issue, when running it in a docker container:
```
events.js:182
       throw er; // Unhandled 'error' event
       ^
 Error: Failed to create thread: Resource temporarily unavailable (11)
```
It works like a charm, when running it directly. So do you know if I need to set some special values in the container?

this is my dockerfile
```
# Do the npm install or yarn install in the full image
FROM node:alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        bash \
        g++ \
    && WITH_SASL=0  yarn install --production \
    && apk del .gyp 


WORKDIR /app
COPY . .
EXPOSE 3000
CMD ["npm", "run", "stream"]
```

I"m using the stream API like:
```
var Kafka = require('node-rdkafka');


// Read from the librdtesting-01 topic... note that this creates a new stream on each call!
var stream = Kafka.KafkaConsumer.createReadStream({
  'group.id': 'abc', // Specifies an identifier to use to help trace activity in Kafka
  'metadata.broker.list': 'kafka_1:9092', // Connect to a Kafka instance on localhost
  'auto.offset.reset':'latest'
}, {}, {
  topics: ['t1']
});




stream.on('data', function(message) {
  console.log('Got message');
  console.log(message.value.toString());
});
```

**Comment by webmakersteve** [comment]
What docker image are you using? This happens with some of the really tiny ones that ship with a different version of glibc - like Alpine. If you're using one of those you will need to install the full version of glib c to get this to work properly.

**Comment by webmakersteve** [comment]
See if this helps you any: https://github.com/Blizzard/node-rdkafka/issues/125

**Comment by FuzzOli87** [comment]
@quorak I have had no luck allowing node-rdkafka to build librdkafka in an Alpine image. I've tried all sorts of combinations and packages.

I have a ton of luck installing it native and not letting this library build it.

**Comment by webmakersteve** [comment]
I believe the alpine issues have been fixed on the master branch. If you'd like to try that, please go ahead.
