### ISSUE TITLE
Unexpected high latency

### ISSUE THREAD

**Issue by 0x530302** [Blizzard/node-rdkafka#259]
I use the following code to measure the time it takes to consume a message after producing it.
The delay is usually either around 500 ms or 1000 ms.
However, by analyzing this scenario with Wireshark I found out that only around 7 ms have passed between the produce request and the fetch response, that includes the message.
So somewhere between receiving the messages and actually emitting the `data` event, one second is "wasted".
Is there maybe a configuration parameter that I missed, to reduce the time messages remain in some kind of consumer input queue?

I already played around with the parameters mentioned in [How-to-decrease-message-latency](https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency), which didn't help much.

```javascript
const Kafka = require('node-rdkafka');

const host = process.argv[2] || 'localhost:9092';
const groupId = `node-rdkafka-${Math.random()}`;
const topic = 'test';

const options = {
    'group.id': groupId,
    'metadata.broker.list': host,
    'queue.buffering.max.ms': 0,
    'fetch.wait.max.ms': 1
};

const producer = new Kafka.Producer(options);
const consumer = new Kafka.KafkaConsumer(options, {});

producer.connect()
    .once('ready', () => {
        consumer.connect()
            .once('ready', () => {
                consumer.subscribe([topic]);
                consumer.consume();
                setTimeout(() => {
                    console.time('delay');
                    producer.produce(topic, null, new Buffer('payload-' + groupId), null);
                }, 1000);
            })
            .once('event.error', err => {
                console.error(err);
                process.exit(1);
            })
            .once('data', message => {
                console.timeEnd('delay');
                message.value = message.value.toString();
                consumer.disconnect();
                producer.disconnect();
                process.exit(0);
            });
    })
    .once('event.error', err => {
        console.error(err);
        process.exit(1);
    });
```

**Comment by 0x530302** [comment]
After digging a little deeper, I found out that the actual delivery to kafka was delayed and not the consumption of the message. Setting `socket.blocking.max.ms` to a lower value decreased the latency to a reasonable value. I first ignored that parameter, as it was marked as deprecated in the librdkafka documentation `¯\_(ツ)_/¯`

**Comment by spro** [comment]
Thanks, saved me some time writing up a very similar issue. I also passed over that blocking option at first.
