### ISSUE TITLE
[SOLVED] configuration property "ssl.ca.location" is not available in C code on OS X 10.12.6 node v8.6 npm 5.4.2

### ISSUE THREAD

**Issue by liesislukas** [Blizzard/node-rdkafka#262]
Hi, started writing issue report but fixed and i wanted to share my findings, so leaving here. 

OS X 10.12.6
Node v8.6.0
npm 5.4.2

openssl installed with brew

```

 setup server error
error: {
    "type": "other",
    "statusCode": 500,
    "details": {
      "message": "No such configuration property: \"ssl.ca.location\""
    }
  }

stack: Error: No such configuration property: "ssl.ca.location"
    at Producer.Client (/Users/lukas/Desktop/www/node_modules/node-rdkafka/lib/client.js:54:18)
    at new Producer (/Users/lukas/Desktop/www/node_modules/node-rdkafka/lib/producer.js:71:10)
    at new Producer (/Users/lukas/Desktop/www/node_modules/@company-stuff/lib/producer.js:32:20)
    at Function.Producer.new (/Users/lukas/Desktop/www/node_modules/@company-stuff/lib/producer.js:40:10)
    at Object.<anonymous> (/Users/lukas/Desktop/www/lib/enf.js:9:30)
```

For debugging I added couple console.log lines in client.js before line 54:

```
  console.log('globalConf: ', JSON.stringify(globalConf, null, 2));
  console.log('topicConf: ', JSON.stringify(topicConf, null, 2));

  this._client = new SubClientType(globalConf, topicConf);

```

and console logs:

```
globalConf:  {
  "metadata.broker.list": "xxxx....srvs.cloudkafka.com:xxxx",
  "ssl.ca.location": "/Users/lukas/Desktop/www/.full.path....kafka.ca",
  "ssl.certificate.location": "/Users/lukas/Desktop/www/...full.path...kafka.cert",
  "ssl.key.location": "/Users/lukas/Desktop/www/...full.path...kafka.pkey",
  "ssl.key.password": "foobarbaz",
  "security.protocol": "ssl"
}
topicConf:  {}
```

so `ssl.ca.location` does exist in globalConf object.

Only place where i find `No such configuration property` error message is in `rdkafka_conf.c`

![image](https://user-images.githubusercontent.com/2733862/31385595-8179f466-adcc-11e7-9907-b193ccb9aedf.png)

so i guess something with build process is incorrect. 

I added these 2 to `~/.bashrc`

```
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
```

and it fixed the issue after `rm -rf node_modules` and `npm i` in a new terminal window

cheers

**Comment by webmakersteve** [comment]
It looks like it isn't linking with openssl correctly. Adding those flags just is forcing it to find the open ssl install you're using, which then activates those configuration parameters internally in librdkafka.

I think this still may be an issue

**Comment by liesislukas** [comment]
started working with new MacBook and had same issue, so glad I left here this solution, it was the way out again. all software up to date. Issue is still there and is exactly the same.

**Comment by jyono** [comment]
im having this issue as well

**Comment by jyono** [comment]
this fixed it for the producer, but im having this issue for the consumer

**Comment by SpeCT** [comment]
Hey @liesislukas 
it's funny, but in 2020 we're still fighting this issue ;)

This time I'm using docker (`node:8`). It works ok with 8.10 and 8.11, but fails with `No such configuration property: "ssl.ca.location"` on <8.13.

**Comment by liesislukas** [comment]
@SpeCT  just now noticed notification :)) I moved all to aws, no more kafka, managed services solves such issues.
