### ISSUE TITLE
Installation Failed 

### ISSUE THREAD

**Issue by naveenkerati** [Blizzard/node-rdkafka#263]
I tried to install the node-rdkafka on Amazon Linux . But I got the following Configuration failure. I am running the latest node.js and npm version. 
###########################################################
###########################################################
###########################################################
 cc (WITH_CC)
    module: cc
    action: fail
    reason:
command 'cc --version' failed:
mklove/modules/configure.base: line 1114: cc: command not found

 cxx (WITH_CXX) C++ compiler (c++)
    module: cc
    action: fail
    reason:
command 'c++ --version' failed:
mklove/modules/configure.base: line 1114: c++: command not found

 socket_nsl ()
    module: socket
    action: fail
    reason:
compile check failed:
CC: CC
flags:
  -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror  _mkltmpVLNqZI.c -o _mkltmpVLNqZI.c.o -lsocket -lnsl :
mklove/modules/configure.base: line 917: -g: command not found
source:
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
void foo (void) {
   int s = socket(0, 0, 0);
   close(s);
}

 libpthread ()
    module: librdkafka
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lpthread
  -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror -lpthread _mkltmpaDgJtW.c -o _mkltmpaDgJtW.c.o  :
mklove/modules/configure.base: line 917: -g: command not found
source: #include <pthread.h>

make: *** [deps/librdkafka/config.h] Error 1
make: Leaving directory `/home/ec2-user/consumer/node_modules/node-rdkafka/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.43-17.39.amzn1.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/consumer/node_modules/node-rdkafka
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN kafka-apis@1.0.0 No repository field.
npm ERR! Linux 4.9.43-17.39.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-rdkafka" "--save"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-rdkafka@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-rdkafka package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-rdkafka
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-rdkafka
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/consumer/npm-debug.log

**Comment by webmakersteve** [comment]
It looks like you're missing some essential build tools. Does amazon linux have the yum group "Development Tools"? I would try to start there and after installing all the build tooling trying to build again.

**Comment by naveenkerati** [comment]
Yes, I have missed the installing packages
yum install gcc-c++ python-devel.x86_64 cyrus-sasl-devel.x86_64
installing above packages solved the issue
