### ISSUE TITLE
Version 2.1.1 install error

### ISSUE THREAD

**Issue by patrixgdd** [Blizzard/node-rdkafka#268]
Hi ,
I have tried the 2.1.1 with node 8.7.0.
It compiled with error.
The version 2.1.0 is working fine though.

ERR LOG:

/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install node-rdkafka@2.1.1

Standard error:
ld: library not found for -llz4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node-librdkafka.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxxxx/repos/gxxxx-data-collector/node_modules/node-rdkafka
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2017-10-19T04_03_24_643Z-debug.log

**Comment by webmakersteve** [comment]
Can you send the configure logs for librdkafka? They should appear earlier in the build.

**Comment by patrixgdd** [comment]
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install node-rdkafka@2.1.1

Standard error:
ld: library not found for -llz4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node-librdkafka.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxxxxx/repos/gxxx-data-collector/node_modules/node-rdkafka
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxxx/.npm/_logs/2017-10-20T01_44_00_103Z-debug.log


Standard output:

> node-rdkafka@2.1.1 preinstall /Users/xxxxxx/repos/gxxx-data-collector/node_modules/node-rdkafka
> node util/configure

checking for OS or distribution... ok (osx)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for debug symbols compiler flag (-g...)... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... failed
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... failed
checking for OSX linker options... ok
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... failed (ignore)
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x000b01ff'... ok (0.11.1)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... ok
checking for liblz4 (by compile)... ok (cached)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... ok
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... failed
checking for strndup (by compile)... ok
checking for strerror_r (by compile)... ok
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for nm (by env NM)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               osx
  SOLIB_EXT                .dylib
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -dynamiclib -Wl,-install_name,$(DESTDIR)$(libdir)/$(LIBFILENAME)
  RDKAFKA_VERSION_STR      0.11.1
  MKL_APP_VERSION          0.11.1
  LIBS                     -lpthread -L/opt/local/lib -lz -L/opt/local/lib -lcrypto -L/opt/local/lib -llz4 -L/opt/local/lib -lssl -L/opt/local/lib -lsasl2 -ldl
  CFLAGS                   -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -g
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build

> node-rdkafka@2.1.1 install /Users/xxxxxxx/repos/gxxxx-data-collector/node_modules/node-rdkafka
> node-gyp rebuild

  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_broker.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msg.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_topic.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_conf.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_timer.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_offset.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_transport.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_buf.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_queue.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_op.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_request.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_cgrp.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_pattern.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_partition.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_subscription.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_assignor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_range_assignor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_roundrobin_assignor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_feature.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdcrc32.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/crc32c.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdaddr.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdrand.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdlist.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/tinycthread.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdlog.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdstring.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_event.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_metadata.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdregex.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdports.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_metadata_cache.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdavl.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_plain.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_interceptor.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msgset_writer.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_msgset_reader.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdvarint.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdbuf.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdunittest.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_lz4.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/xxhash.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/lz4.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/lz4frame.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/lz4hc.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_cyrus.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_sasl_scram.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/snappy.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdgz.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rddl.o
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka_plugin.o
  LIBTOOL-STATIC Release/rdkafka.a
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/RdKafka.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/ConfImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/HandleImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/ConsumerImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/ProducerImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/KafkaConsumerImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/TopicImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/TopicPartitionImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/MessageImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/QueueImpl.o
  CXX(target) Release/obj.target/librdkafkacpp/deps/librdkafka/src-cpp/MetadataImpl.o
  LIBTOOL-STATIC Release/rdkafkacpp.a
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
  CXX(target) Release/obj.target/node-librdkafka/src/callbacks.o
  CXX(target) Release/obj.target/node-librdkafka/src/common.o
  CXX(target) Release/obj.target/node-librdkafka/src/config.o
  CXX(target) Release/obj.target/node-librdkafka/src/connection.o
  CXX(target) Release/obj.target/node-librdkafka/src/errors.o
  CXX(target) Release/obj.target/node-librdkafka/src/kafka-consumer.o
  CXX(target) Release/obj.target/node-librdkafka/src/producer.o
  CXX(target) Release/obj.target/node-librdkafka/src/topic.o
  CXX(target) Release/obj.target/node-librdkafka/src/workers.o
  SOLINK_MODULE(target) Release/node-librdkafka.node


Process finished with exit code 1

**Comment by webmakersteve** [comment]
It is showing llz4 as on your machine but maybe the path is different than where your ldpath is looking.

```
LIBS -lpthread -L/opt/local/lib -lz -L/opt/local/lib -lcrypto -L/opt/local/lib -llz4 -L/opt/local/lib -lssl -L/opt/local/lib -lsasl2 -ldl
```

Can you locate where the lz4 directory is and check what your ldpaths are? `librdkafka` is setting a few extra ones there.

**Comment by patrixgdd** [comment]
Since I am using macports, but I forget to export LIBRARY_PATH="/opt/local/lib" to the environment.
Now it is working fine.
Just wonder why version 2.1.0 has no issue at all.

**Comment by webmakersteve** [comment]
I made adjustments in 2.1.1 that is supposed to make it smarter when installing optional dependencies. But they need to be in your library path now that they are included.
