### ISSUE TITLE
Number of producers per process

### ISSUE THREAD

**Issue by dmtrs** [Blizzard/node-rdkafka#269]
Would it be an issue to instantiate multiple producers per process? Could it be an issue if this multiple N producers have only one instance in `metadata.broker.list` (broker list length to 1) ?

**Comment by fega** [comment]
did you experimented issues? I didn't, with 3 o 4 producers per process

**Comment by webmakersteve** [comment]
Having multiple producers per process is totally fine, just remember there is thread overhead per producer. 

Each producer corresponds to at least one thread in C++ land for processing the messages.

**Comment by fega** [comment]
@webmakersteve would be better if only one producer is used?

**Comment by webmakersteve** [comment]
I don't know if better is the right word, but there should not be a noticeable performance increase from not sharing a producer. The only time I would recommend having multiple producers is when their configuration differs.

**Comment by webmakersteve** [comment]
Closing this issue because I think the question has been answered :)
