### ISSUE TITLE
Accessing Kafka with Kerberos and SSL failed with Segmentation fault

### ISSUE THREAD

**Issue by Kevin-Lee** [Blizzard/node-rdkafka#274]
Accessing Kafka with Kerberos and SSL failed with Segmentation fault.

* OS: CentOS 7
* node-rdkafka version: 2.0.0
* node --version: v6.11.3
* npm --version: 3.10.10

The server it's running has cyrus-sasl-devel and openssl-devel.

I have no idea how to debug it as the only thing I got was the 'Segmentation fault' message.

I've tried to test librdkafka using kafkacat with the following options and it worked.

```
kafkacat -b 'localhost:9092' -L \
-X security.protocol=SASL_SSL \
-X sasl.kerberos.keytab=/path/to/kafka.keytab \
-X sasl.kerberos.principal='kafka/some-host@realm' \
-X ssl.ca.location=/path/to/kafka-trust.pem \
-X ssl.certificate.location=/path/to/kafka.pem \
-X ssl.key.location=/path/to/kafka.key
```

So I can confirm that librdkafka works in that server, but node-rdkafks's Producer.connect() fails with 'Segmentation fault'.

**Comment by webmakersteve** [comment]
What configuration are you giving the producer?

**Comment by Kevin-Lee** [comment]
@webmakersteve Just the same ones as I used with `kafkacat` mentioned above.

**Comment by Kevin-Lee** [comment]
Without `ssl.ca.location=/path/to/kafka-trust.pem`, there's no error but nothing happens. So nothings produced. There is no error and the Producer never gets 'ready' state.

**Comment by webmakersteve** [comment]
I'll take a look at this and add some unit tests around it. 

Did the error happen when you called `.connect`? Or at construct time. Any code you have would help :)

**Comment by webmakersteve** [comment]
Closing the issue because of inactivity. Please re-open if you're still experiencing the problem on the latest version.

**Comment by mrrotberry** [comment]
I have this problem when try called function connect, also I delete from configuration field "group.id" or leave it with empty string connect success but I have error - "Error: "group.id" must be configured.

OS: Linux Deepin 15.5
node-rdkafka version: 2.3.1
node --version: 9.11.1
npm --version: 5.6.0

**Comment by webmakersteve** [comment]
@mrrotberry this is a different issue. Can you open a separate issue for what you're experiencing, and please give the entirety of your Consumer config in that issue?

**Comment by mrrotberry** [comment]
not relevant to me. I changed the OS to Manjaro Linux Hakoila 17.1.8 and everything works
