### ISSUE TITLE
Is there a way to commit offsets to Zookeeper?

### ISSUE THREAD

**Issue by fsck-mount** [Blizzard/node-rdkafka#277]
I'm using Kafka Manage tool to see the offsets committed by workers. If I switch to node-rdkafka, I'll not be able to see the offsets pending and all. 
1. Is there a way to commit offsets to zookeeper?
or 
Is there any other tool like Kafka Manage (which can read offset and change/alter configs in Kafka?

**Comment by webmakersteve** [comment]
You should use the new tooling kafka has for checking committed offsets instead of using zookeeper. Kafka now keeps track of its offsets in a compacted topic in kafka.

https://github.com/linkedin/Burrow also works great for keeping track of offset lag if thats your intended purpose :)
