### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by majorsean** [Blizzard/node-rdkafka#278]
hello，i am getting this：

> node-rdkafka@2.1.1 install /opt/host/www/emarket-node/node_modules/node-rdkafka
> node-gyp rebuild

make: Entering directory `/opt/host/www/emarket-node/node_modules/node-rdkafka/build'
  CC(target) Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka.o
In file included from ../deps/librdkafka/src/rdposix.h:119,
                 from ../deps/librdkafka/src/rd.h:68,
                 from ../deps/librdkafka/src/rdkafka_int.h:44,
                 from ../deps/librdkafka/src/rdkafka.c:38:
../deps/librdkafka/src/rdatomic.h: 在函数‘rd_atomic32_add’中:
../deps/librdkafka/src/rdatomic.h:68: 警告：隐式声明函数‘__atomic_add_fetch’
../deps/librdkafka/src/rdatomic.h:68: 错误：‘__ATOMIC_SEQ_CST’未声明(在此函数内第一次使用)
../deps/librdkafka/src/rdatomic.h:68: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
../deps/librdkafka/src/rdatomic.h:68: 错误：所在的函数内也只报告一次。)
../deps/librdkafka/src/rdatomic.h: 在函数‘rd_atomic32_sub’中:
../deps/librdkafka/src/rdatomic.h:85: 警告：隐式声明函数‘__atomic_sub_fetch’
../deps/librdkafka/src/rdatomic.h:85: 错误：‘__ATOMIC_SEQ_CST’未声明(在此函数内第一次使用)
../deps/librdkafka/src/rdatomic.h: 在函数‘rd_atomic32_get’中:
../deps/librdkafka/src/rdatomic.h:99: 警告：隐式声明函数‘__atomic_fetch_add’
../deps/librdkafka/src/rdatomic.h:99: 错误：‘__ATOMIC_SEQ_CST’未声明(在此函数内第一次使用)
../deps/librdkafka/src/rdatomic.h: 在函数‘rd_atomic64_add’中:
../deps/librdkafka/src/rdatomic.h:139: 错误：‘__ATOMIC_SEQ_CST’未声明(在此函数内第一次使用)
../deps/librdkafka/src/rdatomic.h: 在函数‘rd_atomic64_sub’中:
../deps/librdkafka/src/rdatomic.h:156: 错误：‘__ATOMIC_SEQ_CST’未声明(在此函数内第一次使用)
../deps/librdkafka/src/rdatomic.h: 在函数‘rd_atomic64_get’中:
../deps/librdkafka/src/rdatomic.h:170: 错误：‘__ATOMIC_SEQ_CST’未声明(在此函数内第一次使用)
在文件层：
cc1: 警告：无法识别的命令行选项“-Wno-maybe-uninitialized”
make: *** [Release/obj.target/librdkafka/deps/librdkafka/src/rdkafka.o] 错误 1
make: Leaving directory `/opt/host/www/emarket-node/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.1.1.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v8.8.1/bin/node" "/root/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/host/www/emarket-node/node_modules/node-rdkafka
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-30T10_27_41_840Z-debug.log

**Comment by matthax** [comment]
Can you try with `v6.11.5` I'm not sure `v8.8.1` is supported yet.

**Comment by majorsean** [comment]
it's ok ,thanks.
