### ISSUE TITLE
What's the difference between flowing mode and no-flowing mode in consumer?

### ISSUE THREAD

**Issue by thekingofworld** [Blizzard/node-rdkafka#280]
in my opinion,
we can get messages as soon as they are available in flowing mode;
we can control the speed of consumption and the amount of message obtained in no-flowing mode.
is that right? or someone know the other difference? 
thx  : )

**Comment by thekingofworld** [comment]
use flowing mode,  send msg ~ receive msg   spent  6-10ms
###here's code : 
```js
consumer.on('ready', function(){
  consumer.subscribe([topicName]);
  consumer.consume();
});

consumer.on('data', function(msg){
  //processMsg...
});
```

when use no-flowing mode, send msg ~ receive msg spent 1000+ms
###here's code:
```js
consumer.on('ready', function() {
        consumer.subscribe([topicName]);

        function processRecords(data, cb) {
          if (data.length == 0) {
            return setImmediate(cb);
          }

          setImmediate(cb);
        }

        function consumeNum() {
          consumer.consume(20, (err, data) => {
            if (err) {
              console.error(err);
              return;
            }
            processRecords(data, () => {
              consumeNum();
            });
          });
        }
        consumeNum();
      });
```

**Comment by webmakersteve** [comment]
Flowing mode is more akin to low-latency stream processing. It is constantly fetching messages and pushing them to you as it finds them available, not stopping the processing for anything.

Regular batch consumption mode will work just the same if messages are constantly flowing into kafka, but you can reduce the latency in cases where there are not messages by reducing the consume timeout using `setDefaultConsumeTimeout()`

**Comment by thekingofworld** [comment]
yup, using setDefaultConsumeTimeout() can reduce latency, thx.

**Comment by thekingofworld** [comment]
another problem... Is there any side effect of using this method? if I set a very low value.

**Comment by webmakersteve** [comment]
There is especially low impact if you have data flowing constantly through your consumer, but having that value higher will potentially keep a thread in the uv threadpool in use until the timeout has exceeded. 

If you have a lot of asynchronous calls being made in your application it is probably good to increase the UV threadpool if you plan on setting long timeouts. 

`process.env.UV_THREADPOOL=<numthreads>`
