### ISSUE TITLE
Outdated version exists in npmjs.com? "node-rdkafka": "^2.1.1" install fails (both under npm and yarn)

### ISSUE THREAD

**Issue by d-sphinx** [Blizzard/node-rdkafka#281]
Hello, everyone! Create a simple package.json:

{
  "name": "Test",
  "version": "0.0.1",
  "dependencies": {
    "node-rdkafka": "^2.1.1"
  }
}

Installation process will fail under both npm and yarn packet managers.

If i do manual git pulling (including submodules) from here and then yarn it - it's OK, everything compiles, but in a real life when i have to use package.json it doesn't work.

I decided to compare files downloaded from this repo and npmjs (yarn), and they are different!

![2017-11-01 13_51_20-greenshot](https://user-images.githubusercontent.com/4455753/32271654-eaae4e3c-bf0b-11e7-9c71-25aa8af4926c.png)

Differences exist even in *.js files, for example consumer.spec.js:

![2017-11-01 13_54_50-greenshot](https://user-images.githubusercontent.com/4455753/32271710-3f1cdbaa-bf0c-11e7-831e-9b12552e9e17.png)

Why? Is the packet currently available at npmjs outdated?

**Comment by matthax** [comment]
The currently published version on NPM doesn't support windows. Support was just recently added by #248

**Comment by d-sphinx** [comment]
When there will be an update of published version?

**Comment by ancashoria** [comment]
I'm also unable to install `node-rdkafka` because of this error:
```
SOLINK_MODULE(target) Release/node-librdkafka.node
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node-librdkafka.node] Error 1
```

I'm using MacOs

**Comment by webmakersteve** [comment]
This is because the crypto search path. I am making an adjustment to the ld search paths so this doesn't happen anymore.

**Comment by webmakersteve** [comment]
I have made the change to crypto in the search path. And this thread has a few different issues, but I believe they are all resolved. So... closing! Re-open if I'm wrong :)
