### ISSUE TITLE
Consuming all events in a topic

### ISSUE THREAD

**Issue by ankon** [Blizzard/node-rdkafka#287]
I would like to implement the following logic:
1. Connect to kafka
2. Read all events currently in the topic (from beginning to "now")
3. Disconnect
4. Process these events

With the KafkaConsumer I have issues with step 2: 
* I do not know how many events are in the topic, so I cannot simply try to read a known number of events. 
* For the same reason I also do not know when to stop, so "flowing mode" also doesn't work. 

I can see that rdkafka reports 'EOF' for topics, but node-rdkafka seems to just ignore these (and retries reading): https://github.com/Blizzard/node-rdkafka/blob/master/src/workers.cc#L476

Some approaches I tried:
* Always use `auto.offset.reset` and a new consumer group: I couldn't figure out how to position my consumer properly to the beginning
* Delay for "a while", and then consume until eventually I do not see any messages anymore. Problem here was determing how long to delay until rebalancing had happened(?)

**Comment by battlecow** [comment]
Although the following could use a promise and other cleanup I just ran through this exact scenario late last night and got it to read from the beginning of every partition when referencing a new group.id: [https://gist.github.com/battlecow/efab71d180e593ea0dc6cbcead78b3a7](Gist)

**Comment by ankon** [comment]
Thanks for your code example, @battlecow! Based on that I came up with https://gist.github.com/ankon/9c2263bf1d04600129aeaa06e8c49179, which avoids the 5s sleep and uses promises.

**Comment by webmakersteve** [comment]
It does not ignore EOF, it just does not treat it as a throwable error as it is an expected case. If you want to react to this, consume x messages until you get less than x messages in a timeout, then you know you have reached the end of the partition.
