### ISSUE TITLE
v1.0.6 consumer stuck during consuming

### ISSUE THREAD

**Issue by rbustami** [Blizzard/node-rdkafka#288]
From: https://github.com/Blizzard/node-rdkafka/issues/235
The cause for this issue was never really explained.

I'm dealing with a similar issue when implementing batch consumption and manual commits in v1.0.6.

The round trip time for commits slowly increments until we see a commit failure. The consumers in my group aren't rebalanced and the offset never increments on the partitions where the offset is stuck.

We ran the exact same implementation with v2.1.1 and everything works perfectly. I've looked through the release documentation and haven't found anything specifying a fix to this specific issue.

Any insight as to why we are seeing this problem with v1.0.6 would be very helpful.

**Comment by webmakersteve** [comment]
Chances are it is something with librdkafka under the hood. I only document that I upgrade the librdkafka version, not what the changes of that version entail. Those details can be found in the librdkafka repository.

2.1.0 is using librdkafka 0.11
