### ISSUE TITLE
ProducerStream error in produce function

### ISSUE THREAD

**Issue by michallevin** [Blizzard/node-rdkafka#294]
Hi,

I am using the ProducerStream in objectMode. When writing more than 1 message to Kafka at the same time (without waiting for the previous write to finish), a `"topic" must be a string` error is thrown in the producer's produce function.

I noticed that in the first call to produce, the `topic` parameter exists and the `message` is of type Uint8Array. On subsequent calls, the `topic` parameter is `undefined` and the message is of type `Object` with the keys `partition`, `topic`, and `value` (all defined). But since the function's `topic` parameter is undefined, the error is thrown.

What is going on? 😨 
The code which configures the Producer stream and writes to Kafka is below for reference...

Thanks!  

```
const Kafka = require('node-rdkafka');
const EventEmitter = require('events');

let stream = null;

module.exports = function init(config, logger) {
  const kafkaEmitter = new EventEmitter();
  const hosts = config.kafka.hosts.reduce((host, string) => string.concat(',', host));

  stream = !stream ? Kafka.Producer.createWriteStream({
    'metadata.broker.list': hosts,
    'batch.num.messages': 50000,
    'message.send.max.retries': 5,
    'retry.backoff.ms': 5000,
    'message.max.bytes': 10 * 1024 * 1024,
    'request.required.acks': 1,
    'dr_msg_cb': true
  }, { 'request.required.acks': 1 }, {
    objectMode: true
  }) : stream;

  stream.producer.on('error', (err) => logger.error('Error writing to Kafka due to producer',
                                                        { error_message: err.message }));
  stream.on('error', (err) => logger.error('Error writing to Kafka due to stream', { error_message: err.message }));
  stream.producer.on('delivery-report', (error, message) => {
    return kafkaEmitter.emit(message.value, error)});

  return {
    write: write
  };

  function write(orgName, resource, value) {
    const message = {
      topic: `service-name.${orgName}.${resource}`,
      partition: 0,
      value: new Buffer(JSON.stringify(value))
    };

    const queuedSuccess = stream.write(message);

    if (!queuedSuccess) {
      logger.error('Kafka message not queued', { organization: orgName });
      return Promise.resolve();
    }

    return new Promise((resolve) => {
      kafkaEmitter.on(message.value, (error) => {
        if (error) {
          logger.error('Error in Kafka delivery report', { organization: orgName, message_value: value });
        }

        resolve();
      });
    });
  }
};

```

**Comment by JaapRood** [comment]
I saw the same thing and managed to track it down to `ProducerStream.prototype._writev` (called by Node when there's multiple chunks buffered in the stream to all be written at once), or more specifically [the `writev` function declared above it](https://github.com/Blizzard/node-rdkafka/blob/master/lib/producer-stream.js#L199-L220). This function accepts a `topic` as an argument, which is passed as the topicName set at the stream's construction. However, in object mode, we expect the `topic` in the message object to be used, instead.

A workaround for now should be passing the `topic` option while creating the producer stream (if you're only writing to a single topic).

I'm new to the codebase, but I'll see if I can contribute a fix good enough for it to be merged.

**Comment by webmakersteve** [comment]
This has been merged! I think that fixes your issue according to your comment there? So closing!
