### ISSUE TITLE
How to set consumer group to specific offset?

### ISSUE THREAD

**Issue by jmwilkinson** [Blizzard/node-rdkafka#295]
Trying to follow examples and docs around this, but it's really unclear. How do you go about setting a particular consumer group to a particular offset? Don't want to actually read data, just want to set the offset.

Example of what I've tried:

```javascript
var consumer = new Kafka.KafkaConsumer({
  'group.id': groupId,
  'metadata.broker.list': brokers,
  'enable.auto.commit': false
});

console.log('connecting....');

consumer.connect();

consumer.on('ready', () => {
    // consumer.disconnect();
    /*
    console.log('consumer is ready');
    consumer.seek({ topic: topic, partition: 0, offset: offset }, 10, (err) => {
        console.log(err);
        console.log(consumer.position());
        console.log('set topic to offset');
        consumer.disconnect();
    });
    */


    consumer.subscribe([topic]);
    consumer.consume(1, function(err, data) {
        if(err) console.log(err);
        console.log(data.length);
        console.log('got data, seeking now');

        consumer.assign([{ topic: topic, partition: 0, offset: offset }]);
        consumer.commit();
        consumer.seek({ topic: topic, partition: 0, offset: offset }, 10, (err) => {
            console.log(err);
            // console.log(consumer.position());
            consumer.commitSync();
            console.log('set topic to offset');
            consumer.disconnect();
        });
    })

});
```

It's become more convoluted as I've tried to deal with various error messages.

It seems like such a simple thing.

Most recent failure:

```
Error: Local: No offset stored
    at Function.createLibrdkafkaError [as create] (kafk-offset-tool/node_modules/node-rdkafka/lib/error.js:260:10)
    at KafkaConsumer.Client._errorWrap (kafk-offset-tool/node_modules/node-rdkafka/lib/client.js:422:29)
    at KafkaConsumer.commitSync (kafk-offset-tool/node_modules/node-rdkafka/lib/kafka-consumer.js:519:8)
    at consumer.seek (kafk-offset-tool/index.js:43:22)
    at kafk-offset-tool/node_modules/node-rdkafka/lib/kafka-consumer.js:228:5
```

Where am I going wrong? I've tried both `seek` and `assign` and various incantations to try and get into the right state but nothing seems to work....

**Comment by jmwilkinson** [comment]
After some more investigation, it seems this is a bug with the assign function.

**Comment by webmakersteve** [comment]
Why are you committing directly after the assignment? If you remove that do things work? Commit with no parameters is going to try to commit the currently stored offsets, which don't exist because you haven't called consume once yet. 

If you want to commit there pass in the topic partition just the same as the other functions.

**Comment by jmwilkinson** [comment]
Yes, I tried various permutations of passing in partitions, consuming first, etc. The problem is with the assign function, which should do precisely what is in the question (assigning a consumer group's offset for a particular topic), but fails with esoteric error messages.

It was fairly straightforward to accomplish the same thing with a python script using the confluent kafka library.

My recommendation for reproduction would be to simply try and use the assign function. It doesn't work.

**Comment by krishanfrog** [comment]
@jmwilkinson any luck with this?

**Comment by jmwilkinson** [comment]
No, I just used the confluent kafka package and wrote a python script.

**Comment by erik-stephens** [comment]
I just saw this:

https://github.com/DavidLiuXh/KafkaOffsetTools/blob/master/kafka_offset_resetter.cc#L175

I haven't done the exercise of translating into node-rdkafka calls yet - my current needs are to read from specific offsets, not reset.  I've been able to read from specific offsets using `connect(); assign(); consume();`.  Hope it helps.

**Comment by webmakersteve** [comment]
I'm not having the same problems with assign as you, and there are some integration tests around it. I'm going to close this issue because it was a specific use-case and not necessarily a general library problem. If you have additional problems with assign open a new issue thread so we can work through those.

**Comment by jmwilkinson** [comment]
Maybe it would be good just to have some example documentation on the use of assign. Again, as stated in the original question, the issue is around setting the offset and then NOT consuming data.

**Comment by webmakersteve** [comment]
Sure. I can totally agree with you that assign is not documented well enough. I'll work on adding some documentation around it to the README.

And sorry, I think I may be mixing up this issue with another one.

You should just be able to give the offsets you want to the `commit` method to accomplish what you want to do. If that isn't working for you I'll try to take a look.
