### ISSUE TITLE
Install issues - Docker and Ubuntu

### ISSUE THREAD

**Issue by josh-stevens** [Blizzard/node-rdkafka#300]
I've had to jump through a series of hoops to get this to build in a Docker image with Node 8 and Ubuntu. I have to have this as part of my build process:

```
prepare-agent:
  ln -s /usr/.npm /home/build/.npm
  $(NPM) install -g node-gyp
  rm -rf kafka-build
  mkdir -p kafka-build && cd kafka-build && git clone https://github.com/Blizzard/node-rdkafka.git node-rdkafka --recursive
  cd kafka-build/node-rdkafka && git checkout tags/v2.2.0 && rm -rf .git && $(NPM) install nan && ./configure && node-gyp rebuild
  $(NPM) install
```

and a later part of the build moves that folder into the build image: 
`rsync -ahu --no-compress --info=progress2 kafka-build/node-rdkafka build-image/node_modules/`

This feels super gross and hacky, and now I've pinned a dependency version here in my Makefile rather than my package.json. If I don't do it this way, it fails at some point, and usually is complaining that ./configure hasn't been run. Let me know if there's more information I could provide, I'd like to help solve the install issues so I don't have to do this workaround.

**Comment by jSherz** [comment]
What's the output of your `npm install`? Does it fail to build node-rdkafka? Which Docker base image are you using?

**Comment by josh-stevens** [comment]
Sorry, normally signed into my work's github and forgot about this. Something must have changed since I originally posted this, it all seems to be working just fine now!

**Comment by webmakersteve** [comment]
Awesome. Glad to hear :)
