### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by marianban** [Blizzard/node-rdkafka#306]
Hi,

I'm trying to install the latest version 2.2.0 and it fails with the following error:

/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status

[npm.log](https://github.com/Blizzard/node-rdkafka/files/1495075/npm.log)

I tried few older versions:
2.1.1 - failed as well
2.1.0 - works

Thanks

**Comment by JoseBalado** [comment]
If you are using Linux (Ubuntu/Mint) try:
sudo apt-get install libssl-dev

That solved the problem for me.
Regards.

**Comment by marianban** [comment]
@JoseBalado Thank you, it worked for me as well.

**Comment by JoseBalado** [comment]
@marianban Glad it helped.
