### ISSUE TITLE
"Queue full" Error when writing batch of messages

### ISSUE THREAD

**Issue by bobrowadam** [Blizzard/node-rdkafka#307]
I'm trying to write messages in batches yet I fail to write in batch that is  > ~20 messages after `stream.write(message) === false`.
I believe this means that the queue is full although the default `queue.buffering.max.messages` is 100000.
Here is my config:
```
const stream = Kafka.Producer.createWriteStream({
    'metadata.broker.list': hosts,
    'batch.num.messages': 1000,
    'message.send.max.retries': 5,
    'retry.backoff.ms': 5000,
    'message.max.bytes': 10 * 1024 * 1024,
    'request.required.acks': 1,
    dr_msg_cb: true
  }, { 'request.required.acks': 1 }, {
    objectMode: true
}

```
Thanks

**Comment by webmakersteve** [comment]
The stream internal buffer and the librdkafka queue are actually separate. The stream buffer is set using the node option, `highWatermark`. If you want more room in it you will need to adjust that.

However, the stream producer should generally not get full unless you are saturating it synchronously.

**Comment by bobrowadam** [comment]
That did the trick. Thanks!  :)

**Comment by michallevin** [comment]
@webmakersteve From what I understand, this means that the highWatermark must be set to at least the `batch.num.messages` (in objectMode) for the batching to work as expected. Should this be in the documentation?

**Comment by webmakersteve** [comment]
Batching will still work fine as long as you do not synchronously batch more messages than the high watermark. The write callback is just in a set immediate call because the produce call is non blocking in librdkafka.
