### ISSUE TITLE
Local queue gets filled up and delivery reports not obtained if not flushing

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#308]
What is the exact use case of calling flush() on a producer.

I thought it is to be called if disconnecting the producer. But I have to call it periodically otherwise the local queue doesn't get cleared (And I get a `Local: Queue full` error) and I don't get the delivery reports too. Why is that so?

`var producer = new Kafka.Producer({`
`      'client.id': 'group',`
`      'metadata.broker.list': 'localhost:9092',`
`      'socket.keepalive.enable': true,`
`      'queue.buffering.max.messages': 100,`
`      'batch.num.messages': 1,`
`      'queue.buffering.max.ms': 0,`
`      'dr_cb': true`
`    }, { 'request.required.acks': 1 });`

`producer.connect();`

`producer.on('ready', function() {`
`    setInterval(function() {`
`        sendMessage();`
`    }, 100);`
`});`

I get the delivery reports only if I call producer.flush() periodically.

Also on my 101st message I get the error `Local: Queue full` if I don't call flush() even though all the prior messages have been pushed and consumed.

**Comment by krishanfrog** [comment]
I see that instead of a flush() a poll() done periodically also fulfills the requirement. 

Can close the issue but I don't understand why we need to wait to poll when there is an event listener for real time updates

**Comment by webmakersteve** [comment]
`Poll` is to allow `librdkafka` internally to execute pending events. It uses this to mark messages in the queue as having been successfully delivered. I went through several iterations, baking poll into a produce call, etc, but ended up settling on it needing to be manually executed.

If you use the stream producer you do not need to poll manually. Additionally there is a method on the producer to set an automatic polling interval that deals with cleanup.
