### ISSUE TITLE
Messages lost or queued out of order if broker connection broken

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#309]
If I send messages at the rate of 1000 messages per second and terminate a broker connection in the middle, I see different behaviors randomly

For eg: If broker connection was terminated at the 500th message and reconnected when trying to send the 3000th message

- Sometimes messages in the middle are lost
messages 600-3000 are resent successfully but the other 100 messages in between are not. I do not even get the delivery report error for these 100 messages.

- Rest of the times messages in the middle are inserted in the kafka queue out of order
messages 500-600 are queued out of order (sometimes exactly in reverse). messages 600-3000 are resent in order.

`var producer = new Kafka.Producer({`
`  'client.id': 'dummy',`
`  'metadata.broker.list': 'localhost:9092,localhost:9093',`
`  'retry.backoff.ms': 200,`
`  'message.send.max.retries': 10,`
`  'socket.keepalive.enable': true,`
`  'queue.buffering.max.messages': 1000000,`
`  'batch.num.messages': 1,`
`  'queue.buffering.max.ms': 0,`
`  'dr_msg_cb': true`
`}, { 'request.required.acks': 1 });`

`producer.connect();`

`producer.on('ready', function() {`
`    setInterval(function() {`
`        producer.poll(0);`
`        sendMessage();`
`    }, 1);`
`});`

`producer.on('event.error', function(err) {`
`  console.error('Error in producing' + err);`
`})`

`producer.on('delivery-report', (err, report) => {`
`    deliveryReport(err, report);`
`});`

`function deliveryReport(err, report) {`
`    console.log("delivery payload " + report.value.toString());`
`    if (err) {`
`        console.log("delivery err " + err);`
`    }`
`}`

**Comment by krishanfrog** [comment]
@webmakersteve can you take a look at this.

**Comment by edenhill** [comment]
Messages should not be lost, but re-ordering may happen:
https://github.com/edenhill/librdkafka/issues/1092

This will be solved properly when Idempotent transactions are implemented.

**Comment by krishanfrog** [comment]
I saw one instance of messages being lost. will try to reproduce it again.

Any timeframe for when Idempotent transactions will be implemented?

**Comment by webmakersteve** [comment]
The re-ordering fix will come to node-rdkafka on the next librdkafka release.
