### ISSUE TITLE
Low-level Fetch API

### ISSUE THREAD

**Issue by erik-stephens** [Blizzard/node-rdkafka#313]
I have (topic, partition, start offset, end offset) and would like to be able to fetch that range.  This is to support a batch or replay scenario, not so much a streaming scenario.  I'm looking for an api here that is close to [the kafka fetch api](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI).  There a way to do that with this library?  I couldn't find such an api from a quick scan of the underlying librd-kafka library either.  Is such a low-level api in-scope for this project?  In other words, if a PR was submitted with such an api, would it be welcome or considered potential technical debt?  Thanks!

**Comment by erik-stephens** [comment]
I found #18 which captures what I'm trying to do.  Looks like I can accomplish what I need with `assign()`.  Was having problems trying to use `seek()`.  Is it correct to use assign and not seek for this use case?

**Comment by erik-stephens** [comment]
Assigning gets me close but I'm stuck with `consume(count)` which isn't deterministic enough for my needs.  In other words, this code won't always produce the same results for the same values of `i`, `j`, and `count`:
```
assign([{topic: 'a', partition: 0, offset: i}, {topic: 'a', partition: 1, offset: j}])
consume(count)
```

Maybe put another way, how can I [re-]consume a topic in a consistent way?  For simplicity sake, assume topic retention never reached, brokers never die, consumer rebalancing not at play, etc.

**Comment by erik-stephens** [comment]
I have some code [1] that can very easily get into a hung state (see the "hung-*.out" files).  My first thought is that it's an issue with librdkafka since it's saying it doesn't think it needs to fetch any more.  Plus, I don't see the node bindings adding much to the assign() & consume() code paths.  However, I was unable to get kafkacat (librdkafka=0.11.0) to hang.  My `mycat` make target takes the multiple partition assignment out of the equation to try to be a more apples-to-apples comparison with kafkacat, but I can get it to hang as well.  I tried against node-rdkafka master against librdkafka version 0.11.{0,1,3} and can get all those versions to hang.  Thoughts on where I should focus my debug efforts?

I'm using really small topic & fetch parameters in order to provide an easier to reproduce case to "stalled workers/partitions" that I'm seeing in the wild at high volume - similar sounding issue as others have reported (see edenhill/librdkafka#1395 for example).

[1] https://github.com/erik-stephens/kafka-slicer

**Comment by erik-stephens** [comment]
Today I learned that `consume(count)` makes a best effort to read `count` messages.  If the messages haven't been pre-fetched yet, then there is a good chance that the consume call will [quietly do nothing](https://github.com/Blizzard/node-rdkafka/blob/master/src/workers.cc#L479-L483) and it's up to us to try to consume some more.

**Comment by erik-stephens** [comment]
Am able to accomplish what I need by assigning to a single partition at a time and consuming the desired offset+count.

**Comment by webmakersteve** [comment]
Glad you figured it out. Sorry I wasn't able to respond earlier!
