### ISSUE TITLE
Producer does not return an error when a message is published while Kafka is down

### ISSUE THREAD

**Issue by prabathabey** [Blizzard/node-rdkafka#314]
$Subject was reproduced in an attempt to verify error handling of Producer component in node-rdkafka version 2.2.0. I've got an "always-on" client in my test, which is connected once and reused afterwords. I had turned off Kafka after the client has successfully connected to encounter the aforementioned behaviour. During the test, "Producer#produce" method neither threw an error nor did it return "false" as it should have. Is this a bug or is there something I'm missing?

**Comment by edenhill** [comment]
Produce is an async API:
Messages are queued internally (for up to `message.timeout.ms`) waiting for a partition leader broker to come up.

**Comment by prabathabey** [comment]
@edenhill Thanks for the feedback. If I'm not mistaken the method comment of "Producer#produce" says "Produce a message to Kafka synchronously. ...", which made think the messages are produced synchronously. Anyhow, to ensure transactional properties of application components are honoured at all times, I've enabled acks via the topic conf with the parameter "request.required.acks" and scheduled immediate polling of the producer right after a message is published to receive delivery reports as below. 

    ...
    var producer = new Kafka.Producer(settings, {"request.required.acks" : 1});

    producer.on('ready', function () {
        try {
            producer.produce("test", null, new Buffer("test message"));
            setInterval(function() {
                producer.poll();
            }, 0);
        } catch (e) {
            // log error
        }
    });
    ...
    producer.on('delivery-report', function(err, report) {
        if (err) {
            // handle error and let the other application components know of the failure
        }
        // log report
    });
    producer.connect();

I'd appreciate your feedback as to if the above approach is recommended to handle delivery failures?

**Comment by webmakersteve** [comment]
If you want to produce synchronously, you can do:

```js
var producer = new Kafka.Producer(settings, {"request.required.acks" : 1});

var timeout = 5000;
function cb(err) {
  if (!err) {
    console.log('produced successfully');
  }
}

producer.on('ready', function () {
    try {
        producer.produce("test", null, new Buffer("test message"));
        producer.flush(timeout, cb);
        setImmediate(function() {
            producer.poll();
        });
    } catch (e) {
        // log error
    }
});
...
producer.on('delivery-report', function(err, report) {
    if (err) {
        // handle error and let the other application components know of the failure
    }
    // log report
});
producer.connect();
```

**Comment by prabathabey** [comment]
Thanks Steve. I've actually figured this out after a quick look into the sources, and therefore closed the ticket earlier. Thanks anyways.

**Comment by lukasimha** [comment]
@webmakersteve do we need both delivery-report callback and the flush callback to know if the error happened during publish. Wouldn't just the flush callback suufice?
