### ISSUE TITLE
How to call Librdkafka methods and work on this?

### ISSUE THREAD

**Issue by JonathanGladwin** [Blizzard/node-rdkafka#317]
Hi,

As per the instructions below, I am not sure what program editor that I should use and add require code, use Librdkafka Methods, Sending Messages, etc. after installation? Is there development help documentation to work on this?

============================================================
You can install the node-rdkafka module like any other module:
npm install node-rdkafka

To use the module, you must require it.

var Kafka = require('node-rdkafka');
============================================================

**Comment by JonathanGladwin** [comment]
Do I need to use Eclipse ? How do I call  Librdkafka Methods? Do I need to create new class and call?

**Comment by webmakersteve** [comment]
You can get the docs here. https://blizzard.github.io/node-rdkafka/current/

There is no intellisense for Javascript, but if you use typescript you can get the benefits of some of the typescript bindings available.
