### ISSUE TITLE
Avro Question

### ISSUE THREAD

**Issue by andre-l-mm** [Blizzard/node-rdkafka#318]
I have used node-rdkafka to create producers and consumers in node and it worked great. However, In the company I work for, there is a requirement from enterprise to use AVRO and confluent schema registry. We are using confluent distribution here. 

I have noticed that the support to AVRO and schema registry on confluent C/C++ implementation seems to be provided in the libserdes library. 

I understand that the original goal of node-rdkafka is to create a wrapper on librdkafka only but I would like to ask this question anyway.  Is there any intention or plan to extend the scope of node-rdkafka to incorporate libserdes or to create a new project to wrap that C/C++ library?

**Comment by jobetdelima** [comment]
Any update on this one? I'm assuming this means this node module doesn't support being able to send AVRO data with a producer? Thanks

**Comment by webmakersteve** [comment]
There is no current plan to do bindings for avro and bake them into the project as it stands. I think this fits well into another library.

`node-rdkafka` is focused on being bindings or `librdkaka`. It deals with buffers and strings, so any way you get those buffers and strings is okay by me! 

Looks like there is an avro library you may be able to use here: https://github.com/mtth/avsc

**Comment by ismriv** [comment]
There's also a wrapper of this library that does exactly what's asked here: https://github.com/waldophotos/kafka-avro
