### ISSUE TITLE
Write stream does not flush when piped from readable stream

### ISSUE THREAD

**Issue by rationull** [Blizzard/node-rdkafka#320]
When writing a small script to populate a topic for testing, I hit an issue where the messages I write are not being flushed out to Kafka before the script terminates. I think that when piping a read stream into a stream created by Producer.createWriteStream(), the write stream is being closed when the read stream is exhausted (as expected) but without attempting to flush writes.

I've implemented a repro at https://github.com/rationull/node-rdkafka-producer-stream-bug

This is under node-rdkafka 2.2.1.

**Comment by webmakersteve** [comment]
Fixed with https://github.com/Blizzard/node-rdkafka/commit/3a2d5835602806f364108cc2fae338e6615a98fe

Thanks for the report and thorough test case! Helped me a lot! :)

**Comment by rationull** [comment]
@webmakersteve awesome, thanks for the fix!
