### ISSUE TITLE
Kafka consumer stream _read called after close and this.consumer is set to `null`

### ISSUE THREAD

**Issue by sprijk** [Blizzard/node-rdkafka#321]
This causes an error thrown:
```
Uncaught TypeError: Cannot read property 'isConnected' of null
      at KafkaConsumerStream._read_message (node_modules/node-rdkafka/lib/kafka-consumer-stream.js:136:22)
      at Timeout._onTimeout (node_modules/node-rdkafka/lib/kafka-consumer-stream.js:180:16)
```

A check for `this.consumer` or presence should fix this?

**Comment by sprijk** [comment]
Cannot replicate anymore (new installation of Kafka)

**Comment by bobrowadam** [comment]
@sprijk I still get this error. What did you do that solved that?

**Comment by sprijk** [comment]
@bobrowadam I've implemented my own readable stream (based on extracting data from the KafkaConsumer). So, now I don't have these errors any more.

The only issue I am really having now is described in #330 

If you are interested in my readable stream implementation, let me know! (If it would be of any use, I could publish it)

**Comment by bobrowadam** [comment]
@sprijk I'll be glad to see how did you implement the readable stream thanks!

**Comment by sprijk** [comment]
@bobrowadam It's here: https://www.npmjs.com/package/rdkafka-streams

Let me know if you have any questions or recommendations.

**Comment by bobrowadam** [comment]
Thanks!

**Comment by sprijk** [comment]
Due to @erik-stephens 's comment (#330 (comment)), and the added semicolons, I am reopening this issue.
