### ISSUE TITLE
npm install of node-rdkafka failed on windows as well

### ISSUE THREAD

**Issue by mdenoun** [Blizzard/node-rdkafka#324]
npm install node-rdkafka does not work on windows
(also node-gyp configure --msvs_version=2013 does not work but I dont think it is the problem)

The error I got when doing npm install node-rdkafka are

c:\install\test\node_modules\node-rdkafka\deps\librdkafka\src\rdkafka_int.h(53):                         
 fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory

I set the following environment variable to be able to compile and resolve libraries libeay32MT.lib and ssleay32MT.lib related to OpenSSL

set CL=/I C:\OpenSSL-Win32\include
set LINK=/LIBPATH:"C:\OpenSSL-Win32\lib\VC"

Then I got errors related to resolving external symbol related to OpenSSL I assume
      Creating library C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\\outdir\v120\x64\Release\librdkafka.lib and object C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node
  -rdkafka\deps\librdkafka\win32\\outdir\v120\x64\Release\librdkafka.exp
rdkafka_broker.obj : error LNK2019: unresolved external symbol ERR_remove_thread_state referenced in function rd_kafka_broker_thread_main [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\wi
n32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_set_flags referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vc
xproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_new referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj]
 [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_read referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj
] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_write referenced in function rd_base64_encode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxpro
j] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_ctrl referenced in function rd_base64_encode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj
] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_push referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj
] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_free_all referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcx
proj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_s_mem referenced in function rd_base64_encode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxpro
j] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_new_mem_buf referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.
vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol BIO_f_base64 referenced in function rd_base64_decode [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcx
proj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol EVP_sha1 referenced in function rd_kafka_sasl_scram_conf_validate [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\l
ibrdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol EVP_sha256 referenced in function rd_kafka_sasl_scram_conf_validate [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32
\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol EVP_sha512 referenced in function rd_kafka_sasl_scram_conf_validate [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32
\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol SHA1 referenced in function rd_kafka_sasl_scram_conf_validate [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librd
kafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol SHA256 referenced in function rd_kafka_sasl_scram_conf_validate [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\lib
rdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol SHA512 referenced in function rd_kafka_sasl_scram_conf_validate [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\lib
rdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_sasl_scram.obj : error LNK2019: unresolved external symbol HMAC referenced in function rd_kafka_sasl_scram_HMAC [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcx
proj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol CRYPTO_cleanup_all_ex_data referenced in function rd_kafka_transport_ssl_term [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdka
fka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol CRYPTO_num_locks referenced in function rd_kafka_transport_ssl_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\
librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol CRYPTO_set_locking_callback referenced in function rd_kafka_transport_ssl_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdk
afka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol CRYPTO_set_id_callback referenced in function rd_kafka_transport_ssl_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\
win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol OPENSSL_add_all_algorithms_noconf referenced in function rd_kafka_transport_ssl_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\
librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol X509_STORE_set_flags referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafk
a\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol X509_verify_cert_error_string referenced in function rd_kafka_transport_ssl_verify [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\li
brdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol X509_free referenced in function rd_kafka_transport_ssl_verify [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librd
kafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_set_cipher_list referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdk
afka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_new referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\l
ibrdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_free referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\
librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_get_cert_store referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdka
fka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_set_fd referenced in function rd_kafka_transport_ssl_connect [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\lib
rdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_use_PrivateKey_file referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\li
brdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_use_certificate_chain_file referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\
deps\librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function rd_kafka_transport_ssl_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\
win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_get_peer_certificate referenced in function rd_kafka_transport_ssl_verify [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdka
fka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_set_default_passwd_cb referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\
librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_set_default_passwd_cb_userdata referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdka
fka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_new referenced in function rd_kafka_transport_ssl_connect [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdk
afka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_free referenced in function rd_kafka_transport_close [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.
vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_connect referenced in function rd_kafka_transport_ssl_connect [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\li
brdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_read referenced in function rd_kafka_transport_ssl_recv [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkaf
ka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_write referenced in function rd_kafka_transport_ssl_send [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdka
fka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_ctrl referenced in function rd_kafka_transport_ssl_connect [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librd
kafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_ctrl referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\
librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_get_error referenced in function rd_kafka_transport_ssl_io_update [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win3
2\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSLv23_client_method referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafk
a\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_do_handshake referenced in function rd_kafka_transport_ssl_handshake [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\w
in32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_shutdown referenced in function rd_kafka_transport_close [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdka
fka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_library_init referenced in function rd_kafka_transport_ssl_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\
librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_set_default_verify_paths referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\de
ps\librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_CTX_load_verify_locations referenced in function rd_kafka_transport_ssl_ctx_init [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\
librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol SSL_get_verify_result referenced in function rd_kafka_transport_ssl_verify [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka
\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol ERR_get_error_line_data referenced in function rd_kafka_ssl_error [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\li
brdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
rdkafka_transport.obj : error LNK2019: unresolved external symbol ERR_error_string_n referenced in function rd_kafka_ssl_error [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdka
fka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\\outdir\v120\x64\Release\librdkafka.dll : fatal error LNK1120: 54 unresolved externals [C:\projects\code\kafka-nodejs\kafka-nodejs\node
_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafkacpp.vcxproj]
  Done Building Project "C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj" (default targets) -- FAILED.
  Done Building Project "C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafkacpp\librdkafkacpp.vcxproj.metaproj" (default targets) -- FAILED.
  Done Building Project "C:\projects\code\kafka-nodejs\kafka-nodejs\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.sln" (librdkafkacpp target(s)) -- FAILED.

  Build FAILED.

**Comment by yerol** [comment]
I had to install openssl x64 version to overcome this issue. It is not mentioned in the readme but the vsproj requires 64 bit version if your system is 64 bit.

It needs to be on c:\OpenSSL-Win64 folder

**Comment by mdenoun** [comment]
Thank you very much it work well

Sent from my iPhone

On Mar 5, 2018, at 3:22 AM, Stephen Parente <notifications@github.com<mailto:notifications@github.com>> wrote:


The instructions at https://github.com/edenhill/librdkafka/blob/master/README.win32 mention that penssl needs to be installed, but as @yerol<https://github.com/yerol> has said, you need the 64 bit version if you are compiling on a 64 bit system.
