### ISSUE TITLE
Parallel Consumption of messages from each partition in the non flowing mode

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#325]
Non flowing mode reads a fixed number of messages from Kafka at a time manually. 

The next messages are not read until requested by the process. This blocks the messages in other partitions which are assigned to the consumer from being read also. 

Because the partitions are independent of each other, I would like to parallelly consume messages in each partition in the non flowing mode. 

How can I achieve this?

**Comment by webmakersteve** [comment]
If you want to consume messages without blocking for a batch to be processed you need to split your batch consumers up appropriately. It is the nature of batch processing that you need to finish a batch before you fetch the next one. 

If you need a situation where each partition is consumed separately you should use separate consumers. Scale out to ensure you have one consumer per partition. I would recommend keeping them in their own process if possible (use node's `cluster` library)
