### ISSUE TITLE
Kafka Producer and Consumer stream error

### ISSUE THREAD

**Issue by senthil5053** [Blizzard/node-rdkafka#326]
I use version `2.0.0` of node-rdkafka in my project. I get the below below error very often eventhough my Kakfa cluster is healthy.
`"Kafka readStream consumer error', { [Error: broker transport failure]\n  origin: 'local',\n  message: 'broker transport failure',\n  code: -1,\n  errno: -1,\n  stack: 'Error: Local: Broker transport failure\\n    at Error (native)' }"`

Below is my code for read stream consumer:
```
var readStream = Kafka.createReadStream(kafka_settings.consumer, {
    'auto.offset.reset': 'latest'
}, {
    topics: topics,
    waitInterval: 0,
});

readStream.on('error', function(err) {
    global.log.error('Kafka readStream stream error', err);
});

readStream.consumer.on('event.error', function(err) {
    global.log.error('Kafka readStream consumer error\',', err); // Here this error being logged
})

readStream.consumer.on('ready', function(err) {
    global.log.error('Kafka readStream consumer ready\',', err);
})

readStream.consumer.on('disconnected', function(arg) {
    global.log.info('consumer disconnected. ' + JSON.stringify(arg));
});
```

And below is the consumer options set:

```
consumer: {
        'group.id': 'interface-consumer-' + env_suffix,
        'metadata.broker.list': kafka_host,
        'enable.auto.commit': true,
        'fetch.wait.max.ms': 5,
        'fetch.error.backoff.ms': 10,
        // 'debug': 'all',
        'socket.keepalive.enable': true,
        'auto.commit.interval.ms':5000,
        'heartbeat.interval.ms': 10000,
    }
```

Could you please help to resolve this ?

**Comment by erik-stephens** [comment]
Might be idle connection reaper which is harmless other than the noise.  If so, can consider it noise and [shut it up like so](https://github.com/edenhill/librdkafka/issues/768#issuecomment-246302856) or maybe [adjust metadata refresh rate](https://github.com/edenhill/librdkafka/issues/581).

**Comment by senthil5053** [comment]
Thanks @erik-stephens . How can we confirm that this is due to broker's idle connection reaper ?

**Comment by erik-stephens** [comment]
I don't know.  Unfortunately librdkafka is simply relaying the error that the broker is returning, so I think will depend on a change to the broker.  If you figure it out, let me know.

**Comment by webmakersteve** [comment]
If you check the Kafka logs it should tell you when connections are reaped. Broker transport errors can happen because of an unstable network as well. If you aren't seeing impact I think it would be safe to ignore it. `librdkafka` recovers in almost all error cases, but the log is just for your information. It is more concerning when you are producing data than when you are consuming data.

**Comment by senthil5053** [comment]
@webmakersteve @erik-stephens Sorry for replying so late. I have a question here, my Nodejs app would produce (using stream api) messages to different topic and consume the response from single topic.. So, i would be producing more messages than I consume.. Could you please help how we can best handle this error (`Local tranport failure`) in that case ?
