### ISSUE TITLE
Poll for errors from consumer

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#334]
How do I poll for errors in consumer?

According to librdkafka [documentation](https://github.com/edenhill/librdkafka/wiki/Error-handling), even the consumer needs to call the polling API to get error callbacks. 

But node-rdkafka doesn't support setting poll interval for consumers.

Is there another way to poll for errors or is this a missing feature?

**Comment by webmakersteve** [comment]
It is not a missing feature. You should not need to use `poll` on a consumer. Instead, you should use `consume` which polls for you.

As long as you are calling `consume` on regular intervals you will get errors propagated up to your object.
