### ISSUE TITLE
implement subscribe(pattern)

### ISSUE THREAD

**Issue by emilesalem** [Blizzard/node-rdkafka#337]
other libraries (https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#subscribe(java.util.regex.Pattern,%20org.apache.kafka.clients.consumer.ConsumerRebalanceListener)) let the consumer subscribe to topics matching given pattern. Would be nice to have.

**Comment by webmakersteve** [comment]
You can already subscribe to regular expressions. The code will look if the type of an element of an array is a regular expression, and if so, will use it instead of a string.

**Comment by mattness** [comment]
Closing, since similar functionality exists and no further information has been provided.
