### ISSUE TITLE
error_cb

### ISSUE THREAD

**Issue by sawdiggy** [Blizzard/node-rdkafka#338]
Would it be possible to allow the error_cb to be added?  It seems this is not supported (but part of librdkafka)

Thanks

**Comment by webmakersteve** [comment]
`error_cb` is new. You should be using `event_cb`, which will propagate `event.error` to the emitter.

**Comment by webmakersteve** [comment]
Closing the issue because I believe I gave a workaround. Upgrading librdkafka in the next few weeks which will bring in the new callback interfaces.
