### ISSUE TITLE
Node consumer process crashing with SIGSEGV 

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#339]
My consumer process crashes on starting up with SIGSEGV error. I tried debugging with segfault-handler but the crash log is absent. Without the node-rdkafka library the consumer process starts. 

Is this something known and any ideas how can I debug this further for some logs/fixes?

**Comment by webmakersteve** [comment]
No idea why you're getting a segfault without any logs. You should use gdp to get some more information

```bash
gdp node
...
(gdb) set args "path/to/file.js"
(gdb) run
```

**Comment by lewisdiamond** [comment]
`0x00007ffff6b9b67a in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6`

**Comment by lewisdiamond** [comment]
Since the previous trace didnt have debug symbols, I built librdkafka and node-rdkafka with debug symbols. Here's the result:
```
FATAL ERROR: v8::String::Cast Could not convert to string
 1: node::Abort() [ava]
 2: 0x121a2cc [ava]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [ava]
 4: v8::String::Cast(v8::Value*) [/home/ldiamond/dev/proj/analytics-endpoint/node_modules/node-rdkafka/build/Debug/node-librdkafka.node]
 5: v8::Local<v8::String> v8::Local<v8::String>::Cast<v8::Value>(v8::Local<v8::Value>) [/home/ldiamond/dev/proj/analytics-endpoint/node_modules/node-rdkafka/build/Debug/node-librdkafka.node]
 6: v8::Local<v8::String> v8::Local<v8::Value>::As<v8::String>() const [/home/ldiamond/dev/proj/analytics-endpoint/node_modules/node-rdkafka/build/Debug/node-librdkafka.node]
 7: NodeKafka::Conf::create(RdKafka::Conf::ConfType, v8::Local<v8::Object>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [/home/ldiamond/dev/proj/analytics-endpoint/node_modules/node-rdkafka/build/Debug/node-librdkafka.node]
 8: NodeKafka::Producer::New(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/ldiamond/dev/proj/analytics-endpoint/node_modules/node-rdkafka/build/Debug/node-librdkafka.node]
 9: 0x7ffff40c2ea6 [/home/ldiamond/dev/proj/analytics-endpoint/node_modules/node-rdkafka/build/Debug/node-librdkafka.node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [ava]
11: 0xb9095f [ava]
12: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [ava]
13: 0x2befbe68463d
```

**Comment by jpwilliams** [comment]
Had this issue recently and the issue was the result of having `node-rdkafka` use a version of `librdkafka` that was already on the system (in `/usr/lib`) rather than letting it use the version it compiles itself on installing the package.

Had to remove the system's `librdkafka`, but then `node-rdkafka` was always looking in the wrong place, so had to change the `LD_LIBRARY_PATH` to point at the right directory _inside_ `node_modules`.

Ugly, ugly patch, but see if the situation is the same for you; if so, this might be indicative of that bug inadvertently causing this.

**Comment by lewisdiamond** [comment]
Mine's getting the right lib
```
openat(AT_FDCWD, "/home/ldiamond/.../node_modules/node-rdkafka/build/Release/librdkafka.so.1", O_RDONLY|O_CLOEXEC) = 12
openat(AT_FDCWD, "/home/ldiamond/.../node_modules/node-rdkafka/build/Release/librdkafka++.so.1", O_RDONLY|O_CLOEXEC) = 12
```

**Comment by webmakersteve** [comment]
What are you passing into the config of your producer/consumer?

**Comment by krishanfrog** [comment]
I am not facing the issue anymore on updating the module. Will report if it occurs again

**Comment by webmakersteve** [comment]
@lewisdiamond Are you still seeing the issue?
