### ISSUE TITLE
Is it possible to completely manage offsets by application.

### ISSUE THREAD

**Issue by mario-grgic** [Blizzard/node-rdkafka#341]
I am evaluating node-rdkafka for a particular use case. I only have experience using Java Kafka client, and it seems node-rdkafka is quite different. 

In Java world, the client would poll and fetch a certain number of messages, the application loops through the messages and usually commits something to the database also committing offsets for the partition(s) the message belongs too. 

In case of rebalance the processed records and offsets are committed to the DB immediately. 

However, in node-rdkafka there does not seem to be poll() call for consumers. From application point of view you are given a message that you must process asynchronously (or else you are blocking the event queue), and while you are doing that you may be given the next message. If you commit the offset of the next message and the previous one (whose processing for what ever reason takes longer) is still running and you crash, you will effectively end up in a weird state where the committed offset is higher and previous message is lost.

Is there a way to use node-rdkafka like Java client? Basically, 

1. get a batch of messages, by explicitly asking for them (poll() in Java client world).
2. process each message and saving partition/offsets to database and results of message processing in single transaction. The message processing will entail a lot of async calls to fetch data (http requests, reading/writing stuff to db etc).
3. On rebalance commit transaction immediately and get new partitions, read DB committed offsets for new partitions and start consuming from saved offsets.
4. repeat step 1 indefinitely.

**Comment by erik-stephens** [comment]
I think so using `assign()`.  You may find #313 & confluentinc/confluent-kafka-go#91 helpful.

**Comment by mario-grgic** [comment]
Sure, assign allows me to restore offsets and to start consuming from persisted offsets for specified partitions. 

But how do you poll for messages manually when you want a batch of messages? Basically something like:

```
while (true) {
    data[] = poll(timeout);
   processData(data);
}

```

where `processData` saves data and partition/offsets to DB.

**Comment by erik-stephens** [comment]
If the question is how to poll, then something like the following?
```
consumer.on('data', (event) => {
    processData();
});
consuming = setInterval(() => consume(count), milliseconds);
```

**Comment by mario-grgic** [comment]
It seems this:

```
consumer.on('data' (data) => {
    processData(data);
}
```

gives continuous stream of data. It does not give me a "batch" i.e. an array of messages (whose size depends on various Kafka params). 

Basically, this just fires rapidly indefinitely, and you have to process message one by one, leading to a problem if one message takes longer to process than the next, the persisted offset will be wrong.

**Comment by clayne11** [comment]
It looks to me like you can just use the `[consume](https://blizzard.github.io/node-rdkafka/current/KafkaConsumer.html#consume)` method.

```typescript
const poll = () => {
  let timeoutHandle

  const consumeMessages = (err, messages) => {
    // handle message consumption
    
    timeoutHandle = setInterval(fetchAndCounsumeMessages(consumer), 500)
  }

  const fetchAndCounsumeMessages = (consumer) => {
    consumer.consume(100, consumeMessages)
  }

  return () => {
    clearInterval(timeoutHandle)
  }
}

poll()
```

**Comment by mario-grgic** [comment]
I have managed to consume message(s) synchronously (i.e. get one message, process it, get another etc) as follows:

```js
#!/usr/bin/env node

/**
 * Kafka consumer with at least once semantics.
 */

const Kafka = require('node-rdkafka');
const request = require('request');
const kafkaoffsets = require('./kafkaoffsets.js');

// Kafka topic to subscribe to.
const topic = 'test';

/**
 * When Kafka consumer group is rebalanced (because consumer joined/left the
 * group), we have to stop the work in progress, since we are potentially
 * assigned a different Kafka topic partition to work on, and someone else will
 * get our message in progress to process instead.
 *
 * @type {boolean}
 */
let stopWorker = false;

/**
 * This callback is invoked each time Kafka consumer group re-balance occurs.
 * We will be given our new partitions for each of the topics we subscribed.
 * Here we need to lookup the latest saved (successfully processed) offset
 * for each of the partitions and set it accordingly, so we start consuming
 * messages from next offset. This way in case we are restarted or crash we
 * remaining consumers can continue to process messages without losing anything.
 *
 * @param err any error that may have occurred on re-balance.
 * @param assignment new partition assignments for each of the topics.
 * we subscribed to.
 */
async function onRebalance(err, assignment) {
    try {
        // kill the work in progress, since we are getting new partitions for
        // the topic to consume.
        stopWorker = true;
        console.log('Rebalance called');
        console.log(assignment);
        if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
            // Load persisted offsets for the given partition assignments.
            let newAssignments = await kafkaoffsets.loadOffsets(assignment);
            console.log(newAssignments);

            // Note: this can throw when you are disconnected.
            // restore offsets for given assignments.
            this.assign(newAssignments);
        } else if (err.code === Kafka.CODES.ERRORS.ERR__REVOKE_PARTITIONS) {
            // Same as above, this can throw if we are disconnected.
            this.unassign();
        } else {
            // We had a real error.
            console.error(err);
        }
    } catch (error) {
        // an error occurred when trying to assign or unassign new assignments
        // for this consumer (most likely because we are disconnected).
        // The client will try to re-connect, and re-balance should be called
        // again.
        console.log(error);
    }
}

/**
 * Our Kafka consumer.
 */
const consumer = new Kafka.KafkaConsumer({
    'group.id': 'logprocessor_consumer_group',
    'enable.auto.commit': false,
    'enable.auto.offset.store': false,
    'auto.offset.reset': 'earliest',
    'metadata.broker.list': 'localhost:9092',
    'rebalance_cb': onRebalance
}, {});

// Connect the consumer.
consumer.connect({timeout: "1000ms"}, (err) => {
    if (err) {
        console.log(`Error connecting to Kafka broker: ${err}`);
        process.exit(-1);
    }

    console.log("Connected to Kafka broker");
});

consumer.on('disconnected', (args) => {
    console.error(`Consumer got disconnected: ${JSON.stringify(args)}`);
});

// register ready handler.
consumer.on('ready', onReady);

/**
 * Consumer is ready to start receiving messages.
 */
async function onReady() {
    console.log('Consumer is ready');
    consumer.subscribe([topic]);

    // noinspection InfiniteLoopJS
    while (true) {
        try {
            const data = await new Promise((resolve, reject) => {
                consumer.consume(1, (err, data) => {
                    if (err) {
                        return reject(err);
                    }
                    resolve(data)
                });
            });

            if (data.length > 0) {
                // new messages will start arriving after re-balance and new
                // assignments are given to us.
                stopWorker = false;
                await processMessage(data[0]);
            }
        } catch (err) {
            console.error(`Failed to consume message ${err}`);
            // TODO: Is this fatal error? Should the consumer process exit?
        }
    }
}

/**
 * Process single message we received.
 *
 * @param data Kafka message (object).
 * @return {Promise<void>}
 */
async function processMessage(data) {
    await print(data);
    await processData(data);
    if (!stopWorker) {
        await kafkaoffsets.saveOffsets(data.partition, data.offset);
    }
}

/**
 * Print Kafka message
 *
 * @param m
 */
async function print(m) {
    if (m) {
        console.log('Received a message:');
        console.log('  message: ' + m.value.toString());
        console.log('  key: ' + m.key);
        console.log('  size: ' + m.size);
        console.log('  topic: ' + m.topic);
        console.log('  offset: ' + m.offset);
        console.log('  partition: ' + m.partition);
    }
    return Promise.resolve();
}

/**
 * Wait specified number of milliseconds.
 * @param ms
 */
async function wait(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Process the payload.
 */
async function processData(message) {
}
```

However, my main concern now is if librdkafka or its wrapper is going to keep consuming and buffering messages while I am taking my time to run processData here. What if processData is taking say an hour? Will everything continue to work?

**Comment by webmakersteve** [comment]
`librdkafka` has a max queue buffer size. If your processing functions are taking long, so long as you have a limit on how often you are calling consume, you will only have so many messages in the buffer available to you. Additionally, auto committing offsets will only happen if the message has not only been read, but passed to you through consume.

Librdkafka, however, will continue heartbeating in the background as you do your work, as opposed to the default behavior of the Java client, which only heartbeats on polling for new messages.

**Comment by mario-grgic** [comment]
Thank you for the clarification. I have also run some experiments with my code above taking 1 hour to process each message, while a bunch of producers were writing to Kafka at the same time on the same topic. I left this running all weekend and it all worked fine (messages were really small on the other hand).

I have also taken a look at go and python clients and they also use librdkafka to implement producer/consumer. However, they use typical consumer.poll() loop, just like Java client.

I wonder if it would be too hard to do the same for node-rdkafka as well? It would definitely make things more consistent for people that have to provide consumer wrappers for various languages.

**Comment by webmakersteve** [comment]
Node is an async language for IO operations. I kept that in mind when designing the interface to the client. This, however, complicates things a lot when you want to keep the poll loop pattern of doing things that librdkafka has.

The way I suggest doing something very similar is by using streams. If you get a consumer read stream, back pressure will stop the consumer from reading too many messages as you spend the time you need to do the work in your "loop", which can be the write method of a write stream.
