### ISSUE TITLE
[feature] Multi topics and partitions commit

### ISSUE THREAD

**Issue by oliviertassinari** [Blizzard/node-rdkafka#345]
In order to prevent messages lost. I'm reimplementing the offset commit logic on userland (I commit only once the messages are processed, not received).
I'm using the `'enable.auto.commit': false` global option to disable the "auto commit". I'm also batching the commit of the offsets evert *X* messages or *Y* seconds. In order to do so, I call the async `consumer.commit()` API multiple times (one time per (topic, partition) tuple).

I have noticed that the "auto commit" logic commit on different topics and partitions **at the same time**. I was looking into using such API instead of calling `consumer.commit()` *X* times. It would be more efficient.

**Comment by webmakersteve** [comment]
The commit calls under the hoot will still be multiple requests to the broker, but I am totally for a JSland function that will allow an array of topic, partition, and offsets to be provided in order to help optimize this case - if that's what you're envisioning.

**Comment by oliviertassinari** [comment]
> The commit calls under the hoot will still be multiple requests to the broker

Oh great. So there is no performance overhead with my approach. The issue is solved as far as I'm concern.

**Comment by webmakersteve** [comment]
Well, it isn't a 1:1 request-per-call necessarily, so we can definitely get more performance out of commits.

https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1685

There is a method I can bind to that will take an array so I will go ahead implementing that. Shouldn't be too long and it will make it in the next release!

**Comment by webmakersteve** [comment]
Support added with #351

**Comment by webmakersteve** [comment]
Published 2.2.3 


f5b9d802e562b47dc9125f262aa2a51fb9f3c71b

**Comment by oliviertassinari** [comment]
@webmakersteve Thank you a lot. I will update our integration with `node-rdkafka` :).
