### ISSUE TITLE
Consumer commits only after successful message produce

### ISSUE THREAD

**Issue by nabeelz6** [Blizzard/node-rdkafka#346]
I have the following stream processing use case:
1. Consume a message
2. Do some processing on that message
3. Produce the result to a different topic

After step 3 is successful (i.e. producer message got successfully written to Kafka and acknowledged), I'd like to commit the offset for the consumer but not before.

Is there a fool-proof way to ensure I commit the right offset for the consumed+produced message (assuming 1 message = 1 produced message). This question is the same as python library's question [here](https://github.com/confluentinc/confluent-kafka-python/issues/300). 

The following solutions come to mind are:

---

**Solution 1**
1) `dr_cb ` ise true. `enable.auto.commit` is false. 
2) Consume a message, then process the message, and then produce the final message to a different topic -- passing the original consume partition and offset for `opaque` parameter of produce
3) On deliver-report event (setup outside the process/produce function), call `consumer.commit()` for the delivery report's `report` parameter. 

NOTE: With this solution, I'm not sure if I could accidentally commit an older offset then the previously committed offset. Maybe I keep a hash of the latest offset by partition to avoid this problem?

---

**Solution 2** (per edenhill's response [here](https://github.com/confluentinc/confluent-kafka-python/issues/300#issuecomment-358435530)):
1) `dr_cb ` ise true. `enable.auto.offset.store` is false. `enable.auto.commit` is true ???
2) Consume a message, then process the message, and then produce the final message to a different topic -- passing the original consume partition and offset for `opaque` parameter of produce
3) On deliver-report event (setup outside the process/produce function), call `consumer.offsetsStore()`for the delivery report's `report` message (which includes partition and offset).  

NOTE: Similar to Solution 1's note above, do I need to worry about handling out-of-order offsets? I didn't fully understand edenhill's [response](https://github.com/confluentinc/confluent-kafka-python/issues/300#issuecomment-358435530) about *'need a separate layer that maps consumed&processed message offsets to delivered offsets'*

---

Which is the better solution for my use case? Are there other solutions I'm not thinking about? 

Thanks!

**Comment by localzjaz** [comment]
In my previous experiments you do need to worry about committing out of order offsets. By that I mean if you commit an offset older than what is committed I'm pretty sure that will be accepted. Will you get out of order offsets from the callback? I don't know.

**Comment by webmakersteve** [comment]
Messages are read in order per partition. Offsets are stored per partition. As long as you are processing messages serially, you can just commit to the highest offset.

But consider this:

1. Consume messages using a kafka consumer in batches
2. Process messages, in batches
3. Produce messages, in batches
4. Every so often on an interval, call the `producer.flush()` method
- If the method errors out, crash the process and begin reading from the last committed offsets again
- If the method succeeds, commit your offsets for all read messages

In this case flush will ensure that all messages in the queue have been published successfully, then you can just commit on an interval with the assurances that your messages have made it to their next destination.
