### ISSUE TITLE
Error: Local: Authentication failure" with node-rdkafka

### ISSUE THREAD

**Issue by atulkumar-it** [Blizzard/node-rdkafka#349]
I am using node-rdkafka 2.0.0 version.
My application is trying to make connection with IBM MessageHub, Below are the config.
'security.protocol' : 'sasl_ssl',
'ssl.ca.location' : '/etc/ssl/certs',
'sasl.mechanisms' : 'PLAIN',
'api.version.request' : true,
'compression.codec' : 'gzip',
'retry.backoff.ms' : 1000,
'message.send.max.retries' : 5,
'socket.keepalive.enable' : true,
'delivery.report.only.error' : false,
'socket.timeout.ms' : 30000,
'dr_msg_cb' : true,
'dr_cb' : true,
'log.connection.close': false

Kafka.librdkafkaVersion: 0.9.5 |  
Kafka.features: gzip,snappy,ssl,sasl,regex,lz4 |

But I am getting below error:
{"message":"authentication failure","stack":"Error: Local: Authentication failure","origin":"local","code":-1,"errno":-1}

Also once the application goes in disconnect mode, it never able to reconnect. Is there any way to recover the connection after its idle time passed?

**Comment by webmakersteve** [comment]
Calling `disconnect` and `reconnect` on an object should cause it to reconnect, however, if there is an error connecting I recommend you make a new object if you are trying to recover in those failure cases because the state could be unknown.

As far as that authetnication failure - it looks like it is just a credential problem and not something inside `librdkafka`. I would just ensure the SASL stuff you are providing is correct.

**Comment by webmakersteve** [comment]
Interesting that they're working without any problems even with authentication failures...

I don't have any ideas other than to make sure librdkafka thinks it has sasl support. You can do this by running `console.log(require('node-rdkafka').features);`

**Comment by gonejack** [comment]
I got the same issue with SASL, After manually turn off the network for testing reconnect mechanisms, the document seems not mentioning how to handle connection failures, what error should be listen and check before calling disconnect and reconnect? @webmakersteve

**Comment by webmakersteve** [comment]
@gonejack you do not need to call disconnect unless you are shutting down your application. The client internally manages disconnection and reconnection to individual brokers seamlessly so you should not need to.

**Comment by gonejack** [comment]
@webmakersteve I tried your suggestion, just new consumer without invoking disconnect, then the old consumers would still taking topic partitions after network restarted, resulting new consumer consumes only part of the messages.

**Comment by bernardpletikosa** [comment]
@webmakersteve it does

```
[ 'gzip',
  'snappy',
  'ssl',
  'sasl',
  'regex',
  'lz4',
  'sasl_gssapi',
  'sasl_plain',
  'sasl_scram',
  'plugins' ]
```

**Comment by gonejack** [comment]
@bernardpletikosa After switch to local Kafka brokers, reconnection working fine when restarting the Kafka, the problem may cause by the Kafka server but not sure now.
