### ISSUE TITLE
Commit callbacks don't seem to be invoked until disconnect() is called

### ISSUE THREAD

**Issue by thomaslee** [Blizzard/node-rdkafka#350]
I can't work out the expected semantics of `offset_commit_cb: <function>`. Probably worth noting I'm using `auto.commit.enabled=false`.

See this repro case: https://gist.github.com/thomaslee/cb080010ab950956f7efc312dfbc5e2f#file-repro-js (there's a little unused/unnecessary diagnostic code in there left in place in case it's useful).

I was expecting `offset_commit_cb` to be invoked each time I commit a message, but although it seems like the commits occur (per debug output from rdkafka), the callbacks don't seem to be invoked until disconnect() is called:

```
ready
processing message consumer-service-test-1/0 @ 182481
consume is done: 1
processing message consumer-service-test-1/0 @ 182482
consume is done: 1
processing message consumer-service-test-1/0 @ 182483
consume is done: 1
processing message consumer-service-test-1/0 @ 182484
consume is done: 1
processing message consumer-service-test-1/0 @ 182485
consume is done: 1
processing message consumer-service-test-1/0 @ 182486
consume is done: 1
processing message consumer-service-test-1/0 @ 182487
consume is done: 1
processing message consumer-service-test-1/0 @ 182488
consume is done: 1
processing message consumer-service-test-1/0 @ 182489
consume is done: 1
processing message consumer-service-test-1/0 @ 182490
consume is done: 1
processing message consumer-service-test-1/0 @ 182491
consume is done: 1
#
# I sit here for 10s or so doing nothing, then CTRL-C/SIGINT
# note offset_commit_cb is not invoked until the SIGINT+disconnect fires,
# then they all fire at once
#
^Ccommitted [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182482 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182483 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182484 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182485 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182486 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182487 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182488 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182489 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182490 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182491 } ]
committed [ { topic: 'consumer-service-test-1',
    partition: 0,
    offset: 182492 } ]
```

Am I using this feature wrong? What's happening here?

**Comment by webmakersteve** [comment]
The consumer's consume method is the thing that initiates a request to the consumer and does a lot of housekeeping, such as sending asynchronously sent commits. When you call disconnect, it is cleaning up by sending out pending requests. But the library is optimized, so it will try to batch up the sends as best as it can.

I think you can get around what you're trying to do by using the sync commit methods. Those ensure the request is sent. Or, alternatively, you can consume another time after you have queued up all the commits and that should get the commit request to actually be sent.

**Comment by oliviertassinari** [comment]
@thomaslee I believe I have already experienced this issue. As far as I know `auto.commit.enabled=false` does nothing. It's `'enable.auto.commit': false,`.

**Comment by thomaslee** [comment]
Finally figured it out while playing around with librdkafka++: @webmakersteve you were right that the key to it all is consume(), the thing that caught me up here was that each prior consume() completed prior to the _final_ consume(): the commits were still in flight when the final consume() was invoked. Adding a sleep between each call to consume() (via `setTimeout`) gives each commit time to complete prior to the next call to consume(). Quirky, but workable. Thanks folks!
