### ISSUE TITLE
Read Data in round robin sequence with multiple consumer

### ISSUE THREAD

**Issue by mjafarpour** [Blizzard/node-rdkafka#355]
Hi,
I use this scenario : 

1.Use a topic with 3 partitions
2. Use Producer in stream form
3. Use Consumer in Stream form with different group.id

I want the consumers get unique message but i see the 3 consumers get same message from queue and this consumers is a kind of task worker.
I try to use 'partition.assignment.strategy' with 'roundrobin' but NOT worked.
How can run this scenario?

**Comment by webmakersteve** [comment]
Your consumers need to have the same group id in order to do what you’re asking.
