### ISSUE TITLE
Unable to install node-rdkafka

### ISSUE THREAD

**Issue by subhasisbanik** [Blizzard/node-rdkafka#356]
Hi,
I am running the below command to install node-rdkafka into my node app:
npm install node-rdkafka --save

But it seems node-gyp is throwing me the issue,
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/eternity/Data/nodeapp/node_modules/node-rdkafka
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN nodekafkaapp@1.0.0 No description
npm WARN nodekafkaapp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eternity/.npm/_logs/2018-02-18T06_31_28_425Z-debug.log

I have node@9.4.0, npm@5.6.0
when I am trying to run node-gyp -v, I am getting the error below:
module.js:540
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

I am also attaching a screenshot. Please help.
![unable to install node-rdkafka](https://user-images.githubusercontent.com/25420904/36349060-06e16d80-14a4-11e8-81f8-bc04128075a9.png)

**Comment by webmakersteve** [comment]
You need to install crypto and ssl libraries. I believe on Ubuntu you can instal openssl-dev for those.

**Comment by subhasisbanik** [comment]
Hi,
I installed,
sudo apt-get install libssl-dev
and then tried to,
npm install -g node-rdkafka
But it seems it fails again.
Attached is the screenshot.
![unable to install node-rdkafka](https://user-images.githubusercontent.com/25420904/36405779-6158a128-1618-11e8-9603-baf17289c07c.png)

**Comment by webmakersteve** [comment]
This was happening to a few other people too but I haven't been able to pinpoint the problem.

Does installing it not globally work? That's probably the recommended way to do it anyway.

**Comment by subhasisbanik** [comment]
No, it doesnt work in anyway I try..
Please help..

**Comment by webmakersteve** [comment]
Taking another look at the logs you posted, it looks like it is a file permission issue.

https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

Try what that says and see if that fixes the issue.

**Comment by capnmctavish** [comment]
Still having the same issue while installing node-rdkafka on OSX Catalina. 

Already installed and exported the following
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib

ERROR IS AS FOLLOWING

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jay/Documents/azure-event-hubs-for-kafka-master/quickstart/node/node_modules/node-rdkafka
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN kafka_node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jay/.npm/_logs/2021-04-28T09_09_51_725Z-debug.log
