### ISSUE TITLE
How to process consumer data with Avro?

### ISSUE THREAD

**Issue by subhasisbanik** [Blizzard/node-rdkafka#360]
I am getting Avro messages from Producer and would like to process the same in my consumer.
I am using,
https://www.npmjs.com/package/avsc

But it seems that consumer isn't processing anything and even not throwing any errors.
Could you please help me?

**Comment by FuzzOli87** [comment]
@subhasisbanik I wrote a library last year that wrapped this library and avsc to produce and consume Avro messages. I need to do some updates on it but you can see the implementation here:
https://github.com/parkhub/iris/blob/master/src/lib/wrapConsumerHandler.js

You have to define the schema you want to use to decode your messages first and then decode it.

**Comment by codeburke** [comment]
@subhasisbanik How are you handling schemas? If you are using the Confluent platform and schema registry then I am actively working on a version that extends node-rdkafka Produce and Consumer classes to support the Confluent platform.

**Comment by webmakersteve** [comment]
Let me know if the answers @codeburke and @FuzzOli87 have provided are insufficient, but `node-rdkafka` does not care what the format of your data is - it deals with consuming and producing binary buffers.

**Comment by tannad** [comment]
@FuzzOli87, @webmakersteve, @codeburke  
Hi Daniel, Stephen and Ryan,
I am connecting with Kafka with kerberos.keytab and kerberos.principaI, that connection with rdkafka is running fine. My consumer is receiving the buffer. I would like to read the stream of data using avro or with schemaRegistry  but schema registry and avro with rdkafka doesn't seem to work. 
@webmakersteve : How do you format the binary buffers? ... 

After looking at this post I looked into the iris example.... herewith my question:
1. How do you connect with kerberos.keytab and kerberoes.principal with iris, is there an example?  

@codeburke 
I am looking for one library where in  that helps end to end with Kafka kerberos connection and also formatting the binary buffers, also may be sorting those streams per id etc..

Appreciate your prompt response.

Many thanks,
Dharmi

**Comment by webmakersteve** [comment]
If you had a code sample I could look at it may help me, but otherwise I don't know how to help. It seems like a lot of the trouble you're having is implementation specific.

**Comment by tannad** [comment]
@webmakersteve 
Hi Stephen, 
I have sent you an email with all the details. Hope that is fine.
Thank you for helping me out.

Best regards,
Dharmi

**Comment by codeburke** [comment]
Sounds very KStream-ish (transforming/sorting streams). Let me know if you'd like another pair of eyes on your code/use cases.

**Comment by tannad** [comment]
@codeburke 
Hi Ryan,
Have sent you an email. Hope to hear from you. Appreciate it.

Many thanks,
Dharmi

**Comment by tannad** [comment]
@codeburke  and @webmakersteve 

Hi Ryan and Stephen,

AVRO is working now. 

Best regards,
Dharmi

**Comment by webmakersteve** [comment]
@subhasisbanik did you solve your issue with AVRO? Can I close this issue?

**Comment by eliw00d** [comment]
I am running into almost verbatim what the OP described: consumer.on('data') does not seem to process for AVRO messages and as far as I can tell is not throwing any errors. The same consumer has no problem processing non-AVRO messages, so it is quite perplexing.

Is there any sort of configuration with node-rdkafka or librdkafka that would prevent these messages from being consumed?

**Comment by codeburke** [comment]
You should still be getting the Avro-encoded Buffers in the event.value.
Are you saying you are getting no events from consumer.on(‘data’)?

**Comment by eliw00d** [comment]
That was my thought as well, but it gets no events from those topics.

**Comment by codeburke** [comment]
Whether it is Avro or not won’t affect the consumer. Can you share some
code?

**Comment by codeburke** [comment]
No problem!
