### ISSUE TITLE
librdkafka Upgrade

### ISSUE THREAD

**Issue by stefanhipfel** [Blizzard/node-rdkafka#362]
Hi,

is there a timeline when node-rdkafka will be upgraded to the next librdkafka version?

Thanks a lot in advance!

**Comment by rbustami** [comment]
Bump

**Comment by webmakersteve** [comment]
I was seeing if I could hold out until the next release which has some other bug fixes I'm looking for. But I'm not sure when it's going to be released. Will look into upgrading in the next week.

**Comment by stefanhipfel** [comment]
Maybe worth waiting for 0.11.4:
https://github.com/edenhill/librdkafka/issues/1712

**Comment by stefanhipfel** [comment]
Next release of librdkafka within 2 weeks:
https://github.com/edenhill/librdkafka/issues/1691
