### ISSUE TITLE
Space in path the reason of "no such file or directory" [make failed]

### ISSUE THREAD

**Issue by dassader** [Blizzard/node-rdkafka#364]
I have error: `no such file or directory` when i try `npm install node-rdkafka` into folder which has space in name. But when i remove spaces the problem has gone.
![image](https://user-images.githubusercontent.com/6272505/36735631-47d0ff08-1bdf-11e8-9e34-b253dec7493a.png)

OS: High Sierra 10.13.3
NPM: 5.6.0
Node: 8.9.4

**Comment by webmakersteve** [comment]
This looks like a limitation of the way `node-gyp` passes the path into clang for linking. It is thinking they are separate files. Unfortunately the only thing I can recommend here is to not have a folder with spaces in it =\ 

I know that isn't an awesome answer, but I'm not sure this is something I can solve.
