### ISSUE TITLE
CHANGES.md empty since 0.3.0?

### ISSUE THREAD

**Issue by IdanAdar** [Blizzard/node-rdkafka#371]

**Comment by JaapRood** [comment]
If you're looking for release notes, [you can find those as part of the Github releases](https://github.com/Blizzard/node-rdkafka/releases). As far as the file is concerned, looks like it might have been some common project boilerplate, but never used?

**Comment by webmakersteve** [comment]
I have been using the releases to publish the changelog rather than the changes file. I'll leave this open until I remove the changes.md file because it isn't being used.
