### ISSUE TITLE
Partition equal to 0 coerces to "false", it returns a TypeError

### ISSUE THREAD

**Issue by alexayalabonilla** [Blizzard/node-rdkafka#375]
When I set "partition" to 0, I got this error ` 'partition" must be a number and must set"`

`Line 57: topic-partition.js `

**Comment by webmakersteve** [comment]
Fixed with https://github.com/Blizzard/node-rdkafka/commit/80a25e05a27f2a979ac8395a4ec964ef88f1c257. Try 2.3.1 :) Sorry about that!
