### ISSUE TITLE
Bug Introduced in version 2.3.0: TypeError: "partition" must be a number and must set

### ISSUE THREAD

**Issue by miguelpais** [Blizzard/node-rdkafka#376]
Hi,

First of all thanks a lot for the work put in to create this library. I'm very thankful for it.

I've noticed that the most current version (2.3.0) introduces a small bug, in which, when calling:

``` 
this.consumer.assign([ { topic: TOPIC, partition: 0, offset: 0 } ]);
```

The following error is returned:

```
TypeError: "partition" must be a number and must set
``` 

This behaviour does not occur on version 2.2.3, so I think it might have been introduced very recently.

Thanks you.

**Comment by webmakersteve** [comment]
Fixed this today! Sorry about that. Try 2.3.1

**Comment by miguelpais** [comment]
Thanks a lot @webmakersteve for your effort ! ;)
