### ISSUE TITLE
Reset to earliest a consumer that previously has commit all message.

### ISSUE THREAD

**Issue by alexayalabonilla** [Blizzard/node-rdkafka#377]
I am trying to assign a consumer to the earliest offset, however, it only consumes the messages that have not commit. Is there a way to assign the consumer to the ‘earliest’ value even it has committed all messages previously?

```javascript
const consumer = new Kafka.KafkaConsumer({
  'group.id': 'set2',
  'metadata.broker.list': 'localhost:9092',
  'enable.auto.commit': false,
  'rebalance_cb': function(err, assignment) {
    if (err.code === Kafka.CODES.ERRORS.ERR__ASSIGN_PARTITIONS) {
      this.assign([ { topic: topic, partition: 0, offset: 'earliest' } ]);
    } else if (err.code == Kafka.CODES.ERRORS.ERR__REVOKE_PARTITIONS){
      this.unassign();
    } else {
      console.error(err);
    }
  }
})

consumer.connect();

consumer.on('ready', function() {
    console.log('connected');
    consumer.subscribe([topic]);
    consumer.consume();
  })
  .on('data', function(data) {
    console.log(`offset: ${data.offset}`);
  });
```

Thanks in advance

**Comment by webmakersteve** [comment]
You should use `auto.offset.reset` and set it to `earliest` in your consumer config. Then, just ensure you do not commit offsets on any sort of interval to make sure no offsets are stored for your group.

If you'd prefer not to do it that way, you can assign the partitions yourself by fetching metadata and assigning the consumer to every partition with a starting offset of 0 or "earliest". 

Hope that helps.

**Comment by alexayalabonilla** [comment]
Hi @webmakersteve , I have tried the second option, using 🥇 
```javascript
this.assign([ { topic: topic, partition: 0, offset: 'earliest' } ]);
```
It does not work. 

However, I have tried with `offset: 200`, and it works( sending msgs since offset = 200)
