### ISSUE TITLE
client.getMetadata(...) no longer creating default Topic ?

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#387]
Hi @webmakersteve I just noticed on our sample apps that the infamous side effect of using `client.getMetadata({ topic: topicName, ... ` 
i.e. to create a topic with default options, canceling any further use of topic-level configs such as acks/reset.offsets 

is apparently gone if I use the code at the current master level (but still there if npm grabs 2.3.1).

looking at the commits must be a side effect of the librdkafka upgrade.

can you confirm the good news ?

**Comment by webmakersteve** [comment]
I don't see any comments in the `librdkafka` change log about that, but maybe it's a happy accident! 

Did you upgrade your Kafka cluster's recently? It may also be a broker side change that is causing the side effect to no longer happen.
