### ISSUE TITLE
Stale stats are being reported for partitions not consumed by a consumer instance

### ISSUE THREAD

**Issue by rsubramanyam2994** [Blizzard/node-rdkafka#390]
I am using non-flow mode of kafka consumer, running 2 consumer instances with the same consumer group id. I have set "statistics.interval.ms" to be 30 seconds. I observe that when an instance is not actively consuming a topic, the stats for that topic are not updated. 

For example, here are the stats reported by two consumer instances around the same point of time.

Stats from consumer instance which is NOT actively consuming the partition
```
{
  "topicStats": {
    "hiOffset": 5745429764,
    "partition": 0,
    "appOffset": 5742681968,
    "lowOffset": 5670818881,
    "committedOffset": 5742681968,
    "storedOffset": 5742681968,
    "topic": "test",
    "consumerLag": 2747796,
    "messages": 21997,
    "nextOffset": 5742690775
  }
}
```

Stats from consumer instance which IS actively consuming the partition
```
{
  "topicStats": {
    "hiOffset": 5748025881,
    "partition": 0,
    "appOffset": 5748025881,
    "lowOffset": 5670818881,
    "committedOffset": 5748025656,
    "storedOffset": 5748025881,
    "topic": "test",
    "consumerLag": 0,
    "messages": 5538225,
    "nextOffset": 5748025881
  }
}
```
We observed the hi offset for the partition is constantly increasing as reported by the actively consuming instance

We also observed the same stale stats message for an hour even though the stats interval is set at 30 seconds. (hiOffset as reported by this instance was constant which is not the case)

Is this an expected behaviour for reporting stats or is it a bug?

**Comment by webmakersteve** [comment]
This is something you will need to bring up on the `librdkafka` repository. This library just forwards the stats it gets along for consumption.
