### ISSUE TITLE
queryWatermarkOffsets is not a function

### ISSUE THREAD

**Issue by leovujanic** [Blizzard/node-rdkafka#392]
Hi @webmakersteve ,

I am trying to use `queryWatermarkOffsets` on producer and I am getting `TypeError: this._client.queryWatermarkOffsets is not a function`.  I don't have that issue with the consumer.  I was following the README where is mentioned that `queryWatermarkOffsets` can be used both with producers and consumers.

**Comment by azabbyy** [comment]
I am also getting this issue.
