### ISSUE TITLE
Dealing with a Producer "memory leak"

### ISSUE THREAD

**Issue by fvcaputo** [Blizzard/node-rdkafka#395]
The last few days I was dealing with a small, but very annoying, memory leak that seemed to start happening when I started using the lib's producer.

I have this process that every few hours it looks for messages to producer on a kafka topic. So the idea here was, create a producer, connect, send, disconnect. It works but I noticed every time a small memory increase that just wouldn't go away.

I believe I have tracked the problem to `setPollInterval`. During the process I mentioned above, I also set an interval to the producer, which I believed was cleared on `disconnect`.  However after reading the documentation and looking at the code I realized that on disconnect the producer does clear the interval, but then it binds a function on `ready` to set it again. The "leak" I was investigating seems to be this listener that was bound on disconnect.

I was able to solve my problem by calling poll during the process, instead of setting the interval. However I kind of feel this looks like a workaround more than anything.

So here I'm really more of posing a question about the behavior of `producer.disconnect()`. I feel that this method should simply clear everything and not have this other side-effect of binding listeners, and instead if someone plans on reconnecting the producer then that person should need to set the interval again. I also feel this is specially bad when using streams, the producer stream sets a poll interval by itself so when you close it you don't even know this is happening internally to the producer instance.

What do you think, @webmakersteve? I could do this change in a small PR if you agree. :)

**Comment by indieyourself** [comment]
@fvcaputo I also meet a memory leak case. Can you show how you fix it?

**Comment by fvcaputo** [comment]
@indieyourself Sorry, we ended up changing the lib to interact with kafka. Currently we are using kafka-node.

**Comment by webmakersteve** [comment]
Disconnect should clear everything. If it doesn't, it's a bug. Would be happy to take a PR for that @fvcaputo !
