### ISSUE TITLE
No such configuration property: "auto.offset.reset"

### ISSUE THREAD

**Issue by jayeheffernan** [Blizzard/node-rdkafka#40]
I am trying to have my consumer start from the smallest/earliest offset when there is none yet stored, using the option `"auto.offset.reset":  "smallest"`, as according to [Configuration.md](https://github.com/edenhill/librdkafka/blob/2213fb29f98a7a73f22da21ef85e0783f6fd67c4/CONFIGURATION.md'), but am getting the error`No such configuration property: "auto.offset.reset"`.  Other configuration options do work, e.g. `"auto.commit.enable": false`.

**Comment by jayeheffernan** [comment]
Guess I didn't RTFM,

> Not all of these options are supported. The library will throw an error if the value you send in is invalid.

Any plans to support this option?  Or any other recommended way of achieving this functionality?

**Comment by Pchelolo** [comment]
@jayeheffernan Are you quite sure you're setting the ` "auto.offset.reset"` in the topic config, not in the global config?

**Comment by jayeheffernan** [comment]
I am quite sure I was *not* setting it on the topic config.  Correcting this, it works!  Thanks very much for your help.
