### ISSUE TITLE
KafkaConsumerStream consumption rate causing time-outs and overall instability on clusters with throughput quota

### ISSUE THREAD

**Issue by JaapRood** [Blizzard/node-rdkafka#401]
We're running a service that consumes messages from a cluster with [a throughput quota](https://cwiki.apache.org/confluence/display/KAFKA/KIP-13+-+Quotas). At moments of high throughput we're getting reports of throttling through `event.throttle`, with the amount the broker throttled a Fetch request going up steeply and reaching time-outs.

As a result, everything becomes unstable. The most common thing we see is a `ConsumerGroup` heartbeat timing out, causing a rebalance event. As we restore processing state from Kafka this only puts more stress on the cluster.

I've tried implementing a `KafkaConsumerStream` based solution, listening for `event.throttle` from the consumer and wrapping `_read_message` and `_read_buffer` to delay consumption for a while. However, it seems that because `KafkaConsumer.consume()` uses it's own timeout, we never wait for the throttled response from the broker to come back, basically ignoring the back-pressure the Broker is trying to give. In our testing this means we've generally already made ~30 requests for the first throttle event from request~10 to come in, with it already to late to react to.

## Expected behaviour

For the consumption of messages to respect throughput quotas set, slow down consumption and prevent time-outs causing more instability.

## Possible fix

I'm not sure how `librdkafka` deals with quotas itself, if at all. My limited knowledge of C and just the reference docs don't paint me a picture. That makes it hard to say at what level of the stack a back-off would be implemented, as it already might be at some point.

_If_ the `KafkaConsumerStream` is the place to implement this (which I can imagine as it already is responsible for the back-pressure mechanism), it would need feedback from calling `consumer.consume()` about the consume call having timed-out. It could then respond by backing-off future consumption until either a subsequent request doesn't time out or throttling information is received. Currently, from what I can gather, [the required time-out errors are caught by the worker executing the consumption call and not forwarded to Node](https://github.com/Blizzard/node-rdkafka/blob/master/src/workers.cc#L523-L550).

I'd be more than happy to give the `KafkaConsumerStream` level of rate limiting a shot if that's the way to go. I just can't really tell if it is 😅.

**Comment by webmakersteve** [comment]
I think having the stream implement `event.throttle` is a great idea, and is the perfect place to put that logic. I reviewed your PR initially and left some other comments there.
