### ISSUE TITLE
Consumers failover handling within the same consumer group

### ISSUE THREAD

**Issue by mlazzarini** [Blizzard/node-rdkafka#402]
My scenario is the following: I'm running 2 Kafka consumers in the same consumerGroup. They consume messages from one topic on a single partition: so one of them is actively consuming from that topic, while the other one is idle. When the "active" consumer fails, I expect the other one to take over the message consumption, and this actually happens, but just after _some_ time. 

Now, here I see 2 issues:
1. during this time the application is unavailable, so I want to minimize this time
2. I lose messages during the "hand-over"

### Around issue 1:
I reduced this time by setting:
```
'session.timeout.ms': 6000,
```
which after some tries seems to be the minimum value (even if [lib-rdkafka documentation](https://github.com/edenhill/librdkafka/blob/0.11.1.x/CONFIGURATION.md) is reporting a different range of possible values: `1 .. 3600000`)

### Around issue 2:
As long as I know, I should not be losing any messages, as zookeeper should store the last commit, rebalance and restore the next consuption from _there_. So maybe I'm running sth wrong in my configuration. Here's some of the possible relevant ones that I'm using:
```
		'debug': 'all',
		'enable.auto.commit': false,
		'log.connection.close': false,
		// Trying to reduce latency
		'queue.buffering.max.ms': 1,
		// Client group session and failure detection timeout
		'session.timeout.ms': 10000,
		'socket.blocking.max.ms': 100,
		'socket.keepalive.enable': true,
```

NB. I do a `stream.destroy()` before shutting down the consumer, trying to trigger an immediate rebalance, but this doesn't actually happen.

I'm using:
- node v. 8.9.0
- node-rdkafka v. 2.1.1

**Comment by sfrooster** [comment]
You say you lose messages during the handover, meaning you know consumer-1 has processed through offset N, and committed either offset N or n<N back to the broker/cluster/zookeeper and then consumer-2 starts consuming from offset n>=N+2.  Is that right?

I see you have "enable.auto.commit" set to false, so you probably out to include your manual offset commit code so it can be verified you don't have a bug there.

While on the topic - I'd highly recommend setting "enable.auto.commit" to true and instead set "enable.auto.offset.store" to false and then manually managing when you call "offsetsStore".  It likely accomplishes the same thing as trying to manually manage the actual commits, and it's simpler.  Just my .02..

**Comment by webmakersteve** [comment]
The delay you are experiencing in the "handoff" is the rebalance delay. Kafka debounces multiple consumers going down at the same time. This also allows for time for the consumer leader to assign offsets after a known set of consumers are available, and for the group coordinator to send those assignments out to all the consumers in the group.

Destroying the stream will eventually cause a rebalance, but it will not be immediate. Rebalances are debounced and they also wait for clients to have the chance to commit their current offsets.

The rebalance delay is both broker side and client side. You need to set the minimum value for the debouncing on your cluster if you want it to be lower than the 6 seconds you provided.

As for your messages being lost, it could be for a few reasons:

1. You are not committing.

If you are not committing, when a rebalance happens and consumers begin consuming, they start from the offset reset. If the offset reset they are configured to start on is latest (the default), they will begin consuming from the tail of the log and miss any messages between the rebalance and the tail at that moment. I would ensure that commits are going through.

You can potentially do this by registering an offset_commit_cb to the config to have it logged each time you commit offsets.

2. They are in different groups

The group id is not specified in the config you provided but I assume it is the same. If it's not it would mean that rebalances are not triggered the way you expect.

**Comment by mlazzarini** [comment]
Thanks for the explanation. As you said, the rebalance delay's value must be in the allowable range as configured in the cluster configuration by `group.min.session.timeout.ms` and `group.max.session.timeout.ms`. Looking at our broker configuration, `group.min.session.timeout.ms` is set to `6000`, so that makes sense. 

As far as losing messages, we were indeed not committing. So that side of the problem is now solved as well.

Thanks for the help!
