### ISSUE TITLE
What is the meaning of negative offset

### ISSUE THREAD

**Issue by Patafix** [Blizzard/node-rdkafka#411]
Hello,

I produce message with this library, and i have some negative offset in the delivery_report event :  

[2018-04-26T16:00:59.717] [INFO] default - { topic: 'incident',
  partition: 0,
  offset: -1001,
  key: null,
  value: &lt;Buffer 00 00 00 00 a2 00 f6 de 8f ae 0b 0e 64 65 66 61 75 6c 74&gt;,
  size: 19 }

It's seem to work, but it's worry me .

**Comment by webmakersteve** [comment]
Do you have `produce.offset.report` set to true?

**Comment by Patafix** [comment]
No, i didnt know this settings, but most of the time i have the a good offset.

**Comment by webmakersteve** [comment]
I wouldn't worry about it too much, then. It's okay to get an offset like that when `librdkafka` could not ascertain the correct offset for that particular message.

**Comment by Patafix** [comment]
Thank you very much, you can close it
