### ISSUE TITLE
node-rdkafka build fails in Windows

### ISSUE THREAD

**Issue by indrajithpatelrsap** [Blizzard/node-rdkafka#413]
Hi Colleagues,

I have been trying to install node-rdkafka library from past 3 days, but the Build fails every time. I have followed the document but, even then i get an error. I get some error related to snappy.c. Below are the logs

Node version = 8.11.1
npm version = 6.0.0
nuget version = 4.6.2 (64 bit)
Installed Visual studio 2013
Open SSL = V 1.0.2 (64bit)

I have followed the installation process correctly, but still unable to build this

C:\Users\myID\git\dummy-kafka-forwarder>npm install --msvs_version=2013

> node-rdkafka@2.3.2 preinstall C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka
> node util/configure

Skipping run because we are on windows

> node-rdkafka@2.3.2 install C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka
> node-gyp rebuild

C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka>if not defined npm_config_node_gyp (node "C:\Users\myID\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\myID\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\outdir\v120\x64\Release\librdkafka.dll
C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\outdir\v120\x64\Release\librdkafkacpp.dll
C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\outdir\v120\x64\Release\zlib.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka/deps/librdkafka/win32/outdir/v120/x64/Release/librdkafkacpp.dll to C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdk
  afka/build/Release\librdkafkacpp.dll
  The system cannot find the file specified.
  nuget_restore, and also build_dependencies
  MSBuild auto-detection: using msbuild version '12.0' from 'C:\Program Files (x86)\MSBuild\12.0\bin\amd64'.
  Restoring NuGet package zlib.1.2.8.8.
  Restoring NuGet package zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8.
  Restoring NuGet package zlib.v120.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8.
  Adding package 'zlib.1.2.8.8' to folder 'C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages'
  Adding package 'zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8' to folder 'C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages'
  Adding package 'zlib.v120.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8' to folder 'C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages'
  Added package 'zlib.1.2.8.8' to folder 'C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages'
  Added package 'zlib.v120.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8' to folder 'C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages'
  Added package 'zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8' to folder 'C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages'

  NuGet Config files used:
      C:\Users\myID\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\myID\.nuget\packages\
      https://api.nuget.org/v3/index.json

  Installed:
      3 package(s) to packages.config projects
  Microsoft (R) Build Engine version 12.0.21005.1
  [Microsoft .NET Framework, version 4.0.30319.42000]
  Copyright (C) Microsoft Corporation. All rights reserved.

  Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Build started 5/7/2018 9:14:10 AM.
  Project "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.sln" on node 1 (librdkafkacpp target(s)).
  ValidateSolutionConfiguration:
    Building solution configuration "Release|x64".
  ValidateProjects:
    The project "interceptor_test" is not selected for building in solution configuration "Release|x64".
  Project "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.sln" (1) is building "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\l
  ibrdkafka\win32\librdkafkacpp\librdkafkacpp.vcxproj.metaproj" (2) on node 1 (default targets).
  Project "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafkacpp\librdkafkacpp.vcxproj.metaproj" (2) is building "C:\Users\myID\git\dummy-kafka-forwarder\no
  de_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj" (3) on node 1 (default targets).
  PrepareForBuild:
    Creating directory "interim\v120\x64\Release\".
    Creating directory "interim\v120\x64\Release\librdkafka.tlog\".
  InitializeBuildStatus:
    Creating "interim\v120\x64\Release\librdkafka.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  ClCompile:
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\CL.exe /c /I"C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\packages\zlib.v120.windesktop.msv
  cstl.dyn.rt-dyn.1.2.8.8\build\native\include" /Zi /nologo /W3 /WX- /O2 /Oi /D WIN32 /D NDEBUG /D _WINDOWS /D _USRDLL /D LIBRDKAFKA_EXPORTS /D _CRT_SECURE_NO_WARNINGS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EH
  sc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Fo"interim\v120\x64\Release\\" /Fd"interim\v120\x64\Release\vc120.pdb" /Gd /TC /errorReport:queue ..\src\crc32c.c ..\src\rdaddr.c ..\src\rdbuf.c ..\src\rdc
  rc32.c ..\src\rdgz.c ..\src\rdkafka.c ..\src\rdkafka_assignor.c ..\src\rdkafka_broker.c ..\src\rdkafka_cgrp.c ..\src\rdkafka_conf.c ..\src\rdkafka_event.c ..\src\rdkafka_lz4.c ..\src\rdkafka_msg.c ..\src\rdka
  fka_msgset_reader.c ..\src\rdkafka_msgset_writer.c ..\src\rdkafka_offset.c ..\src\rdkafka_op.c ..\src\rdkafka_partition.c ..\src\rdkafka_pattern.c ..\src\rdkafka_queue.c ..\src\rdkafka_range_assignor.c ..\src
  \rdkafka_roundrobin_assignor.c ..\src\rdkafka_request.c ..\src\rdkafka_sasl.c ..\src\rdkafka_sasl_win32.c ..\src\rdkafka_sasl_plain.c ..\src\rdkafka_sasl_scram.c ..\src\rdkafka_subscription.c ..\src\rdkafka_t
  imer.c ..\src\rdkafka_topic.c ..\src\rdkafka_transport.c ..\src\rdkafka_buf.c ..\src\rdkafka_feature.c ..\src\rdkafka_metadata.c ..\src\rdkafka_metadata_cache.c ..\src\rdkafka_interceptor.c ..\src\rdkafka_plu
  gin.c ..\src\rdkafka_header.c ..\src\rdlist.c ..\src\rdlog.c ..\src\rdmurmur2.c ..\src\rdstring.c ..\src\rdrand.c ..\src\rdregex.c ..\src\rdunittest.c ..\src\rdvarint.c ..\src\snappy.c ..\src\tinycthread.c ..
  \src\regexp.c ..\src\rdports.c ..\src\rdavl.c ..\src\xxhash.c ..\src\lz4.c ..\src\lz4frame.c ..\src\lz4hc.c ..\src\rddl.c
    crc32c.c
    rdaddr.c
    rdbuf.c
    rdcrc32.c
    rdgz.c
    rdkafka.c
    rdkafka_assignor.c
    rdkafka_broker.c
    rdkafka_cgrp.c
    rdkafka_conf.c
    rdkafka_event.c
    rdkafka_lz4.c
    rdkafka_msg.c
    rdkafka_msgset_reader.c
    rdkafka_msgset_writer.c
    rdkafka_offset.c
    rdkafka_op.c
    rdkafka_partition.c
    rdkafka_pattern.c
    rdkafka_queue.c
    Generating Code...
    Compiling...
    rdkafka_range_assignor.c
    rdkafka_roundrobin_assignor.c
    rdkafka_request.c
    rdkafka_sasl.c
    rdkafka_sasl_win32.c
    rdkafka_sasl_plain.c
    rdkafka_sasl_scram.c
    rdkafka_subscription.c
    rdkafka_timer.c
    rdkafka_topic.c
    rdkafka_transport.c
    rdkafka_buf.c
    rdkafka_feature.c
    rdkafka_metadata.c
    rdkafka_metadata_cache.c
    rdkafka_interceptor.c
    rdkafka_plugin.c
    rdkafka_header.c
    rdlist.c
    rdlog.c
    Generating Code...
    Compiling...
    rdmurmur2.c
    rdstring.c
    rdrand.c
    rdregex.c
    rdunittest.c
    rdvarint.c
    snappy.c
..\src\snappy.c(1205): error C2275: 'size_t' : illegal use of this type as an expression [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users
\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
            ..\src\snappy.c : see declaration of 'size_t'
..\src\snappy.c(1205): error C2146: syntax error : missing ';' before identifier 'n' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\I32
8838\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1205): error C2065: 'n' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1206): error C2065: 'n' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1206): warning C4133: 'function' : incompatible types - from 'int *' to 'size_t *' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj]
 [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1207): error C2065: 'n' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1209): error C2143: syntax error : missing ';' before 'const' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\gi
t\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1211): error C2065: 'c' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1212): error C2065: 'c' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1358): error C2275: 'u32' : illegal use of this type as an expression [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\I3
28838\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
            c:\users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\src\snappy_compat.h(110) : see declaration of 'u32'
..\src\snappy.c(1358): error C2146: syntax error : missing ';' before identifier 'to_add' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\User
s\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1358): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1359): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1360): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1361): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
    tinycthread.c
    regexp.c
    rdports.c
    rdavl.c
    xxhash.c
    lz4.c
    lz4frame.c
    lz4hc.c
    rddl.c
    Generating Code...
  Done Building Project "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj" (default targets) -- FAILED.
  Done Building Project "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafkacpp\librdkafkacpp.vcxproj.metaproj" (default targets) -- FAILED.
  Done Building Project "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.sln" (librdkafkacpp target(s)) -- FAILED.

  Build FAILED.

  "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.sln" (librdkafkacpp target) (1) ->
  "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafkacpp\librdkafkacpp.vcxproj.metaproj" (default target) (2) ->
  "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj" (default target) (3) ->
  (ClCompile target) ->
..\src\snappy.c(1206): warning C4133: 'function' : incompatible types - from 'int *' to 'size_t *' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj]
 [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]

  "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.sln" (librdkafkacpp target) (1) ->
  "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafkacpp\librdkafkacpp.vcxproj.metaproj" (default target) (2) ->
  "C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj" (default target) (3) ->
  (ClCompile target) ->
..\src\snappy.c(1205): error C2275: 'size_t' : illegal use of this type as an expression [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users
\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1205): error C2146: syntax error : missing ';' before identifier 'n' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\I32
8838\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1205): error C2065: 'n' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1206): error C2065: 'n' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1207): error C2065: 'n' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1209): error C2143: syntax error : missing ';' before 'const' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\gi
t\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1211): error C2065: 'c' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1212): error C2065: 'c' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-kafka-
forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1358): error C2275: 'u32' : illegal use of this type as an expression [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\I3
28838\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1358): error C2146: syntax error : missing ';' before identifier 'to_add' [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\User
s\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1358): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1359): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1360): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]
..\src\snappy.c(1361): error C2065: 'to_add' : undeclared identifier [C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka\deps\librdkafka\win32\librdkafka.vcxproj] [C:\Users\myID\git\dummy-k
afka-forwarder\node_modules\node-rdkafka\deps\librdkafka.vcxproj]

      1 Warning(s)
      14 Error(s)

  Time Elapsed 00:00:30.78
  Copying C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka/deps/librdkafka/win32/outdir/v120/x64/Release/librdkafka.dll to C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafk
  a/build/Release\librdkafka.dll
  The system cannot find the file specified.
  Copying C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka/deps/librdkafka/win32/outdir/v120/x64/Release/zlib.dll to C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka/buil
  d/Release\zlib.dll
  The system cannot find the file specified.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\myID\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myID\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\myID\git\dummy-kafka-forwarder\node_modules\node-rdkafka
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN kafka-forwarder@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myID\AppData\Roaming\npm-cache\_logs\2018-05-07T03_44_42_199Z-debug.log

@webmakersteve Any help on this?

**Comment by webmakersteve** [comment]
Can you try 2.3.3?

**Comment by a-maggioni** [comment]
I have the same issue even with 2.3.3

**Comment by a-maggioni** [comment]
@webmakersteve Any help on this?

**Comment by ManfredLange** [comment]
Getting node-rdkafka to install on Windows is - generally speaking - a bit tricky. You may find the discussion for [Issue #487](https://github.com/Blizzard/node-rdkafka/issues/487) valuable.

For us, we've been able to make version 2.3.4 to install. It still required some ancient version of Visual Studio C++ compilers and particular settings in the environment (paths, env variables, etc.) to make it work.
