### ISSUE TITLE
Feature Request - Support for Message Headers

### ISSUE THREAD

**Issue by olib963** [Blizzard/node-rdkafka#414]
The underlying library has support for kafka message headers: https://github.com/edenhill/librdkafka/pull/1480.

It would be nice if you could expose the headers to the node library for both consumers and producers. We are looking at using them to store event metadata which we can use to debug issues in the case where our avro messages cannot be deserialised properly.

Thank you.

**Comment by webmakersteve** [comment]
It is definitely something I want to add. I can't tell when I will have time right now to dedicate to it because of how my time at the office has had to be spent, but it is on my radar.

Hopefully I will have some time soon but will also be very, very happy to take a contribution for this.

**Comment by alexander-alvarez** [comment]
@webmakersteve what's necessary to make this happen? I could try to take a look at it, but the codebase is pretty foreign to me

**Comment by Fr8Traindb** [comment]
Please!  This would be a great feature!

**Comment by davidtrihy** [comment]
I have this PR open https://github.com/Blizzard/node-rdkafka/pull/478 needs a few changes once the librdkafka changes are merged but it should follow it mostly.

**Comment by davidtrihy** [comment]
Updates to the PR have been made with the new merged changes

**Comment by cfinkenstadt** [comment]
👍

**Comment by iradul** [comment]
This is resolved with 6065784faea0585d00c5196adb2f20cfd220f517

**Comment by raman20** [comment]
Still not getting headers in message.
