### ISSUE TITLE
How to avoid/handle WriteStream queue full error ?

### ISSUE THREAD

**Issue by senthil5053** [Blizzard/node-rdkafka#418]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Mac 
 - Node Version [e.g. 8.2.1]: 8.9.4
 - NPM Version [e.g. 5.4.2]: 5.6.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.0.0

**Steps to Reproduce**
Intermittently getting into the else block "'Too many messages...." when Kafka broker goes down and gets connected back.
```
// Writes a message to the stream
var queuedSuccess = stream.write(new Buffer('Awesome message'));

if (queuedSuccess) {
  console.log('We queued our message!');
} else {
  // Note that this only tells us if the stream's queue is full,
  // it does NOT tell us if the message got to Kafka!  See below...
  console.log('Too many messages in our queue already');
}
```

**node-rdkafka Configuration Settings** 

```
producer: {
        'metadata.broker.list': <host>,
        'enable.auto.commit': true,
        'retry.backoff.ms': 50,
        'message.send.max.retries': 100,
        'socket.keepalive.enable': true,
        'queue.buffering.max.messages': 100000,
        'queue.buffering.max.ms': 5,
        'batch.num.messages': 1000000,
        'topic.metadata.refresh.interval.ms': 10000,
        'auto.commit.interval.ms':5000,
        'heartbeat.interval.ms': 10000
    },
    consumer: {
        'metadata.broker.list': <host>,
        'enable.auto.commit': true,
        'fetch.wait.max.ms': 5,
        'fetch.error.backoff.ms': 10,
        'socket.keepalive.enable': true,
        'auto.commit.interval.ms':5000,
        'heartbeat.interval.ms': 10000
    }
```

**Additional context** 
So, the producer is not able to post any messages even after Kafka broker connection success. And this happens intermittently. 
Could you please help me how we can best avoid/handle this error (too many message in write stream queue) ?

**Comment by senthil5053** [comment]
@webmakersteve  Could you please help me here ? Eventually, the internal producer gets stuck after 'too many messages in queue' and not sending any message to Kafka even after the broker is connected.

**Comment by webmakersteve** [comment]
Are you using the producer stream? Or your own custom stream?

**Comment by senthil5053** [comment]
I'm using producer stream like:
```  
var writeStream = Kafka.Producer.createWriteStream(<kafka_settings.producer>, {}, {
        topic: <topic>
    });
```

**Comment by webmakersteve** [comment]
Can you upgrade to 2.3.3? I believe a fix has been put in a few versions ago that will fix this issue.

**Comment by senthil5053** [comment]
Okay, let me try that. I believe configurations for producer and consumer are good. Just curious, is this a known issue in v2.0.0 ? 

Thanks @webmakersteve

**Comment by webmakersteve** [comment]
It was a known issue that if you consumed faster than the rate of autopolling it would cause a thrown exception. You could circumvent it a little bit by tuning your autopoll interval, but the new commit should pressure the stream appropriately

**Comment by senthil5053** [comment]
@webmakersteve Yes, it did work fine with v2.3.3. However with v2.0.0, Could you please explain on what needs to be done to tune autopoll interval considering I use stream api ?

**Comment by webmakersteve** [comment]
```js
var writeStream = Kafka.Producer.createWriteStream(<kafka_settings.producer>, {}, {
        topic: <topic>,
        pollInterval: 10, // number of ms between polls
    });
```

**Comment by senthil5053** [comment]
@webmakersteve  Yeah, I did try this with v2.0.0 and still seeing the same issue 'Too many messages in our queue already' and it's not posting to Kafka topic. Also tried adding 'pollInterval' to my consumer stream, but no luck. Am I missing anything else ?

**Comment by webmakersteve** [comment]
Poll interval is for the producer stream. Is that what you meant?

It still may be too quick. It's just a bug with the old behavior, which is why it was fixed in a newer release :) 

You can manually call `writeStream.producer.poll()` after you `write()` to it every time and that should fix it as well.

**Comment by senthil5053** [comment]
@webmakersteve  Sorry to bug you again. I already tried `writeStream.producer.poll()` after write as like below:

```
writeStream.write(data);
writeStream.producer.poll();
```
Seeing the below error:
```
Mon, 21 May 2018 22:12:54 GMT uncaughtException: Local: Queue full Error: Local: Queue full
    at Function.createLibrdkafkaError [as create] (/Users/vananse/Senthil/Verizon/Sensity/GitHub/v3.0.4_release/Farallones/api_service/ui_api/node_modules/node-rdkafka/lib/error.js:260:10)
    at Producer.Client._errorWrap (/Users/vananse/Senthil/Verizon/Sensity/GitHub/v3.0.4_release/Farallones/api_service/ui_api/node_modules/node-rdkafka/lib/client.js:422:29)
    at Producer.produce (/Users/vananse/Senthil/Verizon/Sensity/GitHub/v3.0.4_release/Farallones/api_service/ui_api/node_modules/node-rdkafka/lib/producer.js:137:15)
    at writev (/Users/vananse/Senthil/Verizon/Sensity/GitHub/v3.0.4_release/Farallones/api_service/ui_api/node_modules/node-rdkafka/lib/producer-stream.js:216:14)
    at ProducerStream._writev (/Users/vananse/Senthil/Verizon/Sensity/GitHub/v3.0.4_release/Farallones/api_service/ui_api/node_modules/node-rdkafka/lib/producer-stream.js:242:3)
    at doWrite (_stream_writable.js:385:12)
    at clearBuffer (_stream_writable.js:491:5)
    at onwrite (_stream_writable.js:439:7)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
May be upgrading the version is better option here I guess.

**Comment by webmakersteve** [comment]
The only way that would still happen is if you are actually producing faster than the producer can write. Or you are not giving the libuv event thread time to execute on the node thread (by producing only synchronously).

But I definitely recommend upgrading if it works for you.

**Comment by senthil5053** [comment]
Thanks @webmakersteve . Sorry, may be a final question. Does config `dr_cb` for producer should be set to true for this to work with v2.3.3 ? Because, I did see it failing if `dr_cb` is missing in producer config.
