### ISSUE TITLE
Consumer message read time increases over the time of application running

### ISSUE THREAD

**Issue by senthil5053** [Blizzard/node-rdkafka#422]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Mac 
 - Node Version [e.g. 8.2.1]: 8.9.4
 - NPM Version [e.g. 5.4.2]: 5.6.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.0.0

**Steps to Reproduce**
I'm trying to read lots of data from Kafka topic using consumer stream. It's working fine and respond as expected for the first 30 mins of application start time, then the read time gradually increases.
Below is the code snippet of my consumer:

```
var readStream = Kafka.createReadStream(kafka_settings.consumer, {
    'auto.offset.reset': 'latest'
}, {
    topics: topics,
    waitInterval: 0    
});

readStream.on('error', function(err) {
    global.log.error('Kafka readStream stream error', err);
});

readStream.consumer.on('event.error', function(err) {
    global.log.error('Kafka readStream consumer error\',', err);
})

readStream.consumer.on('ready', function(err) {
    global.log.error('Kafka readStream consumer ready\',', err);
})

readStream.consumer.on('disconnected', function(arg) {
    global.log.info('consumer disconnected. ' + JSON.stringify(arg));
});

readStream.on('data', function(message) {
    // console.log('Got message');
    // console.log(message.value.toString());
});

```

**node-rdkafka Configuration Settings**
```
producer: {
        'metadata.broker.list': <host>,
        'enable.auto.commit': true,
        'retry.backoff.ms': 50,
        'message.send.max.retries': 100,
        'socket.keepalive.enable': true,
        'queue.buffering.max.messages': 100000,
        'queue.buffering.max.ms': 5,
        'batch.num.messages': 1000000,
        'topic.metadata.refresh.interval.ms': 10000,
        'auto.commit.interval.ms':5000,
        'heartbeat.interval.ms': 10000
    },
    consumer: {
        'metadata.broker.list': <host>,
        'enable.auto.commit': true,
        'fetch.wait.max.ms': 5,
        'fetch.error.backoff.ms': 10,
        'socket.keepalive.enable': true,
        'auto.commit.interval.ms':5000,
        'heartbeat.interval.ms': 10000
    }
```
@webmakersteve @edenhill   Could you please help me with this ?

**Comment by webmakersteve** [comment]
It looks like it is probably an application level problem. What are you doing with the data after you read it?

Also if you're concerned about backpressure (in this case, so memory can exert backpressure), you should leverage the streaming api and not use the `on('data')` callback. Let me know if that helps at all.

I would also definitely recommend upgrading your node-rdkafka version as it is very out of date.
