### ISSUE TITLE
Reconnect after losing connection to broker

### ISSUE THREAD

**Issue by srikav** [Blizzard/node-rdkafka#424]
**Environment Information**
 OS:  Docker alpine linux 
 node-rdkafka version- 2.3.2]

**Steps to Reproduce**
1) start kafka and zoo keeper
2) start producer and consumer
3)  stop kafka and zookeeper
4) producer will show broker failure errors
5) restart kafka and zoo keeper
6) the producer and consumer seems like they reconnect, but they do not consume or produce data to topics.
-- seems like it is hung in a state.

**node-rdkafka Configuration Settings**
initProducer: {
      'metadata.broker.list'  : process.env.KAFKA || 'localhost:9092',
      'group.id'              : 'podlink-reporter',
      //'dr_cb'                 : true,
      //'event_cb'              : true,
      'debug'                   : 'topic,metadata,msg,fetch,cgrp'
    },
    initConsumer: {
      'metadata.broker.list'  : process.env.KAFKA || 'localhost:9092',
      'group.id'              : 'podlink-reporter',
      'enable.auto.commit'    : true,
      'debug'                   : 'topic,metadata,msg,fetch,cgrp'
    },
[log.txt](https://github.com/Blizzard/node-rdkafka/files/2035933/log.txt)
[log.txt](https://github.com/Blizzard/node-rdkafka/files/2035938/log.txt)

**Additional context**

**Comment by jsnoble** [comment]
Any headway with this? We are facing the same issue. After complete broker disconnection it seems to hang. When the connection comes back the consumer does not get any more data

**Comment by webmakersteve** [comment]
As far as the producer is concerned, disconnects should be managed fully transparently. If you're seeing the producer stop producing after a disconnect when the brokers come back up I would recommend you add delivery reports and logging around errors and successes to ensure that data is still flowing in that capacity.

I can't tell anything significant from the logs other than there was a disconnection.

**Comment by gnitsenko93** [comment]
@webmakersteve does node-rdkafka manage re-connections internally? 

I mean the best approach (based on you advice) is:
(1) detect connection failure
(2) reconnect on a service layer (restart service/service worker/or whatever else).

But if after the step (1) we do not want to do anything will node-rdkafka make attempts to re-establish connection with brokers?

**Comment by webmakersteve** [comment]
@gnitsenko93  correct, `node-rdkafka` manages re-connections internally. The only disconnection it does not manage is the initial disconnection, which I am considering changing.

**Comment by webmakersteve** [comment]
You should use `produce` or `consume` constantly and dumbly, just assuming it will work eventually, and node-rdkafka will reconnect to brokers as they come back online.

**Comment by deyceg** [comment]
@webmakersteve on reconnect to the broker will you emit another `ready` event?

**Comment by mvtm-dn** [comment]
Same issue. Looks like after some attempt to reconnect node-rdkafka just stop infinity loop in flow mode.

**Comment by hugomd** [comment]
@mvtm-dn Did you end up finding a solution for this? I'm having the same issue

**Comment by mvtm-dn** [comment]
Yep. I stop using flow mode
