### ISSUE TITLE
Configuration fails without bash installed

### ISSUE THREAD

**Issue by SkeLLLa** [Blizzard/node-rdkafka#426]
**Environment Information**
 - OS:  docker, alpine
 - Node Version: 10.0.0
 - NPM Version: 5.6.0/6.0.0
 - C++ Toolchain: g++ (alpine with libc installed)
 - node-rdkafka version: 2.23

**Steps to Reproduce**
During npm install configuration fails because of bash.
```
env: can't execute 'bash': No such file or directory
Command failed: ./configure
```

**Comment by alexander-alvarez** [comment]
@SkeLLLa  https://github.com/Blizzard/node-rdkafka/blob/master/configure#L1 specifies a bash shell, and it seems to use [BASH_SOURCE](https://github.com/Blizzard/node-rdkafka/blob/master/configure#L9) for some of it's logic.

Are you familiar with how to replicate this in a non bash environment?

**Comment by SkeLLLa** [comment]
@alexander-alvarez I've looked through the script and I think it's possible to replace that logic with sh compatible syntax. I'll clone the repo and try to do that and if it will be ok, then I'll submit PR.

**Comment by SkeLLLa** [comment]
@alexander-alvarez The problem isn't only in that file you've mentioned. Dependency `rdkafka` also uses bash in it's config files.

So in node-rdkafka `configure` could be changed to:
```sh
#!/usr/bin/env sh

# This file is intended to be run on unix systems to configure librdkafka
# inside the submodules

# This does not get run on windows which uses the build in solutions file

# Get script directory
SCRIPT_PATH=$0;
SCRIPT_DIR=$(cd "$( dirname "${SCRIPT_PATH}" )" && pwd)
# Store current directory
CURRENT_DIR=$(pwd)
echo "$SCRIPT_PATH"
echo "$SCRIPT_DIR"

cd ./deps/librdkafka &> /dev/null

./configure --prefix="${SCRIPT_DIR}/build/deps" --libdir="${SCRIPT_DIR}/build/deps" $*

cd $CURRENT_DIR
```

However it will fail later on rdkafka configuration stage.
