### ISSUE TITLE
Remote broker is not working

### ISSUE THREAD

**Issue by shbhsngh** [Blizzard/node-rdkafka#429]
Hi,

Here is the detail of error which i am getting:
`kafkacat  -b 10.99.199.230:9092 -C -t DRIVERS`
results:
```
%4|1527337137.816|PROTOERR|rdkafka#consumer-0| :9092/0: Protocol parse failure at rd_kafka_fetch_reply_handle:3155
%4|1527337137.816|PROTOERR|rdkafka#consumer-0| :9092/0: Remaining data after message set parse: 335 bytes
```
I am using noderdkafka which uses librdkafka and trying to access remote kafka broker (which is hosted on kubentes service) from another microservice (which is also hosted on different kubernetes service and same clluster)
Here is config detail of producer client:
```
{
  'client.id': 'kafka',
  'metadata.broker.list': '10.99.199.230:9092',
  'compression.codec': 'none',
  'retry.backoff.ms': 200,
  'message.send.max.retries': 10,
  'socket.keepalive.enable': true,
  'queue.buffering.max.messages': 100000,
  'queue.buffering.max.ms': 1000,
  'batch.num.messages': 1000000,
  'dr_cb': true,
  'api.version.request':true,
  'debug':'all',
  'broker.version.fallback':'0.8.2.2'
 }
```
Could please check what is wrong here?

**Comment by webmakersteve** [comment]
If kafkacat is not working on your kafka brokers this kind of support is probably outside of the scope of node-rdkafka. I would raise the issue with the `librdkafka` base repo, but it is more than likely that it is your brokers that are the problem. 

You're using `'broker.version.fallback':'0.8.2.2'` which means it is going to try to use the 0.8 format as the fallback, which may be incompatible.
