### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by jumping** [Blizzard/node-rdkafka#432]
**Environment Information**
npm ERR! Linux 2.6.32-696.10.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.0.0/bin/node" "/root/.nvm/versions/node/v6.0.0/bin/npm" "bugs" "node-rdkafka"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
**Steps to Reproduce**

**node-rdkafka Configuration Settings**

**Additional context**
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v6.0.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v6.0.0/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'node-rdkafka' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 silly fetchPackageMetaData node-rdkafka
5 silly fetchNamedPackageData node-rdkafka
6 silly mapToRegistry name node-rdkafka
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npm.taobao.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'node-rdkafka',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   name: 'node-rdkafka',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npm.taobao.org/node-rdkafka
11 verbose request uri https://registry.npm.taobao.org/node-rdkafka
12 verbose request no auth needed
13 info attempt registry request try #1 at 13:47:45
14 verbose request id bc6d105ded21c93e
15 verbose etag "17179-LiXS2iXHiFReSa6ZOFD6/FRNhcU"
16 http request GET https://registry.npm.taobao.org/node-rdkafka
17 http 304 https://registry.npm.taobao.org/node-rdkafka
18 verbose headers { date: 'Mon, 04 Jun 2018 05:47:45 GMT',
18 verbose headers   connection: 'keep-alive',
18 verbose headers   'x-current-requests': '1',
18 verbose headers   vary: 'Origin',
18 verbose headers   etag: '"17179-LiXS2iXHiFReSa6ZOFD6/FRNhcU"',
18 verbose headers   'x-readtime': '56' }
19 silly get cb [ 304,
19 silly get   { date: 'Mon, 04 Jun 2018 05:47:45 GMT',
19 silly get     connection: 'keep-alive',
19 silly get     'x-current-requests': '1',
19 silly get     vary: 'Origin',
19 silly get     etag: '"17179-LiXS2iXHiFReSa6ZOFD6/FRNhcU"',
19 silly get     'x-readtime': '56' } ]
20 verbose etag https://registry.npm.taobao.org/node-rdkafka from cache
21 verbose get saving node-rdkafka to /root/.npm/registry.npm.taobao.org/node-rdkafka/.cache.json
22 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
23 silly bugs url https://github.com/Blizzard/node-rdkafka/issues
24 verbose stack Error: spawn xdg-open ENOENT
24 verbose stack     at exports._errnoException (util.js:896:11)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
24 verbose stack     at onErrorNT (internal/child_process.js:348:16)
24 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
24 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
25 verbose cwd /mnt/webapps/data-suite/data-assets/webapi
26 error Linux 2.6.32-696.10.1.el6.x86_64
27 error argv "/root/.nvm/versions/node/v6.0.0/bin/node" "/root/.nvm/versions/node/v6.0.0/bin/npm" "bugs" "node-rdkafka"
28 error node v6.0.0
29 error npm  v3.8.6
30 error path xdg-open
31 error code ENOENT
32 error errno ENOENT
33 error syscall spawn xdg-open
34 error enoent spawn xdg-open ENOENT
35 error enoent spawn xdg-open ENOENT
35 error enoent This is most likely not a problem with npm itself
35 error enoent and is related to npm not being able to find a file.
36 verbose exit [ 1, true ]

**Comment by webmakersteve** [comment]
Unfortunately this doesn't tell me anything. It's getting an ENOENT but it doesn't tell me what file or anything. Can you give more debug information?

**Comment by ankon** [comment]
You're running npm as root, which is definitely not a good idea. I'm not sure whether this could also affect npm's/node's ability to spawn `xdg-open`.
