### ISSUE TITLE
First messages in a topic missing when setting auto.offset.reset to 'latest'

### ISSUE THREAD

**Issue by abyx** [Blizzard/node-rdkafka#435]
**Environment Information**
 - OS: macOS 10.13.5
 - Node Version: 9.2.0
 - NPM Version: 6.1.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: Not sure how to check this :)
 - node-rdkafka version: 2.3.3

**Steps to Reproduce**
 - Setup a consumer stream to subscribe to a few topics using a pattern, e.g. `/^foobar.*/`, with `auto.offset.reset` set to `'latest'`
 - Start the consumer
 - Write a few messages to a new topic
 - The first message doesn't get to the consumer, sometimes even more (i.e. the first message received from a topic would be with offset 2)

**node-rdkafka Configuration Settings**
See [this gist](https://gist.github.com/abyx/d8213c23626f79019184acac6ed39bc2) for a full example of the code done.

**Additional context**
I started the gist, e.g. `node foobar.js`, then used `kafkacat` to write a few messages to a new topic. At some point the new topic's messages would start getting to the consumer, but not the first.

This doesn't seem to reproduce when setting the `auto.offset.reset` to `'beginning'`.

**Comment by webmakersteve** [comment]
This is the intent of that config parameter. If you want to read from the beginning of a topic you need to set the offset reset to earliest or beginning. The default behavior is to start consuming data that is sent after consumer group stablization. The stabilization of the group may be taking longer than it takes for your producer to start consuming. 

If you are doing this for testing purposes you should ensure that the rebalance has finished and you are getting PARTITION_EOF codes before you start producing.

**Comment by jesse-localz** [comment]
@webmakersteve would you be able to point one in the direction of where they could find how to receive `PARTITION_EOF` codes?

**Comment by abyx** [comment]
I understand that this is the expected behavior then, thanks!
