### ISSUE TITLE
Topic Admin API

### ISSUE THREAD

**Issue by subk** [Blizzard/node-rdkafka#436]
Topic Admin API has been merged into master See PR [#1766](https://github.com/edenhill/librdkafka/pull/1766)
Is there any plan to support it in node-rdkafka ?

**Comment by webmakersteve** [comment]
0.11.5 has not been officially released. When a new version of librdkafka is cut, work can begin on integrating it.

**Comment by javierholguera** [comment]
how long does it usually take from when a new release of librdkafka is out to when it is _wrapped_ in the node-rdkafka library?

**Comment by webmakersteve** [comment]
It depends a lot on how many breaking changes there are (if any), and the specific feature implementations.

**Comment by godber** [comment]
This appears to be in the master branch of node-rdkafka now: https://github.com/Blizzard/node-rdkafka/pull/504

**Comment by subk** [comment]
Great job !

**Comment by webmakersteve** [comment]
Released with 2.5.0
