### ISSUE TITLE
Segmentation fault on calling "committed"

### ISSUE THREAD

**Issue by abyx** [Blizzard/node-rdkafka#439]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Both Ubuntu and macOS
 - Node Version [e.g. 8.2.1]: 8.9.0
 - NPM Version [e.g. 5.4.2]: 5.5.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++/llvm
 - node-rdkafka version [e.g. 2.3.3]: 2.3.3

**Steps to Reproduce**
Running this code:

```javascript
const Kafka = require('node-rdkafka');

const consumer = new Kafka.KafkaConsumer({'metadata.broker.list': ['localhost:9092'], 'group.id': 'my_group', 'offset.store.method': 'broker'}, {});

consumer.on('ready', () => {
        consumer.getMetadata({}, (e, meta) => {
                consumer.committed(meta.topics.splice(0, 50), 10000, (e, tps) => { console.log('tps', tps, e) })
        });
});

consumer.connect();
```

**node-rdkafka Configuration Settings**
See above

**Additional context**
Running this causes a seg fault on both macOS and Ubuntu. What is the correct way to get all the current committed offsets for a group as well as the latest offsets for all topics (preferably using a regex, but getting them all will also be good)?

**Comment by batjko** [comment]
I'm getting the same thing when trying to use createReadStream, e.g.

```js
const stream = KafkaConsumer.createReadStream({
      'metadata.broker.list': config.kafkaHost,
      'group.id': config.groupId,
    }, {
        // 'enable.auto.commit': false,
        'auto.offset.reset': 'earliest',
      }, {
        topics: config.topics,
      })
```
```shell
[1]    4904 segmentation fault (core dumped)  node myConsumerStream
```

Ubuntu 18.04
Node 8.11.1
node-rdkafka 2.3.4
