### ISSUE TITLE
stream.write(...) does not execute within a while/unbound-for loop.

### ISSUE THREAD

**Issue by iiian** [Blizzard/node-rdkafka#444]
**Environment Information**
 - OS: macOS Sierra
 - Node Version: 8.9.4
 - NPM Version: 5.6.0
 - C++ Toolchain: g++
 - node-rdkafka version: 2.3.4

**Steps to Reproduce**
1. Spin up a kafka server
2. make a topic called 'someTopicName'
3. Simply build and run with node the following script
```
var Kafka = require('node-rdkafka')

var producer = new Kafka.Producer({
  'metadata.broker.list': 'localhost:9092'
})

var stream = Kafka.Producer.createWriteStream({
  'metadata.broker.list': 'localhost:9092'
}, {}, {
  topic: 'someTopicName'
});
var i = 0;
while(true)
{
  stream.write(new Buffer(`${i}`));
  i++;
}

```
3. Try changing the while(true) to other things. if it is a while, it will not run. If it is a for loop with unbounded iteration limits, it will not run. This may be by design.

**node-rdkafka Configuration Settings**
default

**Comment by webmakersteve** [comment]
If you run that in an infinite loop it will eventually just oom out. You need to allow the stream to drain by checking the return value of the write call. 

It will never write to Kafka because you are never yielding event loop time to the other threads.
