### ISSUE TITLE
Feature request: emit "error" event on connection failure

### ISSUE THREAD

**Issue by xplorld** [Blizzard/node-rdkafka#447]
Currently, `Producer.connect` uses callback to notify users about connection failure, and emits events to notify users about other things, e.g. `ready`. This is a inconsistency and user have to provide both callback and event listeners to handle them.

Please define a new event, e.g. `error.connection` to give chance of unified event handling.

**Comment by webmakersteve** [comment]
Sure. I am going to do a pass at all of the events anyway. It will likely be breaking, because I want to begin to follow the correct paradigm (I think) of using `camelCase` for node emitted events.
