### ISSUE TITLE
Consumer.consume reading messages out of order

### ISSUE THREAD

**Issue by yuxuansean1** [Blizzard/node-rdkafka#452]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Windows 10
 - Node Version [e.g. 8.2.1]: 8.11.3
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: Visual Studio
 - node-rdkafka version [e.g. 2.3.3]: 2.3.1

**Steps to Reproduce**
Using Consumer non-flowing mode:
~~~~
onReady()
{
    setInterval(() =>
    {
        this.client.consume(2000, (err, data) =>
        {
            if (data.length)
            {
                data.forEach((msg) =>
                    console.log(`${msg.offset} ${msg.topic}`)
                );
            }
        });
    }, 2000);
}
~~~~
We have a python script producing messages to our kafka while we're consuming.
It works fine when theres a backlog of messages to consume but when the consumer catches up to the producer the messages are out of order.
~~~~
577863 TOPIC-1
577870 TOPIC-1
577832 TOPIC-2
577877 TOPIC-1
577839 TOPIC-2
577879 TOPIC-1
577884 TOPIC-1
577846 TOPIC-2
577891 TOPIC-1
577853 TOPIC-2
577898 TOPIC-1
~~~~
We only have 1 partition.
How do we fix this?

**node-rdkafka Configuration Settings**
            'group.id': 'consumerGroup1',
            'metadata.broker.list': address,
            'enable.auto.commit': false,
            'auto.commit.interval.ms': 0,
            'enable.auto.offset.store': false,
            'topic.metadata.refresh.interval.ms': 20000,
            'event_cb': true

**Comment by webmakersteve** [comment]
Order is only guaranteed per partition (which implies, additionally, per topic). Are you seeing inconsistent behavior with that tenant of Kafka? It looks like the numbers only go up per topic.

**Comment by yuxuansean1** [comment]
Sorry what I meant is that it is skipping messages. Is this the intended behavior?
From the above example,
~~~~
577863 TOPIC-1
577870 TOPIC-1
577832 TOPIC-2
577877 TOPIC-1
577839 TOPIC-2
577879 TOPIC-1
577884 TOPIC-1
577846 TOPIC-2
577891 TOPIC-1
577853 TOPIC-2
577898 TOPIC-1
~~~~
The next call to consume could return some of the offsets that were skipped like `577865 TOPIC-1`. That's what I meant when I said out of order, since later offsets have already been consumed but not committed.
Is there a way to consume non-flowing mode and guarantee at least once?

**Comment by webmakersteve** [comment]
I'm not sure why you're having the problem of skipped offsets... it could be something done on the node side, as I think the C++ API guarantees order. I'll need to spend some time investigating to see exactly why.

**Comment by tsillan-p** [comment]
I'm experiencing the same same, i.e. messages are received out of order, and some are skipped. When reading again, some of the skipped messages may be returned. I'm reading from a single topic. 

OS [e.g. Mac, Arch, Windows 10]: Amazon Linux AMI release 2018.03
Node Version [e.g. 8.2.1]: 8.15.1
NPM Version [e.g. 5.4.2]: N/A (yarn)
C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
node-rdkafka version [e.g. 2.3.3]: 2.5.1

**Comment by paguayo-iexcloud** [comment]
Experiencing the same issues, @SeanYHe did you figure out the root cause?

**Comment by SeanYHe** [comment]
@paguayo-iexcloud, I left the project before we found a root cause. I think as a workaround we changed the consume to be in an infinite loop instead of `setInterval`, but I don't have access to the code anymore. Sorry I can't be of more help.
