### ISSUE TITLE
Question: best way to pass a callback to Producer.produce()

### ISSUE THREAD

**Issue by ismriv** [Blizzard/node-rdkafka#455]
If I want to invoke a callback function upon delivery of the message to Kafka, what's the best/recommended way to handle this since `Producer.produce()` doesn't accept a callback or return a Promise, and reports deliveries via events?

I have implemented this by passing a function as the `opaque` value, and then calling `opaque` on the `delivery-report` handler. Is this a typical pattern, or is the fire & forget pattern what others do?

Below is the snippet of code that shows what I've come up with:

    producer.on('delivery-report', (err, report) => {
      if (typeof report.opaque === 'function') {
        report.opaque.call(null, err, report);
      }
    });

    producer.on('ready', () => {
      publishMessage('Awesome key', new Buffer('Awesome message'), (err) => {
        if (err) {
          console.log('Message failed', {err});
          return;
        }
        console.log('Message published successfully!');
      });
    });

    function publishMessage(messageKey, messageValue, callback) {
      try {
        const topicName = 'Test';
        const partition = -1;
        const timestamp = Date.now();

        producer.produce(topicName, partition, messageValue, messageKey, timestamp, callback);
      } catch (err) {
        callback(err);
      }
    }

Thanks!

**Comment by ismriv** [comment]
@webmakersteve if you put together a spec of how you would want it, I can give it a go...

**Comment by umarrasydan** [comment]
If someone is looking for a promise version of this
```javascript
const Kafka = require('node-rdkafka');

const producer = new Kafka.Producer({
    'metadata.broker.list': 'host:9092',
    dr_cb: true
});

producer.connect();

producer.setPollInterval(10);

producer.on('delivery-report', (err, report) => {
    if (typeof report.opaque === 'function') {
        report.opaque.call(null, err, report);
    }
});

producer.on('ready', async () => {
    console.log('ready');
    try {
        const report = await produceMessage({
            foo: 'bar'
        });
        console.log('report', report);
        console.log('message published');
    } catch (e) {
        console.log(e);
    }
});

function produceMessage(messageValue) {
    return new Promise((resolve, reject) => {
        try {
            producer.produce(
                'some-topic',
                null,
                new Buffer(JSON.stringify(messageValue)),
                null,
                Date.now(),
                (err, report) => {
                    if (err) return reject(err);
                    return resolve(report);
                }
            );
        } catch (e) {
            return reject(e);
        }
    });
}

```

**Comment by webmakersteve** [comment]
#516 seems to be mentioning a similar problem.

#536 has a potential fix
