### ISSUE TITLE
Order not being respected

### ISSUE THREAD

**Issue by thebigredgeek** [Blizzard/node-rdkafka#456]
For some reason, I am getting firehosed with events when dealing with only 2 message keys... even though I am not using auto commit.  Any help here would be awesome

```
const Kafka = require("node-rdkafka")
const { v4 } = require("uuid")

let outstanding = 0

const wait = time => new Promise(resolve => setTimeout(resolve, time))

const consumer = new Kafka.KafkaConsumer({
  "group.id": "workbench",
  "metadata.broker.list": "localhost:9092",
  "enable.auto.commit": false,
  "auto.commit.enable": false,
})

var producer = new Kafka.Producer({
  "metadata.broker.list": "localhost:9092",
})

producer.connect()
consumer.connect()

producer
  .on("ready", () => {
    // console.log("PRODUCER READY!")

    // producer.produce("workbench-bar", null, new Buffer("bar!"), v4())

    setInterval(() => {
      if (outstanding > 0) {
        return
      }
      try {
        for (var i = 0; i < 10; i++) {
          console.log("producing event foo!")
          producer.produce("workbench-foo", null, new Buffer(v4()), "foo")
          outstanding++
        }
        for (var i = 0; i < 10; i++) {
          console.log("producing event bar!")
          producer.produce("workbench-bar", null, new Buffer(v4()), "bar")
          outstanding++
        }
      } catch (err) {
        console.error("error producing message")
        console.trace(err)
      }
    }, 10)
  })
  .on("event.error", e => console.trace(e))

consumer
  .on("ready", () => {
    // consumer.unsubscribe(["workbench-foo"])
    consumer.subscribe(["workbench-bar", "workbench-foo"])

    console.log("CONSUMER CONSUMING")
    consumer.consume()
  })
  .on("data", async message => {
    // consumer.seek(0)
    console.log("MESSAGE!")
    console.log(
      `${message.topic}:${message.partition}`,
      message.key.toString("utf8"),
      message.value.toString("utf8"),
      outstanding - 1
    )
    outstanding--
    await wait(1000) // THIS ISN'T WAITING!  I AM RECEIVING EVERY SINGLE MESSAGE WITH KEY
                              // "bar" ALL AT ONCE! HOW DO I GUARANTEE PROCESSING ORDER?
    consumer.commitMessage(message)
  })
  .on("event", e => console.log(e))
```

**Comment by thebigredgeek** [comment]
https://github.com/edenhill/librdkafka/issues/1902

**Comment by ricardohbin** [comment]
Hmmm.. same here. 

Appears that when the consumer process a "real time" event, the message is auto commited. 

This don't happen to messages that is already in topic.

**Comment by Patafix** [comment]
Same probleme here

**Comment by webmakersteve** [comment]
Data callbacks aren't going to wait, they get emitted as fast as they can on available threads. If you want the behavior you are looking for you need to do the consume calls manually or use the stream.

**Comment by thebigredgeek** [comment]
@webmakersteve I'm confused, I thought the point of disabling auto-commit was that you can control when messages are committed?  Is that not the case?

**Comment by thebigredgeek** [comment]
Let me be more clear:  If I have 300 messages with key "foo" on a single topic, I want to fully process each "foo" message... which means I want to open a transaction, do some work, and then commit the transaction along with the offset before committing back to Kafka.  Because it seems like the auto-commit is failing to work, it seems like I am instead receiving all 300 messages at once (or up to a maximum) because this lib is automatically committing each message as it receives them rather than allowing me to manually commit.  AFAIK, Kafka ensures delivery order for a given topic and message key...

**Comment by thebigredgeek** [comment]
*UPDATE* https://anirudhbhatnagar.com/2016/08/22/achieving-order-guarnetee-in-kafka-with-partitioning/ < this is what i am trying to accomplish.  Forgive me, I am a bit of a Kafka noob and I was conflating "commit offset" with "receive next message with a given message id on a given topic"

Here is my scenario:

I publish 5 different messages to my `User` topic, all with the message key `1234` which is the ID of a user.  All 4 messages update the user and there is overlap between them, meaning that they cannot be treated as idempotent.  What I need to be able to do is process, fully, these messages one at a time and commit the offset every time I finish into Postgres along with Kafka to ensure exactly-once processing.  However, in the above code (which sets up basically the same scenario) I receive all 4 messages at the same time because my callback is invoked over and over with no way to apply backpressure while doing async work.  I don't want to apply global backpressure for the consumer, I just want to apply backpressure for the topic.id + message key permutation.  My consumer should still be able to process other `User`'s events while guaranteeing ordering for the user mentioned before.  How can I make this work?

**Comment by NealHumphrey** [comment]
@thebigredgeek I'm trying to solve a related problem and found this thread in googling. I'm new to `node-rdkafka` but from @webmakersteve's answer it seems like you have to do this manually. 

[This answer](https://github.com/confluentinc/confluent-kafka-python/issues/300#issuecomment-358416432) in the Python library (which uses the same librdkafka underneath) I think describes some of the steps you need to do regarding committing the offsets. But, that still won't stop you from receiving messages. 

Options:
1) `.on("data", async message => {`: in this function, load your message into a queue. Remove the `async` and do the queue loading synchronously. Make a different queue for each partition  / message key. This will put all your messages in order and you can handle then appropriately. Then, store the offsets or use `commitSync()` as each message is actually processed. This will put more messages into memory while they're in-flight in your application - depending on use case that's probably OK but depends on the frequency of concurrent messages and the lag of executing your transation. 

2) Use the [non-flowing mode](https://github.com/Blizzard/node-rdkafka#standard-api-1) to get the messages only when you're ready for them, i.e. done with the previous message.

**Comment by Tapppi** [comment]
You are confusing Kafkas guarantees for partitions to how the library actually works. With the basic consumer you can use non-flowing mode to get all messages as fast as possible, with the non flowing mode you can consume messages in batches and guarantee whatever you want yourself. They are not high-level intefaces.

The stream interface will naturally give you one message at a time and guarantee that your message is processed before the next one. If you use asynchronous stuff, use some promise-supporting library to set up your streams. There is no simple "function callback with settings for how to process messages with guarantees" high-level interface at the moment. I am creating one at our company, but it is not ready for OSS yet, as it just got rewritten on top of the streaming interface and still uses some internal libraries..

Note: remember to still commit your messages after processing if you care about asynchronous code being executed at-least-once.

**Comment by Tapppi** [comment]
@thebigredgeek  To answer your specific use case because I feel like it 😊 

> All 4 messages update the user and there is overlap between them, meaning that they cannot be treated as idempotent. What I need to be able to do is process, fully, these messages one at a time and commit the offset every time I finish into Postgres along with Kafka to ensure exactly-once processing.

One would hope your actual update IS idempotent as long as the updates are processed in order. Why wouldn't they be, do they increment something? However, you can skip duplicates by saving offsets to the target if you really need it.

> However, in the above code (which sets up basically the same scenario) I receive all 4 messages at the same time because my callback is invoked over and over with no way to apply backpressure while doing async work.

Backpressure is not trivial in node without using the node's streams. You'll probably want a library, as you have started making, to do that if you want to use the flowing or non-flowing basic client

> I don't want to apply global backpressure for the consumer, I just want to apply backpressure for the topic.id + message key permutation. My consumer should still be able to process other User's events while guaranteeing ordering for the user mentioned before.

With the streaming interface, you could use a concurrent stream's library (such as https://github.com/almost/through2-concurrent) to more granularly apply backpressure, blocking messages until concurrent ones with the same `topic+partition` or even just the same `key` have finished executing. A `concurrencyKey` option to our internal library is an implementation of this idea. We've found that although it's not trivial, it's not particularly hard either.

**Comment by SoyYoRafa** [comment]
Hi, my team found the same issue with node-rdkafka. One of the biggest things that kafka guarantees is order in a partition. If we use promises, then the order of operations can and will breaks down. At the very least, this *needs* to be documented. It shouldn't require reading the node-rdkafka code to realize that it doesn't handle promises. Using non-flowing with consume(1) seems to fix this. I still saw reordering in KafkaConsumerStream.

**Comment by Wouter86** [comment]
You can easily fix this by integrating [async-function-queue](https://www.npmjs.com/package/async-function-queue), creating a queue per topic partition and enqueue your event handling jobs (async functions) on the correct queue from the node-rdkafka Consumer#on(data) event handler.

Happy consuming!
