### ISSUE TITLE
Consumer 'stream API' and sharing consumers

### ISSUE THREAD

**Issue by ankon** [Blizzard/node-rdkafka#459]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]:  Linux x86-64
 - Node Version [e.g. 8.2.1]: 8.11.3
 - NPM Version [e.g. 5.4.2]: 5.6.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: 2.3.4

**Steps to Reproduce**

1. Follow the documentation, and decide to use the consumer 'stream API' in a project that consumes many topics from the same brokers.
2. Observe that one needs to bump `UV_THREADPOOL_SIZE` so that node-rdkafka can handle consuming all these topics (see #363, maybe also #332)

What eventually "dawned" on me was that I should look a bit further into what node-rdkafka/rdkafka/kafka are actually doing, and found that the way we use streams is problematic: Each of the streams requires a new Consumer instance, which will create its own needed threads etc. I've now changed the implementation to use the 'standard API', with some custom batching/multiplexing logic between a single node-rdkafka Consumer and our own per-topic abstractions.

I think it would be nice to mention in the documentation for the stream API explicitly that this will have considerable overhead when consuming more than a few topics, rather than just saying that the standard API is better "for performance": We're actually not having that many messages per second to process, so initially I didn't connect the dots here.

--
EDIT: Fixed on mistaken 'producer' that should be 'Consumer'

**Comment by webmakersteve** [comment]
Maybe the docs can be adjusted, but the streams are supposed to be alternatives to using the consumer or producer. Just as I would not recommend having too many consumers or producers, I would not recommend having too many streams. 

What is your use case that requires so many separate streams? Maybe that will help me understand why the use case is problematic because of the overhead involved. 

I tried to mirror the behavior of, for example, a read stream from a file. 1 file handle = 1 stream. If you open a tons of those, there will be lots of open file handles and you need to deal with the overhead as needed.

**Comment by ankon** [comment]
Essentially we have a multi-tenant application, and decided[*] to have one topic for events, commands, errors, and "query responses" for each tenant. Opening a stream for each quickly got us into resource consumption issues, which we initially counter-acted by bumping `UV_THREADPOOL_SIZE`. But, ultimately that just doesn't scale. 

Each of these topics is configured identically in a particular service, so we can share consumers for all events for example, and just dispatch the events to the correct per-tenant handler on the application side. Sharing consumers changes the way the application scales from "one tenant extra costs us a lot" to "one tenant extra is essentially a free change in the subscriptions of the existing consumers".

I understand that the streams approach can and should be simple to use, and it was fine for us -- but I find it problematic (and "surprising") that a stream requires so many "internal" resources to maintain it. Being able to share our consumers though works for my case, so I am really more thinking on how to make people see that sharing aspect, and not rely on streams for too long :)

**Comment by Tapppi** [comment]
Well, both the standard `consume` and stream will have this same problem when consuming with many consumers instead of one consumer on multiple topics and not modifying timeout with [`consumer.setDefaultConsumeTimeout`](). The stream uses `consume(size, cb)` in the background, and each stream currently waiting for messages consumes a libuv thread.

You could do the same multiplexing logic on streams as you used with the usual consumer api. Having bigger `UV_THREADPOOL_SIZE` than number of consumers is kind of mandatory regardless of which API you use, unless you are sleeping between `consume`s, in which case you could sleep longer in nodeland and wait less in c++ land with lower consume timeout. Streams sleep 0-1000ms between fetches by default, you can modify it with the `waitInterval: 1000` option, or set it to `waitInterval: 0` for no sleeping and faster delivery.

**Comment by ankon** [comment]
> [...] and each stream currently waiting for messages consumes a libuv thread.

For my understanding: Is (node-)rdkafka doing mostly busy waits so that it must consume these threads exclusively, or is it actually able to share the time on the worker threads?

> You could do the same multiplexing logic on streams as you used with the usual consumer api. 

It seems possible to provide an array of topics when constructing a stream, so that should work indeed. One thing I did fail to mention above is that the specific set of tenants is of course not fixed at app startup, so we do change the subscriptions over time. I believe with the stream I would have to close the stream, and create a new one, which might be ever so slightly more expensive than what I do now (unsubscribe, wait for unsubscribed event, then re-subscribe).

> Having bigger `UV_THREADPOOL_SIZE` than number of consumers is kind of mandatory regardless of which API you use [...]

Right. With the setup described I now end up with ~4-5 consumers per app (depending a bit how they configure their topics, our code to decide whether to re-use or create a consumer simply hashes the global and topic configuration), so we're just in the "sweet spot" where bumping the limit isn't that much needed. But I'll keep this in mind for sure, and will make sure to have our systems have a reasonable "Safety margin" for that.

The point I was trying to make stands though: The resource usage in a simple 1:1 model (consumer/stream vs topic) is not suitable for more than a few topics one wants to consume in a single app, and I think it would make sense to spell that out somewhere explicitly :)

**Comment by Tapppi** [comment]
> Essentially we have a multi-tenant application, and decided[*] to have one topic for events, commands, errors, and "query responses" for each tenant. Opening a stream for each quickly got us into resource consumption issues, which we initially counter-acted by bumping UV_THREADPOOL_SIZE. But, ultimately that just doesn't scale.

Creating a topic per tenant or customer is generally discouraged with Kafka because it leads you to have an ever increasing number of topics on the broker, which will consume lots of resources regardless of the traffic in those topics. You probably want to build multi-tenancy into your application logic, by multiplexing the messages from fewer topic(s) (per message type, domain, priority or whatever else you want to split by) instead of multiplexing from X tenant topics with varying messages. This way you will keep your resource usage reasonable on consumers and most importantly on brokers. You can then scale with partition count.

**Comment by Tapppi** [comment]
@ankon to get a bit more into your points
> For my understanding: Is (node-)rdkafka doing mostly busy waits so that it must consume these threads exclusively, or is it actually able to share the time on the worker threads?

IIRC, each consumer currently waiting for messages will fully consume/block the uv thread it's work is scheduled on, so if `UV_THREADPOOL_SIZE=4` and 5 consumers try to wait for messages, one of them will be blocked until a thread frees up. I'm a complete neeb in `libuv` and how the work is scheduled, but I'm guessing this is the intended way for it to work and/or this is a matter of isolation. See https://github.com/Blizzard/node-rdkafka/issues/363#issuecomment-376595266 for webmakersteve's explanation. I will test out how numbered consumes work in a minute out of curiosity.

> The point I was trying to make stands though: The resource usage in a simple 1:1 model (consumer/stream vs topic) is not suitable for more than a few topics one wants to consume in a single app, and I think it would make sense to spell that out somewhere explicitly :)

I completely agree that in case of many slow-throughput topics the model here does not work very well, and could probably be improved somehow. One thing to document IMO is that setting consumption timeout to something like `1-10ms` and `UV_THREADPOOL_SIZE` should improve latency but might increase idle cpu usage? Worth some testing.

---

> One thing I did fail to mention above is that the specific set of tenants is of course not fixed at app startup, so we do change the subscriptions over time. I believe with the stream I would have to close the stream, and create a new one, which might be ever so slightly more expensive than what I do now (unsubscribe, wait for unsubscribed event, then re-subscribe).

A basic principle of topic design for Kafka is keeping your topic partition count to a reasonable level where you can handle traffic spikes but not flood the brokers with low-traffic toppars. IMHO resubscribing consumers based on tenancy changes is also (possibly critical) unwanted lag if your application is concerned about message lag. [See this article for more info about topic partition design and count](https://www.confluent.io/blog/how-to-choose-the-number-of-topicspartitions-in-a-kafka-cluster/). It's a bit old but holds it's own still. The most interesting part is:
>> As a rule of thumb, if you care about latency, it’s probably a good idea to limit the number of partitions per broker to 100 x b x r, where b is the number of brokers in a Kafka cluster and r is the replication factor. 

Say you had 300 low-latency tenants with a single partition and a replication factor of 2, you would want `b = TopParNum / 100 / r = 600 / 100 / 2 = 3` brokers for just a single topic partition per user. This is of course assuming you need low-latency. If you can handle some tens of milliseconds of end-to-end latency, you can safely increase that to `TopParNum = 1000 x b x r`, which will give you some playing room with topic per tenant configurations.

I guess my point is to think hard about whether you actually need the topic per tenancy design and are equipped to support it with your count of tenants. Multi-tenancy by topic separation is surely possible and even recommended by some kafka users, but I only see it as a viable option if:
* (a) your tenant count is reasonable and/or you don't care about end-to-end latency
or
* (b) you can comfortably launch a lot of kafka nodes/clusters based on tenant count and split the tenants between them. You'll want fairly consistent data usage per tenant for this to scale consistently.

I do encourage you to think about how you will scale whether you have a topic per tenant or not and when you start approaching max throughput within multi-tenant topics or topic-per-tenant clusters. Scaling multi-tenant topics beyond planned capacity will get easier if [KIP-253](https://cwiki.apache.org/confluence/display/KAFKA/KIP-253%3A+Support+in-order+message+delivery+with+partition+expansion) ever gets implemented. If your multi-tenant topics are split by e.g. priority, scaling should be fairly trivial by rotating to topics with more partitions gradually or adding priority levels.
