### ISSUE TITLE
Consumer irregularly returns no messages

### ISSUE THREAD

**Issue by robinclaes** [Blizzard/node-rdkafka#465]
**Environment Information**
 - OS: mac
 - Node Version: 8.11.1
 - NPM Version: 6.1.0
 - C++ Toolchain: ?
 - node-rdkafka version: 2.3.4

**Steps to Reproduce** 
See code snippet

**node-rdkafka Configuration Settings**
```
const consumer = new Kafka.KafkaConsumer(
      {
        'metadata.broker.list': `${process.env.KAFKA_HOST}:${
          process.env.KAFKA_PORT
        }`,
        'enable.auto.commit': false,
        rebalance_cb: true,
        event_cb: true,
        debug: 'all',
        'group.id': 'kafka',
      },
      {
        'enable.auto.commit': false,
      },
    );
    consumer.connect();
    consumer.on('ready', () => {
      consumer.queryWatermarkOffsets(
        process.env.KAFKA_TOPIC,
        0,
        0,
        (error, { highOffset }) => {
          if (error) reject(error);
          consumer.assign([
            {
              topic: process.env.KAFKA_TOPIC,
              partition: 0,
            },
          ]);
          consumer.commitSync({
            topic: process.env.KAFKA_TOPIC,
            partition: 0,
            offset: highOffset - count,
          });
          consumer.consume(count, (consumeError, messages) => {
            if (consumeError) console.log(consumeError);
            console.log(messages.length);
            resolve(messages.map(parseMessage).filter(message => message));
          });
        },
      );
    });
```

**Additional context**
Hi, first of all thanks for creating this library.
I want to read the last X messages in Kafka. I use a consumer that consumes X messages and then disconnects. Sometimes the amount of messages matches X, but sometimes it is 0. I'm listening to logging but nothing is logged when the result contains 0 messages. 

Due to this irregular behaviour it's hard to find the cause. I've tried several things without success. Could this be a bug?

**Comment by Tapppi** [comment]
If the consumer is not able to get any messages within a timeout (probably still setting up things with the broker or experiencing network lag), it will return without any messages. This is also why you might get less than `count` messages. If you want to **always** consume that many messages, keep consuming until you have received that many messages.

**Comment by webmakersteve** [comment]
@Tapppi is correct. If you use the stream implementation you do not need to worry about this as it is handled under the hood.

**Comment by Albinzr** [comment]
same issue cant manually perform this
