### ISSUE TITLE
Inconsistency between KafkaConsumer and KafkaConsumerStream regarding 'unsubscribe' event

### ISSUE THREAD

**Issue by ankon** [Blizzard/node-rdkafka#466]
KafkaConsumerStream expects an `unsubscribed` event: https://github.com/Blizzard/node-rdkafka/blob/5e971743047c373aaf046db15528ff6b818eb281/lib/kafka-consumer-stream.js#L110

But, KafkaConsumer produces an `unsubscribe` (without the 'd'): https://github.com/Blizzard/node-rdkafka/blob/5e971743047c373aaf046db15528ff6b818eb281/lib/kafka-consumer.js#L337

It seems the test cases for the stream also set up things with the `unsubscribed` name.

**Steps to Reproduce**

Read through code :)

**Comment by ankon** [comment]
There is a `subscribed` event emitted in KafkaConsumer~subscribe(), so purely based on that I think KafkaConsumer is wrong here, and it should be `unsubscribed`. Neither event is described in the README.md though, so I guess changing either is fine :)

**Comment by webmakersteve** [comment]
Fixed!
