### ISSUE TITLE
Can't use consumer assign() with streams

### ISSUE THREAD

**Issue by sfescape** [Blizzard/node-rdkafka#473]
Looks like read streams only support consumer subscribe(). I understand they are mutually exclusive, but I'm pretty new to kafka. If they are, is there a way to support assign() while still using streams?

**Comment by codeburke** [comment]
You should be able to access the raw consumer via `stream.consumer.assign()`.

Example:
```
const RdKafka = require('node-rdkafka');
const stream = RdKafka.createReadStream(...);
stream.consumer.assign(...);
```
