### ISSUE TITLE
EventCallbackRepositoryArityOne is missing event.stats

### ISSUE THREAD

**Issue by SoyYoRafa** [Blizzard/node-rdkafka#480]
Can't compile TypeScript files that want to set a event.status event handler.  event.stats is missing in EventCallbackRepositoryArityOne located in index.d.ts.

**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Linux
 - Node Version [e.g. 8.2.1]: 8.11.3
 - NPM Version [e.g. 5.4.2]: 5.6.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: 2.4.1

**Steps to Reproduce**

producer.on('event.stats', (stats) => { console.log(stats); });

**node-rdkafka Configuration Settings**

**Additional context**

**Comment by kowalej-homex** [comment]
This issue still persists in version 2.6.1. Like @SoyYoRafa said, the typings are missing in index.d.ts for stats, among other things. I believe this is now being addressed (judging by the commit history for index.d.ts).

Will the updated typings be in the next release?
