### ISSUE TITLE
Error codes are not being propagated in event.error listener

### ISSUE THREAD

**Issue by wxsdion** [Blizzard/node-rdkafka#484]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: macOS 10.13.6
 - Node Version [e.g. 8.2.1]: 9.3.0
 - NPM Version [e.g. 5.4.2]: 5.6.0
 - node-rdkafka version [e.g. 2.3.3]: 2.4.1

I'm producing messages and using the event.error listener like so:

> producer.on('event.error', function(err) {
>         if(err && err.message != BROKEN_TRANSPORT_FAILURE){
>              logger.error(`event.error : ${err.message}`);
>              //do something about it
>         }
>     });

The errors I receive in my event.error listener do not contain any info other than the error message i.e no error code from librdkafka, it's always set to -1. So to ignore errors such as "Broken transport failures" I have to use the message of the error, which is not really ideal.
All callbacks for other listeners do receive error codes since version 2.4.0, following this thread and fix:
https://github.com/Blizzard/node-rdkafka/issues/374
https://github.com/Blizzard/node-rdkafka/commit/ac96c76c0e50471e78cf512c9e4492582e780463

In the code that processes events, it seems that rather than receiving an error, an eventData is received and it doesn't contain anything other than the error message:
https://github.com/Blizzard/node-rdkafka/blob/1c0f2a07aa13e73fe58e19cf7535e5b65367d8b0/lib/client.js#L64-L82

It appears the Event class from the librdkafka lib does contain an error code field:
https://github.com/edenhill/librdkafka/blob/3d3a9e05b992f35bba756fcc32ba80cdac65ccf5/src-cpp/rdkafkacpp.h#L564-L567

I was wondering if this is the desired behavior for events in node-rdkafka or if I'm doing something wrong.
Thanks !

**Comment by webmakersteve** [comment]
Thats what I thought the desired behavior should be, but if you have use in having the code propagated we can enrich the object. It will be a breaking change, but would be glad to take a PR for that :)
