### ISSUE TITLE
Error: librdkafka.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by eliavmaman** [Blizzard/node-rdkafka#489]
**Environment Information**
 - Mac
 - Node Version 8.9.4
 - NPM Version 5.6.0
 
 - node-rdkafka version  2.4.1]:

I'm trying to deploy my app to Heroku, i get this  error.
On ,my local machine the app works fine.. 

We are about to go to production and all our system rely on rd-kafka.

**Comment by eliavmaman** [comment]
anyone?

**Comment by vbhayden** [comment]
Issue cited on another implementation, check the thread here:

https://github.com/confluentinc/confluent-kafka-python/issues/65

**Comment by eliavmaman** [comment]
@vbhayden Sorry my friend it didnt worked but thx.
this is the log i get when i try to run the app.

<img width="895" alt="screen shot 2018-09-27 at 11 09 34 am" src="https://user-images.githubusercontent.com/6911449/46132117-eaa4c900-c245-11e8-8070-159290e163fa.png">

any idea?

**Comment by billidani7** [comment]
@eliavmaman 

There is a heroku build pack that you should install first, before the nodeJs build pack.
https://github.com/SalesforceCloudServices/heroku-buildpack-librdkafka

But this build pack uses 0.11.4 version of librdkafka.

I had the same issue like you. I overcome the problem when I installed the librdkafka build pack but now I have some other connectivity issues with the producers. I think this issues coming from the fact that the build pack uses 0.11.4 version.

if you find any solution I will be glad to hear from you.
