### ISSUE TITLE
Producer exactly once (idempotent) planned?

### ISSUE THREAD

**Issue by steinkamp245** [Blizzard/node-rdkafka#490]
I was wondering if there is some kind of excactly once option for the producer planned?
Like the java-api provides it for the producers?

Thank you in advance

**Comment by codeburke** [comment]
Looks like it just got merged into the underlying librdkafka ([commit](https://github.com/edenhill/librdkafka/commit/94219ef16c51b6565860d3d0246f588b15a6ac7d)). As of this comment it isn't in any official release and after it is released there is usually a bit of lag before it gets pulled into node-rdkafka.
