### ISSUE TITLE
Can not install rdkafka on latest Node.js version

### ISSUE THREAD

**Issue by lewispham** [Blizzard/node-rdkafka#494]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Ubuntu 18.04.1 LTS
 - Node Version [e.g. 8.2.1]: 10.11.0
 - NPM Version [e.g. 5.4.2]: 6.4.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.3.3

**Steps to Reproduce**
npm insintall node-rdkafka

**Logs**
```text
node-librdkafka.target.mk:117: recipe for target 'Release/obj.target/node-librdkafka/src/binding.o' failed
make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
rm 88b77cf19174300b5620a261f4f38c8b8dc3d418.intermediate
make: Leaving directory '/home/lewis/Projects/alax-resource-service/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/lewis/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/home/lewis/.nvm/versions/node/v10.11.0/bin/node" "/home/lewis/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lewis/Projects/alax-resource-service/node_modules/node-rdkafka
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN typedoc-plugin-external-module-name@1.1.3 requires a peer of typedoc@>=0.7 <1.0 but none is installed. You must install peer dependencies yourself.
npm WARN alax-resource-gateway@1.0.50 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lewis/.npm/_logs/2018-09-28T04_54_11_379Z-debug.log

```

**Comment by v3rse** [comment]
@lewispham Any luck? I have the same issue.

**Comment by rocketraman** [comment]
Same problem here, but happens only if I blow away my `yarn.lock` file, which tells me it is related to some newer dependency recently released. It's likely only a matter of time before this starts affecting more people.

**Comment by rocketraman** [comment]
Of course, we're likely reporting to the wrong repo... we should be reporting to https://github.com/edenhill/librdkafka.

**Comment by webmakersteve** [comment]
I need a little bit more information to debug this, but I suspect it may be due to Nan. There are a lot of deprecations that need to be updated. Can you tell me what exact nan version you have? And try downgrading and see if it works?

**Comment by rocketraman** [comment]
> I need a little bit more information to debug this, but I suspect it may be due to Nan. There are a lot of deprecations that need to be updated. Can you tell me what exact nan version you have? And try downgrading and see if it works?

Everything seems to be working now, so it's likely a bug was fixed in some package somewhere. Unfortunately I didn't save the yarn.lock file from the failing installation, but I can at least provide these two working datapoints concerning nan:

1) Working installation, old: nan 2.11.1

2) Working installation, new: nan 2.12.1
