### ISSUE TITLE
Remote bootstrap broker went down for a short period of time,  client failed to reconnect.

### ISSUE THREAD

**Issue by LongNTBui** [Blizzard/node-rdkafka#497]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Amazon AMI
 - Node Version [e.g. 8.2.1]: 8.12.0
 - NPM Version [e.g. 5.4.2]: 6.4.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: 2.4.1

**Steps to Reproduce**

**node-rdkafka Configuration Settings**

api_version_request: true
request_required_acks: 1
log_connection_close: false
enable_keepalive: true

**Additional context**
We have a producer and consumer connecting to a topic with one partition on Confluent Kafka cluster. There was a short outage with the cluster caused both to disconnect from the brokers. I can see in the logs the error messages: "SSL Error" and "Leader broker is down" but the clients don't seem to be able to reconnect once the brokers were back up and only a restart of the instances would fix the issue.

Does this sound a like bug in the library or something, the client should handle?

Thanks

**Comment by LongNTBui** [comment]
I don't know how to replicate this issue. I tested against a local single Kafka broker and the client is able to reconnect when the broker came back online. This might have something to do with AWS Network Load Balancing.

**Comment by diegomanjarres** [comment]
Having the same Issue.
