### ISSUE TITLE
Standardize use of topic vs. topic_name

### ISSUE THREAD

**Issue by ottomata** [Blizzard/node-rdkafka#50]
It seems some interfaces use `topic` when refering to a string topic name, and others use `topic_name`.  E.g. consumer `assign()` expects the assignment object to use `topic` and `assignments()` returns an object with `topic`, but message objects from `consume()` calls use `topic_name`.  I understand that sometimes a topic can be a `Topic` instance, and sometimes just a string topic name, but it'd be nice if the usage of the two was consistent.

I'm reusing the message metadata for future `assign()` calls, and I'd like to not have to translate between topic and topic_name.

**Comment by webmakersteve** [comment]
I tried to keep it in line with the variable names librdkafka was asking for but I definitely understand the frustration. I have been looking to migrating all uses of `topic_name` to `topic` when passed as a jsobj.

**Comment by ottomata** [comment]
Ja, as long as its consistent I don't mind either way.  Thanks.

**Comment by ottomata** [comment]
Q1: is it possible to get this in before the next release?  

Q1: when you thinking the next release might happen?  I'm getting close to deploying stuff in prod, but am blocked on having to add github master dependency in my package.json right now.

**Comment by webmakersteve** [comment]
1. Yes, I will get this in before next release. Looking to add it today.
2. Planning next release this week. At the very least it will be released with `-BETA` or something so you will be able to use an npm dependency instead.

**Comment by ottomata** [comment]
Perfect, thank you so much!

**Comment by webmakersteve** [comment]
Addressed with #57
