### ISSUE TITLE
Clarification about the use of rebalance_cb

### ISSUE THREAD

**Issue by Patafix** [Blizzard/node-rdkafka#503]
Hello,
I have some question about the use of rebalance_cb : 

I use a consumer stream, and commit manually my offset.

Is the flow of message stop immediately when the revoke partition event is fired ?

What kind of code can you make in this callback : 

```
else if (err.code == Kafka.CODES.ERRORS.ERR__REVOKE_PARTITIONS){
      // HERE
      this.unassign();
    } 
```

Can you commit offset ? Will another consumer had this last offset ? Can you make some long operation like uploading a file, before a new consumer handle the partition ?

I have hard time to avoid duplicate message with my consumer.

Thank you in advance.

**Comment by thebigredgeek** [comment]
This might help: https://docs.confluent.io/2.0.0/clients/librdkafka/classRdKafka_1_1RebalanceCb.html

It does look like that is the intended usage

**Comment by webmakersteve** [comment]
You can indeed use that callback to commit offsets - and should if you want to reduce the amount of times a message is replayed across your consumers! 

Going to close the issue because I think the docs there also answer it 😄
