### ISSUE TITLE
Uncaught exception while serving requests

### ISSUE THREAD

**Issue by LongNTBui** [Blizzard/node-rdkafka#505]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: AMI Linux
 - Node Version [e.g. 8.2.1]: v8.1
 - NPM Version [e.g. 5.4.2]: v6
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.4.2

**Steps to Reproduce**

**node-rdkafka Configuration Settings**
- Create a Consumer using StreamAPI to consume messages from a topic from Confluent Bootstrap broker.
- After 5 mins. This error happens causing nodejs process to exit.

**Additional context**

error: Unknown error occurred at the broker 
 message=broker transport failure, origin=local, code=-1, errno=-1, stack=Error: Local: Broker transport failure
error: Uncaught exception while serving requests Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/home/ec2-user/sources/event-receiver/build/event-receiver/node_modules/node-rdkafka/lib/error.js:260:10)
    at /home/ec2-user/sources/event-receiver/build/event-receiver/node_modules/node-rdkafka/lib/kafka-consumer.js:448:29

**Comment by LongNTBui** [comment]
This happens because the application wasn't listening for "error" event and try and catch the exception there. I could only find "event.error" in the documentation. Shouldn't this be in the docs? I only found out "error" event after reading the code examples.

**Comment by webmakersteve** [comment]
`error` is a stream API concept that I just tried to follow with the stream implementation. I can make it clearer on the docs, but generally when you want to have durable error resilient streams you need to listen to that event.

In addition, it is mentioned here a bit: https://github.com/Blizzard/node-rdkafka#stream-api but I updated that sample to be a little more clear.
