### ISSUE TITLE
npm install node-rdkafka error

### ISSUE THREAD

**Issue by lvgithub** [Blizzard/node-rdkafka#508]
**Environment Information**
 - OS [Mac]: 
 - Node Version [v10.3.0]:
 - NPM Version [6.1.0]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [laster]:

**Steps to Reproduce**

**node-rdkafka Configuration Settings**

**Additional context**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [librdkafka.1.dylib] Error 1
make[1]: *** [libs] Error 2
make: *** [deps_librdkafka_gyp_librdkafka_target_build_dependencies.intermediate] Error 2
rm deps_librdkafka_gyp_librdkafka_target_build_dependencies.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/liuwei74/icode.baidu.com/node-kafka/node_modules/node-rdkafka
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node-kafka@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuwei74/.npm/_logs/2018-10-22T09_08_02_680Z-debug.log

**Comment by lfender6445** [comment]
This worked for me 

https://github.com/Blizzard/node-rdkafka/issues/419#issuecomment-390718067

**Comment by webmakersteve** [comment]
Fix for this is in the README under running on new MacOS versions. This is because of an OpenSSL breaking change introduced in the new MacOS
