### ISSUE TITLE
High memory consumption on slow consumers

### ISSUE THREAD

**Issue by amircodota** [Blizzard/node-rdkafka#510]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Ubuntu 18.04
 - Node Version [e.g. 8.2.1]: 8.9
 - NPM Version [e.g. 5.4.2]: yarn
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: 2.4.2

**Steps to Reproduce**

I was originally using kafka-node, and had the issue described below.
I then decided to try node-rdkafka to see if the situation is better, but I am getting similar results (although probably for different reasons).
The use case I have is where I have a topic already filled with many relatively big messages (~1 MB) over many partitions (say 100).
When I start a consumer and subscribe to the topic, memory usage just explodes to gigs of RAM.

I created a repro [here](https://github.com/amircodota/kafka-node-memory-issue), originally for kafka-node.
I then created a branch named test/rdkafka where I have a consumer implemented using node-rdkafka.
I also updated the instructions on how to reproduce.
Would really appreciate if someone can take a look and see if I am missing anything.

Amir

**Comment by amircodota** [comment]
After further investigation, I believe that this is an issue with librdkafka and not with the nodejs wrapper.

I've opened an issue there

https://github.com/edenhill/librdkafka/issues/2076

**Comment by webmakersteve** [comment]
Fetcher threads operate on a per partition basis and keep a lot of data in the buffers. You may be able to help the situation by scaling out to more consumers or reducing how eager the fetchers are and reducing their memory footprints.

**Comment by webmakersteve** [comment]
Looked at the thread and it seems like things are all resolved so closing this issue.
