### ISSUE TITLE
Error installing node-rdkafka on Windows 10 system

### ISSUE THREAD

**Issue by androm3da444** [Blizzard/node-rdkafka#515]
I've installed all the dependencies and trying to run _node-rdkafka_ on my local Windows setup. This was working until a few months back. Now, however, I am getting a _file does not exist_ error.
I have followed all the steps from : https://github.com/Blizzard/node-rdkafka/pull/248
![kafka-error](https://user-images.githubusercontent.com/16587263/47728556-f87aaf00-dc34-11e8-9107-a8b78e6fb5e7.png)

Any help would be appreciated, thanks.

**Comment by ManfredLange** [comment]
Getting node-rdkafka to install on Windows is - generally speaking - a bit tricky. You may find the discussion for [Issue #487](https://github.com/Blizzard/node-rdkafka/issues/487) valuable.

For us, we've been able to make version 2.3.4 to install. It still required some ancient version of Visual Studio C++ compilers and particular settings in the environment (paths, env variables, etc.) to make it work.

**Comment by webmakersteve** [comment]
Hopefully #493 will help you. Will be published today. Let me know if that doesn't work and re-open the issue!
