### ISSUE TITLE
RFC: Adding a callback to produce() to allow for a standard api contract for higher order capabilities

### ISSUE THREAD

**Issue by codeburke** [Blizzard/node-rdkafka#516]
This may be considered a continuation of the conversation in https://github.com/Blizzard/node-rdkafka/issues/124.

I'm currently working on a wrapper around node-rdkafka that allows for adding a plug-n-play serialization/deserialization library into the `produce()` and `consume()` apis. A primary objective is to try to maintain the existing node-rdkafka API surface so that users could switch over as easily as possible. 

The `consume()` is fairly straight forward to hook into since it is already an async callback/event interface. However, `produce()` is a synchronous interface that requires a breaking API change for serialization logic that requires async operation (like talking to a schema registry, for instance). 

My proposal would be to add a callback as the last parameter of `produce()`.  In the case of passing  the callback it doesn't make sense to also return a value from `produce` so there should be a condition added that if a callback is present as the last parameter then it will only call the callback and no explicit return value. That should maintain compatibility with the existing API so it is not a breaking change. The other benefit would be that there would be a very easy path to moving Promises just by using `util.promisify(producer.produce)` instead of having to manually wrap it for async/await code.
 
Current API:
```
var err;
var ret;
try {
    ret = producer.produce(topic, partition, message, key, timestamp, opaque);
} catch(e) {
    err = e;
}

if (err && err.code !== RdKafka.CODES.ERRORS.ERR__QUEUE_FULL) {
    throw err
} else if (err || !ret) {
    // wait and retry since it couldn't queue the message in the underlying producer
}
```

Proposed API Change:
```
producer.produce(topic, partition, message, key, timestamp, opaque, (err, ret) => {
    if (err && err.code !== RdKafka.CODES.ERRORS.ERR__QUEUE_FULL ) {
        throw err;
        return;
    } else if (err || !ret) {
        // wait and retry since it couldn't queue the message in the underlying producer
    }
});
```

Let me know what you think about adding this support and I'd be happy to turn this into a PR.

**Comment by codeburke** [comment]
So I just found https://github.com/Blizzard/node-rdkafka/issues/455. It looks like we are both proposing a callback to `produce` but for 2 different use cases.

 - My use case is purely to move the existing "got enqueued" logic into a callback in order to keep the API consistent.
 - @ismriv is looking for a full deliverability report via callback so that it is possible to wire up a Promise to the guarantee that a message was delivered . 

I like the idea of #455. We'd need to require a unique opaque token when the callback is present and fail if the token wasn't opaque. We'd also need to only store the opaque token when the callback was present in order to limit the memory impact for high volume producers. I would be willing to wire it up if that is the direction @webmakersteve would like to go.

Thoughts?

**Comment by webmakersteve** [comment]
I have toyed around with adding this functionality, but felt it was better to leave it parallel with `librdkafka` in the base method.

What I think may be desirable is an alternative, higher order function that adds callback delivery guarantee semantics on top of produce calls. I have done this in applications I maintain using `opaque` tokens and delivery reports.

I think this is a good enough addition to be added, provided it is a JS-land concern.

**Comment by webmakersteve** [comment]
https://github.com/Blizzard/node-rdkafka/pull/536 I just pushed this PR up, which has a lot of the work I needed to do in my other application encapsulated in this library as optional enriched behavior.

**Comment by codeburke** [comment]
I’m still working on this. Bumping in priority since I saw the
HighLevelProducer was merged.
