### ISSUE TITLE
add support for seek

### ISSUE THREAD

**Issue by hjespers** [Blizzard/node-rdkafka#52]
rdkafka has support for seeking to a specific offset using rd_kafka_seek(). It would be nice to expose this in node-rdkafka as well. I could not see this supported anywhere today.

**Comment by webmakersteve** [comment]
This change is waiting the next release of `librdkafka`, and will be worked on after some of the other priority issues are addressed.

However, PRs always welcome :)

**Comment by hjespers** [comment]
Happy to help. Just wanted to get the idea on the TODO list.

**Comment by edoardocomar** [comment]
@webmakersteve are you waiting for librdkafka 0.92 ? 
so hopefully not too far away (rc1 2 weeks ago)

**Comment by edenhill** [comment]
If you just need to set the starting offset for consumption you can pass the offset to assign() (for each partition).

seek() should typically only be used when you want to seek & skip during consumption.

**Comment by edoardocomar** [comment]
There is no `seek()` in `librdkafka` balanced C++ consumer yet.
https://github.com/edenhill/librdkafka/issues/1001

**Comment by edenhill** [comment]
assign() covers most cases where seek() is sought:
https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset
