### ISSUE TITLE
Alpine Linux - Error: Error loading shared library libsasl2.so.2

### ISSUE THREAD

**Issue by miskiw** [Blizzard/node-rdkafka#527]
**Environment Information**
 - OS: Alpine Linux 3.8
 - Node Version: 10.13.0
 - NPM Version: 6.0.0
 - node-rdkafka version: 2.4.2

Hi, I am having an impossible time trying to get node-rdkafka to run inside an Alpine linux docker image. I am using node:10-alpine as my base and have installed all the desired packages defined: https://github.com/Blizzard/node-rdkafka/blob/master/examples/docker-alpine.md

```sh
/usr/src/app/node_modules/bindings/bindings.js:88
throw e
^
Error: Error loading shared library libsasl2.so.2: No such file or directory (needed by /usr/src/app/node_modules/node-rdkafka/build/Release/../deps/librdkafka.so.1)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
at Module.load (internal/modules/cjs/loader.js:598:32)
at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
at Function.Module._load (internal/modules/cjs/loader.js:529:3)
at Module.require (internal/modules/cjs/loader.js:636:17)
at require (internal/modules/cjs/helpers.js:20:18)
at bindings (/usr/src/app/node_modules/bindings/bindings.js:81:44)
at Object.<anonymous> (/usr/src/app/node_modules/node-rdkafka/librdkafka.js:10:32)
at Module._compile (internal/modules/cjs/loader.js:688:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! your-app-name-here@0.1.0 prod:start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the your-app-name-here@0.1.0 prod:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-11-15T15_53_45_048Z-debug.log
``` 

when I "step into" the docker image and search for `find / -name  libsasl2*` I get the following:
```
/usr/src/app # find / -name libsasl2*
/usr/lib/pkgconfig/libsasl2.pc
/usr/lib/libsasl2.so.3
/usr/lib/libsasl2.so
/usr/lib/libsasl2.so.3.0.0
/usr/src/app/node_modules/node-rdkafka/deps/librdkafka/packaging/cmake/try_compile/libsasl2_test.c
```

so `libsasl2.so.3` is available but `libsasl2.so.2` is nowhere to be found.

If I switch to a `node:10.13.0-stretch` docker base image and install `libsasl2-dev`
```
# find / -name libsasl2.*
/usr/lib/x86_64-linux-gnu/libsasl2.a
/usr/lib/x86_64-linux-gnu/pkgconfig/libsasl2.pc
/usr/lib/x86_64-linux-gnu/libsasl2.so
/usr/lib/x86_64-linux-gnu/libsasl2.so.2
/usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
```

So it appears Alpine no longer has the desired version of libsasl2 required for librdkafka ?

does anyone have a work around for this? Is there an older package I can install somehow?

Thanks!

**Comment by vdrg** [comment]
I used node:10-alpine and it worked. Dockerfile:

```
FROM node:10-alpine

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies (allow caching)
COPY package.json yarn.lock /usr/src/app/
RUN yarn install --pure-lockfile

COPY . /usr/src/app/

EXPOSE 3000

CMD [ "yarn", "start" ]
```

Did you add a `.dockerignore` file to your repo? It may be happening because you are overriding the lib that is built inside the container with your local `node_modules` :thinking:

**Comment by uditalias** [comment]
@vdrg It's not working with `node-rdkafka@2.5.1`.
What is the `node-rdkafka` version you're using in package.json?

**Comment by theliuk** [comment]
I'm having this problem as well.
I tried the solution proposed by @vdrg , but I get the same error.
Any idea?

**Comment by Vidz51** [comment]
getting same error. Did anyone found the workaround?

**Comment by eduardomrodrigues** [comment]
Hi, people!

Same problem here!
Any ideia?

**Comment by Chebura** [comment]
hi, nothing changed for me, same error with installed proper packages with libsasl2.so. 
.netcore 3.1 with confluent.kafka client.
There are no native librdkafka.so dependencies included in packages, and there are no properly resolved dependencies in alpine. I'll be dig deeper.

**Comment by Vidz51** [comment]
hi @Chebura  I resolved it by making sibling. I am using centos8.  here is my docker file inputs:

```
RUN yum -y install epel-release python3-configobj gcc python3-devel
RUN yum -y install openssl-devel
RUN cd /usr/lib64 \
 && ln -s  /usr/lib64/libsasl2.so.3.0.0 libsasl2.so.2
RUN yum install cyrus-sasl-md5 cyrus-sasl-plain cyrus-sasl-gssapi cyrus-sasl-devel -y
RUN yum install -y gcc-c++
RUN dnf install -y librdkafka
```

hope it helps
