### ISSUE TITLE
Is there any sample for kerberos connection?

### ISSUE THREAD

**Issue by phuongnq** [Blizzard/node-rdkafka#528]
While trying Consumer with Kerberos, I could not get it work (I tried Kafka official consumer-console.sh and it is working as normal).
While using node-rdkafka, the application hang and there is no error or connect ready emit.
Here is my Consumer log:

````
KafkaConsumer {
  _events:
   { ready: [Function],
     disconnected: [Function],
     'event.error': [Function] },
  _eventsCount: 3,
  _maxListeners: undefined,
  _client: KafkaConsumer {},
  metrics: {},
  _isConnected: false,
  errorCounter: 0,
  _metadata: {},
  globalConfig:
   { debug: 'all',
     'group.id': 'my_group_id',
     'metadata.broker.list':'host1:port,host2:port,host3:port',
     'security.protocol': 'sasl_plaintext',
     'sasl.kerberos.kinit.cmd':
      'kinit -k -t /my.keytab ${principal}',
     'sasl.mechanisms': 'GSSAPI',
     'sasl.kerberos.keytab': '/my.keytab',
     'sasl.kerberos.service.name': 'kafka',
     'sasl.kerberos.principal': '${principal',
     'sasl.kerberos.min.time.before.relogin': 60000,
     'enable.auto.commit': false,
     connect_cb: [Function: connect_cb],
     rebalance_cb: [Function] },
  topicConfig: { 'auto.offset.reset': 'earliest' },
  _consumeTimeout: 1000 }

I have my custimized krb5.conf which is easily set if using Java: `-Djava.security.krb5.conf=/my/krb5.conf`

I set it using environment variable `KRB5_CONFIG` but still not work.

**Comment by webmakersteve** [comment]
There aren't any examples in `node-rdkafka` but the `librdkafka` repo may have more information. I would check there first. 

https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by aparolin** [comment]
@phuongnq Did you find any examples? Did you make it work? I'm having the exact same issue.

**Comment by phuongnq** [comment]
@aparolin I didn't find a good one so I end up using Java client.

**Comment by aparolin** [comment]
@phuongnq Thanks for the update. As an FYI, we ended up switching to a different package ([kafkajs](https://www.npmjs.com/package/kafkajs)), and it worked :)

**Comment by fanz1984** [comment]
@aparolin I don't see kerberos implemented in kafkajs. Could you share some example how you made it work?

**Comment by aparolin** [comment]
@fanz1984 We ended up switching the authentication to SASL with PLAIN mechanism. So, unfortunately, I don't have an example of Kerberos working.

**Comment by coolgooze** [comment]
Here's a working sample working with Secured Kafka Cluster

```
kafkacat -b '<**Broker_Hostname**>:<**Broker_Listen_Port**>' -L \
-X security.protocol=**sasl_plaintext** \
-X sasl.kerberos.keytab='kafka.service.keytab' \
-X sasl.kerberos.service.name=kafka \
-X sasl.kerberos.principal=' kafka/<**Broker_Hostname**>@<REALM>' \
-X sasl.kerberos.kinit.cmd="kinit -kt <**App_KeytabName**> <**App Keytab Principal**>"
-t <**TopicName**>```
