### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found

### ISSUE THREAD

**Issue by meierval** [Blizzard/node-rdkafka#529]
**Environment Information**
 - OS [Mac Mojave]: 
 - Node Version [10.13.0]:
 - NPM Version [6.4.1]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [2.4.2]:

**Steps to Reproduce**
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib
npm install node-rdkafka
npm install
npm start
> MyProject@1.0.0 start /Users/myuser/Documents/projects/myproject
> electron .

dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/myuser/Documents/projects/myproject/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/myuser/Documents/projects/myproject/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Expected in: flat namespace

**node-rdkafka Configuration Settings**

**Additional context**
Electron project, with only "const kafka = require('node-rdkafka')"

**Comment by webmakersteve** [comment]
I haven't used any of this in electron, but the symbols mentioned seem like core symbols in node. This could happen if the version you compiled for is linking against different symbols at run time than you expect, which may be something to do with how Electron runs node in its embedded engine.

I would start there - sorry I can't be of any more help.

**Comment by klesgidis** [comment]
Hey guys, any update here?

**Comment by sanketdhoble** [comment]
Any update on this?
