### ISSUE TITLE
'Error: Can’t set headers after they are sent' at validateHeader (_http_outgoing.js:494:11)

### ISSUE THREAD

**Issue by rsryanstephen** [Blizzard/node-rdkafka#530]
**Environment Information**
 - OS [Linux]: 
 - Node Version [8.9.4]:
 - NPM Version [6.1.0]:
 - C++ Toolchain [Visual Studio Code]:
 - node-rdkafka version [2.2.3]:

**Steps to Reproduce**
Using the code below, sending this kind of message with these settings resulted in the following error:
`Error: Can’t set headers after they are sent. 
   at validateHeader (_http_outgoing.js:494:11)
   at ServerResponse.setHeader (_http_outgoing.js:501:3)
   at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:767:10)
   at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
   at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
   at producer.flush.err (/usr/src/app/api/kafka.js:153:14)
   at /usr/src/app/node_modules/node-rdkafka/lib/producer.js:254:7`

function sendKafkaMessage(req, res) {
                    const kafka = require('node-rdkafka');
                
                    const options = {
                        'client.id': 'batch-monitor',
                        'metadata.max.age.ms': '300000',
                        'metadata.request.timeout.ms': '60000',
                        'session.timeout.ms': '300000',
                        'metadata.broker.list': config.kafka_brokers,
                        'sasl.kerberos.principal': config.kerberos_principal,
                        'sasl.kerberos.keytab': config.keytab_loc,
                        'sasl.kerberos.service.name': 'kafka',
                        'sasl.kerberos.min.time.before.relogin': '600000', //'86400000',
                        'security.protocol': config.kafka_security_protocol,
                        'sasl.kerberos.kinit.cmd': 'kinit -kt "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}',
                        'request.required.acks': '1',
                        'dr_msg_cb': true, //delivery report callback
                        'event_cb': true
                    };
                
                    var producer = new kafka.Producer(options);
                    producer.on('ready', () => {

                            const topic = 'v2_start_cube';
                            const partition = 0;
                            const msg = '{"id":"7bf4250d-7bc7-aa61-7bc5-8e0636b7fb74", "key":"LoadCompleted", "agency":"All", "data_key":"Steps.Cube",  "data_date":"2018-11-21T05:48:13.163Z", "batch_id":"808" }';

                            producer.produce(topic, partition, msg, '1', Date.now());
                    })   

                    const timeoutObj = setTimeout(() => {
                        producer.flush(resp.failCode, err => {
                            res.status(resp.failCode)
                                .json({
                                    status: `${resp.from} flushed error: `,
                                    error: err
                                });
                                producer.disconnect(null, () => {
                                    clearTimeout(timeoutObj);
                                });
                            return;
                        })

                        return;
                    }, 15000);

                }

**node-rdkafka Configuration Settings**

 const options = {
                        'client.id': 'batch-monitor',
                        'metadata.max.age.ms': '300000',
                        'metadata.request.timeout.ms': '60000',
                        'session.timeout.ms': '300000',
                        'metadata.broker.list': config.kafka_brokers,
                        'sasl.kerberos.principal': config.kerberos_principal,
                        'sasl.kerberos.keytab': config.keytab_loc,
                        'sasl.kerberos.service.name': 'kafka',
                        'sasl.kerberos.min.time.before.relogin': '600000', //'86400000',
                        'security.protocol': config.kafka_security_protocol,
                        'sasl.kerberos.kinit.cmd': 'kinit -kt "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}',
                        'request.required.acks': '1',
                        'dr_msg_cb': true, //delivery report callback
                        'event_cb': true
                    };

**Additional context**

Error is thrown as soon as the following line is called:
`producer.produce(topic, partition, msg, '1', Date.now());`

**Comment by rsryanstephen** [comment]
Same error occurs for the latest version 2.4.2

**Comment by webmakersteve** [comment]
These problems generally occur as "error after error" errors. Something in your request/response loop is throwing, causing express to end the request as a 500. But then, somewhere else in your code, you are trying to write a response. So it fails.

This is something internal to your logic and not the library. If you are concerned with that type of throwing you should wrap the produce call in a try catch so it does not bubble up to the request exception domain.
