### ISSUE TITLE
Is possible consumer.disconnect on consumer.on.data?

### ISSUE THREAD

**Issue by sl5310** [Blizzard/node-rdkafka#532]
I would like to receive message then process logic & store into database, how can I set a maxMessage or disconnect while after logic process done?

Works:
1. `consumer.offsetsForTimes` get x offset
2. `consumer.assign` start from x offset
3. when 
`consumer.on('data', (m) => {`
    `   if (m.timestamp > x) {`
    ` consumer.disconnect(); //stop receiving message `
    `    } else {`
    `//process logic`
     `}`
`});`

but i put `consumer.disconnect(); ` it does not stop & disconnect & still receiving message, any way i can stop it?

**Comment by webmakersteve** [comment]
Don't use `on('data')` if possible in your use case. Instead you should manually use the `consume` call to consume batches as you need them, and then when your condition is true and you do not wish to consume anymore, you can `disconnect` with no threat of new messages being emitted.
