### ISSUE TITLE
Can we create topics using node-rdkafka lib?

### ISSUE THREAD

**Issue by JulienCarnec** [Blizzard/node-rdkafka#534]
Is it possible to create a new kafka topic using node-rdkafka?

The following closed issue seems to tell that this could be feasible: https://github.com/Blizzard/node-rdkafka/issues/85

And the following method from the AdminClient seems to match my need: 
https://github.com/Blizzard/node-rdkafka/blob/be47c8b5422fc39c5b41dab33850cd98d89f03b7/src/admin.cc#L138

However, I could not find a way from the Javascript API to execute this method in v2.4.0, but seems available in master. 

Is there a workaround to execute AdminClient methods using v2.4.0?
When will changes from master be released in an official version?

**Comment by webmakersteve** [comment]
I'm trying to get a new build out today with the AdminClient methods, but it may not be until middle of this week. Dedicating a bunch of time on node-rdkafka this week so it should push that stuff to the finish line.

**Comment by webmakersteve** [comment]
Next week was today! Closing this issue 😛 

Use version 2.5.0 and you can create/delete/scale topics.

**Comment by JulienCarnec** [comment]
Thanks a lot!
