### ISSUE TITLE
when i tried start node index.js file

### ISSUE THREAD

**Issue by stephenjesus** [Blizzard/node-rdkafka#541]
/home/stephen/Desktop/node-rdkafka/node_modules/bindings/bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:

**Comment by ankon** [comment]
I think without any further information there is nothing that could be done here.

@stephenjesus can you 
1. Describe what you tried exactly, potentially with code?
2. Describe your environment (operating system and version, node.js version, node-rdkafka version, ...)
3. Provide full logs of the failure?
