### ISSUE TITLE
when i tried to build  (npm install)

### ISSUE THREAD

**Issue by stephenjesus** [Blizzard/node-rdkafka#542]
make: Entering directory '/home/stephen/Desktop/node-rdkafka/build'
  ACTION deps_librdkafka_gyp_librdkafka_target_configure deps/librdkafka/config.h
./configure: line 13: ./configure: No such file or directory
make: *** No rule to make target '../deps/librdkafka/config.h', needed by '11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate'.  Stop.
make: Leaving directory '/home/stephen/Desktop/node-rdkafka/build'

and my 
node -v (v8.12.0)

npm -v (6.4.1)

@webmakersteve Sir

**Comment by webmakersteve** [comment]
This looks like you pulled down from Github and then tried to build. In that case make sure you are initializing the sub module. You can either ‘git clone —recursive’ or follow the steps on the readme around submodule initialization.


________________________________

**Comment by stephenjesus** [comment]
Thanks @webmakersteve
