### ISSUE TITLE
KafkaConsumer hangs if 'group.id' property is missing

### ISSUE THREAD

**Issue by subk** [Blizzard/node-rdkafka#561]
**Environment Information**
 - OS : debian 9.6 (x86_64)
 - Node Version : 9.11.1
 - NPM Version : 6.5.0
 - node-rdkafka version : 2.5.1

**Steps to Reproduce**
Instantiate a `KafkaConsumer` client without specifying a `group.id` property.

**node-rdkafka Configuration Settings**
```javascript
const rd = require('node-rdkafka');

const options = {
  'metadata.broker.list': 'localhost:9092'
}

const consumer = new rd.KafkaConsumer(options);

consumer.on('ready', () => {
  consumer.subscribe([ 'some-topic' ]);
  consumer.consume((err, message) => {
    console.log(err, message);
  });
});

consumer.connect();
// .... nothing will happens : ready event will never been triggered, nor logging events
// Note: Kafka cluster is healthy
```
**Additional context**
Kafka client just hangs - no event triggered, no debug message

I would expect `KafkaConsumer` to throw an error if `group.id` is missing or to generate a random one.

**Comment by mirek-burkon** [comment]
Actually, I believe this happens even if you subscribe to a topic which never receives any messages (doesn't exist in Kafka). Then it's even impossible to unsubscribe and/or disconnect the consumer which I find to be a major headache. I'd appreciate if anyone could share a workaround other than non-flowing mode

**Comment by subk** [comment]
maybe manually create the topic first using the Admin API ?
