### ISSUE TITLE
Error connecting to producer : Error: ssl.certificate.location failed:

### ISSUE THREAD

**Issue by mrinalblr** [Blizzard/node-rdkafka#563]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Windows10
 - Node Version [e.g. 8.2.1]:10.4.1
 - NPM Version [e.g. 5.4.2]:6.4.1
 - node-rdkafka version [e.g. 2.3.3]:2.5.1

**Steps to Reproduce**

**node-rdkafka Configuration Settings**
```
var producer = new Kafka.Producer({
    'metadata.broker.list': '<ssl-enabled-host>:<port no>',
    'dr_cb': true,
    'security.protocol': 'SSL',
    'ssl.key.location': 'test.key',   //path to the self signed certificate
    'ssl.certificate.location': 'test.crt',  //path to certificate key.
  });
```
**Additional context**
The kafka producer is ssl enabled .When tried connecting the broker without the security and ssl configuration in metadata it  threw **Error:timeout** .
Hence went ahead to add the configuration for enabling ssl and adding the path to ssl crt and key as mentioned above in the configuration, but that didnot work either throwing error which i am not able to understand below is the error : 
`Error connecting to producer : Error: ssl.certificate.location failed: .\ssl\ssl_rsa.c:701: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:`

**Comment by mrinalblr** [comment]
I debugged the code and found that the path to certificates location was not correct.
Hence this issue can be closed .

**Comment by lamrani00** [comment]
I had the same issue, you can put the path in this param SslCaCertificateStores
{"SslCaCertificateStores", "yourCertificatPath"}
