### ISSUE TITLE
Failure to initialize (error:SSL routines:SSL_CTX_new:library has no ciphers)

### ISSUE THREAD

**Issue by anastasios-workable** [Blizzard/node-rdkafka#566]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: `Debian GNU/Linux 8 (jessie), 4.4.0-141-generic`
 - Node Version [e.g. 8.2.1]: `10.3.0`
 - NPM Version [e.g. 5.4.2]: `6.1.0`
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: `g++ (Debian 4.9.2-10+deb8u1) 4.9.2`
 - node-rdkafka version [e.g. 2.3.3]: `2.5.1`

**Steps to Reproduce**
```
$ docker run -it node:10.3.0 bash
$ npm init
$ npm i node-rdkafka --save
$ echo "new require('node-rdkafka').Producer({\
    'metadata.broker.list': '...',\
    'security.protocol': 'ssl',\
    'ssl.key.location': './any-service.key',\
    'ssl.certificate.location': './any-service.cert',\
    'ssl.ca.location': './any-ca.pem'\
}).connect({}, e => console.log(e));" > test.js
$ node test.js
```
Fails with:
```bash
{ Error: SSLv23_client_method() failed: ../deps/openssl/openssl/ssl/ssl_lib.c:2583: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers: 
    at Function.createLibrdkafkaError [as create] (/node_modules/node-rdkafka/lib/error.js:261:10)
    at /node_modules/node-rdkafka/lib/client.js:187:28
  message:
   'SSLv23_client_method() failed: ../deps/openssl/openssl/ssl/ssl_lib.c:2583: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers: ',
  code: -172,
  errno: -172,
  origin: 'kafka' 
```

**node-rdkafka Configuration Settings**
See above

**Additional context**
Same thing happens on

```bash
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 16.04.5 LTS"
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016

**Comment by miton18** [comment]
Hi !
Same issue here

```sh
$ node --version
v10.15.1

$ openssl version
OpenSSL 1.1.0j  20 Nov 2018

"node-rdkafka": "^2.5.1",

```

On Debian GNU/Linux 9 (stretch)

**Comment by SoyYoRafa** [comment]
This is because node 10 is compiled against OpenSSL 1.1.1 but librdkafka doesn't support OpenSSL 1.1.x. librdkafka will support it in 1.0.0

**Comment by ScottONeal** [comment]
Can confirm. When I built with Node 10 I received this error, however, when building with Node 8 which is bundled with 1.0.2q all worked as intended.

**Comment by rclayton-the-terrible** [comment]
Hey friends, it looks like librdkafka does support 1.1.0: https://github.com/edenhill/librdkafka/pull/2000

**Comment by ScottONeal** [comment]
Not being as familiar with `node-gyp`, is it possible that `librdkafka` is building with the systems OpenSSL and not from the node.js bundled one? The documentation for link openssl in the `node-gyp` wiki is pretty old and I'm not sure it still applies: https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL

**Comment by SoyYoRafa** [comment]
I manually configured and built librdkafka 0.11.6 in node-rdkafka with node v10 libraries to compile against OpenSSL 1.0.0 and 1.1.0. I couldn't get it to work.

**Comment by shayaShav** [comment]
In my case I could "afford" downgrading nodejs to 8.15.1, which solved the problem

**Comment by ammills01** [comment]
I'm seeing the same thing with the following stack:
- Alpine 3.8.2 (node:10.15.0-alpine docker container)
- node 10.15.0
- npm 6.4.1
- node-rdkafka version 2.6.1

Looking at the instructions [here](https://github.com/Blizzard/node-rdkafka/blob/master/examples/docker-alpine.md) they are using 8-apline, is that the highest version this lib works with?

**Comment by Banashek** [comment]
+1 on this issue.

We experienced it using the same referred to docker image wiki page linked by ammills01

The dockerfile bases off of `node:8-alpine`, which now comes with `libssl1.1`, however `openssl-dev` version `1.0.2` requires `libssl1.0` [as shown on the apk page](https://pkgs.alpinelinux.org/package/v3.3/main/x86/openssl-dev).

Switching to `node:8.15.1-alpine` as shayaShav mentions above does install `libssl1.0` and allows `openssl-dev1.0.2` to be added correctly.

I'm guessing that the `node:8-alpine` image switched to a new version of the `alpine base image`.

Looking at the `node:8-alpine` history, we can see that it bumped the alpine version when updating the minor version from `15` to `16`: https://github.com/nodejs/docker-node/commit/a8dbfa5c7cac9dca9145c6f429cd2c4f11176707#diff-c27c14abc33ff0f1ffaf5aaa5b6bd6ea

Additionally, looking at [the alpine release history](https://alpinelinux.org/posts/), there were plenty of ssl changes between 3.8.0 and 3.9.0.

**Comment by ammills01** [comment]
@Banashek were you able to get SSL working with node:8.15.1-alpine?  After fighting with this for nearly a week, we ended up cutting bait and rewriting our API in Go, it's way faster anyway and supported directly by Confluent.

https://github.com/confluentinc/confluent-kafka-go

**Comment by Banashek** [comment]
@ammills01 yes switching to node:8.15.1-alpine ssl works fine.

The `KafkaConsumer` config has the following:

```
    'sasl.username': 'yourusername',
    'sasl.password': 'yourpassword',
    'security.protocol': 'sasl_ssl',
    'ssl.ca.location': `${caFileLocation}`,
    'sasl.mechanism': 'PLAIN',
```
