### ISSUE TITLE
stats: commited_offset, hi_offset, consumer_lag and next_offset are not clear

### ISSUE THREAD

**Issue by th3nu11** [Blizzard/node-rdkafka#567]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Docker image, from ubuntu:16.04
 - Node Version [e.g. 8.2.1]:v8.15.0
 - NPM Version [e.g. 5.4.2]: 6.4.1
 - node-rdkafka version 2.5.1

**Steps to Reproduce**
I don't know how to reproduce, sometimes happens. 
I start the consumer on topic with no lag and I'm using the streams to read.

**node-rdkafka Configuration Settings**
* enable.auto.commit: false
* enable.auto.offset.store: false

**Additional context**

` BEFORE
"20": {
  "partition": 20,
									"leader": 0,
									"desired": true,
									"unknown": false,
									"msgq_cnt": 0,
									"msgq_bytes": 0,
									"xmit_msgq_cnt": 0,
									"xmit_msgq_bytes": 0,
									"fetchq_cnt": 0,
									"fetchq_size": 0,
									"fetch_state": "active",
									"query_offset": -1,
									"next_offset": 19063471,
									"app_offset": -1001,
									"stored_offset": -1001,
									"commited_offset": 16571473,
									"committed_offset": 16571473,
									"eof_offset": 19063471,
									"lo_offset": 18376014,
									"hi_offset": 19063471,
									"consumer_lag": 2491998,
									"txmsgs": 0,
									"txbytes": 0,
									"rxmsgs": 0,
									"rxbytes": 0,
									"msgs": 0,
									"rx_ver_drops": 0
								},
`

I don’t understand this partition statistics:
- “consumer_lag”: 2491998 -> it seems that I have a big lag on this partition
- hi_offset - max(app_offset, committed_offset): 2491998 -> equal to the consumer_lag
- “next_offset”: 19063471 (equal to hi_offset) - it seems that I have already fetched all data but that I've not committed offsets yet, right?

I tried to restart the consumer and statistics didn't change. (no messages consumed)
Then I started a new consumer with "kafka-consumer-groups.sh" script (same group/same topic): no messages were consumed but stats changed and lag became 0.
Can you help me to understand this problem?
I’m doing many checks on statistics because sometimes my consumers stop fetching messages from only one or two partitions and I don't understand the reason.

AFTER kafka-consumer.sh scripts
 `
app_offset: -1001
commited_offset: 19063471
committed_offset: 19063471
consumer_lag: 0
desired: true
eof_offset: 19063471
fetch_state: "active"
fetchq_cnt: 0
fetchq_size: 0
hi_offset: 19063471
leader: 0
lo_offset: 18497120
msgq_bytes: 0
msgq_cnt: 0
msgs: 0
next_offset: 19063471
partition: 20
query_offset: -1
rx_ver_drops: 0
rxbytes: 0
rxmsgs: 0
stored_offset: -1001
txbytes: 0
txmsgs: 0
unknown: false
xmit_msgq_bytes: 0
xmit_msgq_cnt: 0
`

Thanks.
Carlo

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by th3nu11** [comment]
Yes, I already read this page, thanks.

I'm only asking an help to understand why stats say about a big lag if lag doesn't exists.

Why if the committed_offset is lower than hi_offset and if I start a new consumer, it doesn't read any message?

Why if I start a rdkafka consumer the lag remains in the stats, instead if I start a kafka-consumer-groups.sh lag magically became 0? (and obviously don't consume any message)

Maybe the answer is in the url but, please, help me to find it.

Thanks,
Carllo

**Comment by th3nu11** [comment]
Nothing?
