### ISSUE TITLE
Non-flowing mode is not working as expected

### ISSUE THREAD

**Issue by yonigoyhman** [Blizzard/node-rdkafka#571]
I have a consumer that needs to handle a big load of messages where handling a message is a memory consuming task.

Implementing a Flowing mode causes Out Of Memory Issues, so I am trying to implement a non-flowing mode, but without success.

What I want to do: 

Have a max number of messages being handled simultaneously.

Here is my code:

    const maxMsgs = 10;
    const config = {
      'rebalance_cb': onRebalance,
    }

    const cb = async (data) => {

      console.log("data is " + data);
      for (let i = 0; i < data.length ; i++) {
        await handle(data[i]);
        if (maxMsgs)
          consumer.consume(1)
      }
    }

    const onRebalance = (err, assignments) => {
      console.log("rebalance occurred");
    }

    const consumer = new kafka.Consumer(config);
    
    consumer.on('ready', () => {
      consumer.subscribe(topicsList);
      if(maxMsgs)
        consumer.consume(maxMsgs);
      else
        consumer.consume();
    });
    
    consumer.on('data', cb);

    consumer.connect();

If I set maxMsgs to null, everything works (until the memory crash), and I get:
    // rebalance occurred
    // data is [Object]
But if maxMsgs is a number i get:
    // data is []
And nothing else happens, no rebalance and no new messages arrive. 

I can wrap the `consumer.consume(maxMsgs);` in a setTimeout, and if the timeout is long enough it works (over 10 seconds timeout), but I do not want to have unnecessary timeouts in my code.

Is there a better way to limit the amount of parallel handles? Am I missing anything?

**Comment by poslegm** [comment]
I have this problem too. It's very contrintuitive API. If such behavior is expected, then you should write about it in the documentation.

**Comment by analytik** [comment]
I think the method should be renamed to `consumeBatch(n, [cb])` because it behaves so differently. I don't have a problem the data handler being called with an empty array, but it should be explicitly an array of objects. Also the examples in the documentation should be expanded and commended better, but I'll have to sit on it to come up with suggestions, because I'm still not sure if I got all the caveats and gotchas of the driver.

Not to mention that Producers and Consumers have very different reconnection logic after a network outage or broker downtime.

**Comment by philipyoo** [comment]
I'm experiencing something similar. Adding a timeout works, but it seems as though the more entries I produce and try to consume, the larger I need to increase the timeout.

What's very strange is if I create a console consumer, I see entries being consumed, but once the kafka consumer timeout ends, sometimes it does not actually consume those entries itself.
