### ISSUE TITLE
Missing messages when consuming after first start

### ISSUE THREAD

**Issue by AlexKonstantinov1991** [Blizzard/node-rdkafka#572]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]:  Ubuntu 18.04.2
 - Node Version [e.g. 8.2.1]: 10.14.1
 - NPM Version [e.g. 5.4.2]: 6.7.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.5.1
 - I'm having kafka and zookeeper in docker-compose file
**Steps to Reproduce**
  1) Launch kafka
  2) Start a Producer generating messages for a certain topic
  3) Start a Consumer after a couple of messages have been sent by a producer, the consumer will start receiving messages from the last generated message.
  
**node-rdkafka Configuration Settings**
 - consumer: 
          'group.id': `node_local_kafka1_service_localhost`,
          'metadata.broker.list': 'localhost:9092',
          'socket.keepalive.enable': true,
          debug: 'consumer,cgrp,topic',
          'enable.auto.commit': false,
          'auto.offset.reset': 'smallest',
 - producer: 
       'metadata.broker.list': 'localhost:9092',
      'client.id': `node_localplay_service_localhost`,
      debug: 'broker,topic,msg',
      'linger.ms': 0,
      dr_cb: true,

**Additional context**
docker-image: confluentinc/cp-kafka:5.1.0

When I commit offsets at least one, then kafka works as it supposed, a consumer consumes data from the last unconsumed offset.

example: 
1) producer generated offsets: [0, 1, 2, 3, 4, 5]
2) consumer connected.
3) consumer gets only offset with number = 5;

**Comment by rclayton-the-terrible** [comment]
`'auto.offset.reset': 'smallest',` should be in the second settings object passed into the consumer:

```typescript
const config = Object.assign({}, this.options.connection, {
  'client.id': this.clientId,
  'group.id': consumerOptions.groupId,
  'rebalance_cb': true,
})
const topicConfig = {
  'auto.offset.reset': 'smallest',
}
this.consumer = new KafkaConsumer(config, topicConfig)
```
