### ISSUE TITLE
Request for librdkafka upgrade

### ISSUE THREAD

**Issue by ThePrez** [Blizzard/node-rdkafka#578]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: IBM i
 - Node Version [e.g. 8.2.1]: 8.x, 10.x
 - NPM Version [e.g. 5.4.2]: 6.x
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: latest

**Steps to Reproduce**
`npm install kafka-avro`

**node-rdkafka Configuration Settings**

**Additional context**
This is not an issue, merely a request to grab a newer version of librdkafka. Doing so would enable this package to run on a new operating system (IBM i), as well as 64-bit AIX. Support was added via a small fix in this PR: https://github.com/edenhill/librdkafka/pull/2017

Thanks in advance for your consideration!

**Comment by sreejithp** [comment]
Please upgrade the librdkafka. The new 1.0.0 release supports idempotent producer. Please consider upgrading as it helps a lot of people node community. https://github.com/edenhill/librdkafka/releases/tag/v1.0.0.

Let us know if we could help in upgrading.
