### ISSUE TITLE
Unable to specify topic configurations in produce()

### ISSUE THREAD

**Issue by mimaison** [Blizzard/node-rdkafka#58]
Following the latest update, `producer.produce()` now only accepts `topic` as a string. This prevents us from setting topic properties like `request.required.acks`.

Looking at the code, it all boils down to the way `produce()` evaluates if it's called from the old API or the new one.

**Comment by webmakersteve** [comment]
Merged #59. Thanks for the PR

**Comment by edoardocomar** [comment]
@webmakersteve this is fixed with PR https://github.com/Blizzard/node-rdkafka/pull/59

**Comment by webmakersteve** [comment]
Re-opening so I can close it when I release it to NPM.

**Comment by cjolif** [comment]
may I ask when you do you expect to release to NPM as I'm blocked by this as well? 

Also I was wondering if you should not tag your GHE code with the NPM release? When facing that regression I was trying to figure how the code moved along the NPM releases history but without the tags in GHE it was not easy.

**Comment by webmakersteve** [comment]
I'll start tagging the releases. Just retroactively tagged 0.6.0.

As far as when I'm going to release - it will be today. I just need to make some fixes to CI.

**Comment by cjolif** [comment]
@webmakersteve any news on the release with the fix?

**Comment by webmakersteve** [comment]
Reelased!

**Comment by cjolif** [comment]
thanks!
