### ISSUE TITLE
high memory usage using stream consumer and potentialy memory leaking

### ISSUE THREAD

**Issue by yanqi321** [Blizzard/node-rdkafka#581]
**Environment Information**
 - CentOS Linux release 7.6.1810
 - Node Version : v8.15.0
 - NPM Version [e.g. 5.4.2]: 6.4.1
 - C++ : gcc  4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
 - node-rdkafka version: 2.5.1
**Relative Issue** #179
high rss and steady and low heap usage  closed#12805 
**Steps to Reproduce**
the memory keep increase while i start the process of kafka consumer, i dont know why it took so much memory of rss. Could you  help me, thanks.
**node-rdkafka Configuration Settings**
```
const Kafka = require('node-rdkafka')
const Writable = require('stream').Writable
let logStream = Kafka.KafkaConsumer.createReadStream(
        {
          'metadata.broker.list': 'kafka1:19092,kafka2:19092',
          'group.id': 'new-recomm-test',
          'socket.keepalive.enable': true,
          'enable.auto.commit': false
        },
        { 'auto.offset.reset': 'latest' },
        { 'topics': ['userlog'] }
      )
```
**Additional context**
my consumer codes:
```
let counter = 0
      let numMessages = 10
      logStream.pipe(new Writable({
        objectMode: true,
        write: async (message, encoding, callback) => {
          counter++
          try {
            let userLog = JSON.parse(message.value)
            console.log(userLog)
            callback(null)
            if (counter % numMessages === 0) {
              logStream.consumer.commit()
            }
            // 每处理 10000 条打印一次日志，避免日志过大
            if (counter % 10000 === 0) {
              console.info(`solved 10000 messge:${actType}, ${uuid}, ${addTime}`)
            }
          } catch (error) {
            __klogger.error(error.message)
            logStream.pause()
          }
        }
      }))

      logStream.on('error', function (err) {
        process.exit(1)
      })

      logStream.consumer.on('event.error', function (err) {
        __klogger.warn(`log kafka event err: ${err.message}`)
      })
```
**the screensot of memory using**
![rss](https://user-images.githubusercontent.com/22360047/54440775-51775980-4776-11e9-820f-dadefbf5af3b.png)
this is the screenshot of the comsuer process after Add some business code(like mysql query,redis)
but if i just console.log the message , it took over 1G of memory(rss) on the topic. 
Is there any way to limit the message count or  memory leak ?  the pipe methods not working.

**Comment by yanqi321** [comment]
i solved ,thank you

**Comment by octava25** [comment]
Hello @yanqi321, can you share how you resolved this problem ?

**Comment by skairali** [comment]
@yanqi321  how did you solve this?

**Comment by MayankMoonfrog** [comment]
@yanqic Can you please tell how did you solve this?
