### ISSUE TITLE
Feature Request - implement support for Exactly-Once-Semantics

### ISSUE THREAD

**Issue by TatyanaBol** [Blizzard/node-rdkafka#582]
Please implement support for Exactly-Once-Semantics according to changes in librdkafka: https://github.com/edenhill/librdkafka/issues/1308 
It will be released in the nearest future.

**Comment by TatyanaBol** [comment]
Idempotent producer was released:
https://github.com/edenhill/librdkafka/releases/tag/v1.0.0
Please implement it in **node-rdkafka**

**Comment by cfinkenstadt** [comment]
Supported by #596

**Comment by giri-jeedigunta** [comment]
Any progress on this? I'm looking to implement Exactly-Once-Semantics as introduced in Apache Kafka 0.11.0. More ref: https://www.confluent.io/blog/transactions-apache-kafka/#:~:text=Why%20Transactions%3F,known%20as%20stream%20processing%20applications.
