### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by bobzsj87** [Blizzard/node-rdkafka#586]
**Environment Information**
 - Node docker (debian): 
 - Node 10.13:
 - node-rdkafka version 2.6.1

**Additional context**
We switched from node-kafka to node-rdkafka and the task (running on AWS ECS) will stop just after some time and nothing else happened. No logging, the express server still accepts requests but just block everything.

![image](https://user-images.githubusercontent.com/568939/54881423-151bbb80-4e50-11e9-82e9-8e2fc88a5449.png)
We identified the memory problem after a while. You can see that before Mar.18, it was with node-kafka. We only touched the kafka related library. And everytime the service was restarted, the memory goes back to lowerest.

**Comment by laurynasra** [comment]
It seems that we are having a similar issue. @bobzsj87 did you manage to find a reason behind this?

**Comment by bobzsj87** [comment]
@laurynasra nope. We switched to Kafkajs and were happy ever since.
