### ISSUE TITLE
stats committed-offset -1001

### ISSUE THREAD

**Issue by th3nu11** [Blizzard/node-rdkafka#589]
Environment Information

OS [e.g. Mac, Arch, Windows 10]: Docker image, from ubuntu:16.04
Node Version [e.g. 8.2.1]:v8.15.0
NPM Version [e.g. 5.4.2]: 6.4.1
node-rdkafka version 2.5.1
3 brokers, 3 zookeepers

I have a consumer that already consumed all messages. I restart it and these are the stats of a partition. There aren't new messages.

Why committed_offset is -1001? Should it be equal to hi_offset/next_offset?
From documentation

> committed_offset | int gauge |   | Last committed offset

`
app_offset: -1001
commited_offset: -1001
committed_offset: -1001
consumer_lag: 3644684
desired: true
eof_offset: 3643683
fetch_state: "active"
fetchq_cnt: 0
fetchq_size: 0
hi_offset: 3643683
leader: 0
lo_offset: 3643683
msgq_bytes: 0
msgq_cnt: 0
msgs: 0
next_offset: 3643683
partition: 0
query_offset: -1
rx_ver_drops: 0
rxbytes: 0
rxmsgs: 0
stored_offset: -1001
txbytes: 0
txmsgs: 0
unknown: false
xmit_msgq_bytes: 0
xmit_msgq_cnt: 0
`
thanks

**Comment by jeeteshchel** [comment]
Hello, I am facing similar issue, can anyone help to explain why commited_offset is -1001?
