### ISSUE TITLE
node-rdkafka cannot be installed on windows 10

### ISSUE THREAD

**Issue by fungiboletus** [Blizzard/node-rdkafka#591]
**Environment Information**
 - OS: Windows 10
 - Node Version: 10.14.0
 - NPM Version: 6.1.0
 - C++ Toolchain: Visual Studio
 - node-rdkafka version: 2.6.1

**Steps to Reproduce**

`npm install node-rdkafka`

```
node_modules\nan\nan.h(1674): note: see declaration of 'Nan::Callback::Call' (compiling source file ..\src\connection.cc)
..\src\callbacks.cc(275): error C2589: '(': illegal token on right side of '::' [stuff\node_modules\node-rdkafka\build\node-librdkafka.vcxp
roj]
..\src\callbacks.cc(275): error C2059: syntax error: '::' [stuff\node_modules\node-rdkafka\build\node-librdkafka.vcxproj]
```
**Additional context**

It's a bit sad.

**Comment by fungiboletus** [comment]
It's similar to #487 (which is closed but not fixed) with a different error.

**Comment by terebentina** [comment]
@fungiboletus I don't think it's similar to that other issue. For the issue you're having see my PR here: https://github.com/Blizzard/node-rdkafka/pull/585 . It's a really quick fix.

**Comment by jomaleda** [comment]
Do we have any update on this issue? I have problems with version 2.6.1 of node-rdkafka on Windows 10 too.

**Comment by kowalej-homex** [comment]
Same issue over here. I also get a bunch of compilation errors with the new 2.7.0 version. 2.5.1 worked fine.

**Comment by iradul** [comment]
`2.7.1` installs fine on Windows. Please reopen if you're still having issues.
