### ISSUE TITLE
Update to librdkaka 1.0

### ISSUE THREAD

**Issue by codeburke** [Blizzard/node-rdkafka#596]
Just a placeholder Issue for upgrading node-rdkafka to librdkafka 1.0. Librdkafka contains quite a few new features including idempotent Producer support and ZStandard compression.

~From what I can see there shouldn't be any node-binding updates required.~ (See Magnus comment) I'll start working on a PR to get this in.

Librdkafka 1.0 Release Notes:
https://github.com/edenhill/librdkafka/releases/tag/v1.0.0

**Comment by edenhill** [comment]
You will want to add support for fatal errors, if nothing else at least the rd_kafka_fatal_error() API.
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#fatal-errors

**Comment by dnwe** [comment]
@codeburke have you started on this and do you have a working branch for this PR?
