### ISSUE TITLE
Throttle - Consume messages one by one

### ISSUE THREAD

**Issue by vykimo** [Blizzard/node-rdkafka#603]
Hello, I've a question :
Is this possible with this implementation of Kakfa to process message one by one (or more) ?
A way to makes Kafka act like with a throttle.

Thank you in advance for your answer 👍

**Comment by codeburke** [comment]
There are at least a few ways to handle this:
1. Using the Consumer API, you can `consumer.consume(1, cb);` to consume 1 message and then pass it to the `cb()` function for processing. As long as you are careful with any async tasks (using async/await can help) then you should be guaranteed to only be processing 1 thing at a time.
2. Using the ConsumerStream you can write a `Transform` stream and `pipe()` from the ConsumerStream -> Transform stream. Kafka stream processing plugs into Node Streams with little effort and you get that per topic-partition ordering guarantee. But similar to #1, take care to make sure that you flow control accounts for async operations.
3. Plug into another streaming API like `rxjs`. It takes a little bit of work to get a Node Stream into an RX Stream, but once you do there is a rich API of stream operations functions to help process, merge, split, replay, throttle, etc your stream of data.

Hope this helps!

**Comment by aadii104** [comment]
Hi @codeburke ,
Thanks for your solution, can u please provide a minimal example for your **point #1**?
It will be helpful.
