### ISSUE TITLE
Key value store thoughts

### ISSUE THREAD

**Issue by useminmin** [Blizzard/node-rdkafka#604]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: 
 - Node Version [e.g. 8.2.1]:
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]:

**Additional context**
We have a topic with multiple partitions. And push data to each partition by a key.  
We want to use kafka as a key value store.

Take one example. Total 15 partition when created the topic.
And partition 3 has 8 messages. 
partition 7 has 2 messages.
All rest are empty by now.

What we want to do is to build the key value store by getting the last message for each partition:
**a. get the last message from each partition which includes none empty messages at this time 
b. and then quick return no need to wait to consumer any new messages.**

How can we configure the settings to do this? 
I set auto.commit.reset to latest  doesn't work as expected since it only focus on the new messages. 

Please advise!

**Comment by codeburke** [comment]
Not sure if Kafka is the right tool for you here. You are looking for a LIFO (last in first out) queue by the sounds of it, while Kafka is built around an append-only log that is FIFO (with per consumer offset tracking). 

I've never actually done this, but it appears that you could use `consumer.seek(toppar)` where toppar is
```
{
    topic: "<topic>",
    partition: <partition int>,
    offset: 'latest'
}
```
Once `seek()` returns (it is an async function with a callback) then you could do a `consumer.consume(1);` to read just one message. After processing that message then you'd need to do the seek-to-latest again for that topic-partition before consuming another message.

That should get you pretty close to the latest message per topic-partition, curious if you've tried anything like that yet.

**Comment by useminmin** [comment]
Thanks @codeburke. Not yet.

Is there any retention setting for each partition to make sure there is only 1 message left for each partition? If so, we don't need to seek the offset and seek back.

Also, any api to get all the partition indices?

**Comment by codeburke** [comment]
Kafka has per-topic retention but it is based on time, not # of messages. I'm not sure of a way to get just 1 message in a topic-partition. 

You should be able to get the list of topic/partitions by using `getMetadata()` and then `offsetsForTimes()` for each topic-partition using `latest` as the `offset`.
