### ISSUE TITLE
No "enable.idempotence" support?

### ISSUE THREAD

**Issue by viniciusbo** [Blizzard/node-rdkafka#611]
Trying to achieve "exactly-once" write for producers using `enable.idempotence` and `transactional.id`, with the following piece of code:

```js
const producer = new Kafka.Producer({
    // ...
    'enable.idempotence': true,
    'transactional.id': 'prod-1',
  });
```

Raises this error:

```
Error: No such configuration property: "enable.idempotence"
```

Isn't `enable.idempotence` and `transactional.id` settings supported?

**Comment by GeoffreyHervet** [comment]
@viniciusbo which version of `node-rdkafka` are you using ?

**Comment by viniciusbo** [comment]
2.6.1

Em sáb, 29 de jun de 2019 às 06:04, Geoffrey Hervet <
notifications@github.com> escreveu:

**Comment by GeoffreyHervet** [comment]
`enable.idempotence` will be support in the next release of `node-rdkafka` (it's due to the librdkafka version)
