### ISSUE TITLE
Error "make failed with exit code 2 node-rdkafka"

### ISSUE THREAD

**Issue by owitiA** [Blizzard/node-rdkafka#613]
Hello been getting this error when trying to npm install 

```gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/owitia/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/home/owitia/.nvm/versions/node/v8.9.1/bin/node" "/home/owitia/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node_modules//node_modules/node-rdkafka
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```
kindly help with a fix 
using Ubuntu 16.04

**Comment by ivomirra** [comment]
@owitiA Did you fix this problem?

**Comment by owitiA** [comment]
i think so, got a way to work around it

**Comment by unfrgivn** [comment]
Care to share @owitiA? I am running into the same issue with node 10.16 on OS X

**Comment by ivomirra** [comment]
@unfrgivn did you tried to implemented a docker with the node 8.0.0 version?

**Comment by MidnightP** [comment]
Any solution?

**Comment by unfrgivn** [comment]
@MidnightP what system are you running on? If OS X see the README of this repo. I am running fine on Mojave and a Docker image built off `node:10-alpine`

**Comment by MidnightP** [comment]
@unfrgivn running Ubuntu 18.04

I created a separate issue with more specifics here: https://github.com/Blizzard/node-rdkafka/issues/694
