### ISSUE TITLE
Partitioning is not same as kafka-console-producer, or other libs

### ISSUE THREAD

**Issue by tcollinsworth** [Blizzard/node-rdkafka#616]
**Environment Information**
 - OS: Ubuntu 14.04 LTS 64-bit
 - Node Version: v10.15.3
 - NPM Version: 6.9.0
 - C++: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
 - node-rdkafka version: node-rdkafka@2.5.1

**Steps to Reproduce**

create a topic with 10 partitions
use kafka-console-producer to produce a message with a key and consume from the various partitions to see on which partition it was published, or use your awesome kafkacat tool

**kafka-console-producer, no-kafka, murmur2-partitioner**
key = '354afe16-939a-4ea8-8e17-8bb0840b6886', partition = 4
key = 'f562ac3b-2224-4e25-a0ab-56094e10c239', partition = 5

**node-rdkafka**
key = '354afe16-939a-4ea8-8e17-8bb0840b6886', partition = 9
key = 'f562ac3b-2224-4e25-a0ab-56094e10c239', partition = 6

```
rdkafkaProducer.produce(
        topic,
        null, // partition, defaults to -1, default kafka behavior
        Buffer.from(mesgValue),
        key, // partition key
        Date.now(),
        ackKey, // ack unique key returned in delivery report
      )
```

**node-rdkafka Configuration Settings**

```
  {
     'metadata.broker.list': '127.0.0.1:9092',
     'message.timeout.ms': 10100,
     dr_cb: true,
     event_cb: true,
  }
```

**Additional context**

The node-kafka lib is not producing the same partitions for a key as kafka-producer, npm lib murmur2-partitioner, and no-kafka.

We have multiple microservices by different teams with different libs and different languages. The consumers rely on consistent partitioning for cache efficiency and correct processing order. Messages from different publishers with the same key are not on the same partition and not being processed in the correct order and cause excessive cache misses and flushing.

A temporary workaround might be to use a custom partitioner and the npm murmur2-partitioner lib since that seems to work the same as the kafka and no-kafka libs.

murmur2-partitioner [partitioner impl](https://github.com/vuza/murmur2-partitioner/blob/master/index.js)

[kafka (java) common utils partitioner impl](https://github.com/apache/kafka/blob/1.0.0/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L353)

node-kafka [librdkafka partitioner impl](https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/src/rdmurmur2.c)

**Comment by tcollinsworth** [comment]
My associate believes the librdkafka murmur2 implementation linked above is the culprit.

**Comment by tcollinsworth** [comment]
I've implemented the temporary workaround using the murmur2-partitioner to override the partition on keyed messages when publishing to node-rdkafka until the underlying libraries are fixed.

**Comment by edenhill** [comment]
Set the `partitioner` configuration value to `murmur2_random` for a java producer compatible partitioner.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2273
