### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by ivomirra** [Blizzard/node-rdkafka#617]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: 
 - Node Version [e.g. 8.2.1]:
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]:

**Steps to Reproduce**
Simply tried to npm install it.

Already did what the latest README suggests

**node-rdkafka Configuration Settings**

> node-rdkafka@2.6.1 install /Users/ivomirra/Documents/Huub Software/huub-public-gateway/node_modules/node-rdkafka
> node-gyp rebuild

  ACTION deps_librdkafka_gyp_librdkafka_target_configure deps/librdkafka/config.h
/bin/sh: Software/huub-public-gateway/node_modules/node-rdkafka/build/Release/lib.host:/Users/ivomirra/Documents/Huub: No such file or directory
Unknown non-option argument: Software/huub-public-gateway/node_modules/node-rdkafka/build/deps
Usage: ./configure [OPTIONS...]

 mklove configure script - mklove, not autoconf
 Copyright (c) 2014-2015 Magnus Edenhill - https://github.com/edenhill/mklove

 librdkafka - The Apache Kafka C/C++ library
 Copyright (c) 2012-2015 Magnus Edenhill

Standard options:
   --prefix=PATH                        Install arch-independent files in PATH [/usr/local]
   --exec-prefix=PATH                   Install arch-dependent files in PATH [$prefix]
   --bindir=PATH                        User executables [$exec_prefix/bin]
   --sbindir=PATH                       System admin executables [$exec_prefix/sbin]
   --libexecdir=PATH                    Program executables [$exec_prefix/libexec]
   --datadir=PATH                       Read-only arch-independent data [$prefix/share]
   --sysconfdir=PATH                    Configuration data [$prefix/etc]
   --sharedstatedir=PATH                Modifiable arch-independent data [$prefix/com]
   --localstatedir=PATH                 Modifiable local state data [$prefix/var]
   --libdir=PATH                        Libraries [$exec_prefix/lib]
   --includedir=PATH                    C/C++ header files [$prefix/include]
   --infodir=PATH                       Info documentation [$prefix/info]
   --mandir=PATH                        Manual pages [$prefix/man]

Configure tool options:
   --list-modules                       List loaded mklove modules
   --list-checks                        List checks
   --fail-fatal                         All failures are fatal
   --no-cache                           Dont use or generate config.cache
   --debug                              Enable configure debugging
   --clean                              Remove generated configure files
   --reconfigure                        Rerun configure with same arguments as last run
   --no-download                        Disable downloads of required mklove modules
   --update-modules                     Update modules from global repository
   --repo-url=URL_OR_PATH               Override mklove modules repo URL [http://github.com/edenhill/mklove/raw/master]
   --help                               Show configure usage
   --program-prefix=PFX                 Program prefix

Compatibility options:
   --enable-maintainer-mode             Maintainer mode (no-op)
   --disable-maintainer-mode            Maintainer mode (no-op)
   --disable-dependency-tracking        Disable dependency tracking (no-op)
   --disable-silent-rules               Verbose build output (no-op)

Cross-compilation options:
   --host=HOST                          Configure to build programs to run on HOST (no-op)
   --build=BUILD                        Configure for building on BUILD (no-op)
   --target=TARGET                      Configure for building cross-toolkits for platform TARGET (no-op)

Compiler options:
   --cc=CC                              Build using C compiler CC [$CC]
   --cxx=CXX                            Build using C++ compiler CXX [$CXX]
   --arch=ARCH                          Build for architecture [x86_64]
   --cpu=CPU                            Build and optimize for specific CPU [generic]
   --mbits=BITS                         Machine bits (32 or 64)
   --CFLAGS=CFLAGS                      Add CFLAGS flags
   --CPPFLAGS=CPPFLAGS                  Add CPPFLAGS flags
   --CXXFLAGS=CXXFLAGS                  Add CXXFLAGS flags
   --LDFLAGS=LDFLAGS                    Add LDFLAGS flags
   --ARFLAGS=ARFLAGS                    Add ARFLAGS flags
   --pkg-config-path=EXTRA_PATHS        Extra paths for pkg-config
   --enable-profiling                   Enable profiling
   --enable-static                      Enable static linking
   --disable-optimization               Disable optimization flag to compiler [n]
   --disable-debug-symbols              Disable debugging symbols [n]
   --enable-werror                      Enable compiler warnings as errors [n]

Development options:
   --enable-devel                       Enable development asserts, checks, etc [n]
   --disable-devel                      Disable development asserts, checks, etc
   --enable-valgrind                    Enable in-code valgrind suppressions [n]
   --disable-valgrind                   Disable in-code valgrind suppressions
   --enable-refcnt-debug                Enable refcnt debugging [n]
   --disable-refcnt-debug               Disable refcnt debugging
   --enable-sharedptr-debug             Enable sharedptr debugging [n]
   --disable-sharedptr-debug            Disable sharedptr debugging

Feature options:
   --enable-lz4                         Enable external LZ4 library support [y]
   --disable-lz4                        Disable external LZ4 library support
   --enable-ssl                         Enable SSL support [y]
   --disable-ssl                        Disable SSL support
   --enable-sasl                        Enable SASL support with Cyrus libsasl2 [y]
   --disable-sasl                       Disable SASL support with Cyrus libsasl2

Honoured environment variables:
  CC, CPP, CXX, CFLAGS, CPPFLAGS, CXXFLAGS, LDFLAGS, LIBS,
  LD, NM, OBJDUMP, STRIP, PKG_CONFIG, PKG_CONFIG_PATH,
  STATIC_LIB_<libname>=.../libname.a

make: *** No rule to make target `../deps/librdkafka/config.h', needed by `11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ivomirra/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/ivomirra/.nvm/versions/node/v10.15.1/bin/node" "/Users/ivomirra/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ivomirra/Documents/Huub Software/huub-public-gateway/node_modules/node-rdkafka
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN huub-public-gateway@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ivomirra/.npm/_logs/2019-05-13T14_06_57_373Z-debug.log

**Additional context**

**Comment by BernhardRode** [comment]
Same issue

**Comment by MidnightP** [comment]
Any known solution?
