### ISSUE TITLE
consumer.disconnect not working properly?

### ISSUE THREAD

**Issue by netofri** [Blizzard/node-rdkafka#623]
**Environment Information**
 - OS [Windows 10]: 
 - Node Version [e.g. 10.15.0]:
 - NPM Version [e.g. 6.4.1]:
 - node-rdkafka version [e.g. 2.5.1]:

**Steps to Reproduce**

1. Start up a consumer
2. Call `disconnect`
3. On the kafka server itself run a describe command for this consumer group:
`$ ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group my-group`

The group will still be listed as if it is currently consuming when in face it isn't.
It takes 30 seconds **exactly** until the describe command will show no consumer, this seems like the timeout duration of the Kafka server itself against a non-responsive consumer.

Compared with a Kafka Console Consumer, killing the console consumer and running describe directly after, will show that there are no consumers, as it should.
Also, the [`kafka-node`](https://github.com/SOHU-Co/kafka-node) library functions properly as well, without the 30 seconds delay.

This is inconvenient because during these 30 seconds I cannot, for example, run a reset offsets command for this consumer, as it is listed as active.

```ts
const consumer = new Kafka.KafkaConsumer({
	'metadata.broker.list': 'localhost:9092',
	'group.id': 'my-group',
	'client.id': 1337,
	'fetch.wait.max.ms': 100,               // Default
	'fetch.message.max.bytes': 1024 * 1024, // Default
	'enable.auto.commit': false,
	'rebalance_cb': true
}, {'auto.offset.reset': 'smallest'});

// Call disconnect
consumer.disconnect(() => {
        // This callback will execute without issues
	console.log('Disconnected kafka consumer');
});
```
**node-rdkafka Configuration Settings**

**Additional context**

**Comment by harleynuss** [comment]
This is probably being caused by a bug in the version of librdkafka that this is using. 
 https://github.com/edenhill/librdkafka/issues/2040.
