### ISSUE TITLE
Feature Request -- Maybe we should publish prebuilt binary by using node-gyp-pre

### ISSUE THREAD

**Issue by k7** [Blizzard/node-rdkafka#624]
Building the binary every time in CI system is a little waste and slow, so maybe publish prebuilt binary would be better.

**Comment by joelday** [comment]
@webmakersteve Would you take a PR for this? I got it working in a fork with prebuildify, but with GitHub actions. Would require some Travis CI iteration for a PR here. Any advice, @yunnysunny?

**Comment by yunnysunny** [comment]
I think you can create a pull request first. I add the Windows binary after your pull request been accepted. @joelday

**Comment by IvanAlegre** [comment]
Any update on this?
Tried to got it working with prebuildify but no luck (sorry, first time working with bindings and native libs in node).

It would be really appreciated
