### ISSUE TITLE
Internal event implementation could block NodeJSs internal event loop

### ISSUE THREAD

**Issue by HenryKellner** [Blizzard/node-rdkafka#625]
**Environment Information**
 - OS Windows 10: 
 - Node Version: 10.15.3
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: VisualStudio 2017
 - node-rdkafka version [e.g. 2.3.3]: 2.6.1

**Steps to Reproduce**
start more than 4 consumers

**Additional context**
I made a script which tryed to start 6 consumers, but after the first 4, the consumer.connect callback was never called. After days of investigation of NodeJS and C++ code, i have found out that the "node-librdkafka.node" dll is using uv_queue_work() to queue tasks like connecting and waiting for kafka events. This will block the Nodes own internal event loop which seems to have a default of 4 threads. So after trying to start more than 4 blocking things in the "node-librdkafka.node" dll, the whole internal Node loop will block, and no more callbacks will be called. I Think this has to be redesigned, the libuv loop must not be blocked with workers like KafkaConsumerConsumeLoop,KafkaConsumerConsumeNum or even KafkaConsumerConsume, otherwise it may occure that the event loop will be completely blocked or at least very slow!

**Comment by subk** [comment]
Did you try adjusting libuv thread pool size by setting the [UV_THREADPOOL_SIZE](http://docs.libuv.org/en/v1.x/threadpool.html) environment variable ?

**Comment by HenryKellner** [comment]
Yes it works, ths is a possible workaround

**Comment by chadmott** [comment]
We saw this exact same behavior in our app, though I could not articulate it as well as @HenryKellner ... we refactored the app to use one consumer and things were considerably faster. Might consider adding this to the docs to help others with this same problem

**Comment by iradul** [comment]
With a single consumer, you can consume multiple topics at the same time unless of course these topics are located on different clusters. Then when you receive a message you can check what topic it belongs to and continue your business logic based on that.
One thing to be aware of is that you will use the same group id across all those topics.
