### ISSUE TITLE
Get consumer partition

### ISSUE THREAD

**Issue by sneerin** [Blizzard/node-rdkafka#633]
I want to put partition of the consumer into the header of producer, so that message produced by producer returns to the consumer that runs on the same machine. What are the best options for that? 
Spring Kafka implementation defines this header like this, what's the easiest option to be on par with that : https://docs.spring.io/spring-kafka/api/org/springframework/kafka/support/KafkaHeaders.html

**Comment by iradul** [comment]
I'm not sure what you're trying to achieve but headers are supported with the latest version. Check out [Producer example](https://github.com/Blizzard/node-rdkafka/blob/master/examples/producer.md) for more details.
