### ISSUE TITLE
Rebalancing a consumer stream and ignoring old buffered messages

### ISSUE THREAD

**Issue by ajwootto** [Blizzard/node-rdkafka#638]
Hi,

I was hoping for clarification on what happens to buffered messages in the case where I am managing offsets manually, using the KafkaConsumerStream class, and a rebalance occurs.

From my understanding, the stream is always fetching messages and storing them in the internal stream buffer until a rebalance forces consumption to stop. At that point, there would still be messages from the previous generation stored in the stream buffer. Would these then be emitted to my consumer once the rebalance completes (or even before it completes), thus potentially violating the new partition assignments and processing messages from the previous generation? 

I'm trying to figure out how best to clear out and finish processing any messages from the previous generation before allowing a rebalance to complete, using the rebalance_cb. Any advice is appreciated.

Thanks.

**Comment by Patafix** [comment]
I find this : 
https://github.com/edenhill/librdkafka/issues/1977

But in my observation, the stream will get the old messages.
