### ISSUE TITLE
consume error: Broker transport failure

### ISSUE THREAD

**Issue by quyuyue** [Blizzard/node-rdkafka#640]
got the following error when KafkaConsumer was ready to consume:
```
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
```
guessing the error is caused by using librdkafka version 0.11.6, update a release of version 1.0.1 may help.

**Comment by ankon** [comment]
> guessing the error is caused by using librdkafka version 0.11.6, update a release of version 1.0.1 may help.

Why do you think that? Are you suspecting a particular fix in that version would have prevented this error?

With just that error message there is really not much to go with unfortunately, can you elaborate a bit more about the context in which you get this?

**Comment by sneerin** [comment]
I'm also having this in production, I'm doing tons of workarounds, none of them are perfect since someone is using this issue in production, is there any best practice of reconnecting?

**Comment by sneerin** [comment]
by the way 1.0.1 version in master 2.7.0-2 version, but not in master, how production ready is it?
