### ISSUE TITLE
Local: No offset stored

### ISSUE THREAD

**Issue by jacob-bennett** [Blizzard/node-rdkafka#646]
When running a high volume of data through kafka, using the standard consumer API, my service will eventually hit the "Local: No offset stored" error.

This only happens on version 2.7.0.
I have tested on version 2.5.1 and this issue does not occur.

I wonder if the cause could be similar to https://github.com/confluentinc/confluent-kafka-python/issues/71

**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: 
 - Node Version [e.g. 8.2.1]:
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]:

**Steps to Reproduce**

**node-rdkafka Configuration Settings**

**Additional context**

**Comment by jacob-bennett** [comment]
Turns out this is an error on my part, closing issue, thanks for the great work team!

**Comment by pranaygp** [comment]
@jacob-bennett what was the error on your part?

**Comment by zenweasel** [comment]
We are running into this in production and I would love to know what the solution here was

**Comment by jacob-bennett** [comment]
@pranaygp @zenweasel It happens when commit is called without actually having anything to commit.

Turning on autocommit can help, or just making sure that commit is only called when something has actually been produced (and then ensuring that autocommit is actually switched off).
