### ISSUE TITLE
HighLevelProducer: Support custom headers

### ISSUE THREAD

**Issue by alkiskal** [Blizzard/node-rdkafka#648]
Is there a reason that the HighLevelProducer doesn't support custom headers?

**Comment by bojanrajkovic** [comment]
I was about to hack this in, but it would be a breaking API change, unless you add the headers parameter _after_ the callback, which would look weird. :-/

**Comment by alkiskal** [comment]
Yes... You could track the arguments length and come up with a hackish way to handle the old invocation as well, but I wouldn't go this way. Another way would be to make the last argument either the callback or an object, which will contain the callback and the headers. In general there is no best way at this point. But being able to set custom headers is important IMHO.

**Comment by priyabratap** [comment]
@alkiskal  I am looking for the same, to pass custom headers. Sorry I did not completely understand your comments. Could you please give some example with sample code?
