### ISSUE TITLE
node:8.16-alpine and node-rdkafka 2.x are not compatible

### ISSUE THREAD

**Issue by IdanAdar** [Blizzard/node-rdkafka#649]
@webmakersteve 

This has in fact started with node:8.15-alpine, which is based on Alpine 3.9 rather than Alpine 3.8. This seems to happen with 2.3.2 up to 2.7.0, but might just be with any version of node-rdkafka. Note that if I switch back to node:8.13-alpine, then it works...

I am not sure where it is breaking, as the `npm install` passes successfully, or so I think.
This is the log during the `npm install` that takes place in the Dockerfile, perhaps someone can spot something wrong happening? https://pastebin.com/nyWBTkRJ

This is our base image, which provides required packages for rdkafka:
It follows the suggested setup: https://github.com/Blizzard/node-rdkafka/blob/master/examples/docker-alpine.md

**myBaseImage**
```
FROM node:8.16-alpine

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash
```

It is later used in other images, like so: 
```
FROM myBaseImage

# Create app directory
RUN mkdir -p /usr/src/app
RUN mkdir temp

# Copy package.json first to check if an npm install is needed
COPY .npmrc /temp
COPY package.json /temp
RUN cd temp && npm install --production
RUN cp -a /temp/node_modules /usr/src/app

# Bundle app source
COPY . /usr/src/app

WORKDIR /usr/src/app

ENV PORT 8080
EXPOSE 8080

# Run as non-root
RUN chmod -R 775 /usr/src
RUN addgroup -g 1001 -S appuser && adduser -u 1001 -S appuser -G appuser
RUN chown -R appuser:appuser /usr/src/app
USER appuser

CMD ["npm", "start"]
```

node-rdkafka is present in the package.json file:
```
...
...
"dependencies": {
    ...
    ...
    "node-rdkafka": "^2.7.0"
  },
...
```

**Comment by gregd72002** [comment]
I experience the same problem. When using node:8.13.0-alpine all work fine.
I'm using librdkafka 1.1.0.

My intuition tells me this is something to do with SSL compatibility.

**Comment by IdanAdar** [comment]
Are you using it with the latest node-rdkafka release?

**Comment by gregd72002** [comment]
I believe so:
 
```
  "name": "node-rdkafka",
  "version": "v2.7.2",
  "description": "Node.js bindings for librdkafka",
  "librdkafka": "1.1.0",
  "main": "lib/index.js",
```

**Comment by IdanAdar** [comment]
So we’re still stuck...

**Comment by gregd72002** [comment]
I've created a simple test:
https://github.com/gregd72002/node-rdkafka-test

In 8.13 it will run and the interval function. While in 8.16 it dies straight off.

**Comment by IdanAdar** [comment]
Do we have any leads here?

I know that the OpenSSL version has changed in `node:8.16-alpine` to OpenSSL 1.1.1 or so because it switched to Alpine 3.9. I hoped that 2.7.2 would've resolve this...

Do you get any errors with debug mode?

**Comment by IdanAdar** [comment]
The rdkafka developer added the following in Gitter: 

```
Hi. I know this place is for rdkafka and not node-rdkafka, but I'm out of ideas... It seems that with node:8.13-alpine all is good, but with node:8.16-rdkafka stuff break. We think it has to do with OpenSSL but it's not clear where the fault it... rdkafka, node-rdkafka, Node? I'm hoping for some community assistance here... Please see this ticket: Blizzard/node-rdkafka#649 cc: @edenhill

Magnus Edenhill @edenhill 11:00
@IdanAdar Since OpenSSL is not ABI compatible between minor versions librdkafka needs to be built using the same OpenSSL version as on the system. E.g., librdkafka built for openssl 1.0.2s will not work with openssl 1.1.0

Idan Adar @IdanAdar 11:03
Node:8:16-alpine is based on Alpine 3.9 which does support/provide OpenSSL 1.1.0 and Node supports this as well

Idan Adar @IdanAdar 11:33
Could it be that the SSL version shipped in alpine is not compatible?
```

**Comment by IdanAdar** [comment]
I asked for insight from the Alpine community and a member had this to say:

> Anyway, I was able to confirm that the segmentation fault occurs in libssl,
which is from OpenSSL. You can gain root in the test container, install gdb, and
run Node.js with gdb to get the full traceback (with `bt').

BTW, this also fails with node:10.16-slim (Ubuntu)...

**Comment by Banashek** [comment]
Not stale, still a problem.

Is there a working path for newer versions that doesn't rely on pinning against node/alpine versions that haven't received security updates?

**Comment by ScottONeal** [comment]
We also unable to to use node-rdkafka w/ Node.js > v8, however we are using feature `sasl_ssl`. Has anyone been able to use node-rdkafka using `sasl_ssl` on Node.js on 10 or 12?

**Comment by maikelmclauflin** [comment]
@ScottONeal trying to do this now. not much luck building docker container
