### ISSUE TITLE
npm install on mac os

### ISSUE THREAD

**Issue by gzunigaskyjack** [Blizzard/node-rdkafka#651]
Hello all,

I am trying to get started with this library, buy I am having issues installing it and I could not find information on this error.

I read a lot, so I have installed OpenSSL through Homebrew and I have added those exports from the README to my .bash_profile. However, installation still fails.

OpenSSL:
`gzuniga$ brew list openssl
/usr/local/Cellar/openssl/1.0.2s/.bottle/etc/ (8 files)
/usr/local/Cellar/openssl/1.0.2s/bin/c_rehash
/usr/local/Cellar/openssl/1.0.2s/bin/openssl
/usr/local/Cellar/openssl/1.0.2s/include/openssl/ (75 files)
/usr/local/Cellar/openssl/1.0.2s/lib/libcrypto.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2s/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2s/lib/engines/ (12 files)
/usr/local/Cellar/openssl/1.0.2s/lib/pkgconfig/ (3 files)
/usr/local/Cellar/openssl/1.0.2s/lib/ (4 other files)
/usr/local/Cellar/openssl/1.0.2s/share/man/ (1683 files)`

Bash profile:
`gzuniga$ cat .bash_profile 
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib`

Error:
[out.txt](https://github.com/Blizzard/node-rdkafka/files/3397839/out.txt)

Node:
 `gzuniga$ node --version
v12.6.0`

NPM:
`gzuniga$ npm --version
6.9.0
`

I also tried this:
`brew install librdkafka`

However, it did not change anything. Do I need it?

What am I missing?

Any help on this would be greatly appreciated. Thank you very much.

**Comment by fd98279** [comment]
This is probably issue with node-12.06. 
I'm trying to update from node10.4 -> node12.6. Is node12.6 supported? 

This is the error message:
4 warnings generated.
  CXX(target) Release/obj.target/node-librdkafka/src/common.o
../src/common.cc:94:46: error: no matching member function for call to 'ToString'
      v8::Local<v8::String> val = parameter->ToString();

**Comment by gzunigaskyjack** [comment]
It seems so. Downgrading my Node made the installation work. README states Node.js >=4, so I just assumed it would be fine with latest version.

**Comment by valo** [comment]
I am seeing similar issue when installing with node 12.4.0:

```
../src/producer.cc:457:46: error: no matching member function for call to 'GetOwnPropertyNames'
        v8::Local<v8::Array> props = header->GetOwnPropertyNames();
                                     ~~~~~~~~^~~~~~~~~~~~~~~~~~~
```

**Comment by senthilsivanath** [comment]
On 11.x.x version it works. But downgrading isn't an option as the electron version doesn't match against build version.

**Comment by z0r1k** [comment]
12.x support was added in PR #610 on Jul, 4th but it wasn't released because 2.7.0 contain changes only from Jul, 1st. Does anybody know when is the next release which would contain node12 support?

**Comment by ganapativs** [comment]
Release new version to support node 12.x please 🙏

**Comment by IdanAdar** [comment]
2.7.4 supports node 12

**Comment by gzunigaskyjack** [comment]
I personally dropped this library for Java's kafka-clients. Thank you everybody for you input.
