### ISSUE TITLE
2.6.1 broke Windows compatibility? (also in 2.7.0)

### ISSUE THREAD

**Issue by d-sphinx** [Blizzard/node-rdkafka#652]
Hi, it seems @2.6.1 Windows compatibility somehow broke:

![image](https://user-images.githubusercontent.com/4455753/61378490-292b7300-a8ae-11e9-9ef2-f80a8bc2fe35.png)

I am aware about Windows platform is being out of thorough support, but in 2.5.0/2.5.1 everything is OK. 2.6.0 builds successfully, too. Starting 2.6.1 we have syntax errors.

**Environment Information**
 - Windows 10
 - Node 10.16
 - NPM 6.9.0
 - Visual Studio Build Tools installed (both 2015.3 and 2017), Python 2.7.16
 - node-rdkafka version >=2.6.1

**Steps to Reproduce**
npm i

**node-rdkafka Configuration Settings**
default

**Comment by iradul** [comment]
Latest version `2.7.1` works.

**Comment by IdanAdar** [comment]
@d-sphinx can you please confirm with 2.7.4 so this ticket could be closed?
