### ISSUE TITLE
Throwing node version error

### ISSUE THREAD

**Issue by avnish-si** [Blizzard/node-rdkafka#656]
**Environment Information**
 - OS: Ubuntu
 - Node Version: 8.9.3
 - node-rdkafka version: 2.7.1

When trying to install `node-rdkfka` it's giving me below error:
`00:09:15 error node-rdkafka@2.7.1: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "8.9.3"`

**Does NodeJS dependency has changed?**
**If NodeJS dependency is `>=12.0.0`, can we use `Openssl 1.1.X` ?**
As in documentation I still see requirement `Node.js >=4`

**Comment by IdanAdar** [comment]
Supporting only Node 12 is crazy! It's not simple for everyone to simply upgrade Node like that. It needs to support at minimum Node 8. @webmakersteve

**Comment by CKarper** [comment]
Not to mention the fact that this was done as a patch release.  Bananas.

https://semver.io/

**Comment by IdanAdar** [comment]
PR to reduce it to Node 8: https://github.com/Blizzard/node-rdkafka/pull/657

**Comment by rocketraman** [comment]
Based on a blame, pull #610 introduced this field, and it seems like the authors thought it was advisory.

In the meantime, you can usually ignore this e.g. `yarn install --ignore-engines`.

**Comment by avnish-si** [comment]
`--ignore-engines` will work but for bigger projects it is a risk which you don't want to take as it will ignore for all.
