### ISSUE TITLE
Consumer not reconnecting after period of inactivity 

### ISSUE THREAD

**Issue by robty123** [Blizzard/node-rdkafka#658]
We have a consumer deployed in aws ECS running in Fargate. The consumer has been written in node JS and uses the node-rdkafka 2.7.0 node module.

When the ECS service starts up the consumer consumes messages without error. The error occurs after around 20-40 minutes of inactivity in the consumer. We receive the error below:  

Error: Local: Broker transport failure  
origin: 'local',  
message: 'broker transport failure',  
code: -1,  
errno: -1,  

The consumer fails to reconnect when we put more messages on the topic after receiving this error. See our consumer code below:.

`function createConsumer(
	bootstrapServers,
	saslUsername,
	saslPassword,
	socketIo
) {
	instrument('consumer-creating', {});

	const consumer = new Kafka.KafkaConsumer({
		'group.id': 'visitorMessageConsumerGroup',
		'bootstrap.servers': bootstrapServers,
		'enable.auto.commit': true,
		'auto.commit.interval.ms': 5000,
		'auto.offset.reset': 'latest',
		'broker.version.fallback': '0.10.0.0',
		'api.version.fallback.ms': 0,
		'socket.keepalive.enable': true,
		'sasl.mechanisms': 'PLAIN',
		'security.protocol': 'sasl_ssl',
		'sasl.username': saslUsername,
		'sasl.password': saslPassword,
		offset_commit_cb: function(err, topicPartitions) {
			if (err) {
				// There was an error committing
				console.error(err);
			} else {
				// Commit went through. Let's log the topic partitions
				instrument('committed offset', topicPartitions);
			}
		}
	});

	consumer.on('ready', function(arg) {
		console.log('consumer ready.' + JSON.stringify(arg));
		consumer.subscribe([topicName]);
		//start consuming messages
		consumer.consume();
	});

	consumer.on('data', function(m) {
		let messageObject = JSON.parse(m.value.toString());
		console.dir(messageObject);
	});

	consumer.on('disconnected', function(arg) {
		console.log('consumer disconnected. ' + JSON.stringify(arg));
	});

	consumer.on('event.error', function(err) {
		console.error('Error from consumer');
		console.error(err);
	});

	consumer.connect();
}
`

**Comment by sobolevan** [comment]
We got to the same state and as dirty workaround we added wrapper which re-initialise consumer if such error occurred.

**Comment by robty123** [comment]
Thanks. That seems like a reasonable work around. If we find a better way will let you know.

**Comment by mi2i** [comment]
I have the same state.

it seems to lose subscription when brokers transport failure.
I resolve this by unsubscribe() and subscribe() to topic.
