### ISSUE TITLE
ENOENT: no such file or directory, open '/root/.npm/node-rdkafka/2.7.0/package.tgz'

### ISSUE THREAD

**Issue by devinfgao** [Blizzard/node-rdkafka#661]
**Environment Information**
 - OS [ Centos 7 and Manjaro 18 ]: 
 - Node Version [ 6.9.5 ]:
 - NPM Version [ 3.10.10 ]:
 - C++ Toolchain [ ]:
 - node-rdkafka version [ ^2.6.1 in package.json]:

**Steps to Reproduce**
npm install

**node-rdkafka Configuration Settings**

**Additional context**
**1808 verbose addTmpTarball already have metadata; skipping unpack for node-rdkafka@2.7.1
1809 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
1810 silly cache afterAdd node-rdkafka@2.7.1
1811 verbose afterAdd /root/.npm/node-rdkafka/2.7.1/package/package.json not in flight; writing
1812 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
1813 verbose afterAdd /root/.npm/node-rdkafka/2.7.1/package/package.json written**
1814 silly rollbackFailedOptional Starting
1815 silly rollbackFailedOptional Finishing
1816 silly runTopLevelLifecycles Finishing
1817 silly install printInstalled
**1818 verbose stack Error: Error extracting /root/.npm/node-rdkafka/2.7.0/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/node-rdkafka/2.7.0/package.tgz'**
1818 verbose stack     at ReadStream.<anonymous> (/opt/node_6.9.5/lib/node_modules/npm/lib/fetch-package-metadata.js:309:10)
1818 verbose stack     at emitOne (events.js:96:13)
1818 verbose stack     at ReadStream.emit (events.js:188:7)
1818 verbose stack     at /opt/node_6.9.5/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:190:14
1818 verbose stack     at /opt/node_6.9.5/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
1818 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
1819 verbose cwd /build/target
1820 error Linux 3.10.0-957.12.2.el7.x86_64
1821 error argv "/opt/node_6.9.5/bin/node" "/usr/local/bin/npm" "install"
1822 error node v6.9.5
1823 error npm  v3.10.10
1824 error code EREADFILE
1825 error Error extracting /root/.npm/node-rdkafka/2.7.0/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/node-rdkafka/2.7.0/package.tgz'

Downloaded version 2.7.1, but trying to extract 2.7.0.

**Comment by hasnat** [comment]
try installing with 
```
"node-rdkafka": "2.6.1",
```
instead of 
```
"node-rdkafka": "^2.6.1",
```
