### ISSUE TITLE
Consumer.position() returns an empty array

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#67]
I Expected consumer.position() to return a non empty array, when connected and consuming.

However, even in a handler`consumer.on('data', function() `
when messages are being received, the array is always empty.

**Comment by webmakersteve** [comment]
I'm able to easily reproduce this, but the c++ library is reporting an empty vector, which should translate to an empty array. It looks like as far as JavaScript is concerned, it's working as intended. I'll look more into why it's receiving an empty array to begin with from the C++ side.

**Comment by edoardocomar** [comment]
fixed via #92
