### ISSUE TITLE
2.7.1-2 package on NPM contains .vscode folder making it >100MB

### ISSUE THREAD

**Issue by martinhanzik** [Blizzard/node-rdkafka#670]
https://registry.npmjs.org/node-rdkafka/-/node-rdkafka-2.7.1-2.tgz has 109MB, that's not right... previous version has 2.7MB.

**Comment by IdanAdar** [comment]
For me it weights 994mb... @webmakersteve 
<img width="1562" alt="Screen Shot 2019-08-04 at 9 11 12" src="https://user-images.githubusercontent.com/7255583/62420262-e502e580-b697-11e9-8d46-a33908a22f23.png">

**Comment by martinhanzik** [comment]
The tgz that is downloaded is roughly 100MB, unpacked about 870MB, probably 1GB when built with all the object files and libraries. 864MB of that in a .vscode folder.

**Comment by hdhruna** [comment]
As a temporary fix, I have added `RUN rm -rf /usr/local/lib/node_modules/node-rdkafka/.vscode` in  my Dockerfile

**Comment by amelialaundy** [comment]
Also experiencing this issue, makes it impossible to deploy as part of a lambda function as it blows out the size of the lambda.
![image](https://user-images.githubusercontent.com/7699279/68292891-baed0500-0084-11ea-940b-a2608d033cc5.png)

**Comment by IdanAdar** [comment]
This us resolved in 2.7.4. Issue can be closed
