### ISSUE TITLE
Docker file for base image node:12.4.0-alpine

### ISSUE THREAD

**Issue by veerugp** [Blizzard/node-rdkafka#673]
Docker file for node:8-alpine base is available [here](https://github.com/Blizzard/node-rdkafka/blob/master/examples/docker-alpine.md). Please provide working Docker file for node:12.4.0-alpine base image.

**Comment by jhartzell** [comment]
This would be great +1

**Comment by IdanAdar** [comment]
Or even Node 10.

node-rdkafka currently seems to work only up to Node 8...

**Comment by jondeandres** [comment]
@IdanAdar why you say it works only up to node8? I am starting a development with it right now and seems to work fine, except for few already open issues

**Comment by jondeandres** [comment]
I am not, but I am not using any node image but compiling node by myself

**Comment by nlhuykhang** [comment]
@IdanAdar @rclayton-the-terrible it works for me with Node 10 on Ubuntu 18.04

**Comment by rclayton-the-terrible** [comment]
> @IdanAdar @rclayton-the-terrible it works for me with Node 10 on Ubuntu 18.04

How did you do it?  Did you compile `librdkafka` with a newer version of `libssl`?

**Comment by nlhuykhang** [comment]
> > @IdanAdar @rclayton-the-terrible it works for me with Node 10 on Ubuntu 18.04
> 
> How did you do it? Did you compile `librdkafka` with a newer version of `libssl`?

I removed `libssl-dev` on Ubuntu before installing `node-rdkafka` by npm

**Comment by mariovinay-nutanix** [comment]
Was anyone able to get this to work with Node 12? @rclayton-the-terrible

**Comment by rclayton-the-terrible** [comment]
@mariovinay-nutanix I tried Node 12, but was unsuccessful.  We are using Node 10 now without issue.

**Comment by iradul** [comment]
```docker
FROM node:12-alpine

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python

WORKDIR /src
RUN npm i node-rdkafka
RUN node -v
```

**Comment by mikeTWC1984** [comment]
The solution from @iradul  works fine, even on node 14,  but keep in mind it will explode the image size (+400MB). Do it only in the intermediate container, then just copy node_modules folder to the destination image. More over remove these items, they are about 200MB, and you don't really need it
 node_modules/node-rdkafka/deps
node_modules/node-rdkafka/build/deps/*.a
You basically need 2 those 2 libraries:
librdkafka++.so
librdkafka.so
They can actually be installed from standard alpine repos.

**Comment by DanielNetzer** [comment]
@mikeTWC1984 Any chance you can share a full Dockerfile please?
Thanks.

**Comment by mikeTWC1984** [comment]
@DanielNetzer 
```Dockerfile
# build:
# docker build -t noderdkafka .

FROM node:12-alpine AS BLD

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python3

WORKDIR /src
RUN npm i node-rdkafka
RUN rm -rf node_modules/node-rdkafka/deps node_modules/node-rdkafka/build/deps/*.a


# --- main
FROM node:12-alpine 

WORKDIR /rdkafka
RUN apk add --no-cache lz4-dev cyrus-sasl
COPY  --from=BLD /src/node_modules  /rdkafka/node_modules 


# test:
# docker run -it --rm noderdkafka node -e "console.log( require('node-rdkafka').features)"
```
