### ISSUE TITLE
Idempotent producer does not seem to work with the HighLevelProducer

### ISSUE THREAD

**Issue by ajwootto** [Blizzard/node-rdkafka#675]
**Kafka Version**: 2.2.1
**Steps to Reproduce**
When using version 2.7.1-2 of the library, and enabling the idempotent producer with "enable.idempotence: true", the HighLevelProducer seems to never call its callback on the produce call, and messages are never published to the topic.

**Comment by Antti-Kaikkonen** [comment]
I had the same issue until I read the [docs](https://github.com/edenhill/librdkafka/blob/v1.1.0/CONFIGURATION.md):

> The following configuration properties are adjusted automatically (if not modified by the user) when idempotence is enabled: max.in.flight.requests.per.connection=5 (must be less than or equal to 5), retries=INT32_MAX (must be greater than 0), acks=all, queuing.strategy=fifo. Producer instantation will fail if user-supplied configuration is incompatible. 

So make sure that you are not setting max.in.flight.requests.per.connection, request.required.acks or queuing.strategy to incorrect values.
