### ISSUE TITLE
Kafka producer is not sending the message to topic and no error is thrown

### ISSUE THREAD

**Issue by dkommineni** [Blizzard/node-rdkafka#676]
Hi,
I am using "node-rdkafka": "^2.5.1", in my package.json. I think with latest minor release of node-rdkafka, my application is not able to send the messages to Kafka topic. 
I don't see any errors, from the producer when the producer sent the messages to Kafka. At the same time, I don't see the message in Kafka topic.

Once I updated my package.json to strict version "node-rdkafka": "2.5.1", I am seeing the messages being to sent kafka topic.

Has any one experienced the same issue? I am using IBM Clould Message Hub as Kafka platform.

Regards
Devaraj

**Comment by jondeandres** [comment]
I am experiencing soomething similar. Having kafka running with Docker, if I kill the container the `produce()` function still returns `(null, true)` and no error is thrown. Using version 2.7.1.

**Comment by iradul** [comment]
`produce()` will not give you an error immediately, your message will be buffered internally and `librdkafka` will try very hard to restore connection and deliver your messages, but it will eventually fail and report an error, you just need to wait long enough.

**Comment by calebebrim** [comment]
I've tryed to produce.flush() then it said that the connection was broken. I have other dockers, like kafka-ui and zookeeper on the same docker-compose with no errors. Any hint about what it might be?

**Comment by jondeandres** [comment]
@iradul I am resuming this. I'd used this configuration in the producer:

```
    'queue.buffering.max.messages': 10,
    'queue.buffering.max.kbytes': 1
```

I've killed Kafka and I received few `event.error` events related to the DNS resolution, etc... But `produce()` still doesn't raise any error and I've wait a long time. Is this a known issue? Something I might be doing wrong?

**Comment by caoanhhao** [comment]
@dkommineni if you are using Higher Level Producer. When the producer is not ready, call `produce()` will return error object and offset is undefined. Just handle error object.

```
producer.produce(topicName, null, Buffer.from('alliance4ever'), null, Date.now(), (err, offset) => {
  if (err) {
    throw err
  }
  // The offset if our acknowledgement level allows us to receive delivery offsets
  console.log(offset);
});
```
