### ISSUE TITLE
Delivery Report not working

### ISSUE THREAD

**Issue by jondeandres** [Blizzard/node-rdkafka#677]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Ubuntu 18.04
 - Node Version [e.g. 8.2.1]:
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: 
 - node-rdkafka version [e.g. 2.3.3]: 2.7.1

**Steps to Reproduce**

```
exports.producer.on('delivery-report', function(err, report) {
      console.log(`report: ${report}`);
});
```

or 

```
Kafka.Producer({
    'metadata.broker.list': config['metadata.broker.list'],
    'dr_cb': function(err, report) { console.log(report); }
  });
```

**node-rdkafka Configuration Settings**

```
function createProducer(config) {
  return new Kafka.Producer({
    'metadata.broker.list': config['metadata.broker.list'],
    'dr_cb': function(err, report) { console.log(report); }
  });
}
```

**Additional context**

I can't see in the logs any message related to the delivery report

**Comment by buinskii** [comment]
The delivery-report event is emitted when a delivery report has been found via polling.

To use this event, you must set request.required.acks to 1/0/-1 in topic configuration and dr_cb (or dr_msg_cb if you want the report to contain the message payload) to true in the Producer constructor options.

And set pool interval after connection
```
const producer = new Kafka.Producer({
    'metadata.broker.list': ...,
    'dr_cb': function(err, report) { console.log(report); }
  }, {
     'request.required.acks': 1
});
producer.setPollInterval(10);
```

**Comment by jondeandres** [comment]
Oh thanks @buinskii for clarifying,
