### ISSUE TITLE
producer acks property may not be honored

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#68]
Even when creating a producer Topic object with code like this 
```
        // Create a topic object for the Producer to allow passing topic settings
        var topicOpts = { 'request.required.acks': -1 };
        var topic = producer.Topic(topicName, topicOpts);
        console.log('Topic object created with opts ' + JSON.stringify(topicOpts));

                producer.once('delivery-report', deliveryReportListener);

                var value = new Buffer('This is a test message #' + counter);
                var key = 'key';
                counter++;
                var partition = -1;

                    producer.produce(topic, partition, value, key);
                    // Keep calling poll() to get delivery reports
```
the produce request over the wire is sending acks=1 (the default).
We also tried setting the property value as a string` '-1'` or `'all'`. No joy.

Note that the property set in code is validated, i.e. an Error is thrown if the name or value are unknown. However valid values 0 and -1 are not honored.

We could verify this enabling tracing on the broker's kafkaApi 
sample log4j conf line:
```
log4j.logger.kafka.server.KafkaApis=TRACE, requestAppender
```
sample broker log:
```
[2016-11-29 17:53:10,103] TRACE [KafkaApi-0] Handling request:{api_key=0,api_version=1,correlation_id=114,client_id=mh-node-console-sample-producer} -- {acks=1,timeout=5000,topic_data=[{topic=mh-nodejs-console-sample-topic,data=[{partition=0,record_set=java.nio.HeapByteBuffer[pos=0 lim=56 cap=56]}]}]} from connection 192.168.1.67:9092-192.168.1.67:52624;securityProtocol:PLAINTEXT,principal:User:ANONYMOUS (kafka.server.KafkaApis)
```

**Comment by edoardocomar** [comment]
Similar results using topic_opts in the Producer constructor and passing just the topicName to the produce method

**Comment by webmakersteve** [comment]
Thanks for the report. I'll take a look at this in the C++ side and see if it's anything to do with node, or potentially a bug internally in `librdkafka`.

**Comment by edoardocomar** [comment]
@webmakersteve FYI we tested with librdkafka 0.91 - using the C example included with the library - and there the setting is honored.

**Comment by edoardocomar** [comment]
@webmakersteve we found the cause for the missing conf.

our code was calling 
```
        producer.getMetadata({
        topic: topicName,
            timeout: 10000
        },function(err, metadata) {...}
```
before calling 
```
        var topicOpts = { 'request.required.acks': -1 };
        var topic = producer.Topic(topicName, topicOpts);
...
                    producer.produce(topic, partition, value, key);
```

the call to `getMetadata()` creates a librdkafka topic with a null conf 
```
RdKafka::Topic *RdKafka::Topic::create (Handle *base,
					const std::string &topic_str,
					Conf *conf,
					std::string &errstr) {
  RdKafka::ConfImpl *confimpl = static_cast<RdKafka::ConfImpl *>(conf);
```

then the subsequent `producer.Topic(topicName, topicOpts);`
called librdkafka with a non-null conf,
but librdkafka returned a cached one, the one without the acks in the config.

Should the `GetMetadata` have deleted the librdkafka topic object after having completed ?

Any other suggestions ?

**Comment by edenhill** [comment]
@edoardocomar This is somewhat defined behaviour, a topic will be stuck with the configuration provided in the first topic_new() call.

**Comment by webmakersteve** [comment]
I guess the workaround here would be to make the topic before you call `getMetadata` for that particular topic. Another option is for `getMetadata` to take a topic object instead of an entire topic name.

I worked a bit on a refactor (you can see it in its `topic-change` branch) for the way you instantiate topics. I need to do some work on topic invalidation to fix the stuck shutdown issue that can happen depending on how you scope your variables in JS, but then I'll look into merging it. 

It will allow you to get set configuration values on the provided topic config.

```js
const topic = producer.Topic('test', { 'acks': -1 });

topic.get('acks'); // -1
```

It will also show default values if you didn't specifically set one.

**Comment by edoardocomar** [comment]
Yes, the workaround is obvious, I am worried that the side effect of the invocation in the wrong order is quite subtle. 

I also like the idea of 
>`getMetadata` to take a topic object instead of an entire topic name.

but maybe documenting the side effect of the call is enough ? @webmakersteve

**Comment by edoardocomar** [comment]
@mimaison and I are happy to have this issue just documented. please see PR and you can close this one

**Comment by edenhill** [comment]
FYI: librdkafka is (very slowly) moving away from the topic_t object in favour of passing a topic_name string.
That is not to say that existing topic_t APIs will be removed (any time soon), but that new APIs will most likely take a topic name rather than an object.

**Comment by Pchelolo** [comment]
I'm experiencing the same behaviour even without calling `client.getMetadata()` explicitly but by just using an a bit modified example from the docs:
```
var producer = new Producer({
    'metadata.broker.list': 'localhost:9092',
    'dr_cb': true
}, {
    acks: -1,
    'message.timeout.ms': 10000
});
producer.connect();
producer.on('ready', function () {
    function produce() {
        console.log(producer.produce(
            'a_b_c',
            null,
            new Buffer('Awesome message ' + Math.random()),
            'Stormwind'
        ));
    }

    setInterval(function () {
        producer.poll()
    }, 500);

    producer.on('delivery-report', (err, report) => {
        if (err) {
            console.log('DELIVERY_ERR', err);
        }
        console.log('REPORT', report);
    });
    producer.on('error', (e) => console.log('ERRROR1', e));
    setInterval(produce, 1000);
});
```

I don't explicitly call the `getMetadata` although it's being called by the `client.connect` method. Still observing that the actual requests to kafka have RequiredAcks=1
