### ISSUE TITLE
Deploying node-rdkafka

### ISSUE THREAD

**Issue by gzunigaskyjack** [Blizzard/node-rdkafka#680]
I have spent two days trying to get my Kafka application deployed to Amazon Elastic Beanstalk to not avail. I seriously need some advice.

Locally, I have been using node 10.16.0 as it was the greatest node version supported by an EB environment. Everything worked fine.

When I tried to deploy my application, I received this error:
```
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/node-rdkafka/build'
  gyp ERR! System Linux 4.14.133-88.105.amzn1.x86_64
  gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v10.16.0-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /tmp/deployment/application/node_modules/node-rdkafka
  gyp ERR! node -v v10.16.0
  gyp ERR! node-gyp -v v3.8.0
  gyp ERR! not ok 
  npm WARN tu-kafka-bms-middleware@1.0.0 No repository field.

  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! node-rdkafka@2.7.0 install: node-gyp rebuild
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the node-rdkafka@2.7.0 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

So I downgraded to node 10.15.0, created a .npmrc file with unsafe-perm=true as recommended [here](https://stackoverflow.com/a/46001517/11985520) and build worked. However, I got this error: 
```
Error: Invalid value for configuration property "security.protocol"
```

That error is discussed [here](https://github.com/Blizzard/node-rdkafka/issues/178#issuecomment-391762031), so as recommended in this issue I ssh into my EC2 instance in the EB environment and run a sudo yum install openssl-devel, which worked. However, I started receiving this error:
```
{ Error: SSLv23_client_method() failed: ../deps/openssl/openssl/ssl/ssl_lib.c:2592: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers: 
    at Function.createLibrdkafkaError [as create] (/var/app/current/node_modules/node-rdkafka/lib/error.js:334:10)
    at /var/app/current/node_modules/node-rdkafka/lib/client.js:187:28
  message:
   'SSLv23_client_method() failed: ../deps/openssl/openssl/ssl/ssl_lib.c:2592: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers: ',
  code: -172,
  errno: -172,
  origin: 'kafka' }
```

So I downgraded node to 8.16.0 as mentioned in this [issue](https://github.com/Blizzard/node-rdkafka/issues/566). But now I am receiving this from my consumer in the event.error event: 
```
{ Error: Local: SSL error
  origin: 'local',
  message: 'ssl error',
  code: -1,
  errno: -1,
  stack: 'Error: Local: SSL error' }
```

And this when my consumer tries to connect:
```
{ Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/var/app/current/node_modules/node-rdkafka/lib/error.js:334:10)
    at /var/app/current/node_modules/node-rdkafka/lib/client.js:339:28
  origin: 'local',
  message: 'broker transport failure',
  code: -195,
  errno: -195,
  stack: 'Error: Local: Broker transport failure\n    at Function.createLibrdkafkaError [as create] (/var/app/current/node_modules/node-rdkafka/lib/error.js:334:10)\n    at /var/app/current/node_modules/node-rdkafka/lib/client.js:339:28' }
```

Kafka.librdkafkaVersion and Kafka.features output:
```
1.0.0-pre2
[ 'gzip',
  'snappy',
  'ssl',
  'sasl',
  'regex',
  'lz4',
  'sasl_plain',
  'sasl_scram',
  'plugins' ]
```

It is worth mentioning that this latest setup works locally just fine. I am running out of ideas here. If anyone has experienced something like this, any help would be greatly appreciate it.

Thank you very much!

**Comment by codeburke** [comment]
I might have missed it, but what version of `node-rdkafka` are you using? The latest version supports up to Node 12 now. Since it looks like you are using SSL I'd also suggest reading the `librdkafka` docs on using SSL and the configuration options for SSL:
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Can you share your Producer/Consumer config that would help.
