### ISSUE TITLE
Compile errors 'no overloaded function takes 0 arguments' in producer.cc

### ISSUE THREAD

**Issue by davydnorris** [Blizzard/node-rdkafka#683]
**Environment Information**
 - OS [Windows 10]: 
 - Node Version [12.10]:
 - NPM Version [6.11.3]:
 - C++ Toolchain [Visual Studio]:
 - node-rdkafka version [2.7.1-2]:

**Steps to Reproduce**
npm install node-rdkafka

I believe the functions are both missing Nan::GetCurrentContext() as a parameter

line 453:         v8::Local<v8::Object> header = v8Headers->Get(i)->ToObject();
line 457:        v8::Local<v8::Array> props = header->GetOwnPropertyNames();

**Comment by codeburke** [comment]
Can you please try again? Node 12 support was added with with version `2.7.4`. If you still are having problems then please reply to this Issue, otherwise feel free to Close it.

**Comment by davydnorris** [comment]
@codeburke thanks for the reminder - I literally pulled this down only three days ago to have another crack at it, and it installed with Deprecation warnings but no errors.

Haven't yet wired it up to see if it will connect or pull events but at least it's installing now!
