### ISSUE TITLE
warning Lockfile has incorrect entry for "node-rdkafka@2.7.1-2". Ignoring it.

### ISSUE THREAD

**Issue by vincent-ogury** [Blizzard/node-rdkafka#689]
**Environment Information**
 - OS: Linux (docker) / MacOSX
 - Node Version: v10.16.0
 - YARN: 1.19.0
 - node-rdkafka version [e.g. 2.3.3]: 2.7.1-2

**Steps to Reproduce**

Install the last version with yarn. It generate this lock file:
```
node-rdkafka@2.7.1-2:
  version "2.7.2"
  resolved "https://registry.yarnpkg.com/node-rdkafka/-/node-rdkafka-2.7.1-2.tgz#686626417af095fd9653d2c6e053f214408da00b"
  integrity sha512-sSpKsAGVeIn5l7Z3wNAtIP122MPK5rqgzNuRIGGwo6Z73bEoRgbjJmLhHwS8zx/lCCFYZ2YGKEnG48Ztr73XDA==
  dependencies:
    bindings "^1.3.1"
    nan "^2.14.0"
```

The version of NPM is 2.7.1-2, the version inside the package is 2.7.2.
YARN detect an error here and ignore the package.

It doesn't use the cache and each time we run yarn it reinstalls the package (and this is long because of the compilation process).

Can you deploy a version with a proper package.json version: 2.7.3 and the same version number on NPM registry?

**Comment by IdanAdar** [comment]
@iradul I believe this is resolved by now and can be closed.
