### ISSUE TITLE
unable to install on Mac Mojave

### ISSUE THREAD

**Issue by lynhnn** [Blizzard/node-rdkafka#691]
Keep getting the same error like below:

../src/producer.cc:453:59: error: no matching member function for call to 'ToObject'
        v8::Local<v8::Object> header = v8Headers->Get(i)->ToObject();
                                       ~~~~~~~~~~~~~~~~~~~^~~~~~~~
../src/producer.cc:457:46: error: no matching member function for call to 'GetOwnPropertyNames'
        v8::Local<v8::Array> props = header->GetOwnPropertyNames();
                                     ~~~~~~~~^~~~~~~~~~~~~~~~~~~
5 warnings and 2 errors generated.
make: *** [Release/obj.target/node-librdkafka/src/producer.o] Error 1
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lynhnn/flow/dcc/dcc-feed/node_modules/node-rdkafka
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by joshrichards37** [comment]
@lynhnn I had this issue, what version of Node are you running? I had to drop down to v10.14.2. Try that and it should be fine.

**Comment by rognorak** [comment]
@joshrichards37 Thank you, I had this issue and downgrading node resolved it.  Any plans to fix the compatibility with future versions of node?

**Comment by iradul** [comment]
> Any plans to fix the compatibility with future versions of node?
Can you try with the latest version `v2.7.4`?

**Comment by rognorak** [comment]
@iradul looks like its working ok with latest version, thanks

**Comment by mdchambers** [comment]
I'm getting this same or a similar error with node-rdkafka v2.7.4 and node v13.1.0. It installs correctly with v12.12.0

```
5 errors generated.
make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd <REDACTED>/node_modules/node-rdkafka
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<REDACTED>/.npm/_logs/2019-11-20T02_11_11_249Z-debug.log
```

**Comment by luxuze** [comment]
> I'm getting this same or a similar error with node-rdkafka v2.7.4 and node v13.1.0. It installs correctly with v12.12.0
> 
> ```
> 5 errors generated.
> make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
> rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> gyp ERR! System Darwin 18.7.0
> gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd <REDACTED>/node_modules/node-rdkafka
> gyp ERR! node -v v13.1.0
> gyp ERR! node-gyp -v v5.0.5
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-rdkafka@2.7.4 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-rdkafka@2.7.4 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/<REDACTED>/.npm/_logs/2019-11-20T02_11_11_249Z-debug.log
> ```

Same Error with `mdchambers`

**Comment by iradul** [comment]
Node 13 is not currently supported.

**Comment by eduardodelaguila** [comment]
This issue is happening to me with node 12.16.1 too, anyone knows how to fix it without downgrading node? Thanks!
