### ISSUE TITLE
using node-rdkafka on Ubuntu

### ISSUE THREAD

**Issue by Lingfighting** [Blizzard/node-rdkafka#692]
hi,  when the app deployed on Ubuntu began consume the message ,  it got an error: 

"fac: 'LIBSASL',
message:'[thrd:sasl_ssl://*:9093/bootstrap]:sasl_ssl://*:9093/bootstrap: No worthy mechs found'"

but the app can work and consume message on mac OS correctly.

Has any one experienced the same issue?

Can someone provide a working Dockerfile for installing on Ubuntu?

**Comment by IdanAdar** [comment]
This works for me with 2.7.4:

```

FROM node:12.13-slim
ENV NO_UPDATE_NOTIFIER true

# Install image packages.
RUN  apt-get update -qqy \
  && apt-get install -y --no-install-recommends build-essential e2fsprogs python librdkafka-dev libssl-dev ca-certificates \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/*
```

Please close the ticket if the issue is resolved.

**Comment by yaphetsglhf** [comment]
> @Lingfighting This works for me with 2.7.4:
> 
> ```
> 
> FROM node:12.13-slim
> ENV NO_UPDATE_NOTIFIER true
> 
> # Install image packages.
> RUN  apt-get update -qqy \
>   && apt-get install -y --no-install-recommends build-essential e2fsprogs python librdkafka-dev libssl-dev ca-certificates \
>   && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/*
> ```
> 
> Please close the ticket if the issue is resolved.

hey, as the dockerfile you provide, i install the lib. but some error occurs, attached below, is there something i missed? thanks.


make[2]: Leaving directory '/share/node_modules/node-rdkafka/deps/librdkafka/src-cpp'
make[1]: Leaving directory '/share/node_modules/node-rdkafka/deps/librdkafka'
  TOUCH Release/obj.target/deps/librdkafka.stamp
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
../src/binding.cc: In function 'void ConstantsInit(v8::Local<v8::Object>)':
../src/binding.cc:134:67: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarati
ons]
   exports->Set(Nan::New("errorCodes").ToLocalChecked(), errorCodes);
                                                                   ^
In file included from /root/.cache/node-gyp/12.13.1/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.1/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from /share/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/root/.cache/node-gyp/12.13.1/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/root/.cache/node-gyp/12.13.1/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/binding.cc:145:66: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarati
ons]

**Comment by sam-github** [comment]
And for the record the "errors" above aren't errors, they are warnings:

> ../src/binding.cc:145:66: ***warning:***
