### ISSUE TITLE
Installation fails: Recipe for target 'Release/obj.target/node-librdkafka/src/producer.o' failed

### ISSUE THREAD

**Issue by MidnightP** [Blizzard/node-rdkafka#694]
**Environment Information**
 - OS: Ubuntu 18.04 
 - Node Version: 12.10.0
 - NPM Version: 6.10.3
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
 - node-rdkafka version: 2.7.1-2

**Steps to Reproduce**
```npm i node-rdkafka```

**node-rdkafka Configuration Settings**
none yet

**Additional context**
```
node-librdkafka.target.mk:128: recipe for target 'Release/obj.target/node-librdkafka/src/producer.o' failed
make: *** [Release/obj.target/node-librdkafka/src/producer.o] Error 1
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory '/home/pim/.nvm/versions/node/v12.10.0/lib/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pim/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-31-generic
gyp ERR! command "/home/pim/.nvm/versions/node/v12.10.0/bin/node" "/home/pim/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pim/.nvm/versions/node/v12.10.0/lib/node_modules/node-rdkafka
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.1-2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@2.7.1-2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pim/.npm/_logs/2019-10-09T13_36_13_535Z-debug.log
```

**Comment by itcig** [comment]
Try downgrading (or using nvm) to switch to Node 10 and see if the problem persists. 

Do you have opensll installed? If not apt install that as well.

**Comment by unfrgivn** [comment]
Try downgrading (or using nvm) to switch to Node 10 and see if the problem persists.

Do you have opensll installed? If not apt install that as well.

**Comment by MidnightP** [comment]
@unfrgivn I did both, same problem persists

I did notice this:
```
checking for C compiler from CC env... failed
checking for C++ compiler from CXX env... failed
checking for librt (by pkg-config)... failed
checking for libpthread (by pkg-config)... failed
checking for libdl (by pkg-config)... failed
checking for libm (by pkg-config)... failed
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
```

Could this be related?

**Comment by MidnightP** [comment]
Yes it works, on both my laptop with Ubuntu 18 and one with Ubuntu 16

I ran:

```
sudo apt-get install libssl-dev
nvm install 10
nvm use 10
nvm alias default 10
npm i
```

**Comment by manisrivastav** [comment]
I'm on Ubuntu 20.04, node 10.15.3, npm 6.4.1, node-gyp -v v3.8.0 

g++: error: apps/appointment-center-ncal-scheduling-kpweb-bff/node_modules/kp-message-hub-connector/node_modules/node-rdkafka: No such file or directory
make: *** [node-librdkafka.target.mk:117: Release/obj.target/node-librdkafka/src/binding.o] Error 1
make: Leaving directory '/home/mani/node apps/node_modules/kp-message-hub-connector/node_modules/node-rdkafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mani/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.128-microsoft-standard
gyp ERR! command "/home/mani/.nvm/versions/node/v10.15.3/bin/node" "/home/mani/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mani/node apps/appointment-center-ncal-scheduling-kpweb-bff/node_modules/kp-message-hub-connector/node_modules/node-rdkafka
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN hystrixjs@0.2.0 requires a peer of rxjs@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apptctr-bff-kpwebncalscheduling@1.1.7 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@0.10.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-rdkafka@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mani/.npm/_logs/2020-09-11T19_02_57_657Z-debug.log

**Comment by Vidz51** [comment]
I am getting the same error with node 14. any fixes ?
