### ISSUE TITLE
How to know producer successfully send the message?

### ISSUE THREAD

**Issue by LYHuang** [Blizzard/node-rdkafka#695]
I am currently using the Standard API to produce the message.
```
const producerOptions = {
    'metadata.broker.list': 'list'
    , 'sasl.username': 'user'
    , 'sasl.password': 'password'
    , 'queue.buffering.max.ms': 10
    , 'queue.buffering.max.messages': 100
    , 'queue.buffering.max.kbytes': 10000
};

const topicOptions = {
    'request.required.acks': -1
};

let producer = new Kafka.Producer(producerOptions, topicOptions);
producer.setPollInterval(100);
producer.connect();

producer.on('ready', () => {
    setInterval(() => {
        let bufferMessage = Buffer.from(message);
        try {
            producer.produce('topic', -1, bufferMessage, null);
        } catch (err) {
           console.log(err);
        }
    })
});

producer.on('event.error', (error) => {
    console.log(error);
});
```

Is there a way to know my message successfully sending to the broker? Or I can assume once the message get produce(push to the producer internal queue), the producer will continue try to send it until it success, even it always get timeout error?

Any help will be appreciated, thanks.

**Comment by noderat** [comment]
Delivery reports and proper configuration of the acks configuration option would allow you to confirm delivery.

**Comment by codeburke** [comment]
Here is an example using the Standard API that wires up the delivery report: https://github.com/Blizzard/node-rdkafka/blob/master/examples/producer.md.The key is to pass an `opaque` value in the `produce()` call and then match it in the subsequent `delivery-report` event.

If you don't mind trading off some potential performance (I'm assuming, I haven't ran perf tests between the two options) then you can use the HighLevelProducer that provides a callback when the event is delivered to the broker. Here is an example using that API: https://github.com/Blizzard/node-rdkafka/blob/master/examples/high-level-producer.md

Hope that helps.
