### ISSUE TITLE
Segmentation fault when using ssl

### ISSUE THREAD

**Issue by CharlesWall** [Blizzard/node-rdkafka#697]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Amazon Linux (4.14.138-114.102.amzn2.x86_64)
 - Node Version [e.g. 8.2.1]: v10.16.3
 - NPM Version [e.g. 5.4.2]: 6.9.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: gcc version 7.3.1 20180712 (Red Hat 7.3.1-6) (GCC) 
 - node-rdkafka version [e.g. 2.3.3]: 2.7.1-2

**Steps to Reproduce**
use ssl to connect to an instance
```
const Kafka = require('node-rdkafka');
const uuid = require('uuid');

const config =
        { 'metadata.broker.list':
          '<broker_list>',
          'security.protocol': 'ssl',
          'client.id': uuid.v4() }

const producer = new Kafka.Producer(config);
function produce() {
        const topic = 'test-topic';
        const partition = null;
        const payloadBuffer = Buffer.from(uuid.v4());
        const key = null;
        producer.produce(
                topic,
                partition,
                payloadBuffer,
                key,
                (err, result) => console.log(err || result)
        );
}

producer.on('ready', async () => {
        console.log('ready');
        while(1) {
                produce();
                await new Promise(resolve => setTimeout(resolve, 1000));
        }

});
producer.connect();
```

```
[ec2-user@ip-xxxxxxxxxx kafka-demo]$ node example.js 
Segmentation fault
```

**node-rdkafka Configuration Settings**
{ 'metadata.broker.list':
   '<msk broker list>',
  'security.protocol': 'ssl',
  'client.id': '<uuid>',
  'fetch.wait.max.ms': 100,
  'fetch.min.bytes': 1024 }

**Additional context**
This works fine on OSX

**Comment by noderat** [comment]
Before using SSL I've found it useful to test the librdkafka.features property to see if SSL support was properly built into librdkafka as there is no warning when SSL dependencies are missing.

**Comment by jaysequr** [comment]
Check to below compatibility according to OS
==============================================
### Environment requirements for node-rdkafka installation in ubuntu OS 16.04
Node version - 8.16.2
NPM version - 6.4.1
OpenSSL version - 1.0.2g  1 Mar 2016

### Environment requirements for node-rdkafka installation in ubuntu OS 18.04
Node version - 10.11.0
NPM version - 6.4.1
OpenSSL version - 1.1.1
