### ISSUE TITLE
Not a bug but a qestion about the official  GitHub account. as I didn’t found an other place to ask it.

### ISSUE THREAD

**Issue by ytrezq** [Blizzard/node-rdkafka#698]
Are all Blizzard repositories even those from Blizzardgames in China supposed to be under this GitHub account?

Because I found https://www.wofgame.net/ which is about a game on Etherem (the cryptocurrency) which them claim is run by Blizzardgame. They even have a repository under https://github.com/blizzardgame (so not the same account).

**Comment by IdanAdar** [comment]
@iradul this is not related to doll this repo and should be closed...

**Comment by ytrezq** [comment]
Thank you.
https://github.com/blizzardgame was deleted as a result.

Too bad Blizzard doesn t have any contact method for such cases.
