### ISSUE TITLE
Not a bug but a qestion about the official GitHub account. as I didn’t found an other place to ask it.

### ISSUE THREAD

**Issue by ytrezq** [Blizzard/node-rdkafka#699]
Are all Blizzard repositories even those from Blizzardgames in china supposed to be under this GitHub account?

Because I found https://www.wofgame.net/ which is about a game on Etherem (the cryptocurrency) which them claim is run by Blizzardgame. They even have a repository under https://github.com/blizzardgame (so not the same account).

Or is it a scam?

**Comment by IdanAdar** [comment]
@iradul this is not related to doll this repo and should be closed...

**Comment by ytrezq** [comment]
@IdanAdar : but this is the only place where official Blizzard can be reached.

**Comment by Tapppi** [comment]
@ytrezq Blizzard is a big company, the one dude from Blizzard that has authored this repo most likely has never heard of anything related to what you are talking about. Github repos are not by default an "official contact" for any company.
