### ISSUE TITLE
v2.7.3 release

### ISSUE THREAD

**Issue by iradul** [Blizzard/node-rdkafka#700]
@webmakersteve since there was confusion regarding version `v2.7.2` that was published as `v2.7.1-2` (#663) and since we didn't hear from you for a few months, I decided to merge #665 that solves Node 12 incompatibility. I also fixed e2e tests, improved and fixed travis ci tests and updated librdkafka to 1.2.1 (#684).
I was hoping that travis will execute npm publish since that stage seems well defined in `.travis.yaml`. I figured that the latest tag will be used as npm version when publishing and that this tag should point to the latest commit as well to bypass `-x` version suffix (which represents the number of commits between the latest tag and the latest commit).
Finally, I decided to try to trigger npm publish by tagging the latest commit with `v2.7.3` but as I expected that didn't work. It looks like you'll again have to manually publish this version but be aware of `.vscode` (#670)

Hope this makes sense.

Update:
I fixed travis deployment stage but provided API key for NPM apparently doesn't work.
I'll now delete `v2.7.3` tag. We're stuck until @webmakersteve comes back.

**Comment by brettkiefer** [comment]
@iradul Is @webmakersteve the only one with the npm creds to release the package? If they don't have time to do it, it'd have to be a fork or at least a new package?

**Comment by iradul** [comment]
>  Is @webmakersteve the only one with the npm creds to release the package?
yes, there are some credentials in `.travis.yaml` for NPM publishing but they [don't work](https://travis-ci.org/Blizzard/node-rdkafka/jobs/599826408#L830)

**Comment by Themandunord** [comment]
Arf... I need the Node 12 compatibility. I hope someone will find a solution!

**Comment by yuu2lee4** [comment]
node12 move into LTS,we need a version to support it.

**Comment by yuu2lee4** [comment]
I tried your forked version,It likely not support node12? @iradul

**Comment by josephxsxn** [comment]
I would like to have the latest in npm as well. Cant install against node12 today easily.

**Comment by donjuandem** [comment]
Hi everybody,
just wanted to let you know, that I published a version with the node12 related fixes of this repo and fixes for some other problems I encountered:

https://www.npmjs.com/package/@circle/node-rdkafka

**Comment by yuu2lee4** [comment]
@donjuandem  @peterdemartini I tried your version,its ok installing with node 12,but cant connect to broker.

**Comment by iradul** [comment]
v2.7.3 is now published :fireworks:

**Comment by vincent-ogury** [comment]
Same issue as the 2.7.2 on the release of the 2.7.3!
Version in the package is set to "version": "v2.7.2-8".
That confuses the "yarn" package manager and lead to reinstalling every time we run a "yarn install" even if it is already there.

Can you release a 2.7.4 with package set to 2.7.4 in the package.json please?

Thanks.

**Comment by iradul** [comment]
> Same issue as the 2.7.2 on the release of the 2.7.3!
Version in the package is set to "version": "v2.7.2-8".
That confuses the "yarn" package manager and lead to reinstalling every time we run a "yarn install" even if it is already there.

This happened because the package was published manually by webmakersteve. In the publishing process, there is a script that actually updates `package.json` version number according to the latest tag and latest commit distance from this tag.

> Can you release a 2.7.4 with package set to 2.7.4 in the package.json please?

I believe he is trying to make a working npm key for us so that we can publish ourselves with Travis. Once this is ready I'll be glad to.

**Comment by yunnysunny** [comment]
@webmakersteve you can run `npm owner add iradul node-rdkafka` to give the right of publishing to iradul.

**Comment by iradul** [comment]
Kudos for @webmakersteve, Travis deploy is now working. I've released v2.7.4
