### ISSUE TITLE
Consumer data event listener causing memory leak

### ISSUE THREAD

**Issue by RaajBadra** [Blizzard/node-rdkafka#701]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Mac
 - Node Version [e.g. 8.2.1]: 10.13.0
 - NPM Version [e.g. 5.4.2]: 6.7.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: Visual Studio
 - node-rdkafka version [e.g. 2.3.3]: 2.7.0

**Steps to Reproduce**
Consume 100,000 messages using the data event listener

**Additional context**

If I produce data at a very high rate using the standard Producer API, I end up with the memory increasing really fast when I consume the messages at the same rate using the data event listener. Is there any issue with the below code ? 

    this.consumer.on('data', async (message) => {
     // Some async processing logic
    });

    Couldn't figure out exactly what causes the memory issue. Tried to remove the async 
    processing logic and just had offset printed as below, but still I see memory utilization is same. Memory is not released.

    this.consumer.on('data', async (message) => {
     // DO NOTHING. JUST PRINT THE OFFSET OF THE CONSUMED MESSAGE
    });

**Comment by skairali** [comment]
Any update on this?

**Comment by skairali** [comment]
Any update on this is highly appreciated.
