### ISSUE TITLE
event.stats in Windows

### ISSUE THREAD

**Issue by keithchew** [Blizzard/node-rdkafka#704]
Hi

I am just checking if anyone is using statistics.interval.ms to get the event.stats in Windows? I enabled this and it caused Node to crash, exiting with "exit status 3221226505"

Just wanted to know if it is working for someone else, and if so, I will dig a bit deeper into the source to track it down.

**Comment by keithchew** [comment]
I can confirm that the crash happens in src/callbacks.cc
```
    case RdKafka::Event::EVENT_STATS:
      message = event.str(); <------------- HERE
    break;
```
Any help to resolve this would be appreciated.

**Comment by gilmishal** [comment]
I can confirm that I have the exact same issue.
