### ISSUE TITLE
The version of 2.7.3 published .vscode folder to npm

### ISSUE THREAD

**Issue by yunnysunny** [Blizzard/node-rdkafka#708]
The version of 2.7.3 push .vscode to npm, the sub directory of ipch contains 800MB files.
 
We need re-publish it now, for its too slow to install node-rdkafka now.

And the version value in the `package.json`, which is `v2.7.3`, is an invalid format. The correct one is `2.7.3`. The wrong format is not recognized by yarn.

**Comment by IdanAdar** [comment]
@iradul can you please fix this and re-publish as 2.7.4?

**Comment by iradul** [comment]
I don't have publishing rights yet. Please see my comment [here](https://github.com/Blizzard/node-rdkafka/issues/700#issuecomment-553447844).

**Comment by sidswamym** [comment]
Can we release the fix immediately, please? It has completely broken our pipeline.

**Comment by iradul** [comment]
I've released v2.7.4
Kudos for @webmakersteve, Travis deploy is now working.

**Comment by IdanAdar** [comment]
Thanks @iradul!!

Going forward, can we go back to having Releases?
https://github.com/Blizzard/node-rdkafka/releases
