### ISSUE TITLE
Cannot read any messages from kafka

### ISSUE THREAD

**Issue by yura415** [Blizzard/node-rdkafka#723]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: MacOS 10.15.1 / alpine 3 (docker) 
 - Node Version [e.g. 8.2.1]: v10.16.2
 - NPM Version [e.g. 5.4.2]: 6.11.3
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: latest (2.7.4)

**Steps to Reproduce**
```js
const kafka = require('node-rdkafka');

const topic = 'testing.topic';
const config = {
  'group.id': 'testgroup',
  'metadata.broker.list': '% REMOTE KAFKA BROKER LIST%',
  'security.protocol': 'sasl_plaintext',
  'sasl.mechanism': 'PLAIN',
  'sasl.username': '% USERNAME %',
  'sasl.password': '% PASSWORD %'
};

(async () => {
  const producerStream = kafka.Producer.createWriteStream(config, {}, {
    objectMode: true
  });
  producerStream.producer.on('error', console.error);

  await new Promise((resolve, reject) => {
    producerStream.producer.once('ready', resolve);
    producerStream.producer.once('error', reject);
    producerStream.producer.connect();
  });

  for (let i = 0; i < 100; i++)
    producerStream.write({
      topic,
      value: Buffer.from(JSON.stringify({ foo: 'bar' }))
    });

  await new Promise((resolve, reject) => {
    producerStream.producer.flush(5000, err => (err ? reject(err) : resolve()));
  });

  console.log('written 100 messages');

  const consumerStream = kafka.KafkaConsumer.createReadStream(config, {
  }, {
    topics: [topic],
    objectMode: true
  });
  consumerStream.on('error', console.error);

  await new Promise((resolve, reject) => {
    consumerStream.consumer.once('ready', resolve);
    consumerStream.consumer.once('error', reject);
    consumerStream.consumer.connect();
  });

  console.log('reading...');

  consumerStream.on('data', (msg) => {
    console.log('DATA', msg);
  });
})();
```

```js
// also if you run the following you can see many `fetching` messages:
consumerStream.consumer.on('event.log', (log) => {
  process.stdout.write(`CONSUMER:${JSON.stringify(log, null, 2)}\n`);
});
```

**node-rdkafka Configuration Settings**
See above.

**Additional context**
Kafka cluster is running on AWS. Everything is working with kafka toolkit and golang libraries.

**Comment by codeburke** [comment]
You don't need the `connect()` calls for either the `producerStream` or `consumerStream`. 
See: https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer-stream.js#L116

Can you remove those blocks and see if that helps?

**Comment by tabulahussla** [comment]
@codeburke Hello. I've placed explicit `connect()` to avoid `Error: Producer not connected` error during explicit `flush()`. After that, consumer connects and hangs indefenitely.

Here is full debug log of that consumer: https://gist.github.com/tabulahussla/9d4e59f6914ae718c139bc3b24a3901c

I can read messages writen by Producer using kafkacat or similar software. Equivalent code implemented with kafka golang library just works.

**Comment by tabulahussla** [comment]
BTW Kafka version I'm using is 2.3.0

**Comment by sam-github** [comment]
@yura415 gist link above is 404
