### ISSUE TITLE
Error: Local: Timed out  are reported every few minutes after the program starts？

### ISSUE THREAD

**Issue by dinggewennuan** [Blizzard/node-rdkafka#737]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: center os
 - Node Version [e.g. 8.2.1]: 10.15.0
 - NPM Version [e.g. 5.4.2]:6.4.1
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]:2.2.0

**Steps to Reproduce**
An error will be reported every few minutes after the program starts, after which the program will continue to run
can you tell me why ?  how to solve ?
[2019-12-26 14:49:40.889] [WARN] info - userlog kafka error: { [Error: Local: Timed out]
  origin: 'local',
  message: 'timed out',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Timed out' }
[2019-12-26 14:50:41.644] [WARN] info - userlog kafka error: { [Error: Local: Timed out]
  origin: 'local',
  message: 'timed out',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Timed out' }
[2019-12-26 14:51:43.046] [WARN] info - userlog kafka error: { [Error: Local: Timed out]
  origin: 'local',
  message: 'timed out',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Timed out' }
[2019-12-26 14:52:45.061] [WARN] info - userlog kafka error: { [Error: Local: Timed out]
  origin: 'local',
  message: 'timed out',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Timed out' }
**node-rdkafka Configuration Settings**
let streamUserlog = Kafka.KafkaConsumer.createReadStream(
  {
    'metadata.broker.list': 'kafaka1:19092,kafka2:19092',
    'group.id': 'productions1223',
    'socket.keepalive.enable': true,
    'enable.auto.commit': false
  },
  {
    'auto.offset.reset': 'latest'
  },
  {
    'topics': ['xxxx']
  }
)
streamUserlog.on('data', async function (m) {
  streamUserlog.pause()
  counter++

  let userLog = JSON.parse(m.value)
  let actType = userLog.ul_actType
  let articleId = userLog.ul_targetId
  let addTime = userLog.ul_addTime
  let userId = userLog.ul_userId
  let appName = userLog.ul_appName
  let ip = userLog.ul_ip
  let strategy = userLog.ul_strategyId
  if (actType === 1000) { // view
      await stock.increaseStock(articleId, actType, addTime, userId)
  }

  if (counter % numCommit === 0) {
    streamUserlog.consumer.commit()
  }

  if (counter % numLog === 0) {
    __logger.info('userlog kafka:', 'consume message ok', 'articleId:', articleId, 'actType:', actType, 'addTime:', addTime)
    counter = 0
  }

  streamUserlog.resume()
})

streamUserlog.on('error', function (err) {
  __logger.error(err)
  process.exit(1)
})

streamUserlog.consumer.on('event.error', function (err) {
  __logger.warn('userlog kafka error:', err)
})

**Additional context**

**Comment by khanhvu161188** [comment]
is there anyone solve this issue?
