### ISSUE TITLE
Can we really implement concurrency on topic with different partitions on same application using node-rdkafka library?

### ISSUE THREAD

**Issue by thesourabh1995** [Blizzard/node-rdkafka#739]
Scenario:

I am using **node-rdkafka library** to create an app that will do some process on the messages that it will get from consumer.

There's one particular requirement where I have to use concurrency on single topic having multiple partitions.

I have checked documentation for this process but didn't any helpful guidelines that I can use for the required result.(Or maybe I missed something.)

Question

Can we really implement concurrency on topic with different partitions on same application using node-rdkafka library and how can it be done?

Suggestions are highly appreciated.

**Comment by codeburke** [comment]
The underlying `librdkafka` threads are concurrently buffering messages from the subscribed topic-partitions and then via the exposed node-rdkafka JS bindings the data is consumed via the node-rdkafka C++ API and passed either via a callback or an EventEmitter to the JS application. Maybe that helps? If not, then can you explain what you mean by "implemented concurrency" in more detail?
