### ISSUE TITLE
timeout with consume()

### ISSUE THREAD

**Issue by coldcoff** [Blizzard/node-rdkafka#74]
Hi!

Is it also possible to build a consumer that polls for data with a timeout?

From documentation and tests I can see the infinite loop ("flowing mode") and the non flowing mode (in which a "hard" consume is called in a certain interval).

"consumer.consume" does not offer a timeout parameter, so it is blocking, right?

Is there also a possibility to use your library with a poll-like-consume like "consumer.consume(timeout)" that *might* either return a message or timeout and return null in that case?

Thanks

Tino

**Comment by webmakersteve** [comment]
`consumer.consume` is non-blocking. It has a callback that gets called after it gets its data. Unless you're talking about `librdkafka`'s consume method, which can timeout and is blocking.

What is your use case where you want to poll to consume? `Consumer.consume` already does time out if it takes too long, and returns that error if it did. You can also set this timeout duration using the hidden method, https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L98

**Comment by webmakersteve** [comment]
Closing issue. Hope I answered your question! If not, please re-open :)
