### ISSUE TITLE
Local: Not implemented Error while upgrading to Node 10.17.0

### ISSUE THREAD

**Issue by rvravi** [Blizzard/node-rdkafka#742]
Error in consuming Kafka messages for the topics TEST.TOPIC {"message":"Local: Not implemented","code":-170,"errno":-170,"origin":"kafka"}
Gettting the above error from kafka consumer using node-rdkafka version 2.7.4 0r 2.7.0 while upgrading to node version 10.17.0 from 8.15.0

**Comment by nareshrubysin** [comment]
@rvravi were you able to resolve this issue. I'm facing a similar issue with node 14.16.1, node-rdkafka 2.12.0.
`LibrdKafkaError: Local: Not implemented
    at Function.createLibrdkafkaError [as create] (/home/deploy/node_modules/node-rdkafka/lib/error.js:454:10)
    at /home/deploy/node_modules/node-rdkafka/lib/kafka-consumer.js:468:29
    at callbackTrampoline (internal/async_hooks.js:130:17) {
  code: -170,
  errno: -170,
  origin: 'kafka'
}`

**Comment by Kerkesni** [comment]
You're probably missing [librdkafka](https://github.com/edenhill/librdkafka) dependencies, you'll need to install [these](https://github.com/edenhill/librdkafka#requirements) for it to work properly.
