### ISSUE TITLE
Consuming using whitelist/blacklist?

### ISSUE THREAD

**Issue by panghalamit** [Blizzard/node-rdkafka#748]
Is it possible  for consumers to subscribe to topics using blacklist/whitelist as Kafka code allows?

**Comment by iradul** [comment]
There is `topic.blacklist` field that you should be able to pass to consumer, you can find more about it on [librdkafka config doc](https://github.com/edenhill/librdkafka/blob/v1.2.2/CONFIGURATION.md).

**Comment by panghalamit** [comment]
I want to consume using regex subscription. ? (topic.whitelist).  Since librdkafka doesn't have topic.whitelist, I should move this issue to kibrdkafka?

**Comment by panghalamit** [comment]
Closing this as you can subscribe to topic regex which is basically whitelist.
