### ISSUE TITLE
Amazon linux 2 error liblz4.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by trujillm** [Blizzard/node-rdkafka#749]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: 4.14.138-99.102.amzn2.x86_64 / Lambda AWS linux 2
 - Node Version [e.g. 8.2.1]: v10.18.1
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: gcc.x86_64 gcc-c++.x86_64 libgcc.x86_64
 - node-rdkafka version [e.g. 2.3.3]: 2.7.4

**Steps to Reproduce**
1. install node modules via npm
2. run code to connect to kafka (see snippet)

**node-rdkafka build**
[buildNode10-node-rdkafka.txt](https://github.com/Blizzard/node-rdkafka/files/4110672/buildNode10-node-rdkafka.txt)

**Error**
```
{
    "errorType": "Error",
    "errorMessage": "liblz4.so.1: cannot open shared object file: No such file or directory",
    "stack": [
        "Error: liblz4.so.1: cannot open shared object file: No such file or directory",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at bindings (/var/task/node_modules/bindings/bindings.js:112:48)",
        "    at Object.<anonymous> (/var/task/node_modules/node-rdkafka/librdkafka.js:10:32)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)"
    ]
}

```

**Comment by trujillm** [comment]
Further research:
When running this in a docker image for same Amazon linux 2 OS it seems when performing the producer.connect function it throws a segmentation fault. 

`Thread 14 "rdk:broker-1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fc246a38700 (LWP 5098)]
0x00007fc26c70d6f7 in ssl3_cleanup_key_block () from /lib64/libssl.so.10
(gdb) quit`

**Comment by julrich1** [comment]
I'm having a similar issue with SASL in Lambda. 

`2020-04-24T23:27:38.217Z	26dc202c-6bb0-4614-a42f-aa67b370ab0c	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Invalid value \"sasl_ssl\" for configuration property \"security.protocol\"",
    "stack": [
        "Error: Invalid value \"sasl_ssl\" for configuration property \"security.protocol\"",
        "    at HighLevelProducer.Client (/var/task/node_modules/node-rdkafka/lib/client.js:54:18)",
        "    at HighLevelProducer.Producer (/var/task/node_modules/node-rdkafka/lib/producer.js:75:10)",
        "    at new HighLevelProducer (/var/task/node_modules/node-rdkafka/lib/producer/high-level-producer.js:93:12)",
        "    at new BusinessEventProducer (/var/task/node_modules/@nordstrom-events/node-sdk/lib/event/producer.js:26:25)",
        "    at PreferencesEventProcessor.processEvent (/var/task/dist/PreferencesEventProcessor/PreferencesEventProcessor.js:184:26)",
        "    at Runtime.exports.processEvent [as handler] (/var/task/dist/PreferencesEventProcessor/lambda.js:9:38)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}`

**Comment by Davenporten** [comment]
Check out this thread: https://github.com/edenhill/librdkafka/issues/2937#issuecomment-644830101

As you're probably aware librdkafka is the underlying lib/tool used by node-rdkafka.
