### ISSUE TITLE
Client can't connect to AWS  MSK  with TLS  enabled

### ISSUE THREAD

**Issue by Denusdv** [Blizzard/node-rdkafka#756]
Hi All

We have the following setup

MSK on AWK with TLS enabled connectivity 

Here is the Kafka.Producer init code

            this.kproducer = new Kafka.Producer({
                    'metadata.broker.list': [".........eu-west- 1.amazonaws.com:9094",
        ".......kafka.eu-west-1.amazonaws.com:9094"],
                    'message.send.max.retries': 10,
                    'security.protocol': 'ssl',
                    'socket.keepalive.enable': true,
                    'dr_cb': true
                });

The problem I never get on.ready event meaning the producer is not able to establish the connection.
The first thought was to disable NODE_TLS_REJECT_UNAUTHORIZED=0 but it didn't help.

Also I don't see any logs from node-rdkafka to get better understanding for troubleshooting the issue.
Any idea what I'm missing or any tips how I get more logs from node-rdkafka for more details.

**Comment by enhanse** [comment]
It may be worth adding debug config to the producer `'debug': 'all'` (Look for possible values under the 'debug' global setting https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#global-configuration-properties)

Also add event callbacks for 'event.log' and 'event.error'

Alternatively, try using the Kafka cli tools on an EC2 container to check connectivity https://kafka.apache.org/quickstart
