### ISSUE TITLE
Error: /src/binding.cc:145:66: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Object>

### ISSUE THREAD

**Issue by trunganh07** [Blizzard/node-rdkafka#763]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: 
 - Node Version [e.g. 8.2.1]:
 - NPM Version [e.g. 5.4.2]:
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]:

**Steps to Reproduce**

**node-rdkafka Configuration Settings**
  ACTION deps_librdkafka_gyp_librdkafka_target_configure deps/librdkafka/config.h
checking for OS or distribution... ok (amzn)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x010202ff'... ok (1.2.2)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for c11threads (by pkg-config)... failed
checking for c11threads (by compile)... failed (disable)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for libcrypto (by pkg-config)... ok
checking for libssl (by pkg-config)... ok
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
checking for libm (by pkg-config)... failed
checking for libm (by compile)... ok
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for strndup (by compile)... ok
checking for strlcpy (by compile)... failed (disable)

**Additional context**

install librdkafka++.so.1 $DESTDIR/var/www/html/tracking-views/node_modules/node-rdkafka/build/deps && \
[ -f "rdkafka++.pc" ] && ( \
        install -d $DESTDIR/var/www/html/tracking-views/node_modules/node-rdkafka/build/deps/pkgconfig && \
        install -m 0644 rdkafka++.pc $DESTDIR/var/www/html/tracking-views/node_modules/node-rdkafka/build/deps/pkgconfig \
) && \
[ -f "rdkafka++-static.pc" ] && ( \
        install -d $DESTDIR/var/www/html/tracking-views/node_modules/node-rdkafka/build/deps/pkgconfig && \
        install -m 0644 rdkafka++-static.pc $DESTDIR/var/www/html/tracking-views/node_modules/node-rdkafka/build/deps/pkgconfig \
) && \
(cd $DESTDIR/var/www/html/tracking-views/node_modules/node-rdkafka/build/deps && ln -sf librdkafka++.so.1 librdkafka++.so)
make[2]: Leaving directory `/var/www/html/tracking-views/node_modules/node-rdkafka/deps/librdkafka/src-cpp'
make[1]: Leaving directory `/var/www/html/tracking-views/node_modules/node-rdkafka/deps/librdkafka'
  TOUCH Release/obj.target/deps/librdkafka.stamp
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
../src/binding.cc: In function ‘void ConstantsInit(v8::Local<v8::Object>)’:
../src/binding.cc:134:67: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Object>&)’
   exports->Set(Nan::New("errorCodes").ToLocalChecked(), errorCodes);
                                                                   ^
In file included from /home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:54,
                 from /var/www/html/tracking-views/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/binding.cc:145:66: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Object>&)’
   exports->Set(Nan::New("topic").ToLocalChecked(), topicConstants);
                                                                  ^
In file included from /home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:54,
                 from /var/www/html/tracking-views/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/binding.cc:148:90: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Function>)’
     Nan::GetFunction(Nan::New<v8::FunctionTemplate>(NodeRdKafkaErr2Str)).ToLocalChecked());  // NOLINT
                                                                                          ^
In file included from /home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:54,
                 from /var/www/html/tracking-views/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/binding.cc:151:98: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Function>)’
     Nan::GetFunction(Nan::New<v8::FunctionTemplate>(NodeRdKafkaBuildInFeatures)).ToLocalChecked());  // NOLINT
                                                                                                  ^
In file included from /home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:54,
                 from /var/www/html/tracking-views/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/binding.cc: In function ‘void Init(v8::Local<v8::Object>, v8::Local<v8::Object>)’:
../src/binding.cc:155:24: warning: ‘void node::AtExit(void (*)(void*), void*)’ is deprecated: Use the three-argument variant of AtExit() or AddEnvironmentCleanupHook() [-Wdeprecated-declarations]
   AtExit(RdKafkaCleanup);
                        ^
In file included from ../../nan/nan.h:54:0,
                 from /var/www/html/tracking-views/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:712:22: note: declared here
     NODE_EXTERN void AtExit(void (*cb)(void* arg), void* arg = nullptr));
                      ^
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:107:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../src/binding.cc:163:64: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>)’
       Nan::New(RdKafka::version_str().c_str()).ToLocalChecked());
                                                                ^
In file included from /home/ec2-user/.cache/node-gyp/13.11.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:54,
                 from /var/www/html/tracking-views/node_modules/node-rdkafka/src/binding.h:13,
                 from ../src/binding.cc:11:
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/ec2-user/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory `/var/www/html/tracking-views/node_modules/node-rdkafka/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.14.165-131.185.amzn2.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v13.11.0/bin/node" "/home/ec2-user/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/html/tracking-views/node_modules/node-rdkafka
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
npm WARN tracking-logs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.7.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-03-13T14_21_12_724Z-debug.log

**We have been npm install node-rdkafka,  but errors "no matching function for call to ‘v8::Object::Set(".**

**Comment by sam-github** [comment]
Duplicate of #733 (please close).

Fixed by #759
