### ISSUE TITLE
README still shows older message structure for message value

### ISSUE THREAD

**Issue by hjespers** [Blizzard/node-rdkafka#77]
Message Structure

Messages that are returned by the KafkaConsumer have the following structure.

{
  message: new Buffer('hi'), // message contents as a Buffer    <--- should be 'value' not 'message'
  size: 2, // size of the message, in bytes
  topic: 'librdtesting-01', // topic the message comes from
  offset: 1337, // offset the message was read from
  partition: 1, // partition the message was on
  key: 'someKey' // key of the message if present
}

**Comment by webmakersteve** [comment]
Fixed readme with #80
