### ISSUE TITLE
Expose InternalAdminClient interface

### ISSUE THREAD

**Issue by henningms** [Blizzard/node-rdkafka#777]
Hi there. First of all, thanks to everyone who has made this library possible. It's amazing :D 

I love the latest release bringing a sought after TypeScript definitions, but there seems to an issue with InternalAdminClient. This interface is not exposed and therefore I can not store an AdminClient in my class without having issues. Can we expose it?

```
Module '"../node_modules/node-rdkafka"' declares 'InternalAdminClient' locally, but it is not exported.ts(2459)
```

Secondly, would it make sense to rename this interface to IAdminClient or something?

I can create a PR on it, but wanted to know your opinions and thoughts before doing so.

**Comment by iradul** [comment]
Sounds good, go ahead and create PR

**Comment by henningms** [comment]
Cool, done! :D
