### ISSUE TITLE
Is there any possible way to get consumer's partition before offset_commit event callback?

### ISSUE THREAD

**Issue by holynls** [Blizzard/node-rdkafka#784]
Hi all, 

I want to manage offset with redis cache to prevent offset unconformity between broker and server.

To check by partition, topic name and partition number are used as keys for the redis cache, but there seems to be no way to know partition number in the first loop after starting consume.

I can't set up specific partitions for each server because I use multiple servers and the number of servers can change.

Is there a way to get a partition number before consume? like subscribed event.

Thanks.

**Comment by iradul** [comment]
You can use `rebalance_cb` or `queryWatermarkOffsets`.
