### ISSUE TITLE
Question) Why should poll () be called by the producer?

### ISSUE THREAD

**Issue by SHwan93** [Blizzard/node-rdkafka#788]
**Additional context**

I don't understand why the poll () function is being requested by the producer.
Doesn't the consumer poll to get the message from the broker?

Why should poll () be called by the producer?

**Comment by iradul** [comment]
First of all
> The node-rdkafka library is a high-performance NodeJS client for Apache Kafka that wraps the native librdkafka library. All the complexity of balancing writes across partitions and managing (possibly ever-changing) brokers should be encapsulated in the library.

So the answers you're looking for you can find in [librdkafka](https://github.com/edenhill/librdkafka) docs, for example [here](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-message-delivery-success):

> ## Producer message delivery success
> When a ProduceRequest is successfully handled by the broker and a ProduceResponse is received (also called the ack) without an error code the messages from the ProduceRequest are enqueued on the delivery report queue (if a delivery report callback has been set) and will be passed to the application on the next invocation rd_kafka_poll().

**Comment by SHwan93** [comment]
thanks. now i understand
