### ISSUE TITLE
Error in delivery report should provide topic/partition/key info

### ISSUE THREAD

**Issue by Pchelolo** [Blizzard/node-rdkafka#79]
In case there's been an error in the delivery report, currently the plain `Error` object is passed to the `delivery-report` callback and there's no way to correlate it with the exact message that has been sent. The `Error` object should has all the same properties as the normal delivery report contains.

**Comment by webmakersteve** [comment]
It should be the second parameter, that is the message that errored. 

```
self.emit('delivery-report', err, report);
```

**Comment by Pchelolo** [comment]
Oh, indeed, sorry for the distraction. Issue is invalid.
