### ISSUE TITLE
gzip compression unavailable within Docker (and no zstd)

### ISSUE THREAD

**Issue by ccarcaci** [Blizzard/node-rdkafka#790]
Hi, I'm pretty new to use node-rdkafka.

When I run my node-rdkafka app within a Docker container I get the following output from
```javascript
console.log(Kafka.features);
```

Output:
```bash
[ 'snappy', 'sasl', 'regex', 'lz4', 'sasl_plain', 'plugins' ]
```
The only one compression method available is lz4.

When I run the same app into my machine I get the output:
```bash
[ 'gzip', 'snappy', 'sasl', 'regex', 'lz4', 'sasl_gssapi', 'sasl_plain', 'plugins' ]
```

It seems that the library compilation within Docker fails to add the gzip compression.
The compilation output is pretty long so I prefer to link the [Dockerfile](https://github.com/ccarcaci/spike-node-kafka/blob/master/producer/Dockerfile).

Aside: no zstd library available in both cases.

What's going on?
Let me know if further information are needed.

**Environment Information**
 - OS: Mac
 - Node Version: 12
 - NPM Version [e.g. 5.4.2]: 6.14.4
 - C++ Toolchain: g++
 - node-rdkafka version: 2.8.1

**Steps to Reproduce**

Run this project
https://github.com/ccarcaci/spike-node-kafka

**Comment by sam-github** [comment]
Why are you using node-slim? The main thing that makes it slim is not having the build tools, which you add back in.

Consider  a multi-stage build, something like:

```
# Install the app dependencies in a full Node docker image
FROM node:12

# librdkafka builds against libssl-dev
RUN apt-get update && apt-get install -y libssl-dev && apt-get clean

WORKDIR /project
RUN npm install --production

# Copy the dependencies into a slim Node docker image
FROM node:12-slim

# librdkafka links against libssl
RUN apt-get update && apt-get install -y libssl1.1 && apt-get clean

COPY --chown=node:node --from=0 /project /project  # or whatever is right for you
```

If that doesn't get you more features, you have to find and add the relevant -dev packages to the build image, libsasl for example (I haven't checked).

**Comment by ccarcaci** [comment]
And finally I got the zstd compression available!

```bash
[ 'gzip', 'snappy', 'ssl', 'sasl', 'regex', 'lz4', 'sasl_gssapi', 'sasl_plain', 'sasl_scram', 'plugins', 'zstd', 'sasl_oauthbearer' ]
```

I've taken inspiration from this https://github.com/Blizzard/node-rdkafka/issues/525
And this https://github.com/Blizzard/node-rdkafka/blob/master/examples/docker-alpine.md

The final result is: https://github.com/ccarcaci/spike-node-kafka/blob/master/producer/Dockerfile

Unfortunately, I have not been able to enable the zstd on node:12 Docker image which uses the apt package manager that seems that is not supporting the zstd-dev version (but maybe I'm wrong).

I think that the procedures of Dockerizing and enabling zstd are very important since the zstd compression has been demonstrated as [the best for kafka](https://blog.cloudflare.com/squeezing-the-firehose/). I'd like to send a PR to update the README to explain how to Dockerize and enable std. Let me know if I can proceed.

Thank you again for your precious hints.

**Comment by sam-github** [comment]
every distro has its own package names, the alpine names won't work for non-alpine.

spin up the node:12 image and do a search for the package names it uses, maybe libzstd-dev, for example? Or search https://packages.debian.org/sid/libzstd-dev

**Comment by ccarcaci** [comment]
Thank you very much for your hints, you've opened a world in my mind that, although it seems to be obvious, it changed my life. Run containers and test commands within to figure out how to write good and optimized Dockerfiles. Very appreciate!

Back to our issue, I've tested the building process inside the node:12 container image.
I have started the container created by the line 2 of this [Dockerfile](https://github.com/ccarcaci/spike-node-kafka/blob/issue/790-node-rdkafka/enabling-zstd/producer/Dockerfile)

Then I've launched the command:
```npm install --production```

But I've got:
```
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
```

The entire console is available [here](https://github.com/ccarcaci/spike-node-kafka/blob/issue/790-node-rdkafka/enabling-zstd/build-output.txt).

In line 1 I join the container.
```claudio:producer$ docker run -it 6360d063c4d4 sh```

In line 35 I reinstall the debian packages.
```# apt-get update && apt-get install -y libssl-dev libzstd-dev && apt-get clean```

In lines 89 and 90 I get the libzstd disabled.
```
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
```

**Comment by sam-github** [comment]
Is it disabled?
`ENABLE_ZSTD              y` is in the configure output after  that. probably best print the node-rdkafka supported options to be sure.

I don't have time to work through this myself, but `docker run -it /bin/bash` and doing the npm install, print node-rdkafka supported features, sigh, apt-get install something else, ./configure, build, .... until it worked is what I'd do to see what the requirements are.

One other hint, on your desktop linux system where you said node-librdkafka does have all the supported features, you can do `ldd .../the/path/to/the/addon.node`, and that will tell you what the dynamic libs it links against are. Do `dpkg -S /lib/the/lib-that-is-needed`, now you know what package they came from. Find the dev version of that package, then install it on docker. If you have a desktop mac, well, ldd should still work, but now you have to work a bit harder to see what the debian name of the package providing that .so is.

**Comment by ccarcaci** [comment]
I've done a complete investigation following your instructions.
The attached files describe the building paths on node:12-alpine (working) and node:12 debian (non-working).

In the alpine-build-output I got:

* On lines 49-50-51 zstd has been installed.
* On line 109 libzstd is checked as OK.
* On line 133 ENABLE_ZSTD flag is y.
* On line 816 zstd is available to my node application.

In the debian-build-output I got:

* On lines 29-35 libzstd has been installed.
* On lines 106-107 libzstd is checked as failed.
* On line 132 ENABLE_ZSTD flag is y.
* On lines 727-738 zstd doesn't appear as available.

I've looked also a check on libraries in both environment and everything is looking good.

* ldd command node:12-alpine (working):

/usr/bin # ldd zstd
        /lib/ld-musl-x86_64.so.1 (0x7f1c4ac4c000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f1c4ac4c000)

* ldd command node:12 debian (non working):

# dpkg -S zstd
libzstd1: /usr/share/doc/libzstd1/changelog.Debian.gz
libzstd-dev: /usr/include/zstd_errors.h
libzstd1: /usr/share/doc/libzstd1
libzstd-dev: /usr/lib/x86_64-linux-gnu/libzstd.a
libzstd-dev: /usr/share/doc/libzstd-dev
libzstd-dev: /usr/share/doc/libzstd-dev/copyright
libzstd1: /usr/lib/x86_64-linux-gnu/libzstd.so.1.1.2
libzstd-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/libzstd.pc
libzstd-dev: /usr/lib/x86_64-linux-gnu/libzstd.so
libzstd1: /usr/share/doc/libzstd1/copyright
libzstd-dev: /usr/share/doc/libzstd-dev/changelog.Debian.gz
libzstd1: /usr/lib/x86_64-linux-gnu/libzstd.so.1
libzstd-dev: /usr/include/zstd.h

I think that there's something wrong in librdkafka compilation.
I'll try to take a look at it.

[alpine-build-output.txt](https://github.com/Blizzard/node-rdkafka/files/4567698/alpine-build-output.txt)
[debian-build-output.txt](https://github.com/Blizzard/node-rdkafka/files/4567699/debian-build-output.txt)
