### ISSUE TITLE
Running node-rdkafka in UBI images

### ISSUE THREAD

**Issue by IdanAdar** [Blizzard/node-rdkafka#795]
Hi all, 

Has anyone managed running the package in a container based on UBI eg: 
```
FROM registry.access.redhat.com/ubi8/nodejs-12:latest
```

Or UBI-minimal (Nodejs 10), eg:
```
# Setup a minimal ubi
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.0

# Install node.js
RUN microdnf install nodejs --nodocs && microdnf clean all
```

and can provide a working Dockerfile?

**Comment by pdykes** [comment]
Folks, running this with ubi8/node-12 image.  I can get the past node rd-kafka node-gyp install, but consumer will not connect and debug all does no show much.  Anyone else try this?

**Comment by pdykes** [comment]
FYI, i was able to get ubi8/node-12 image going... After all debugging, etc... silence vs. complain of security issue was the issue.  

Net, figured security... 

Thus, printed out the default certs as a start to get things going, found one, and then used this in the consumer properties vs. the typical /etc/ssl/certs, and viola in your app.js:

  'ssl.ca.location': '/etc/pki/tls/cert.pem',

Consumer is happily chewing through thousands of messages.

Couple of other Dockerfile tweaks:
a) Put code in /opt/app-root/...  (Dockerfile:   WORKDIR /opt/app-root/src/nodeapp)
b) To ensure all the tools node-gyp needed these Dockerfile stanzas present:

RUN yum -y update && yum clean all

RUN yum -y install bash ca-certificates libevent-devel libevent lz4-devel lz4-libs cyrus-sasl-devel cyrus-sasl openssl-devel openssl make python2 zlib-devel zlib gcc-c++ gcc glibc-headers diffutils

RUN sudo npm install -g --unsafe-perm

RUN mkdir -p /opt/app-root/src/nodeapp/node_modules

RUN sudo chmod -R 777 /opt/app-root/src/nodeapp/node_modules.  (this is more for test, will tighten up and should be, but goal here is initial bringup/boostrap)

RUN npm install

**Comment by princeali2k** [comment]
Were you able to get this working with ubi minimal image?   Please post your entire dockerfile here.   Thanks.
