### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by arditsinani-helius** [Blizzard/node-rdkafka#802]
is the stream API an implementation of the native API that Kafka has,or is just a wrapper and rename of the Producer and Consumer API

**Comment by arditsinani-helius** [comment]
any response? @iradul

**Comment by yunnysunny** [comment]
The stream API extends the native class of `Readable`, but it have a problem of not stopping reading message when the internal buffer has reached the threshold of `highWaterMark`.

**Comment by arditsinani-helius** [comment]
so? what about the stream API? @yunnysunny
