### ISSUE TITLE
Start consuming from a specific offset

### ISSUE THREAD

**Issue by Arkh1** [Blizzard/node-rdkafka#818]
Is it possible in node-rdkafka to start consuming from a specific offset?  Our team is trying to transition from kafka-node to this library, however in kafka-node we had the ability to subscribe to a topic and start consuming from a specific offset.

Any help/direction would be appreciated.

**Comment by syahiaoui** [comment]
You can see that on the library definition [seek](https://github.com/Blizzard/node-rdkafka/blob/master/index.d.ts#L228)

I never use this function but i think that you try this:

`   consumer.seek({topic: 'test', partition: 0, offset: 122}, 10, function (err) {
            console.log(err);
    });`

**Comment by syahiaoui** [comment]
You can see that on the library definition [seek](https://github.com/Blizzard/node-rdkafka/blob/master/index.d.ts#L228)

I have never used this function but I think you can try this:

`consumer.seek({topic: 'test', partition: 0, offset: 122}, 10, function (err) { console.log(err); });`

**Comment by spikepanx** [comment]
... have a look at consumer.assign():
```
/**
 * Assign the consumer specific partitions and topics
 *
 * @param {array} assignments - Assignments array. Should contain
 * objects with topic and partition set.
 * @return {Client} - Returns itself
 */
```
To my knowledge, there you can also set a offset.

**Comment by Arkh1** [comment]
Thank you, I will investigate both of those.

**Comment by Arkh1** [comment]
Update: consumer.assign() did the trick.  Thanks!
