### ISSUE TITLE
SASL GSSAPI Issue on WSL Ubuntu

### ISSUE THREAD

**Issue by wabdalla** [Blizzard/node-rdkafka#819]
**Environment Information**
 - WSL Ubuntu ==> 4.4.0-17763-Microsoft #1217-Microsoft Mon May 05 16:09:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Node Version v8.10.0
 - NPM Version 3.5.2 
 - node-rdkafka": "^2.9.0"

**Steps to Reproduce**
Connect to a broker with SASL-GSSAPI requirement

**node-rdkafka Configuration Settings**

it seems like the current Debian build for node-rdkafka disables out of the box SASL-GSSAPI 

I just ran `npm i node-rdkafka -g` to install it, and I get this error when I connect to our internal brokers

 ```
{ err:
   { Error: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER
     origin: 'no provider for sasl mechanism gssapi',
     message: 'recompile librdkafka with libsasl2 or openssl support. current build options',
     code: -1,
     errno: -1,
     stack: 'Error: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. 
Current build options: PLAIN SASL_SCRAM OAUTHBEARER' },
  metaData: undefined }
```

I made sure I installed `sudo apt-get install libsasl2-modules-gssapi-mit`

**Comment by giulliano-bueno** [comment]
Have you tried `npm rebuild node-rdkafka` after you installed libsasl2?

**Comment by wabdalla** [comment]
Thank you for your response! I managed to get it to work by uninstalling node-rdkafka in npm, deleting node_modules and then reinstalling it.
