### ISSUE TITLE
Error: Invalid value "SASL_SSL" for configuration property "security.protocol"

### ISSUE THREAD

**Issue by Avielyo10** [Blizzard/node-rdkafka#822]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Fedora 31
 - Node Version [e.g. 8.2.1]: 12.16.3
 - NPM Version [e.g. 5.4.2]: 6.14.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: 2.9.0

**Steps to Reproduce**
`node kafka.js`

**node-rdkafka Configuration Settings**
```js
const kafka = require('node-rdkafka')

const USERNAME = <USERNAME>
const PASSWORD = <PASSWORD>

const kafkaConf = {
    "group.id": "cloudkarafka-example",
    "metadata.broker.list": <BROKER_LIST>,
    "socket.keepalive.enable": true,
    "security.protocol": "SASL_SSL",
    "sasl.mechanisms": "SCRAM-SHA-256",
    "sasl.username": USERNAME,
    "sasl.password": PASSWORD,
    "debug": "generic,broker,security"
};

const consumer = new kafka.KafkaConsumer(kafkaConf);

consumer.on("ready", arg => {
    console.log(`Consumer ${arg.name} ready`);
    consumer.subscribe(<SOME_TOPIC>);
    consumer.consume();
});

consumer.on('error', err => {
    console.log("Consumer Error: " + err);
});

```

**Additional context**
```bash
  this._client = new SubClientType(globalConf, topicConf);
                 ^

Error: Invalid value "SASL_SSL" for configuration property "security.protocol"

```

**Comment by alterationx10** [comment]
Have you tried "sasl_ssl" - as lowercase?
From my IDE's bring up config.d.ts:
```
/**
     * Protocol used to communicate with brokers.
     *
     * @default plaintext
     */
    "security.protocol"?: 'plaintext' | 'ssl' | 'sasl_plaintext' | 'sasl_ssl';
```

**Comment by Avielyo10** [comment]
@alterationx10, Yes, still doesn't work

**Comment by RaajBadra** [comment]
May be you have to try this configuration.
https://github.com/Blizzard/node-rdkafka#mac-os-high-sierra--mojave

**Comment by ddhabak1** [comment]
make sure you have openssl installed then set CPPFLAGS and LDFLAGS

example: 
`CPPFLAGS=-I/usr/local/opt/openssl/include` LDFLAGS=-L/usr/local/opt/openssl/lib npm install node-rdkafka@2.8.1

**Comment by Avielyo10** [comment]
I reinstall the package and it's working, thanks all

**Comment by razb-viola** [comment]
For me the same, not working and trying what you wrote here..

**Comment by sojinantony01** [comment]
For **mac OS sequoia 15.1**
Error: Unsupported value "sasl_ssl" for configuration property "security.protocol": OpenSSL not available at build time
Looks like there is no 'opt' folder inside `/usr/local` and for me it got changed to `/opt/homebrew/Cellar/openssl@3/3.4.0/`

Changing `CPPFLAGS` and `LDFLAGS` to  new path works for me
`export CPPFLAGS=-I/opt/homebrew/Cellar/openssl@3/3.4.0/include
export LDFLAGS=-L/opt/homebrew/Cellar/openssl@3/3.4.0/lib
`
