### ISSUE TITLE
If "sasl_ssl" doesn't show up in Kafka.features does that mean it isn't supported?

### ISSUE THREAD

**Issue by Davenporten** [Blizzard/node-rdkafka#824]
My real issue is that I get `Broker transport error` whenever I try to run subscriptions for graphql using node-rdkafka using sasl_ssl and I'm trying to find a solution to that. I've installed everything I believe I need for librdkafka to work properly, but when I print out `Kafka.features` I get

```
[
  'gzip',
  'snappy',
  'ssl',
  'sasl',
  'regex',
  'lz4',
  'sasl_gssapi',
  'sasl_plain',
  'sasl_scram',
  'plugins',
  'zstd',
  'sasl_oauthbearer'
]
```
Because sasl_ssl doesn't explicitly show up in this list does that mean it isn't supported? I thought maybe because sasl and ssl are both there it might work, but I'm wondering if I'm wrong.

Thanks in advance for all the help!

**Comment by giulliano-bueno** [comment]
It should be there. Please make sure that you have OpenSSL installed locally and try to run `npm rebuild node-rdkafka`. You could share your configuration here to help us understand how you are using it, please.

**Comment by Davenporten** [comment]
Thanks for getting back to me @giulliano-bueno 

I believe openssl is configured correctly:
```
$ openssl version -a
OpenSSL 1.1.1g  21 Apr 2020
built on: Thu Jul 23 15:20:23 2020 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/ssl/lib/engines-1.1"
Seeding source: os-specific
```

As far as my configuration I have something like this as an example
```
const stream = Kafka.KafkaConsumer.createReadStream({
    'metadata.broker.list': '<BROKER>',
    'security.protocol': 'sasl_ssl',
    'ssl.keystore.location': '<KEYSTORE>',
    'ssl.keystore.password': '<PASSWORD>',
    'sasl.mechanism': 'GSSAPI',
    'sasl.kerberos.keytab': '<KEYTAB>',
    'sasl.kerberos.principal': '<PRINCIPAL>',
    'sasl.kerberos.service.name': '<NAME>',
    'group.id': 'librd-test',
}, {}, {
    topics: '<TOPIC>',
    waitInterval: 0,
    objectMode: false
});
```

I really appreciate your help!

**Comment by RicardoGralhoz** [comment]
> Because `sasl_ssl` doesn't explicitly show up in this list does that mean it isn't supported?

Probably `sasl_ssl` shoudln't be shown there.  I also had `'security.protocol': 'sasl_ssl'` with similar settings, had multiple issues and was able to fix all of them and `sasl_ssl` is still not shown as librdkafka features. See also [librdkafka Configuration properties](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md), especially `builtin.features`

Here are some useful links to help solving this type of connection issues:

- [librdkafka requirements](https://github.com/edenhill/librdkafka#requirements), especially dependency on `libssl-dev` (for SSL support) and `libsasl2-dev` ( for SASL GSSAPI support)
- [librdkafka Brokers > SSL](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#ssl)
- [Using SSL with librdkafka](https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka)
- [Using SASL with librdkafka](https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka) - special attention to step [4. Install SASL modules on client host](https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka#4-install-sasl-modules-on-client-host) 

And helpful commands to fix missing dependencies and rebuild `node-rdkafka`:

1. `apt -qq list libsasl2-modules-gssapi-mit libsasl2-dev libssl-dev`
2. `sudo apt-get install libsasl2-dev`
3. `sudo apt-get install libssl-dev`
4. `npm rebuild node-rdkafka --loglevel="verbose`


Related issues:

1. [Failure to initialize (error:SSL routines:SSL_CTX_new:library has no ciphers) #566](https://github.com/Blizzard/node-rdkafka/issues/566)
2. [Cant make sasl_ssl work #2257](https://github.com/edenhill/librdkafka/issues/2257)

**Comment by guillaume-kermorgant** [comment]
Anyone managed to make `node v.12`/`node-rdkafka v.2.9.1` work with Kerberos? We always get SSL errors and we are sure our configuration is correct (everything works fine with `node v.8`/`node-rdkafka v.2.7.0`).
We've tried all the suggested solutions to solve this connection issue, but we can't make this work.

**Comment by RicardoGralhoz** [comment]
@guillaume-kermorgant I have node `v.10/node-rdkafka v.2.9.1` working with `Kerberos`. Perhaps you should open a new issue* and add a link to it here. On my experience struggling with these integrations, there are a lot of moving parts and uniqueness on each environment. It helped me tracing each first error logged and fixed it; isolating parts to test if they're working as expected; and re-reading docs.

* add environment configurations, logged errors, etc.

**Comment by amananurag** [comment]
below is my openssl config on Mac. I am still getting same error as 

**Error: Unsupported value "SASL_SSL" for configuration property "security.protocol": OpenSSL not available at build time**

OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
built on: Tue Oct 24 13:41:51 2023 UTC
platform: darwin64-arm64-cc
options:  bn(64,64)
compiler: clang -fPIC -arch arm64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/opt/homebrew/etc/openssl@3"
ENGINESDIR: "/opt/homebrew/Cellar/openssl@3/3.1.4/lib/engines-3"
MODULESDIR: "/opt/homebrew/Cellar/openssl@3/3.1.4/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_armcap=0x187d
