### ISSUE TITLE
Module doesn't self-register from a worker thread

### ISSUE THREAD

**Issue by yura415** [Blizzard/node-rdkafka#831]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Alpine (docker)
 - Node Version [e.g. 8.2.1]: node:12-alpine
 - NPM Version [e.g. 5.4.2]: v5
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.8.1

**Steps to Reproduce**

```
const {
  Worker, isMainThread
} = require('worker_threads');
const kafka = require('node-rdkafka');

if (isMainThread) {
   // Brand new worker
   new Worker(__filename);
}
```

**Additional context**

Even though this issue relates to nodejs internal implementation of workers, nodejs developers wont fix it. However it can be fixed by making native module context-aware. Here is an example for node-lzo: https://github.com/schroffl/node-lzo/pull/11

**Comment by chengsu** [comment]
https://github.com/nodejs/node/issues/21783#issuecomment-429637117

**Comment by eduardogmisiuk** [comment]
I'm experiencing the same problem. I'm not directly using the lib in the worker thread, but it is imported with other modules and crashes.

**Comment by relief-melone** [comment]
any update on this? Still cannot open up workers utilizing node-rdkafka
