### ISSUE TITLE
AdminClient delete/createTopic resolves prematurely

### ISSUE THREAD

**Issue by juanreynolds** [Blizzard/node-rdkafka#833]
I assume that when deleteTopic callback is called the topic has been fully created, however I get error ERR_TOPIC_ALREADY_EXISTS. If I insert a small wait then it works fine. So it seems that either I am missing some crucial configuration setting, or that deleteTopic resolves prematurely. (btw, same holds for createTopic)

**Environment Information**
 - OS: Ubuntu 18.04
 - Node Version: 12.18.3
 - NPM Version: 6.14.7
 - C++ Toolchain: gcc version 7.5.0
 - node-rdkafka version: 2.9.1

**Steps to Reproduce**

async function createTopic(client: IAdminClient, topic: string) {
    return new Promise((resolve, reject) => {
        client.createTopic({
            topic: topic,
            num_partitions: 1,
            replication_factor: 1
        }, function (err) {
            if (err) reject(err);
            else resolve("success");
        });
    });
}

async function deleteTopic(client: IAdminClient, topic: string) {
    return new Promise((resolve, reject) => {
        client.deleteTopic(topic, (err) => {
            if (err) reject(err);
            else resolve("success");
        });
    });
}

async function setup(topic: string) {
    const client = AdminClient.create({
        'client.id': 'kafka-admin',
        'metadata.broker.list': '127.0.0.1'
    });
    try {
        await deleteTopic(client, topic);
    }
    catch (e) {
        console.log(e);
    }
    //await Wait(1000);
    try {
        await createTopic(client, topic);
    }
    catch (e) {
        console.log(e);
    }
    client.disconnect();
}

**node-rdkafka Configuration Settings**
{
        'client.id': 'kafka-admin',
        'metadata.broker.list': '127.0.0.1'
}

**Additional context**
LibrdKafkaError: Topic 'fruit' already exists.
    at Function.createLibrdkafkaError [as create] {
  code: 36,
  errno: 36,
  origin: 'local'
}

**Comment by iradul** [comment]
This seems to be expected behavior. I can confirm that it happens in the native Java client too.
I think that topic deletion is delegated to the Zookeeper and from that point it's unknown when the actual deletion will occur and then when all the brokers are going to become aware of the event.

**Comment by juanreynolds** [comment]
Thanks for confirming that. It's easy enough to code around.
