### ISSUE TITLE
Mutli-consumers for same group.id

### ISSUE THREAD

**Issue by CL-SHLOMIKONCHA** [Blizzard/node-rdkafka#834]
**Environment Information**
 - OS [ Windows 10]: 
 - Node Version [e.g. 12.18.1]:
 - node-rdkafka latest

**node-rdkafka Configuration Settings**

const consumer = new Kafka.KafkaConsumer({
    'group.id': 'msgGroup1',
    'metadata.broker.list': 'localhost:9092',
}, {});

**Additional context**
Hi, first of all, thanks for this package.
I am trying to run 2 consumers with the same group.id to consume message per consumer (one by one) , i mean when first consumer is busy by doing some operation , i want the second consumer to consume the next message meanwhile.
Somehow specific consumer is always consume first message and then another one, and it's seems like the other consumer can't consume the next message meanwhile.

 this is how my consumers code looks like:

> const Kafka = require('node-rdkafka');
const consumer = new Kafka.KafkaConsumer({
    'group.id': 'msgGroup1',
    'metadata.broker.list': 'localhost:9092',
}, {});
let isBusy = false;
consumer.connect();
consumer.on('ready', function () {
    consumer.subscribe(['topic1']);
    setInterval(() => {
        if (!isBusy) {
            isBusy = true;
            consumer.consume(1, (err, message) => {
                if (message.length > 0) {
                    console.log(message);
                }
                setTimeout(() => {
                    isBusy = false;
                }, 3000)
            });
        }
    }, 0);
});

I am running 2 consumers with the same code , only one can consume messages one by one, i want them both share messages when the other is busy, any ideas?

**Comment by iradul** [comment]
You must read from a topic with at least 2 partitions in order to do this.
