### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by unpredict2ble** [Blizzard/node-rdkafka#836]
I'm having an issue with this package. Currently using MacOS High Sierra. I get errors when trying to install 

`npm install node-rdkafka`

<img width="756" alt="Screen Shot 2020-08-27 at 10 39 08 AM" src="https://user-images.githubusercontent.com/16257562/91464511-44f39d80-e852-11ea-8ee6-994634b40e80.png">

The only way I can get it to install is to run...
`npm install node-rdkafka --ignore-script`

Then when trying to run the file with the package added....

<img width="762" alt="Screen Shot 2020-08-27 at 10 45 06 AM" src="https://user-images.githubusercontent.com/16257562/91464791-956afb00-e852-11ea-8cfa-2a3f41c79f04.png">

I've tried....

- Installing binding package
- Installing node-gyp
- Deleting the node_modules and running `npm install`
- I've had a co-worker pull the code, and he has the same issue

I currently only have 2 packages installed at this time. The other package is dotenv. 

If i uninstall the node-rdkafka package, I can run the file, but as soon as I add node-rdkafka (with `--ignore-script`), the file won't run.

Again, it won't install without the --ignore-script flag.

Any help would be highly appreciated!

**Comment by g14a** [comment]
I get the same error on macOS Catalina 10.15.7. Is there any progress on this? @webmakersteve

**Comment by 103cuong** [comment]
The same issue on macOS Catalina 10.15.7. How can I resolve it?
<img width="741" alt="Screen Shot 2020-10-08 at 4 42 55 PM" src="https://user-images.githubusercontent.com/34389409/95442248-5669b280-0985-11eb-9765-2abdcf7d3aab.png">

**Comment by 103cuong** [comment]
> The same issue on macOS Catalina 10.15.7. How can I resolve it?
> <img alt="Screen Shot 2020-10-08 at 4 42 55 PM" width="741" src="https://user-images.githubusercontent.com/34389409/95442248-5669b280-0985-11eb-9765-2abdcf7d3aab.png">

Fixed!
Install [Command Line Tools for Xcode](https://developer.apple.com/download/more/) to resolve this problem.

**Comment by g14a** [comment]
Checkout this issue. I changed my shell from fish to zsh. I know it shouldn't depend on the shell but I don't know what happened. My issue was on a Mac.

https://github.com/Blizzard/node-rdkafka/issues/267#issuecomment-338391501
