### ISSUE TITLE
Consuming kafka msg specific partition

### ISSUE THREAD

**Issue by rabeeshcharles** [Blizzard/node-rdkafka#837]
Hey Guys.....
- rdkafka has many features and i have followed the code samples from npm page

Question
----------
- Could someone help to consume the kafka msg from specifi partition like 0th partition only or 3rd partition only because I am trying to achieve the parallel consumer concept..

Thanks in advance....

Happy Coding.....

**Comment by iradul** [comment]
If you want your consumer to read from specific partitions you need to enable `rebalance_cb` callback and there you need to manually assign topic-partitions you want to consume from.
https://github.com/Blizzard/node-rdkafka#rebalancing
