### ISSUE TITLE
Consumer won't receive the compressed message, when centos not installed zlib

### ISSUE THREAD

**Issue by diandian18** [Blizzard/node-rdkafka#838]
**Environment Information**
 - OS: Centos ( without installing zlib )
 - Node Version: v12.18.3
 - NPM Version 6.14.6:
 - C++ Toolchain: g++
 - node-rdkafka version: 2.9.1

**Steps to Reproduce**

1. Centos, has not installed zlib.
2. Install `node-kafka`,  and it shows: 

    ```bash
    checking for zlib (by compile)... failed
    ```

    but succees finally:

    ```bash
    + node-rdkafka@2.9.1
    updated 1 package in 71.758s
    ```

3. Write a demo.js

```js
var Kafka = require('node-rdkafka');
var stream = Kafka.KafkaConsumer.createReadStream({
    'group.id': 'test-group',
    'metadata.broker.list': 'kafka:9092',
}, {}, {
    topics: ['test-topic']
});

stream
.on('data', function (message) {
    console.log('Got message');
    console.log(message.value.toString());
})
.on('error', function(err) {
    console.log(err);
})
 ```

4. Just run `node demo.js`

5. Produce some meesage to kafka via filebeat, the message data will be compressed. The `demo.js` terminal will not receive any message but show error:

```bash
LibrdKafkaError: Local: Not implemented
```

6. To solve the problem, first install `sudo yum install zlib-devel`, then reinstall `npm i node-rdkafka`

7. Retry `node demo.js`, we will receive the compressed message data.

The problem take me much time. To avoid it for more developers,  **maybe it's neccesary to add some tips in the font of our README**, just like: 

```bash
### tips
Make sure your OS has installed zlib...
```

Or show **failed** after we install `node-rdkafka`, if we don't have `zlib`.

**node-rdkafka Configuration Settings**

```js
var stream = Kafka.KafkaConsumer.createReadStream({
    'group.id': 'test-group',
    'metadata.broker.list': 'kafka:9092',
}, {}, {
    topics: ['test-topic']
});
```

Thx.

**Comment by iradul** [comment]
Compression is optional feature plus there are multiple compression methods that are supported, so installation should not fail without zlib installed. It's clearly visible during installation, specifically compilation of `librdkafka`, what features are enabled, unless you're using Windows. During runtime you can use `features` property to check what feature is available:
https://github.com/Blizzard/node-rdkafka#librdkafka-methods
