### ISSUE TITLE
Kafka Topic Issue

### ISSUE THREAD

**Issue by rabeeshcharles** [Blizzard/node-rdkafka#839]
In RdKakfa , Consumer is not Throwing any error while Subscribing a new Topic which is not created in the Kafka.
Expectation - It should emit an error like topic does not exist, so that we can able to create topic either by manual process or programatically.

Thanks In Advance..

**Comment by spikepanx** [comment]
... would say, that‘s not the way things work with librdkafka based clients. There‘s the metadata request which gives u all available topics, so you can write a small wrapper which throws if a specific topic does not exist, if you like that

**Comment by rabeeshcharles** [comment]
Ok..then let me do that...
Thanks...
