### ISSUE TITLE
Is support node14 with alpine

### ISSUE THREAD

**Issue by yuu2lee4** [Blizzard/node-rdkafka#841]
it's ok installing node-rdkafka2.9.1 with node14.9.1 on my mac, but when using alpine with docker it will stop at building fresh packages to fail.
![image](https://user-images.githubusercontent.com/8046366/91802048-2e3bb500-ec5d-11ea-813c-efd93514b896.png)
And after I change node version to 12.x.x,It will be ok.

**Comment by underbyte** [comment]
Don't believe node v14 is fully supported yet. Support stops at [node v13](https://github.com/Blizzard/node-rdkafka/blob/7b81cb3eab09fe53477371776a943693a7c96057/.travis.yml#L12).

**Comment by yunnysunny** [comment]
Have any plan to support node v14?
