### ISSUE TITLE
Possible  memory leak while sending a message with headers

### ISSUE THREAD

**Issue by Denusdv** [Blizzard/node-rdkafka#846]
Hi Guys

**Environment Information**
 - OS [centos AWS 4.14.181-142.260.amzn2.x86_64]: 
 - Node Version [v10.11.0]:
 - NPM Version [6.4.1]:
 - C++ Toolchain [g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)]:
 - node-rdkafka version [2.9.1]:

**Steps to Reproduce**

We have a system running on the EKS(AWS) platform.
The node is running in the pod with the cluster mode enabled. 
The system has been running for half a year without any mem problem. Recently we started observing a memory leak.  Per our code analysis we managed to isolate the problem which apparently is caused when we add a header to a Kafka message. That's the only code diff we have, notice the problem is replicated even with header null.

To replicate the issue:

Create a simple Producer client and send a message with a header (no matter what value, event null reproduces the mem leak). The memory grows very slow but constantly, our scale is ~250 messages per second. 
We are using node exporter Prometheus to collect the node statistic. 

<img width="1604" alt="Screen Shot 2020-10-04 at 12 28 43" src="https://user-images.githubusercontent.com/2059461/95012435-306ca700-0641-11eb-89c6-d3819530c90c.png">

The chart shows the short period of time, but if you let him run for a few days. the memory doesn't stop growing.

<img width="1565" alt="Screen Shot 2020-10-04 at 13 19 19" src="https://user-images.githubusercontent.com/2059461/95012817-3ca63380-0644-11eb-9d38-1acd0068bb08.png">

**node-rdkafka Configuration Settings**

we have two MSK Kafka brokers with TLS connections

Producer:

```
this.kproducer = new Kafka.Producer({
     'metadata.broker.list': this.producers.toString(),
     'message.send.max.retries': 10,
     'retry.backoff.ms': 1000,
     'compression.codec': 'snappy',
     'linger.ms': this.linger_ms,
     'security.protocol': 'ssl',
     'ssl.ca.location': 'kafka_ssl/ssl.ca',
     'socket.keepalive.enable': true,
     'dr_cb': process.env.DEBUG
});
```

The code for sending a message

Without mem leak:

```
return this.kproducer.produce(
    // Topic to send the message to
    this.successTopics,
    // optionally we can manually specify a partition for the message
    // this defaults to -1 - which will use librdkafka's default partitioner (consistent random for keyed messages, random for unkeyed messages)
    murmur.murmur2(event.id) % this.partitions,
    // Message to send. Must be a buffer
    Buffer.from(JSON.stringify(event)),
    // for keyed messages, we also specify the key - note that this field is optional
    "",
    // you can send a timestamp here. If your broker version supports it,
    // it will get added. Otherwise, we default to 0
    Date.now(),
    // you can send an opaque token here, which gets passed along
    // to your delivery reports
);
```

With mem leak

```
return this.kproducer.produce(
    // Topic to send the message to
    this.successTopics,
    // optionally we can manually specify a partition for the message
    // this defaults to -1 - which will use librdkafka's default partitioner (consistent random for keyed messages, random for unkeyed messages)
    murmur.murmur2(message.id) % this.partitions,
    // Message to send. Must be a buffer
    Buffer.from(JSON.stringify(event)),
    // for keyed messages, we also specify the key - note that this field is optional
    "",
    // you can send a timestamp here. If your broker version supports it,
    // it will get added. Otherwise, we default to 0
    Date.now(),
    // you can send an opaque token here, which gets passed along
    // to your delivery reports
     null,
     null, // note, the header could be [{"header-name":"header-value"}]
);
```

I tried many experiments sending different header values with different payload sizes, it seems like it has no effect on the rate of memory growth, what is important is by the mere fact that you send a header.

I tried troubleshooting it using heap dump snapshots, although without big success. 

**Additional context**

**Comment by Denusdv** [comment]
I found the following thread from the https://github.com/edenhill/librdkafka 
https://github.com/edenhill/librdkafka/issues/2431 (RdKafka::Headers::Header operator= memory leak)

Probably it's related to the memory leak I'm observing. Would like to get some confirmation. 

Based on the librdkafka releases, the fix will be available  only from version 1.5.0
If that's the reason why I see it as well. 
Pls let me know when you plan to upgrade to 1.5, I see you are behind two versions. 


Thanks

**Comment by fabianschmitthenner** [comment]
node-rdkafka was just updated to librdkafka 1.5.1 in version 2.10.0. Is the issue still happening?

**Comment by Denusdv** [comment]
Hi Fabian.
I tried out the new version. Unfortunately observe the same issue. 
I tried two code usage.
1.
 ```
return this.kproducer.produce(
    // Topic to send the message to
    this.successTopics,
    // optionally we can manually specify a partition for the message
    // this defaults to -1 - which will use librdkafka's default partitioner (consistent random for keyed messages, random for unkeyed messages)
    murmur.murmur2(message.id) % this.partitions,
    // Message to send. Must be a buffer
    Buffer.from(JSON.stringify(event)),
    // for keyed messages, we also specify the key - note that this field is optional
    "",
    // you can send a timestamp here. If your broker version supports it,
    // it will get added. Otherwise, we default to 0
    Date.now(),
    // you can send an opaque token here, which gets passed along
    // to your delivery reports
     null,
     header, // note, the header could be [{"header-name":"header-value"}]
);
```

and 

2. 
```
return this.kproducer.produce(
    // Topic to send the message to
    this.successTopics,
    // optionally we can manually specify a partition for the message
    // this defaults to -1 - which will use librdkafka's default partitioner (consistent random for keyed messages, random for unkeyed messages)
    murmur.murmur2(message.id) % this.partitions,
    // Message to send. Must be a buffer
    Buffer.from(JSON.stringify(event)),
    // for keyed messages, we also specify the key - note that this field is optional
    "",
    // you can send a timestamp here. If your broker version supports it,
    // it will get added. Otherwise, we default to 0
    Date.now(),
    // you can send an opaque token here, which gets passed along
    // to your delivery reports
     null,
     null, // note, the header could be [{"header-name":"header-value"}]
);
```

In both cases I see the constantly growing memory.
Only when I remove two last arguments, the leak is gone

```
return this.kproducer.produce(
    // Topic to send the message to
    this.successTopics,
    // optionally we can manually specify a partition for the message
    // this defaults to -1 - which will use librdkafka's default partitioner (consistent random for keyed messages, random for unkeyed messages)
    murmur.murmur2(message.id) % this.partitions,
    // Message to send. Must be a buffer
    Buffer.from(JSON.stringify(event)),
    // for keyed messages, we also specify the key - note that this field is optional
    "",
    // you can send a timestamp here. If your broker version supports it,
    // it will get added. Otherwise, we default to 0
    Date.now(),
); 
```

Based on the librdkafka the probable mem leak should be fixed. The scenario is pretty simple. I'm 100 %  sure I'm not the first who tries to use the header argument. Wondering If I'm missing something or the issues is not fixed. Could you try to replicate  the mem leak.

I attach the screenshot from our monitor  system
<img width="1587" alt="Screen Shot 2020-12-14 at 16 10 33" src="https://user-images.githubusercontent.com/2059461/102092780-14e40080-3e29-11eb-8091-993c27114efc.png">

Thanks

**Comment by fabianschmitthenner** [comment]
That's unfortunate 😞. I wonder if you also see the behaviour when using the `HighLevelProducer`? 🤔

**Comment by DenisVoloshin** [comment]
Hi Fabian.

Using the latest release ~2.10.1, I got the same problem
You mentioned to try out the HighLevelProducer. Unfortunately using it in a following way

```
 this.kproducer = new Kafka.HighLevelProducer({
  'metadata.broker.list': this.producers.toString(),
  'message.send.max.retries': 10,
  'retry.backoff.ms': 1000,
  'compression.codec': 'snappy',
  'linger.ms': this.linger_ms,
  'log.connection.close': false,
  "request.timeout.ms": 5 * 60 * 1000,
  'security.protocol': 'ssl',
  'ssl.ca.location': 'kafka_ssl/ssl.ca',
  'socket.keepalive.enable': true,
  'dr_cb': process.env.DEBUG
});                         
```

I get the following error
```
_uncaughtException: callback is not a function
TypeError: callback is not a function
    at Immediate._onImmediate (/Users/denisvoloshin/WebstormProjects/airlytics-event-proxy/node_modules/node-rdkafka/lib/producer/high-level-producer.js:196:11)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)_
```

Once I found the following sample https://github.com/Blizzard/node-rdkafka/blob/master/examples/high-level-producer.md
and the error got before I changed my **this.kproducer.produce** call



```
return this.kproducer.produce(
    // Topic to send the message to
    this.topic,
    // optionally we can manually specify a partition for the message
    this.partition
    // Message to send. Must be a buffer
    Buffer.from(JSON.stringify(event)),
    // for keyed messages, we also specify the key - note that this field is optional
    event.eventId,
    // you can send a timestamp here. If your broker version supports it,
    // it will get added. Otherwise, we default to 0
    Date.now(),
    // you can send an opaque token here, which gets passed along
    // to your delivery reports
    headers,
    (error) => {
        logger.error(error);
    }
);
```

The code didn't work as well the call returns false and the error in the call back is NULL, the sample doc contains only init instruction without showing the this.kproducer.produce, probably I missed something.
pls advice how I can proceed from this point

**Comment by iradul** [comment]
It seems this is not related to headers but to `opaque` argument witch is 6th argument of the `produce` method. Pass `undefined` to this argument if you're not using it.

**Comment by DenisVoloshin** [comment]
Hi iradul, I'm still in the middle of running a long duration test, although at first glace,it seems like the use of **undefined** value as **opaque** works. The test has been running for a day and I don't observe any significant memory raise. 
I think the issue could be close.
Thanks a lot for your assistance, very appreciate it
