### ISSUE TITLE
How to enable full debug?

### ISSUE THREAD

**Issue by rofrol** [Blizzard/node-rdkafka#847]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: 
 - Node Version [e.g. 8.2.1]: v12.16.1
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version 2.9.1
**Steps to Reproduce**

I try to connect but I get only:

`broker transport failure`

**node-rdkafka Configuration Settings**

I have `debug: all`

**Additional context**

How can I get full debug like here:

```bash
Bismoys-MacBook-Air:portwork bismoy$ kafkacat -L -b 172.31.25.198:9092 -d broker
%7|1550506722.903|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1550506722.903|BROKER|rdkafka#producer-1| [thrd:app]: 172.31.25.198:9092/bootstrap: Added new broker with NodeId -1
%7|1550506722.903|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1550506722.903|BRKMAIN|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: Enter main broker thread
%7|1550506722.903|CONNECT|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: broker in state INIT connecting
%7|1550506722.903|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#producer-1 initialized (builtin.features 0xffff, debug 0x2)
%7|1550506722.903|CONNECT|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: Connecting to ipv4#172.31.25.198:9092 (plaintext) with socket 7
%7|1550506722.904|STATE|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: Broker changed state INIT -> CONNECT
% ERROR: Failed to acquire metadata: Local: Broker transport failure
```

https://github.com/edenhill/kafkacat/issues/169#issuecomment-464796065

**Comment by RicardoGralhoz** [comment]
There is an example [here](https://github.com/Blizzard/node-rdkafka/blob/de127473832b94c0b93d0b14f8bd0e9556fee034/examples/consumer-flow.md); just uncomment the `debug` config line:

```javascript
var Kafka = require('../');

var consumer = new Kafka.KafkaConsumer({
  'debug': 'all',
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'node-rdkafka-consumer-flow-example',
  'enable.auto.commit': false
});
```

---
From your post, it seems like you already are doing this. You may want to share your code snippet to get help from the community. Is the Kafka broker reachable in the network from your node app? Are you using any type of authentication and/or encryption layer?

I recently run on multiple connection issues when trying to upgrade `node-rdkafka` and got it working. I posted the juice of my learnings [here](https://github.com/Blizzard/node-rdkafka/issues/824#issuecomment-715639633).

**Comment by rofrol** [comment]
The solution was to use:
- https://github.com/Blizzard/node-rdkafka/blob/2988587d9ed83f26fc4143964d9213dbc3337c47/examples/consumer-flow.md

Then this:

```
//logging debug messages, if debug is enabled
consumer.on('event.log', function(log) {
  console.log(log);
});
```

showed that I don't have kinit installed (yum install `krb5-workstation` or `apt install krb5-user`).

So when using Standard API (consumerf-flow.md), there is access to `event.log` event.
