### ISSUE TITLE
Question about reading one message at the time

### ISSUE THREAD

**Issue by AAraKKe** [Blizzard/node-rdkafka#850]
Some time ago I opened #720 because I found a memory leak I could not understand when using the `consume(n)` method. At the time it sounded like I should update node and the library version and re-evaluate but I was stuck in those versions for reasons outside my control. 

I have managed to prioritize the version update and now we are running node-14 and the latest version of node-rdkafka. This set me on track again to try and read one message at the time and check if the memory leak is still present. 

Given the resources and time we need to process one message we only process 1 message at the time and the message flow is very low. We just react to a handfull of messages  per day. This means that most of the time we won't be reading any message.

When calling the `consume(1)` method, it seems that every time the method is called some resource is created becase I am still seeing the increase in memory usage even if we are not reading anything. This seems to be aligned with the last comment in #720 .

```ts
this.consumerTimeout = setInterval(  () => {
    this.consumer.consume(1); // This call starts consuming memory when messages are not available.
}, 1000);
```

I cannot seem to find a way to consume one single message at the time without having this memory leak issue. If I call the method and there is no message to read I cannot do anything to release the worker that has been created, that I know off.

The workaround we have now is that to use the `consume()` and save into a messages queue every message received by the data event. We then process the queue once at the time. This has many issues and we would like to consume only one message and avoid the memory issue if possible.

What would be the best way of achieving this? 

Thanks!

**Comment by syahiaoui** [comment]
Hi,

You can try to use this simple: https://github.com/Blizzard/node-rdkafka/issues/735#issuecomment-577503322

**Comment by LahariMadupally** [comment]
Hi @AAraKKe ,

the consumer.consume() method accepts a maximum of 2 arguments - the number of messages to be consumed and the error first callback. i.e., consumer.consume() can be used either as
`consumer.consume((err, data) => {/*some functionality*/})`
or
`consumer.consume(number of messages to be consumer, (err, data) =>{/*some code*/})`
The prior usage keeps a background thread running and gets messages from the subscribed topic as quick as possible whereas the latter consumes a specific number of messages.
Please refer: [Consumer standard API section](https://www.npmjs.com/package/node-rdkafka)

Using `consumer.consume(number_of_messages_to_be_consumed, callback())` would solve the issue

**Comment by AAraKKe** [comment]
Thanks for the answers. Let me just clarify this, you say that, if instead of letting the code react to data events, I pass the callback to it, the memory leak should be gone?

I would have assumed the behaviour is the same whether one use the callback in the consume or the data event. I tried with the callback and although memory increases during the first minutes or so of running it eventually seems to estabilize itself.

I will give it a go and update it that way and see how it goes when it runs over longer periods of time.

**Comment by AAraKKe** [comment]
I have been checking this and it seems that using a callback the memory issue dissappear. Not sure why this happens, must be something internal but it seems to maintain a constant memory usage as far as I can tell. Lets see how it behaves with time. 

I am closing this since I think my question is answered :)

Thanks!
