### ISSUE TITLE
Producers error after version update: Not enough in-sync replicas

### ISSUE THREAD

**Issue by AAraKKe** [Blizzard/node-rdkafka#852]
Hi everyone, I was not sure if I should open this a bug because it might be some misconfiguration although this issue only appears when updating the latest version.

We have been using version 2.7.0 to avoid several issues we had with newer versions becasue we had an old version of node. We are now updating node and node-rdkafka is set to ^2.9.0. 

There seems to be an issue with our producers when updating to this version that causes messages not to be sent when running in an Amazon MSK cluster. We know the cluster is working because we can send and read messages with no problem with our python models (in fact we trigger the node part with a message sent from python). Nonetheless, even though the messages are read properly when the producer needs to send a message, the message never gets sent, or at least I cannot see it in the topic.

It seems to be an issue with the way it communicates with the MSK cluster because if I run exactly the same processes in a local setup with kafka running in a container with the bitnami image, everything works as expected: messages can be read and sent without any problem.

This is how we are sending messages, in case you can see there is something that needs to be done differently:

```ts
this.producerConfig = {
    'metadata.broker.list': "broker1:port,broker2:port,broker3:port",
    'dr_cb': true
};
this.producer = new Producer(this.producerConfig);

// We keep a queue with the messages to send and when the ready event is triggered we start an interval that sends messages from the queue
this.producer.on('ready', () => {
    this.producerInterval = setInterval(producerLoop, 100, this.producer, this.producerQueue);
});

// Producer loop just pops messages from the queue and calls the produce method in the producer
function producerLoop(producer: Producer, queue: Queue<ProducerMessageQueueItem>): void {
    const payload = JSON.stringify(messageItem.message);
    // messageItem.topic stores the topic we want to send the messages to
    producer.produce(messageItem.topic, -1, Buffer.from(payload), undefined, Date.now());
}
```

Do you know what the issue might be? Thanks a lot in advance!

**Comment by AAraKKe** [comment]
I have modified the title of the issue after taking a look at the debug logs. I found an error that says that there are not enough in-sync replicas and prevents the message from sending. 

```
LOG: {"severity":7,"fac":"REQERR","message":"[thrd:b-3.kafkaanalytics.k0zgq9.c7.kafka.us-east-1.amazonaws.com:9092]: b-3.kafkaanalytics.k0zgq9.c7.kafka.us-east-1.amazonaws.com:9092/3: ProduceRequest failed: Broker: Not enough in-sync replicas: explicit actions Retry,MsgNotPersisted"}
```

Nonetheless this error never happend with previous versions and the cluster configuration has not changed. The same cluster with 2.7.0 works just fine. Is there any configuration in the producer that has changed that I need to supply in order for it to work?

Thanks!

**Comment by AAraKKe** [comment]
If I set request.required.acks = 0 in the Producer Topic Config everything works. Messages can be sent without any issue. This seems weird to me though. Before updating the library messages could be send as well so I am not sure what has changed so I have now have to enforce 0 acknowledgements with no changes in the broker configuration.

Any help would be greatly appreciated.

**Comment by iradul** [comment]
The issue you're having is related to librdkafka so I suggest you try to find some answers there. Version `2.7.0` is using librdkafka `0.11.6` and `2.9.0` is using `1.4.2`
