### ISSUE TITLE
Producer and consumer not disconnecting after the test is completed

### ISSUE THREAD

**Issue by Nitish1234** [Blizzard/node-rdkafka#865]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Mac
 - Node Version [e.g. 8.2.1]: 13.6.0
 - NPM Version [e.g. 5.4.2]:  6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.9.1

**Steps to Reproduce**
1. Creating a producer and consumer client.
2. Pushed a message using produce API call.
3. Consumer consumes the message and calls the 3rd party API.
4. Success returned from the 3rd party API.
5. Tried disconnecting the producer using disconnect() which gives `nan:AsyncWorker` error and the test doesn't exits.

**node-rdkafka Configuration Settings**

**Additional context**

**Comment by Nitish1234** [comment]
@webmakersteve @JaapRood @codeburke @ankon @iradul any idea what could be the issue?

**Comment by ankon** [comment]
>  which gives `nan:AsyncWorker` error and the test doesn't exits

I think to have a better chance for help you should post the complete error, and ideally also the code you're using.
