### ISSUE TITLE
Reading events produced before consumer connects

### ISSUE THREAD

**Issue by SBattelini** [Blizzard/node-rdkafka#867]
Hello, 
when using the examples and tutorials provided, the consumer starts listening and logging the events that are sent after the consumer connected. 
But when using the "original" kafka consumer, when it connects, it displays all events that are present in the partition at that time, and then starts listening for new events.
Is there a way to replicate this behaviour with node-rdkafka? How do I access evverything that was present in the partition before the consumer connected?
Thank you for the help.

**Comment by tanmayachugh** [comment]
Setting `auto.offset.reset` to `earliest` in the topic config while creating the consumer should work. You can refer this example:
https://github.com/confluentinc/examples/blob/6.0.1-post/clients/cloud/nodejs/consumer.js

**Comment by SBattelini** [comment]
That worked, thank you very much!

> Setting `auto.offset.reset` to `earliest` in the topic config while creating the consumer should work. You can refer this example:
> https://github.com/confluentinc/examples/blob/6.0.1-post/clients/cloud/nodejs/consumer.js
