### ISSUE TITLE
Getting OpenSSL not available at build time error, for node v14.15.4 and Ubuntu 16 and node-rdkafka v"^2.10.1"

### ISSUE THREAD

**Issue by patelravi** [Blizzard/node-rdkafka#868]
Does anyone have idea what is the ideal setup for using this node-rdkafka package on Ubuntu 16? 
I am currently using node v14.15.4, Ubuntu 16 for hosting, and  node-rdkafka npm version "^2.10.1"

With this configuration I am getting ssl error, I also tried to setup openssl before starting server but no luck.

> Error: Unsupported value "ssl" for configuration property "security.protocol": OpenSSL not available at build time
>     at Producer.Client (/root/kafka-producer-project/node_modules/node-rdkafka/lib/client.js:54:18)
>     at new Producer (/root/kafka-producer-project/node_modules/node-rdkafka/lib/producer.js:75:10)
>     at Function.<anonymous> (/root/kafka-producer-project/dist/kafka-producer.js:78:36)
>     at Generator.next (<anonymous>)
>     at /root/kafka-producer-project/dist/kafka-producer.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/root/kafka-producer-project/dist/kafka-producer.js:4:12)
>     at /root/kafka-producer-project/dist/kafka-producer.js:75:53
>     at new Promise (<anonymous>)
>     at Function.<anonymous> (/root/kafka-producer-project/dist/kafka-producer.js:75:20)

I am new to Kafka and node-rdkafka. So apologies in advance if I am missing anything here.

**I am using following start script on fresh Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-1091-gcp x86_64)  server**

> echo "##################### Start: Install Build Essential #####################"
> sudo -s
> sudo apt-get update
> sudo apt-get install -y build-essential
> 
> echo "##################### Start: Install OpenSSL #####################"
> sudo apt-get install libssl-dev
> ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu
> sudo make
> sudo make install
> 
> echo "#####################++ Start: Node installation #####################"
> curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh -o install_nvm.sh
> sudo bash install_nvm.sh
> source ~/.nvm/nvm.sh
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
> [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
> echo "#####################++ Select Node Version #####################"
> nvm install 14.15.3
> nvm use 14.15.3
> echo "#####################++ Node Version is #####################"
> node -v
> npm -v
> 
> echo "##################### Prining OpenSSL Version #####################"
> openssl version
> echo "#####################++ Install NPM Dependencies #####################"
> npm i 
> npm install -g typescript
> echo "#####################++ Compile Typescript #####################"
> tsc
> echo "#####################++ Start Server #####################"
> node dist/server.js

**Comment by romelgomez** [comment]
I get this error on mac m1

`[ExceptionHandler] Unsupported value "SASL_SSL" for configuration property "security.protocol": OpenSSL not available at build time +3394ms`

**Comment by Michaelangelo-GrizzlyBear** [comment]
@romelgomez 

have you found the solution?

I get this error in ubuntu
