### ISSUE TITLE
What's the plan for supporting node 14?

### ISSUE THREAD

**Issue by Chengxuan** [Blizzard/node-rdkafka#873]
According to https://nodejs.org/en/about/releases/

node 14 is the active lts. Is there any official support statement of this repo on node 14? https://github.com/Blizzard/node-rdkafka/blob/master/.travis.yml supports node version up to 13.

Do you have a plan of when node 14 will be supported?

**Comment by cristian-m-vasile** [comment]
would be very interested in this, as node 12 has some pretty serious security vulnerabilities

**Comment by iradul** [comment]
Although Node 14 and 15 are currently not included in Travis tests, library should work just fine with these two. Are you having any issues?

**Comment by Chengxuan** [comment]
@iradul We haven't found any so far. We are doing more testing at the moment.

It will give the consumers of this library more confidence if this library shows evidence that all of its tests are passing in node 14 and 15.

@iradul what is blocking node 14 and node 15 to be included in the Travis tests?
