### ISSUE TITLE
Unable to set up Kafka consumer stream - Local: Broker transport failure

### ISSUE THREAD

**Issue by stealthrabbi** [Blizzard/node-rdkafka#886]
**Environment Information**
 - OS Ubuntu 20.04.2
 - Node Version [e.g. 8.2.1]: v14.16.1
 - NPM Version [e.g. 5.4.2]: 6.14.12
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: ?
 - node-rdkafka version ]: 2.10.1

**Steps to Reproduce**
Trying to set up a Kafka consumer stream similar to what's in the readme file.

```
    const consumerConfig: ConsumerGlobalConfig = {
      "metadata.broker.list": "mykafkahost:9092"
      "group.id": "group-1",
      "enable.auto.commit": false,
    };
    const topicConfig: ConsumerTopicConfig = {
      "auto.offset.reset": "latest",
      "consume.callback.max.messages": 50
    };

    const consumerStream = KafkaConsumer.createReadStream(
      consumerConfig,
      topicConfig,
      {
        topics: ["my-topic-1"],
      }
    );

consumerStream.on("data", this.consumeMessage);

...
  consumeMessage(message: any): void {
    Logger.info("Got a message!");
    Logger.info(message.value.toString());
  }

```

I'm running this in a JEST test, and after some time after callnig on(), this gets dumped to the console. I've bene able to connect to the kafka server and consume messages in Java, using a kafka consumer library that is configured similarly. Does "origin: 'kafka') referring to some default URL? Almost seems like my `metadata.broker.list` isn't being applied..

The linux box that i'm running this on has a kafka and nginx running in a docker container

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (LibrdKafkaError {
  message: 'Local: Broker transport failure',
  code: -195,
  errno: -195,
  origin: 'kafka' })
    at KafkaConsumerStream.emit (events.js:187:17)
    at KafkaConsumerStream.EventEmitter.emit (domain.js:448:20)
    at connectCallback (/home/my-name/Projects/my-proj/node_modules/node-rdkafka/lib/kafka-consumer-stream.js:305:12)
    at next (/home/me/Projects/my-proj/node_modules/node-rdkafka/lib/client.js:141:7)
    at /home/my-name/Projects/my-proj/node_modules/node-rdkafka/lib/client.js:172:9
```

**Additional context**

**Comment by iradul** [comment]
It looks like you can't access Kafka broker(s). Running Kafka in Docker container can be tricky. For example, you would have to set advertised.listeners property to make it work.
I'd try to consume with `kafkacat` from the same container (or box) where your NodeJS app runs.

**Comment by stealthrabbi** [comment]
Thanks. I'll look in to doing that. For now, I am able to consume from kafka w\o issue. But, this is not an actual issue with this libray, so I will close. Thank you.
