### ISSUE TITLE
can't use consumeLoop with assignments

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#89]
In `kafka-consumer.js` `consume([topics])` calls `subscribe([topics])`
therefore client code like this
```
  consumer.assign([{ topic:topicName, partition:0, offset:2950}]);
  consumer.consume([ topicName ]); 
```

does not work, because the assignment (i.e. unbalanced consumer with manual partition assignment) is overridden by the hidden subscribe (i.e. causing a shift to the balanced consumer)

the consumer API should allow both these use cases:
```
  consumer.assign([{ topic:topicName, partition:0, offset:2950}]);
  consumer.consume();  //invoke the loop
```
and

```
  consumer.subscribe([topics]);
  consumer.consume(); //invoke the loop
```
The consume method should not require again the list of topics that have been subscribed or assigned to.

This behavior looks more consistent with the Java client, though removing the argument from `consume` currently invokes `consumeOne`

**Comment by webmakersteve** [comment]
Commented on the PR about how this situation should be handled.

**Comment by webmakersteve** [comment]
Potentially fixed with #96. Awaiting review.

**Comment by edoardocomar** [comment]
Thanks @webmakersteve 
Frankly, I don't like `consume(null, cb)`.
I'm afraid all the conditionals on the arguments of `consume(...)` are not pretty and do not make for readable code. 

Could we clean the API please ? 
Either by breaking the current consume API a bit, or by deprecating it and add a new API.
https://github.com/Blizzard/node-rdkafka/pull/96#issuecomment-273824639

**Comment by webmakersteve** [comment]
I'm going to break the API a bit and simplify it so it just has two overloads. If people want an abstraction that does not require them to use `subscribe` or `assign`, there will be a `TopicReadable` stream that they can use instead that manages that as a first class object, rather than one returned by a method.

**Comment by webmakersteve** [comment]
#103 fixes this issue. Has been merged, so I am closing.
