### ISSUE TITLE
How/where to do manual commit using node-rdkafka consumer read stream 

### ISSUE THREAD

**Issue by samathan** [Blizzard/node-rdkafka#895]
Hi,

I am using  "node-rdkafka": "2.9.1", and consumer streams , need to understand how/ where to do manual commit?

I am pretty much following the below code
https://github.com/Blizzard/node-rdkafka/blob/master/examples/consumer.md

In the above consumer code didn't see any manual commit.

Can you please help me with manual commit using Consumer Streams.

Thanks & Regards,
Samatha

**Comment by sathyarajagopal** [comment]
I would like to know this as well. I am consuming messages and processing it one by one. After successful process, I now have to commit it. How can we get access to offset in read stream?

**Comment by iradul** [comment]
You can access the underlying consumer instance with `.consumer` and use it for manual commits.
https://github.com/Blizzard/node-rdkafka#stream-api-1

**Comment by sathyarajagopal** [comment]
Yes. I am able to use that.
