### ISSUE TITLE
Unable to pause a consumer in flowing mode.

### ISSUE THREAD

**Issue by ankush2394** [Blizzard/node-rdkafka#904]
**Environment Information**
 - OS: Mac
 - Node Version: 12.19.0
 - NPM Version : 6.4
 - node-rdkafka version: 2.10.1

**Steps to Reproduce**
Try doing consumer.pause in flowing mode, it doesn't pause the consumer

**Comment by iradul** [comment]
The pause will happen, meaning the consumer will stop consuming, but some messages could still be in the buffer, so you can still see those coming in until the buffer gets empty. I guess you can try to poke around with `queued.min.messages` option.
