### ISSUE TITLE
Erroneous state while initialising Admin client

### ISSUE THREAD

**Issue by tanuj32soni** [Blizzard/node-rdkafka#905]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]:  20.04.1-Ubuntu
 - Node Version [e.g. 8.2.1]: v14.17.0
 - NPM Version [e.g. 5.4.2]: 6.14.13
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version [e.g. 2.3.3]: v2.10.1

**Steps to Reproduce**
Just try initialising admin client with this configuration reproduces Erroeous state
`const adminClient = AdminClient.create({
      "bootstrap.servers": "brokers",
      "security.protocol":  "sasl_ssl" ,
      "sasl.mechanisms": "SCRAM-SHA-256",
      "sasl.username": "username",
      "sasl.password": "password",
      "ssl.certificate.pem": 'CLUSTER_CERIFICATE',
      "ssl.key.pem": "CLUSTER_KEY",
      "ssl.ca.location:: "./ca.pem"
     });
`

**Error**
Local: Erroneous state","code":-172,"errno":-172,"origin":"kafka"

_Originally posted by @tanuj32soni in https://github.com/Blizzard/node-rdkafka/issues/583#issuecomment-888025543_

**Comment by joaovitorteixeira** [comment]
Any reason to cloase it as completed?
