### ISSUE TITLE
Node-rdkafka throwing segmentation fault

### ISSUE THREAD

**Issue by ranir505** [Blizzard/node-rdkafka#914]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Ubuntu 14
 - Node Version [e.g. 8.2.1]: 12.14.0
 - NPM Version [e.g. 5.4.2]: 6.13.4
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 2.10.1

**Steps to Reproduce**
I am migrating the kafka library in my application to node-rdkafka. I am getting segmentation in application's deployment logs. Getting below error while running the application in gdb:
Thread 16 "rdk:broker-1" received signal SIGSEGV, Segmentation fault. [Switching to Thread 0x7fffce7fc700 (LWP 32445)] 0x00007fffdd81ba9b in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0

What could be the possible cause for this issue?

**node-rdkafka Configuration Settings**

**Additional context**

**Comment by nishanthmatha** [comment]
Had same issue with similar set up. 
It turned out the libssl and libcrypt libraries were of different version in node-librdkafka (ldd /{app}/node_modules/node-rdkafka/build/Release/node-librdkafka.node) and libssl (system) file used to build the package.

Installing openssl version 1.1.1i and export the `CPPFLAGS` and `LDFLAGS` with values pointing to newly installed open ssl as per documentation and rebuild the package resolved my issue

**Comment by ranir505** [comment]
I ran this "ldd /{app}/node_modules/node-rdkafka/build/Release/node-librdkafka.node" and got:
        linux-vdso.so.1 (0x00007ffdc9ce6000)
	librdkafka.so.1 => /opt/app/node_modules/node-rdkafka/build/Release/./../deps/librdkafka.so.1 (0x00007fa4863f8000)
	librdkafka++.so.1 => /opt/app/node_modules/node-rdkafka/build/Release/./../deps/librdkafka++.so.1 (0x00007fa4861d1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa485e48000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa485a57000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa4856b9000)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fa485451000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fa48500e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa484df1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa484bed000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa4849ce000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa4847c6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa4869be000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa4845ae000)

After manually upgrading the openssl version, these are the files and folders that openssl is having:
<img width="799" alt="Openssl_ls" src="https://user-images.githubusercontent.com/25305668/133890093-92e29501-9356-4e9b-a34c-e118371503f5.png">

CPPFLAGS can point to the /include of newly installed open ssl, but there is no /lib in it , where LDFLAGS can point to.

As per the documentation:
export CPPFLAGS=-I/usr/local/opt/openssl/include
export LDFLAGS=-L/usr/local/opt/openssl/lib

When I ran my appllication after upgrading the openssl version, I am getting below error:
"Error: Unsupported value \"ssl\" for configuration property \"security.protocol\": OpenSSL not available at build time","name":"Error","stack":"Error: Error: Unsupported value \"ssl\" for configuration property \"security.protocol\": OpenSSL not available at build time
