### ISSUE TITLE
Error handling issue - consumer.connect() not redirecting to consumer.on('ready')

### ISSUE THREAD

**Issue by mkscastillo** [Blizzard/node-rdkafka#925]
consumer.connect() does not redirect to consumer.on('ready', function). Tried to display if there was any error through callback but error is not logged/caught
```
        consumer.connect({timeout: "1000ms"}, (err) => {
            if (err) {
                logger.log(`Error connecting to Kafka broker: ${err}`);
                process.exit(-1);
            }
        });
````

**Comment by ceborgemo** [comment]
I have this same issue but with the producer. Any idea of a solution?

**Comment by buffaloDeveloper** [comment]
Seeing the same issue.  Product works fine, but consumer never emits "ready" event.
