### ISSUE TITLE
Consumer issues with `conf.rebalance_cb = true`

### ISSUE THREAD

**Issue by edoardocomar** [Blizzard/node-rdkafka#93]
if `conf.rebalance_cb` is set to `true` 
the consumer does not emit the rebalance event - which could be used to mimick `seek` by using `assign` as suggested by @edenhill

BTW with conf.rebalance_cb = true`, the consumer calls an undefined `unassign` JS function

`kafka-consumer.js` line 54
```
        self.unassign(e.assignment);
```

**Comment by webmakersteve** [comment]
Should be fixed with #95.

**Comment by edoardocomar** [comment]
Thanks @webmakersteve !

Will need to add some tests. 
I remember seeing `unassign` throwing because of client disconnected. will need to retest that path too.

Would be nice to be able to mark the the event as "manually handled" and if so, skip the following `if...assign...else...unassign`

**Comment by webmakersteve** [comment]
You can do that already by providing a function into `conf.rebalance_cb`

**Comment by edoardocomar** [comment]
I was thinking, as the "standard" rebalance action is already coded in the `KafkaConsumer`
```
      if (e.code === 500 /*CODES.REBALANCE.PARTITION_ASSIGNMENT*/) {
        self.assign(e.assignment);
      } else if (e.code === 501 /*CODES.REBALANCE.PARTITION_UNASSIGNMENT*/) {
        self.unassign();
      }
```
that could be extracted in a method that can be called in the user's event handler (eg after changing the offset in `e`) , and then skipping the re-invocation of assign/unassign

**Comment by webmakersteve** [comment]
The way I envisioned it, is that the `rebalance` event being emitted is just extra information we are aware of if we opt into our software handling the rebalances. If you want to override the functionality, it should be done inside a function passed directly into the config, rather than in the emitter. This seems to me the most 1:1 relationship to `librdkafka`, while still adding some extras that make sense.

So, if you want `node-rdkafka` to manage rebalances, but want to be notified, you...

```js
const consumer = new kafka.Consumer({
   'rebalance_cb': true
});
```

If you want to implement custom rebalance logic...

```js
const consumer = new kafka.Consumer({
   'rebalance_cb': function(event, assignments) {
      this.assign(assignments); // this is bound to the kafka.Consumer via bind
   }
});
```

If you'd like to see it a different way, one of the ways I was thinking is to do it the way you've described. But so far this is the API i've come up with.

**Comment by edoardocomar** [comment]
I have written a test that shows the problem I mentioned in
https://github.com/Blizzard/node-rdkafka/issues/93#issuecomment-273438627

consumer.disconnect() causes the self.unassign() in the rebalance
function to be invoked when the consumer is in the wrong state.

the test `should emit events with conf.rebalance_cb=true`
passes but the testsuite hangs (process doesn't exit)

**Comment by pmidge** [comment]
possibly related, but if not i will file a new issue with repro: i noticed today that if i handle rebalance events, `disconnected` is not emitted. a subsequent call to `unassign()` in the rebalance handler causes an exception to be thrown.

**Comment by webmakersteve** [comment]
@pmidge  can you provide a test case that shows this functionality? The disconnect event and rebalance events are pretty decoupled so it could be an underlying c++ issue if this is happening to you.

**Comment by pmidge** [comment]
@webmakersteve absolutely, will try to do ASAP but may be delayed while finishing the project we're using `node-rdkafka` in.

**Comment by pmidge** [comment]
update: since 0.8.0 is released, i'll try to repro with that. in the project just finished i noticed on the `ALPHA.3` release that node-rdkafka would immediately segfault, so i'm still using `ALPHA.2`. i'd like to get current. ;)

**Comment by pmidge** [comment]
the segfault does not appear to repro in 0.8.0. moving on to the `disconnected` issue.

**Comment by webmakersteve** [comment]
Are you reproducing the disconnected issue? Do you have a test case I can run to reproduce it so I can fix it?

**Comment by pmidge** [comment]
I do. Just trying to reduce it down to its essentials while retaining the
character of our implementation. Will post later today.

**Comment by pmidge** [comment]
Here you go. Not strictly a test case per se, but 100% representative of our use case.

1. In the directory containing the unpacked `rebalance.js`, run `npm i node-rdkafka@0.8.0 underscore`.
2. Open `rebalance.js` and modify `topics` and `config` to suit your environment.
3. `node rebalance.js`.

Out of the box, the repro is configured to use an internal rebalance handler. This *should* repro the failure I initially reported. You can modify rebalance behavior by referring to instructions at line 239.

[rebalance.js.gz](https://github.com/Blizzard/node-rdkafka/files/833733/rebalance.js.gz)

**Comment by edoardocomar** [comment]
I had used `conf.rebalance_cb = true` with the current 0.10.2 release and the event was emitted as expected. I'm closing this old issue
