### ISSUE TITLE
Unable to connect Kafka after noderd-kafka version to 2.12.0

### ISSUE THREAD

**Issue by abuazeem** [Blizzard/node-rdkafka#932]
**Environment Information**
 - OS [Linux]: 
 - Node Version : v17.3.0]
 - NPM Version : 8.3.0
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]: g++
 - node-rdkafka version : ^2.12.0

**Steps to Reproduce**
Trying to connect to kafka but getting SASL error.

var kafka=require('node-rdkafka'); 

var producer = new kafka.Producer({
      'bootstrap.servers':'sasl_ssl://somedomain.com:443',
      'sasl.username': 'someusername',
      'sasl.password': 'somepasswrod',
      'security.protocol': 'SASL',
      'sasl.mechanism': 'SCRAM-SHA-256',
      'enable.ssl.certificate.verification':false,
      'dr_msg_cb': true,
	  'debug': 'generic,broker,security'
    });
After executing above statement, getting below error.

Uncaught Error: Invalid value "SASL" for configuration property "security.protocol"
    at Producer.Client (/app/node_modules/node-rdkafka/lib/client.js:54:18)
    at new Producer (/app/node_modules/node-rdkafka/lib/producer.js:75:10)
**node-rdkafka Configuration Settings**

 kafka.librdkafkaVersion
'1.7.0'

OpenSSL> version
OpenSSL 1.1.1d  10 Sep 2019

**Additional context**
Was working with 2.10.0 but later seeing error.

**Comment by iradul** [comment]
[As noted here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md), the valid values for `security.protocol` are  `sasl_ssl`, `plaintext`, `ssl`, and `sasl_plaintext`.
