### ISSUE TITLE
Please release the updated package that now uses rdkafka 1.8.2

### ISSUE THREAD

**Issue by DaveGrahamExpediaGroup** [Blizzard/node-rdkafka#957]
**Additional context**

There are numerous [bugs in rdkafka 1.7.0 consumer that have been documented](https://github.com/edenhill/librdkafka/releases/tag/v1.8.0).  Many of which I have been experiencing with node-rdkafka 2.12.0. 

@iradul 
[It appears that the work is done to upgrade to 1.8.2. Please consider cutting a release.](https://github.com/Blizzard/node-rdkafka/pull/923#issuecomment-1060443594)

Thank you

**Comment by iradul** [comment]
Done

**Comment by DaveGrahamExpediaGroup** [comment]
@iradul Thank you!
