### ISSUE TITLE
Cannot install version 2.14.5 on node 10

### ISSUE THREAD

**Issue by iam-nagarajan** [Blizzard/node-rdkafka#999]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: Mac
 - Node Version [e.g. 8.2.1]: 10.24.1
 - NPM Version [e.g. 5.4.2]: npm -v
 - node-rdkafka version [e.g. 2.3.3]: 2.14.5

**Steps to Reproduce**
yarn install fails with following error
`error node-rdkafka@2.14.5: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "10.24.1"`

2.14.4 works fine in the same node version. 

Shouldn't 2.14.5 be a major version update if it expects node to be > 14?

**Comment by GaryWilber** [comment]
Yes you're right. I reverted the node engine change and published v2.14.6 to fix this. Thanks
